### ISSUE TITLE
JSON condition expression

### ISSUE THREAD

**Issue by kbe69** [danielgerlag/workflow-core#102]
[wf1.txt](https://github.com/danielgerlag/workflow-core/files/1675621/wf1.txt)
Hi,

I would like to define if condition using task data but I got the following error:

System.Linq.Dynamic.Core.Exceptions.ParseException : 'No property or field 'Value1' exists in type 'Object''

what's wrong with my file (attached)?

Thank you for your help

**Comment by danielgerlag** [comment]
Hi,

Can you try adding `"DataType": "MyApp.MyDataClass, MyApp"` to the root element? (Where `MyDataClass` references the name of the class you are using to hold data)

**Comment by kbe69** [comment]
It works perfectly!

thank you very much
[wf1.txt](https://github.com/danielgerlag/workflow-core/files/1676644/wf1.txt)

**Comment by tcochunk** [comment]
Thank you.  this was my problem as well.
