### ISSUE TITLE
How can implement a recursive workflow?

### ISSUE THREAD

**Issue by MohammadHatami20** [danielgerlag/workflow-core#1035]
I have 3 events:

Accept
Reject
Processed

How can I impelemt this scenari?

![Capture](https://user-images.githubusercontent.com/7962499/168580995-3930440e-1b6f-4da8-b710-8264039c6312.PNG)

**Comment by mohamedassem96** [comment]
hello Mr. Mohammad, did you find a way to implement this scenario?
