### ISSUE TITLE
Workflows do not run after switching to WorkflowCore.Persistence.MongoDB

### ISSUE THREAD

**Issue by jongunter** [danielgerlag/workflow-core#105]
Hey, great library! I've been playing around making a few samples. They work just-as-expected with the default in-memory persistence provider. However, as soon as I switch to `WorkflowCore.Persistence.MongoDB` as my persistence provider, my workflows stop running. 

I can put breakpoints in all the steps, and they don't fire when using MondoDB. They will fire as expected when using the in-memory provider.

The only difference is I swapped these two lines of code in my `Startup` class.
```
services.AddWorkflow(x => x.UseMongoDB(@"mongodb://localhost:27017", "workflow"));
//services.AddWorkflow();
```

I've looked in my local MongoDB server and the collection `workflow` is indeed created. If I raise events, I can see documents in the `wfc.events` collection. But no matter what I do, nothing appears in the `wfc.workflows` collection.

Any ideas? Am I just missing something? Or there this bug in the persistence provider?

**Comment by danielgerlag** [comment]
Hi Jon,

Could you attach a project source code that replicates this issue?
Which version of MongoDB are you using?

**Comment by jongunter** [comment]
I'm on MongoDb 3.4.5. Let me get a repro together and I'll upload it to GitHub soon...the project I'm trying this out with is closed-source. Thanks!

**Comment by st2forget** [comment]
Same issue, and also, it consumes memory a lot when running in memory mode (it increase around 1 - 4MB and never release each time with only an empty step).
```
           services.AddWorkflow(o =>
           {
               var conf = container.Resolve<IConfiguration>();
               var connectionString = conf.GetConnectionString("__MigrationDatabase");
               o.UseSqlServer(connectionString, false, true);
           });
```
