### ISSUE TITLE
Oracle Provider

### ISSUE THREAD

**Issue by shakibmiraki** [danielgerlag/workflow-core#106]
Hi,
do you have any plan to implement oracle provider for workflow core ?? 
i want to use workflow core in one of my project but database is oracle and i need an oracle provider.
do you have any suggestion for that ?

**Comment by danielgerlag** [comment]
Not at present, the SQL Server and Postgres providers are built on entity framework core, which does not yet have an Oracle provider.  Once an Oracle provider for EF core is released, it should be trivial to implement an Oracle provider for workflow core.

**Comment by Suriman** [comment]
@shakibmiraki FYI: https://docs.microsoft.com/en-us/ef/core/providers/oracle/
