### ISSUE TITLE
support IHttpContextAccessor injection

### ISSUE THREAD

**Issue by Alundra828** [danielgerlag/workflow-core#1087]
**Is your feature request related to a problem? Please describe.**
It appears that currently if you want to inject to IHttpContextAccessor to say, have a given task pass on a bearer token for an http call, the resulting context is always null. 

**Describe the solution you'd like**
Ideally we should be able to inject the context of the calling user in the same way we can inject it into any other given class. 

**Describe alternatives you've considered**
This appears to be the case with standard dependency injection, as well as more sketchy property injection.

**Comment by danielgerlag** [comment]
The does not workflow execute within the scope of the original call... it could be months later or even on a different machine.... you will need to capture the info you need before you create the workflow and attached it to the workflow data.
