### ISSUE TITLE
How to use in the webpage procedure

### ISSUE THREAD

**Issue by AsenLins** [danielgerlag/workflow-core#109]
Now I have a human system (website) to use the workflow, but I do not know how to use this engine, can you give me some help?

**Comment by AsenLins** [comment]
Now I have a human system (website) to use the workflow, but I do not know how to use this engine, can you give me some help?

**Comment by danielgerlag** [comment]
You could register external events for the workflow to listen to using `WaitFor` and then your UI can publish events with attached data to the workflow engine.

See this sample https://github.com/danielgerlag/workflow-core/wiki/04.-Responding-to-external-events
