### ISSUE TITLE
Workflow Purger - performance improvements

### ISSUE THREAD

**Issue by ThomasBergholdWieser** [danielgerlag/workflow-core#1096]
**Is your feature request related to a problem? Please describe.**
If you have lots of workflows, eg. you created your workflow before the existence of WorkflowPurger, you can come to a point, where it is no longer possible to purge the workflows in reasonable time.

**Describe the solution you'd like**
Purge in batches, that commit. Maybe use a smarter way of deleting entities (BulkExtensions?)

**Describe alternatives you've considered**
For Sql Server, i have created this script, but haven't executed it yet.

```sql
DECLARE @DateTimeMaxAge AS DATETIME
SET @DateTimeMaxAge = DATEADD(dd, 0, DATEDIFF(dd, 0, DATEADD(DAY, -300, GETUTCDATE())))
SELECT @DateTimeMaxAge

DELETE wf FROM [wfc].[Workflow] wf
WHERE [Status] = 2 AND [CompleteTime] < @DateTimeMaxAge

DELETE ea FROM [wfc].[ExtensionAttribute] ea
INNER JOIN wfc.ExecutionPointer ep ON ea.ExecutionPointerId = ep.PersistenceId
INNER JOIN wfc.Workflow wf ON ep.WorkflowId = wf.PersistenceId
WHERE wf.[Status] = 2 AND wf.[CompleteTime] < @DateTimeMaxAge

DELETE ep FROM [wfc].[ExecutionPointer] ep
INNER JOIN wfc.Workflow wf ON ep.WorkflowId = wf.PersistenceId
WHERE wf.[Status] = 2 AND wf.[CompleteTime] < @DateTimeMaxAge
```

**Comment by vladimir-kovalyuk** [comment]
We've recently experienced timeouts and huge memory consumption caused by WorkflowPurger. Going to write our own purging by chunks.
