### ISSUE TITLE
Question: Is there a way to create a suspended workflow?

### ISSUE THREAD

**Issue by peterkozak** [danielgerlag/workflow-core#118]
Hi Daniel,

I would like to create several workflow instances to store the Workflow Instance Id, but the workflow needs to be in a suspended state. 

We're trying to use workflow-core for a migration workflow (one workflow instance per user), and the amount of in parallel running workflows should be controlled by the migration app logic.  I thought the easiest would be to create all required workflow instances as suspended and as soon they should run then to un-pause them.

Is this possible, or can you suggest a different way to achieve this outcome?

Thanks,
Peter

**Comment by danielgerlag** [comment]
Hi Peter,

That is perhaps a feature that should be added, but for now you could use a `.WaitFor` as the first step of the workflow and than the `PublishEvent` method to achieve the same sort of thing.  By default, the max number of concurrent running workflows would be equal to the number of cores as determined by TPL

**Comment by peterkozak** [comment]
Thanks Daniel, one more question related to your statement above:

You've mentioned that the max number of concurrency is the number of cores. Is there any way to change this? The workflows we're running are not really cpu intensive. I'd need to run multiple 100 long running workflow instances (neither CPU nor RAM intensive) in parallel per node. (see below)

How is it parallelism behaving in a multi node environment? We're running workflowcore in Service Fabric on multiple nodes and use Azure as Locking/Queueing.

Thanks,
Peter

**Comment by danielgerlag** [comment]
Whenever a node detects a workflow that needs to be executed, it places it on a shared queue, so any node can pick it up and process it in a competing consumer fashion.  The distributed lock provider ensures that only 1 node can process a given workflow at a time.  

The original version of workflow-core used to spin up it's own thread pool, but I later changed it to use TPL, so there will only be the # of cores per node executing a workflow, the threads can be re-used whilst something is waiting for I/O, so in that sense you could have more in-flight workflows executing on a node than the # of cores.
