### ISSUE TITLE
EntityFramework/ExtensionMethods are private and are not open for extension

### ISSUE THREAD

**Issue by martikyan** [danielgerlag/workflow-core#1180]
**Is your feature request related to a problem? Please describe.**
[ExtensionMethods](https://github.com/danielgerlag/workflow-core/blob/12be88701780e1f1b2d5b5b5d98e7ce4df3e9913/src/providers/WorkflowCore.Persistence.EntityFramework/ExtensionMethods.cs#L10C5-L10C5) in the EntityFramework provider is currently internal and is not open for extension.

**Describe the solution you'd like**
I would like to propose converting `ExtensionMethods` into a service with extensions made public.

**Describe alternatives you've considered**
One alternative would be to simply mark those methods as public

**More context**
 The service will most probably be dependent on `JsonSerializerSettings`. See also #1178

**Comment by danielgerlag** [comment]
The point is encapsulation, so that these things can be refactored in the future without breaking anything external.  Once you make it public, it becomes part of an API surface.
