### ISSUE TITLE
ActivityController.Token is private and is not open for extension

### ISSUE THREAD

**Issue by martikyan** [danielgerlag/workflow-core#1181]
**Is your feature request related to a problem? Please describe.**
[WorkflowCore/Services/ActivityController.Token](https://github.com/danielgerlag/workflow-core/blob/12be88701780e1f1b2d5b5b5d98e7ce4df3e9913/src/WorkflowCore/Services/ActivityController.cs#L108) is private which makes `ActivityController` not open for extension.

**Describe the solution you'd like**
I would like to propose separating the `Token` from `ActivityController` and making it a public class.

**Comment by danielgerlag** [comment]
The point is encapsulation, so that these things can be refactored in the future without breaking anything external.  Once you make it public, it becomes part of an API surface.
