### ISSUE TITLE
SyncWorkflowRunner with AsyncSteps

### ISSUE THREAD

**Issue by svha1977** [danielgerlag/workflow-core#1194]
**Describe the bug**
Sync runner does not respect steps of type StepBodyAsync

Version 3.9.0

**To Reproduce**
Create a Async Step like 

```
    public class PrintStep : StepBodyAsync
    {
        public string Message { get; set; }


        public override async Task<ExecutionResult> RunAsync(IStepExecutionContext context)
        {
            await Task.Delay(2000);
            Console.WriteLine(Message);
            return ExecutionResult.Next();
        }
    }
```

With workflow def
```
public class MyWorkflow : IWorkflow<Request>
    {
        public void Build(IWorkflowBuilder<Request> builder)
        {
            
            builder
                .StartWith<PrintStep>().Input(step => step.Message, data => "Start matchflow")
                .Then<PrintStep>().Input(step => step.Message, data => "Yippie");
        }

        public string Id => "1";
        public int Version => 1;
    }
```

With execution

`var matchflowTask = await workflowService.RunWorkflowSync("1", 1, new Request(), "Foo", test.Token); `

Code moves past await and workflow is still running. In reality the workflow is complete only when 
```
while (matchflowTask.Status != WorkflowStatus.Complete)
            {
                
            }
```

Cancellations seem also not passed through

```
var tokenSource= new CancellationTokenSource();
            test.CancelAfter(1000);
            var matchflowTask = await workflowService.RunWorkflowSync("1", 1, new Request(), "Foo", tokenSource.Token); 
```

The flow still runs to completion even if two steps has a delay of 2 sec 

**Expected behavior**
I´ve would have expected the sync runner to be agnostic about the type of steps and in case the step is async then await them within the flow.

**Comment by danielgerlag** [comment]
It is agnostic of the step implementation.  I cannot reproduce what you describe.... could you wrap this in a failing test that we could work through?
