### ISSUE TITLE
How to build Workflow always listen a Event (.WaitFor) and never END

### ISSUE THREAD

**Issue by mircotamburini** [danielgerlag/workflow-core#120]
I would like to keep running util application End a Workflow instance that trigger my Application Events

How can i do that?

**Comment by danielgerlag** [comment]
put it inside a `.While(data => true).Do(...)`?

**Comment by mircotamburini** [comment]
Yeah i try... but inaspetaclty dont Waitfor a Event... but continue to cycle... strage behaviour
