### ISSUE TITLE
JSON translation of Multiple output in WaitFor 

### ISSUE THREAD

**Issue by germandb** [danielgerlag/workflow-core#121]
Hi Daniel I have a WaitFor that have two outputs like
````
.WaitFor("FinishFillDataEvent", (data,context) => contex.Workflows.Id, data => DateTime.Now)
      .Output(data => data.Code, step => (step.EventData as User).Code)
      .Output(data => data.PreferredName, step => (step.EventData as User).PreferredName)
````
I'm now translating my workflows into JSON but I can't find the correct way of make this work, can you help me with this.

**Comment by danielgerlag** [comment]
Here is the documentation for the expression language that backs the JSON definitions

https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#expression-language

What happens with this syntax?
```
"Outputs": { 
          "Code": "step.EventData.Code",
          "PreferredName": "step.EventData.PreferredName",
      }
```

**Comment by germandb** [comment]
I close the issue because the proposed solution Works.

**Comment by bautigaraventa** [comment]
Hello! I don't understand how to translate to Json this:

```
.WaitFor("MyEvent", (data, context) => context.Workflow.Id)
                    .Output(data => data.Estado, step => step.EventData)
```

I have:
```
{
    	"Id": "MyWaitStep",
	"StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
	"Inputs": {
	    "EventName": "\"MyEvent\"",
	    "EventKey": "context.Workflow.Id"
	},
	"Outputs": {
	    "Estado": "step.EventData"
	}
}
```

but it's not working.

I think the problem is in:
`(data,context) => contex.Workflows.Id`

**Comment by bautigaraventa** [comment]
I was missing the "NextStepId" instruction!

Now it works this way:

```
{
    	"Id": "MyWaitStep",
	"StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
	"NextStepId": "MyIfStep",
	"Inputs": {
	    "EventName": "\"MyEvent\"",
	    "EventKey": "context.Workflow.Id"
	},
	"Outputs": {
	    "Estado": "step.EventData"
	}
}
```

**Comment by martinbianchi** [comment]
Hi @germandb, i was fall in the same issue but this solution is not working for me, can you help me please?
I was trying to use EventData as an object not as a string because i need some other properties in the following step after the WaitApproval 

```
 {
       "Id": "WaitApproval",
        "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
        "NextStepId": "IfUpdateFinding",
        "Inputs": {
            "EventName": "\"Approve\"",
            "EventKey": "context.Workflow.Id",
            "EffectiveDate": "DateTime.Now"
        },
        "Outputs":{
            "EventData": "step.EventData.EventData",
            "Description": "step.EventData.Description",
             "PlantLocationId": "step.EventData.PlantLocationId",
             "SectorLocationId": "step.EventData.SectorLocationId",
             "PlantTreatmentId": "step.EventData.PlantTreatmentId",
             "SectorTreatmentId": "step.EventData.SectorTreatmentId",
             "FindingTypeId": "step.EventData.FindingTypeId"
        }
    },
    {
        "Id": "IfUpdateFinding",
        "StepType": "WorkflowCore.Primitives.If, WorkflowCore",
        "NextStepId": "IfRejected",
        "Inputs": { "Condition": "data.EventData == \"UpdateFinding\"" },
        "Do": [[
          {
            "Id": "UpdateFinding",
            "StepType": "Hoshin.CrossCutting.WorkflowCore.Finding.Steps.UpdateFinding, Hoshin.CrossCutting.WorkflowCore",
            "NextStepId": "WaitApproval",
            "Inputs": {
                "Description": "data.Description",
                "PlantLocationId": "data.PlantLocationId",
                "SectorLocationId": "data.SectorLocationId",
                "PlantTreatmentId": "data.PlantTreatmentId",
                "SectorTreatmentId": "data.SectorTreatmentId",
                "FindingTypeId": "data.FindingTypeId"
            }
          }
        ]]
}
```

EventData is a property of my class too, i have the following error:

> No property or field 'EventData' exists in type 'Object'

Thanks and Regards.

Martin B.

**Comment by dipeshtare** [comment]
Hello, I know its closed issue. But I am doing the same kind of work where I am firing an event with the below json body
`{
  "value1": "0",
  "value2": "00",
  "value3": "000"
}`

And my WaitFor structure is like below
`.WaitFor("MyEvent", (data, context) => context.Workflow.Id, data => DateTime.Now)
    .Output(data => data.Value1, step => (step.EventData as MyClass).MyValue1)
    .Output(data => data.Value2, step => (step.EventData as MyClass).MyValue2)
    .Output(data => data.Value3, step => (step.EventData as MyClass).MyValue3)`

But I am getting the error for wait for step -> Object reference is not set to an instance of an object...
I need to have multiple outputs from event firing. Could you please help me here.

**Comment by dipeshtare** [comment]
I found one solution, but its little heavy because I will need to execute on each output statement if I di have multiple output parameters.

I was doing like below which was giving me error NUllReferenceException
`(step.EventData as MyClass).MyValue1`

Solution that runs on my code
`JsonConvert.DeserializeObject<MyClass>(step.EventData.ToString()).MyValue1`

Let me know if any one having other inbuilt solution like in case of Workflow we have JObject as input parameter.
