### ISSUE TITLE
parallel task works sequentially

### ISSUE THREAD

**Issue by JeffrinGirin** [danielgerlag/workflow-core#1223]
Hi,
I need to excute three methods in parallel but the following code excute it in sequential order. Kindly help me to sort the issue.

Also, tried WaitFor & Delay they didn't work as expected. They are waiting for the first branch to finish.

    public class WorkFlow_BusinessService : IWorkflow<InputData>
    {
        public string Id => "Step1";
        public int Version => 1;
        public void Build(IWorkflowBuilder<InputData> builder)
        {
            builder
                .Parallel()
                    .Do(then =>
                        then.StartWith<Data1>()
                                .Input(step => step.inputObj, data => data)
                                .Output((step, data) => step.OutputObj))
                    .Do(then =>
                        then.StartWith<Data2>()
                                .Input(step => step.inputObj, data => data)
                                .Output((step, data) => step.OutputObj)
                            .Then<Data2A>()
                                .Input(step => step.inputObj, data => data)
                                .Output((step, data) => step.OutputObj))
                    .Do(then =>
                        then.StartWith<Data3>()
                                .Input(step => step.inputObj, data => data)
                                .Output((step, data) => step.OutputObj))
                .Join();
        }

    }
	
	
	
    public class Data1 : StepBody
    {
        public InputData inputObj { get; set; }
        public InputData OutputObj { get; set; }
		
        public override ExecutionResult Run(IStepExecutionContext context)
        {
			Console.WriteLine("Data1 Started at " + DateTime.Now.ToString());

			OutputObj = // Internal Method
			
			Console.WriteLine("Data1 Completed at " + DateTime.Now.ToString());
			
            return ExecutionResult.Next();
        }

    }

**Output**
Data1 started at 1/3/2024 15:09:28
Data1 Completed at 1/3/2024 15:09:29

Data2 started at 1/3/2024 15:09:29
Data2 Completed at 1/3/2024 15:09:31

Data2A started at 1/3/2024 15:09:34
Data2A Completed at 1/3/2024 15:09:37

Data3 started at 1/3/2024 15:09:31
Data3 Completed at 1/3/2024 15:09:34

**Expected Output**

Data1 started at 1/3/2024 15:09:28
Data1 Completed at 1/3/2024 15:09:29

Data2 started at 1/3/2024 15:09:28
Data2 Completed at 1/3/2024 15:09:30

Data2A started at 1/3/2024 15:09:30
Data2A Completed at 1/3/2024 15:09:33

Data3 started at 1/3/2024 15:09:28
Data3 Completed at 1/3/2024 15:09:31

**Comment by cjundt** [comment]
Hi,
For long running steps you should consider using thing like :
```csharp
var taskId = context.PersistenceData;
if(taskId==null){
    taskId = StartLongRunningTask();
    return ExecutionResult.Sleep( 500, taskId);
}
var status = GetLongRunningTaskStatus(taskId);
switch(status) {
	case "OK":
		return ExecutionResult.Next( );
	case "Running":
		return ExecutionResult.Sleep( 500, taskId);
}
```
because next step won't be launched until current step Run method returns.

**Comment by AngrySKL** [comment]
I am facing the same issue here, even for the Sample09 the soure code provides works in sequence, have u solved the problem yet?

**Comment by sunnyzees** [comment]
I am facing similar issue. how do we run steps in parallel?

**Comment by danielgerlag** [comment]
That is by design. Since workflows are long running background processes, parallel in this context means that each parallel branch will not block another branch. So if you have a WaitFor or a Delay, etc... in one of the parallel branches, the others will still be free to execute.

**Comment by sunnyzees** [comment]
I tried to put delay as well but I doesn't really execute in parallel. I
have a workflow where I am getting data from three different APIs which I
want to run in parallel  and final activity which waits for previous three
activities. Can it be achieved ?

**Comment by danielgerlag** [comment]
This is a library for long running workflows. Only one step can be executing code at a time but if the step surrenders control back to the workflow before it is finished, other steps can move forward before the current step is resumed.

**Comment by danielgerlag** [comment]
How did you put the delay in?

**Comment by sunnyzees** [comment]
Ah, so I think that explains. There is no way to achieve true parallelism
in this library. To make sure I understand correctly,  only step for a
particular worklow instance can be running. Also then delay does rnot eally
help if we want 3 steps to execute simulatenously

**Comment by danielgerlag** [comment]
It is while one step is waiting for some external thing, that other steps can move forward. The `WaitFor`, `Activity` and `Delay` steps, have this functionality, you could also implement it in a custom step, with specific `ExecutionResult` values returned by the step handler, which instructs the workflow engine to come back to this step later, or when some event has occured.

**Comment by danielgerlag** [comment]
It sounds like your use case needs TPL rather than a workflow engine.

**Comment by sunnyzees** [comment]
Yea but in TPL error recovery would mean running whole operation of getting
data from 3 Apis again.

**Comment by danielgerlag** [comment]
I think you need something like this https://www.pollydocs.org

**Comment by sunnyzees** [comment]
I think I need workflow library with state tracking ,persistence, recovery
and where whole worlflow is not per thread.
.

**Comment by doug62** [comment]
Oh boy! This is a bummer! I can't get it to be truly parallel/concurrent either - the following is misleading as well:
            pBuilders.Services.AddWorkflow(cfg =>
            {
                cfg.UseMaxConcurrentWorkflows(100);
            });

**Comment by danielgerlag** [comment]
> Oh boy! This is a bummer! I can't get it to be truly parallel/concurrent either - the following is misleading as well:
>             pBuilders.Services.AddWorkflow(cfg =>
>             {
>                 cfg.UseMaxConcurrentWorkflows(100);
>             });

No it it not misleading. Multiple workflows do run concurrently. Sounds like you are looking for a task runtime rather than a workflow engine.

**Comment by doug62** [comment]
@danielgerlag Sorry, it's just that the types of C# devs in this area the are familiar with PLINQ and what parallel means in that domain,  Here the .Parallel is in a workflow, a C# dev would naturally assume it would run parallel/concurrent.  I was interested in the Azure/AI provider - my use case for that would have been to fire off 100 requests hopefully in parallel/concurrent - Don't get me wrong, your code here is awesome tho.
