### ISSUE TITLE
Parallel tasks run in sequence not parallel

### ISSUE THREAD

**Issue by AngrySKL** [danielgerlag/workflow-core#1238]
I am using wfc with json which has a Parallel Task which i want to run simultaneously， the json content looks like below

{
  "Id":  "test",
  "Version": 1,
  "Steps": [
    {
       "Id": "Step1"
       “StepType”: "WorkflowCore.Primitives.Sequence, WorkflowCore",
       "Do": [
          [
            {
               "Id": "Branch1",
               "StepType": "MyProject.Steps.Step1, MyProject"
            }
          ],
          [
            {
               "Id": "Branch1",
               "StepType": "MyProject.Steps.Step2, MyProject"
            }
          ]
        ]
     }
  ]
}

I checked the documention and I think this is the correct Parallel Json mentioned here https://workflow-core.readthedocs.io/en/latest/control-structures/#json-yaml-api_4

And I also downloaded the source code of wfc and played around with its sample projects, and the result of Sample13 which demostrates the usage of Parallel steps shows the same result which these taks runs in sequence not simultaneously.

Does anyone know what I do wrong?

**Comment by AngrySKL** [comment]
@danielgerlag could u help me, thanks a lot.

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/issues/785
