### ISSUE TITLE
Multiple processes are multi-threaded in parallel?

### ISSUE THREAD

**Issue by hypnosis01** [danielgerlag/workflow-core#1242]
public class AspSample : StepBody
{
    private static readonly Logger log = LogManager.GetCurrentClassLogger();
    private static volatile int _counter = 0;

    public AspSample()
    {
        log.Debug("AspSample init ...");
    }

    public override ExecutionResult Run(IStepExecutionContext context)
    {
        if (_counter % 2 == 0) 
        {
            Thread.Sleep(2000);
        }
        log.Debug($"StepBody: {nameof(AspSample)}");
        AspSample._counter++;
        return ExecutionResult.Next();
    }
}

var host = serviceProvider.GetService<IWorkflowHost>();
host.StartWorkflow("PTWorkFlow", 1, null);
host.StartWorkflow("PTWorkFlow", 1, null);
host.StartWorkflow("PTWorkFlow", 1, null);
host.StartWorkflow("PTWorkFlow", 1, null);

Multiple process implementations were initiated。

![image](https://github.com/danielgerlag/workflow-core/assets/17917697/b73ce2b1-2733-439d-a72d-32e343386969)

Multiple processes are executed serially.......

**Comment by hypnosis01** [comment]
How do I make each process instance execute in a separate thread?

**Comment by Blackclaws** [comment]
Don't use Thread.Sleep, use Async and Task.Delay and it will work as expected. The problem is Thread.Sleep blocks the thread that enters the workflow execution preventing additional executions from starting.
