### ISSUE TITLE
[Question] Would it be advisable to structure our process using sub-workflows?

### ISSUE THREAD

**Issue by santhanuv** [danielgerlag/workflow-core#1269]
We have a use case involving nested workflows, where one step includes a sub-workflow that must be completed before proceeding to the next step. Although we found Decision Branching ([#486](https://github.com/danielgerlag/workflow-core/pull/486)), which allows the creation of branches with multiple steps, we have a few concerns:

1. Decision branches are condition-based, but our scenario doesn’t involve conditions. We need to execute a sub-workflow as a step without any conditions.
2. Our workflow is lengthy, and we aim to break it down into smaller, manageable sub-workflows.

Would it be advisable to structure our process using sub-workflows? If so, how can we implement this using the package? We've tried a few options, but they don't wait for the sub-workflow to complete before moving on.

**Comment by jordanwallwork** [comment]
How about using Events to signal that the sub-workflow is finished? 

```
        builder
            .StartWith<StartSubWorkflowA>(x=> x.Input(step => step.WorkflowId, (data, ctx) => ctx.Workflow.Id))
            .WaitFor("SubWorkflowACompleted", (data, ctx) => ctx.Workflow.Id))
```

The StartSubWorkflowA step would trigger the sub workflow, passing it the WorkflowId so it can dispatch it in the event to signal that the subworkflow has finished

```
public class StartSubWorkflowA : StepBody
{
    private readonly IWorkflowHost _workflowHost;
    
    public string WorkflowId { get; set; }

    public StartSubWorkflowA (IWorkflowHost workflowHost)
    {
        _workflowHost = workflowHost;
    }

    public override ExecutionResult Run(IStepExecutionContext context)
    {
        // kick off sub-workflow. 

        return ExecutionResult.Next();
    }
}
```

And then as the final step of the sub workflow you'd need to trigger the event letting the "parent" workflow know it can resume:
```
        await _workflowHost.PublishEvent("SubWorkflowACompleted", _workflowId);
```

(I've not tried any of this btw, just how I'd approach it if it were me)

**Comment by cjundt** [comment]
Hi @jordanwallwork,

This is a good idea but I'd rather use a middleware to trigger the "workflowcompleted" event so that you can use any workflow as a subworkflow.
