### ISSUE TITLE
Sample02 - Obsolete method used

### ISSUE THREAD

**Issue by cnayan** [danielgerlag/workflow-core#127]
So, when I saw that message in compilation, I tried to change the code. But it did not work when I ran it.

First, please update the samples so that they don't misguide people in using obsolete method.

Second, please suggest why this modified code, never exits:

```
    public class SimpleDecisionWorkflow : IWorkflow
    {
        public string Id => "Simple Decision Workflow";
        public int Version => 1;

        public void Build(IWorkflowBuilder<object> builder)
        {
            builder
                .StartWith<HelloWorld>()
                .Then<RandomOutput>(randomOutput =>
                {
                    randomOutput
                        .When(_ => 0)
                        .Do(then => then
                            .StartWith<CustomMessage>()
                            .Input(input => input.Message, cm => "Looping back....")
                        )
                        .Then(randomOutput);  //loop back to randomOutput

                    randomOutput
                        .When(_ => 1)
                        .Do(then => then.StartWith<GoodbyeWorld>());
                });
        }
    }
```

**Comment by danielgerlag** [comment]
Hi,

Thank you for pointing out the obsolete methods in the sample, I'd like to encourage you to submit a pull request to clean this up.  Open source is a community effort 😃 

Looking at that code, it looks like the `.Then(randomOutput)` is supposed to be inside the `Do(...)` of as follows

```c#
public class SimpleDecisionWorkflow : IWorkflow
    {
        public string Id => "Simple Decision Workflow";

        public int Version => 1;

        public void Build(IWorkflowBuilder<object> builder)
        {
            builder
                .StartWith<HelloWorld>()
                .Then<RandomOutput>(randomOutput =>
                {
                    randomOutput
                        .When(_ => 0).Do(then => then
                            .StartWith<CustomMessage>()
                                .Input(input => input.Message, cm => "Looping back....")
                            .Then(randomOutput)  //loop back to randomOutput
                        );                        

                    randomOutput
                        .When(_ => 1)
                        .Do(then => then.StartWith<GoodbyeWorld>());
                });
        }
    }
```

**Comment by cnayan** [comment]
It works!

**Comment by extreme8sev** [comment]
Hello Daniel.
I'm trying to deal with multiple outcome. Can you tell me why this code isn't working:
`public void Build(IWorkflowBuilder<object> builder)
        {
            builder.StartWith<RandomOutput>(randomOutput =>
            {
                randomOutput
                   .When(_ => 0)
                   .Do(then => then
                              .StartWith<TaskA>()
                              .Then<TaskB>());
                randomOutput
                   .When(_ => 1)
                   .Do(then => then.StartWith<TaskC>().Then<TaskD>());
            });
        }` 
And if I add any .StartWith before the RandomOutput, it works, like this:
`public void Build(IWorkflowBuilder<object> builder)
        {
            builder.StartWith(context => ExecutionResult.Next()).Then<RandomOutput>(randomOutput =>
            {
                randomOutput
                   .When(_ => 0)
                   .Do(then => then
                              .StartWith<TaskA>()
                              .Then<TaskB>());
                randomOutput
                   .When(_ => 1)
                   .Do(then => then.StartWith<TaskC>().Then<TaskD>());
            });
        }`

**Comment by extreme8sev** [comment]
Hello Daniel. 
I'm trying to deal with "MultipleOutcome" example.
The workflow isn't working if I use it like this:
```
public void Build(IWorkflowBuilder<object> builder)
        {
            builder.StartWith<RandomOutput>(randomOutput =>
            {
                randomOutput
                   .When(_ => 0)
                   .Do(then => then
                              .StartWith<TaskA>()
                              .Then<TaskB>());
                randomOutput
                   .When(_ => 1)
                   .Do(then => then.StartWith<TaskC>().Then<TaskD>());
            });
        }
```
And it's working if I use it like this:
```
public void Build(IWorkflowBuilder<object> builder)
        {
            builder.StartWith(context => ExecutionResult.Next())
                   .Then<RandomOutput>(randomOutput =>
                    {
                        randomOutput
                           .When(_ => 0)
                           .Do(then => then
                                      .StartWith<TaskA>()
                                      .Then<TaskB>());
                        randomOutput
                           .When(_ => 1)
                           .Do(then => then.StartWith<TaskC>().Then<TaskD>());
                    });
        }
```
Is there some things I should know about it?

**Comment by danielgerlag** [comment]
That seems odd... I will have to debug that
