### ISSUE TITLE
.NET Core 2.0 port

### ISSUE THREAD

**Issue by cnayan** [danielgerlag/workflow-core#129]
I emailed you, Daniel. Since I didn't get response, posting the question here:

I've:
1) Ported the full solution to .Net Core & Standard 2.0
2) Updated all except one Nuget packages to latest version.

Build is successful, and samples run as usual.

Do you want to merge the changes? Shall I create a pull request?

Let me know.

Regards,
Nayan

**Comment by cnayan** [comment]
Thanks for reply, Daniel.

We are not just consuming the lib, but going to add some more features and providers. But we work on 2.0 for is compatibility with .Net Framework (https://stackify.com/net-core-2-0-changes/)

I don't have .Net 1.x runtimes even installed on my machine. Hence, I had to change coffee and target to 2.0.

So, if you still feel that 1.x is the best target for wf-core, I'm okay with it. But I'll continue developing it separately on my fork.

Thanks Daniel!

**Comment by cnayan** [comment]
I don't know why there is "coffee" in the conversation instead of "code" 😀

**Comment by danielgerlag** [comment]
I would definitely like to learn more about the features you would like to add and most certainly would like to be able to merge them into the main repo, are the changes you are planning for the core library or just additional provider libraries?

**Comment by cnayan** [comment]
Right now, I have MySQL provider in mind. Maybe, your MS SQL provider can connect with MySQL, but I have to check.

Daniel, I did not get your reply on email. Just FYI.

**Comment by cnayan** [comment]
Closing this thread, as the answer to "port to 2.0" is given.
