### ISSUE TITLE
Is this lib maintained? Or still active development?

### ISSUE THREAD

**Issue by nrubiano** [danielgerlag/workflow-core#1293]
Hi @danielgerlag, 

First thanks for your work here, this library is really good and I'm wondering if the library is still in active development? or are you looking for maintainers? 

I'm evaluating workflows libraries for an application I'm building so this is the most viable fit but I've not seen too much movement with Issues and PR's.

Thank you again.

**Comment by pedrojreis** [comment]
I wonder the same. We've done some PRs that got merged but no new releases came out.

**Comment by danielgerlag** [comment]
Apologies for the slow movement. I will get a release done in the next few days, and see if there are any other PRs that could be included.
