### ISSUE TITLE
Workflow-core and Blazor Wasm - UI locks when starting workflow-core

### ISSUE THREAD

**Issue by AshD** [danielgerlag/workflow-core#1295]
**Describe the bug**
Workflow-core works fine in a WPF app. 
In a Blazor WASM app, After calling workflowHost.Start(); the Blazor WASM web UI is unresponsive.

**To Reproduce**
1. Create a Blazor Wasm .NET 8 app. 
2. Add WorkflowCore nuget packages
3. Call  **workflowHost.Start()**; on startup of the app

**Expected behavior**
Blazor UI does not freeze

**Additional context**
Wondering if this is because of a threading issue where the UI thread is locked

**Comment by Blackclaws** [comment]
Blazor WASM does not support Threads reliably at this point, anything that relies on a Threadpool will make problems.
