### ISSUE TITLE
Workflow definition is stored in MongoDB , Would it be possible to store into Sql server DB

### ISSUE THREAD

**Issue by chandraarora** [danielgerlag/workflow-core#1296]
We have started 3 years back using the workflow core and workflow definition was stored in mongo db and it was not possible to store inside Sql server. We have all data inside Sqlserver only definition inside mongo db. 

Is there a way to store definition inside SQL server. is Library DSL implented only in mongo DB?

Thank you in advance for feedback!

**Comment by danielgerlag** [comment]
You can store the DSL in anything you like. It is just a json string.
