### ISSUE TITLE
Information on which apps use Workflow-core

### ISSUE THREAD

**Issue by cnayan** [danielgerlag/workflow-core#130]
Hi Daniel,

**This is not an issue, but a query.**

Can you please, if you (or anyone else here) know, tell some commercial or non-commercial apps using Workflow-core?

I'm evaluating whether we can use this app for serious enterprise app development purpose or not.

Thanks!

**Comment by freerider7777** [comment]
Good question, seems threre no real world cases...

**Comment by lankaapura** [comment]
I found this one:
https://github.com/using-system/ProcessMyMedia

@danielgerlag maybe create a new wiki page with a list of repos that uses workflow-core in production.
