### ISSUE TITLE
WaitFor fired only once, when events published rapidly

### ISSUE THREAD

**Issue by cnayan** [danielgerlag/workflow-core#132]
I realize that the documentation for WaitFor doesn't tell if the listener for the event is waiting for one time, or will capture the events then onwards.

Assuming that the workflow waits single time, I created a loop:

```
public void Build(IWorkflowBuilder<MyData> builder)
{
  builder
    .StartWith<Start>()
    .Then<Initialize>(initThen =>
    {
      initThen
        .Parallel()
          .Do(doBuilder =>
          {
            var waiter = doBuilder.StartWith(_ => ExecutionResult.Next());
            waiter.WaitFor(Constants.Receive, (_, ctx) => ctx.Workflow.Id, data => DateTime.Now)
            .Then<InformStep>()
            .Then(waiter); // go back and wait for next event
          });
    })
    .Then<SetupMQListeners>()
}
```

Here is how the event is published in another class:

```
public EventingBasicConsumer Consumer { get; set; }
public void SetupHandlers()
{
  var data = _serviceProvider.GetRequiredService<MyData>();
  data.Channel.BasicConsume(queue: Constants.Receive, autoAck: true, consumer: Consumer);
  Consumer.Received += (sender, e) =>
  {
    //...
    Console.WriteLine($"Message received: {message}");
    host.PublishEvent(eventName, ID, message); // <============ Publishing the event
  };
}
```

And finally, here is the ```InformStep```:

```
internal class InformStep : StepBody
{
  public override ExecutionResult Run(IStepExecutionContext context)
  {
    Console.WriteLine("I'm informed");
    return ExecutionResult.Next();
  }
}
```

I published 3 events, but only 1 was received via "WaitFor". Here is how output looks like:

```
Workflow started - Simple Workflow
========================================
Message received: 2
Message received: 3
Message received: 4
I'm informed
```

I expected this output:

```
Workflow started - Simple Workflow
========================================
Message received: 2
Message received: 3
Message received: 4
I'm informed
I'm informed
I'm informed
```

Whether I create the loop or not, the result remains same, which makes me wonder if WaitFor is waiting for one time event or not.

```
            waiter.WaitFor(Constants.Receive, (_, ctx) => ctx.Workflow.Id, data => DateTime.Now)
            .Then<InformStep>()
            .Then(waiter); // <-------------- This did not matter
```

Can anyone tell if this is bug, or my expectation is incorrect?

**Comment by cnayan** [comment]
```SetupHandlers()``` is called from the ```Run``` method of ```SetupMQListeners```.

So, it would seem that the **SetupHandlers** is not called until the workflow was built completely.

```
    internal class SetupMQListeners : StepBody
    {
        // ...
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            var data = context.Workflow.Data as MyData;
            if (data != null)
            {
                data.Consumer.SetupHandlers(); // <============== Here
            }

            return ExecutionResult.Next();
        }
    }
```

Ideally, the execution should not start before the builder is done building the workflow.

**Comment by cnayan** [comment]
This also did not work

```
initThen
	.Parallel()
	.Do(then =>
		then.StartWith<Dummy>(waiter =>
			waiter.Then<Dummy>(flow =>
				flow.WaitFor(Constants.Receive, (_, ctx) => ctx.Workflow.Id, data => DateTime.Now)
				.Then<InformStep>()
				.Then(waiter) // loop
			)
		)
	);
```

Dummy is:
```
internal class Dummy : StepBody
{
	public override ExecutionResult Run(IStepExecutionContext context)
	{
		return ExecutionResult.Next();
	}
}
```

**Comment by danielgerlag** [comment]
The `DateTime.Now()` expression is only evaluated once that iteration of that step is reached - not on building of the workflow, so if the `PublishEvent` occurs before your effective date expression, it will not fire.

**Comment by cnayan** [comment]
I'm not sure I understand the use of that, but I understand that it is not evaluated immediately. 👍 

So, I removed the datetime expression. Now it goes into infinite loop and doesn't wait.

Now what?!

**Comment by cnayan** [comment]
@danielgerlag Do we even need a looped WaitFor, like what I did in the example? Is the WaitFor effective like C# event handlers for events fired, as log as they are subscribed?

**Comment by cnayan** [comment]
So, I thought that since there is bug in Parallel & Do flow, I'll simplify the workflow and then try again. Result was again same as mentioned above.

```
builder
  .StartWith<Start>()
  .Then<Initialize>(waiter =>
    waiter.Then<Dummy>(x =>
      x.WaitFor(Constants.Receive, (_, ctx) => ctx.Workflow.Id)
      .Then<InformStep>()
      //.Then(waiter)  // <== when commented, event captured only once; when enabled, goes in forever loop
    )
  )
  .Then<SetupMQListeners>();
```

What am I missing?

**Comment by danielgerlag** [comment]
This is how events work:

If you have a `WaitFor` for a given `EventName` and `EventKey` pair, the engine will check all historic events that are dated after the effective date that match this step, including ones that may have triggered other `WaitFor` steps in the past.  By evaluating the effective date field when the step is reached, it can determine the current date time or calculate a required effective date given the data object that is persisted along with the workflow.  You can also specify a different `EventKey` by using an expression that will also only get evaluated when that step is reached.

Does that make sense?  I should probably make this more explicit in the docs.

**Comment by cnayan** [comment]
Okay, I understand. It seems like we need not an expression, but DateTime object in WaitFor. I'll experiment.

So, WaitFor is required to be declared once, and not looped.

I'll post my experiment's results soon.

**Comment by cnayan** [comment]
Okay! After studying the code, I think once the event is captured by subscription, the subscription is terminated: `_persistenceStore.TerminateSubscription`

in
```
at WorkflowCore.Services.BackgroundTasks.EventConsumer.SeedSubscription(Event evt, EventSubscription sub, CancellationToken cancellationToken)
at WorkflowCore.Services.BackgroundTasks.EventConsumer.ProcessItem(String itemId, CancellationToken cancellationToken)
at WorkflowCore.Services.BackgroundTasks.QueueConsumer.ExecuteItem(String itemId)
```
So, the theory that WaitFor will capture all the events, is **not correct**.

**Comment by cnayan** [comment]
So @danielgerlag how do I make a workflow which will forever wait for certain type of event? Please help.

**Comment by germandb** [comment]
Can you give a more detailed example of your using case, because I can't think in a workflow that needs a activity that never end, how do you know that the workflow end, if you have and event that allways is waiting.

**Comment by cnayan** [comment]
The way events in c# work, think of the same.

I wish to listen for an event and associate a handler to it. Until, I choose to unsubscribe, the handler should be able to process the events.

All I need is a workflow to do the same. I thought WaitFor could handle it, but I'm not sure anymore.

Does it make sense to you?

**Comment by danielgerlag** [comment]
A workflow is a long running process but is not meant to live forever, it sounds like you might be looking for more of a state machine.

Perhaps you should see if this library makes more sense for this use case:

https://github.com/dotnet-state-machine/stateless

You could also use the expression parameter for the `EventKey` to append an incremental number on the end, so that each event has a unique key and listener iteration dedicated to it.

**Comment by cnayan** [comment]
I have experimented on stateless for a month before I found this library. I'm familiar with it. It needs lot of development to be used as a configurable workflow engine. I like workflow-core better 👍 

I'll try your suggestion, @danielgerlag and report back. Thanks for help, @danielgerlag @germandb

**Comment by cnayan** [comment]
I'm abandoning this mechanism that we discussed. I'll use a loop if WaitFor has to be executed. Thanks.

**Comment by yuzhaoMR** [comment]
> I'm abandoning this mechanism that we discussed. I'll use a loop if WaitFor has to be executed. Thanks.

I have encountered the same situation,How do you cycle?thanks

**Comment by slav4ik51493** [comment]
Hello everyone. 
I've faced with the same issue.

```
```

**Comment by slav4ik51493** [comment]
Hello everyone. 
I've faced with same issue.

Program.cs
```using ConsoleApp5;
using Microsoft.Extensions.DependencyInjection;
using WorkflowCore.Interface;

IServiceProvider serviceProvider = ConfigureServices();

//start the workflow host
var host = serviceProvider.GetService<IWorkflowHost>();
host.RegisterWorkflow<EventSampleWorkflow, MyDataClass>();
host.Start();

var initialData = new MyDataClass();
var workflowId = host.StartWorkflow("EventSampleWorkflow", 1, initialData).Result;


while (true)
{
    Console.ReadLine();
    Console.WriteLine($"activity in static: {Attempt.ActivityId}");
    var activity = await host.GetPendingActivity(Attempt.ActivityId, workflowId);

    if (activity != null)
    {
        host.SubmitActivitySuccess(activity.Token, Guid.NewGuid()).Wait();
        Console.WriteLine($"Submit sent: {Attempt.ActivityId}");
    }
}
host.Stop();

static IServiceProvider ConfigureServices()
{
    //setup dependency injection
    IServiceCollection services = new ServiceCollection();
    services.AddLogging();
    services.AddWorkflow();

    var serviceProvider = services.BuildServiceProvider();
    return serviceProvider;
}

public static class Attempt
{
    public static int AttemptNumber = 0;
    public static string ActivityId = string.Empty;
}
```

EventSampleWorkflow.cs

```namespace ConsoleApp5
{
    public class EventSampleWorkflow : IWorkflow<MyDataClass>
    {
        public string Id => "EventSampleWorkflow";

        public int Version => 1;

        public void Build(IWorkflowBuilder<MyDataClass> builder)
        {
            builder
                .StartWith(context => ExecutionResult.Next())
                .Then<CustomMessage>()
                .Then(context => Console.WriteLine("workflow complete"));
        }
    }
}
```

CustomMessage.cs
```namespace ConsoleApp5
{
    public class CustomMessage : StepBody
    {

        public string Message { get; set; }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Attempt.ActivityId = Guid.NewGuid().ToString().GetHashCode().ToString();
            Console.WriteLine($"CustomMessage step executed with activity: {Attempt.ActivityId}");
            if (Attempt.AttemptNumber < 5)
            {
                Attempt.AttemptNumber++;
                Console.WriteLine($"CustomMessage step wait for activity: {Attempt.ActivityId}");
                return ExecutionResult.WaitForActivity(Attempt.ActivityId, Guid.NewGuid(), DateTime.UtcNow);
            }
            Console.WriteLine("CustomMessage step finished");
            return ExecutionResult.Next();
        }
    }
}
```

My output:
```CustomMessage step executed with activity: -1995911260 // first call CustomMessage.Run method
CustomMessage step wait for activity: -1995911260

activity in static: -1995911260
Submit sent: -1995911260 // first send event
CustomMessage step executed with activity: 286437905 // second call CustomMessage.Run method
CustomMessage step wait for activity: 286437905

activity in static: 286437905
Submit sent: 286437905 // second sent event
// NO third call CustomMessage.Run!!!!!!!!!!!!!
activity in static: 286437905
```

I'm trying to do logic with several pause/resume the same step. 

Business case for better understanding situation:
I need to try purchase some thing on web site. If balance is negative then I will get notification. When I've topped up my account I need resume my workflow for calling current step again. But let's image that I publish event for resuming step before topping up my account. Then I got frozen step and I couldn't resume my workflow.

How I can to do it? @danielgerlag
