### ISSUE TITLE
When Parallel() used, empty Do() causes following step to execute inside Do

### ISSUE THREAD

**Issue by cnayan** [danielgerlag/workflow-core#133]
Issue is that the **Bye** step is executed twice in the given flow because there are two **Do** invocations declared (although there is nothing in them.)

Here is the code:

```
public void Build(IWorkflowBuilder<MyData> builder)
{
	builder.StartWith<Start>()
		.Then<Dummy>(initThen =>
		{
			initThen.Parallel()
				.Do(then => { })
				.Do(then => { });
		})
		.Then<Bye>();
}
```

where steps are:

```
internal class Start : StepBody
{
	public override ExecutionResult Run(IStepExecutionContext context)
	{
		Console.WriteLine("Workflow started - " + context.Workflow.WorkflowDefinitionId);
		return ExecutionResult.Next();
	}
}

internal class Dummy : StepBody
{
	public override ExecutionResult Run(IStepExecutionContext context)
	{
		return ExecutionResult.Next();
	}
}

internal class Bye : StepBody
{
	public override ExecutionResult Run(IStepExecutionContext context)
	{
		Console.WriteLine("Workflow terminating - " + context.Workflow.WorkflowDefinitionId);
		return ExecutionResult.Next();
	}
}
```

Observed output:
```
Workflow started - Simple Workflow
Workflow terminating - Simple Workflow
Workflow terminating - Simple Workflow
Workflow terminating - Simple Workflow
```

Expected output is:
```
Workflow started - Simple Workflow
Workflow terminating - Simple Workflow
```

I'm trying to figure out the reason of redundant runs of step, but I need help.

Thanks!

**Comment by danielgerlag** [comment]
This seems to be a bug if you have an empty `Do` block.  It works as expected if there are actions inside the `Do` blocks.

**Comment by cnayan** [comment]
Well, actually I have noticed that if there is no wait inside the do, even then there is repetition. I'll provide an example ASAP

**Comment by danielgerlag** [comment]
resolved in version 1.6.2

**Comment by cnayan** [comment]
Can you share the commit details for the patch? Thanks

**Comment by cnayan** [comment]
@danielgerlag I took you latest code to see your patch. You've put a check for empty "Do" block and threw exception.

I don't think this is the right fix. It would throw exception in valid case as well. Example:

```
            builder.StartWith<Start>()
                .Then<Dummy>(initThen =>
                {
                    initThen.Parallel()
                        .Do(then => Console.WriteLine("Do1"))
                        .Do(then => Console.WriteLine("Do2"))
                        ;
                })
                .Then<Bye>();
```

**Comment by cnayan** [comment]
This bug needs to be re-opened.

**Comment by cnayan** [comment]
Something is seriously wrong.

I removed your "throw exception" fix to find a better one. Then I observed that the "Do" is running before the workflow is built even!!

Here is a snap in VS:
![do_bug](https://user-images.githubusercontent.com/2213067/39418388-ca217c30-4c77-11e8-8f4c-6d1b74c33938.PNG)

I expected that the first breakpoint that should be hit will be the "return" statement. But no, that's not the case.

The steps are running before the build is done building the flow. This is breaking my expectation from a workflow engine.

I'll put some effort in fixing it right, if I don't give up.

**Comment by cnayan** [comment]
It seems to me that currently "Do" is about building the flow, not actually defining what is to be done in the flow. If that is the case, then my above sample code is invalid, which leads to this question - why is the "Do" method taking `Action` as parameter then Because one can write any code in the _action_.

But if my sample is valid, then I don't understand the design of "Parallel" ad "Do".

Can you help, @danielgerlag ? Thanks much! Really appreciate your inputs.

**Comment by cnayan** [comment]
I checked your example on Parallel again, and tried to use it in same manner. It worked. I guess I was trying to shorten up the setup of the flow, and that's why I was failing. Sorry for the confusion.

As per your documentation, this works:
```
            builder.StartWith<Start>()
                .Then<Dummy>(initThen =>
                {
                    initThen.Parallel()
                        .Do(then => then.StartWith<InformStep>())
                        .Do(then => then.StartWith<InformStep>())
                        ;
                })
                .Then<Bye>();
```
The output (as observed), is same as expected:
```
Workflow started - Simple Workflow
========================================
========================================
Workflow terminating - Simple Workflow
I'm informed
I'm informed
```
So, your way works.


I've enhanced the `ParallelStepBuilder` in my repository to let me work with my syntax, as well.
```
            builder.StartWith<Start>()
                .Then<Dummy>(initThen =>
                    initThen.Parallel()
                        .Do<InformStep>()
                        .Do<InformStep>()
                )
                .Then<Bye>();
```
