### ISSUE TITLE
Use workflow-core in a distributed fashion

### ISSUE THREAD

**Issue by skavuparambil** [danielgerlag/workflow-core#141]
Currently we are evaluating workflow-core for project. One of our major goal is that it should support distributed workflow. E.g.: some actions (like executing an exe) should be invoked in specific node(s) only. Is that possible with workflow-core? Also, could you please explain the steps to create clustering using RabbitMQ and RedLock

**Comment by danielgerlag** [comment]
There is no functionality to constrain certain actions to specific nodes.  It operates by a shared work queue, each node pulls a workflow deemed ready for execution from the queue in a competing consumer fashion.  It then also uses a distributed lock managers to ensure only one node can process a given workflow instance at a time.  So all your nodes need to be configured to point to the same persistence store, the same RabbitMQ and the same Redis.

You would set it up something like this
```c#
services.AddWorkflow(config => 
{
    config.UseSqlServer(...);
    config.UseRabbitMQ(new ConnectionFactory() { HostName = "QueueHost" };
    config.UseRedlock(new DnsEndPoint("host1", 6379), new DnsEndPoint("host2", 6379));
});
```

https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.QueueProviders.RabbitMQ

https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.LockProviders.Redlock

**Comment by Miggleness** [comment]
@danielgerlag are you open to adding support for inclusion and exlusion filtering per node instance in the work queue? 

Got to say, Im like this project a lot. I built a more primitive job coordinator at work 2 months ago and just found out about your project yesterday. Im planning to adopt workflow.core in our company.

**Comment by danielgerlag** [comment]
@Miggleness I would be open to it but would gauge it on demand from the community
