### ISSUE TITLE
Workflow Steps History

### ISSUE THREAD

**Issue by tameyer1** [danielgerlag/workflow-core#147]
Has anyone implemented a persisted workflow step history?
Issue #12 was an original ask on this subject.

Thanks!

**Comment by AnirudhBharti** [comment]
public async Task<WorkflowInstance> ShowHistoryOfExecutedPath(WorkflowInstance workflow)
        {
            var alreadyExecutedPath = workflow.ExecutionPointers.Where(x => x.Active.Equals(false) && x.Status == PointerStatus.Complete);
            var def = _registry.GetDefinition(workflow.WorkflowDefinitionId, workflow.Version);
            if (def == null)
            {
                _logger.LogError("Workflow {0} version {1} is not registered", workflow.WorkflowDefinitionId, workflow.Version);
                 return await Task.FromResult(workflow);
            }

            foreach (var pointer in alreadyExecutedPath)
            {
                var step = def.Steps.First(x => x.Id == pointer.StepId);
                Console.WriteLine($"{step.Tag} Step is already Completed");
            }

            var lastExecutedPath = workflow.ExecutionPointers.LastOrDefault(x => x.Active.Equals(false));
            if (lastExecutedPath.Status == PointerStatus.WaitingForEvent)
            {
                workflow.ExecutionPointers.Where(x => x.StepId == lastExecutedPath.StepId).FirstOrDefault().Active = true;
                return await Task.FromResult(workflow);
            }

            return await Task.FromResult(workflow);
        }

**Comment by tameyer1** [comment]
Thanks. I'll give this a try.
