### ISSUE TITLE
How to use the workflow persistence?

### ISSUE THREAD

**Issue by biapar** [danielgerlag/workflow-core#148]
How to use the workflow persistence?
I've to build a small workflow ( document approval ) into a web application where at each step, it need to wait some input data from different user but long for time.

**Comment by danielgerlag** [comment]
Hi,

You simply need to configure which persistence provider you want to use on app start up.
See this list for details on each of the available providers:
https://github.com/danielgerlag/workflow-core/wiki/07.-Persistence-Providers
