### ISSUE TITLE
Bug - 'if when steps never complete

### ISSUE THREAD

**Issue by tatejones** [danielgerlag/workflow-core#150]
Hi,

If I have a 'if' or 'when' declared in a workflow and they are executed, after the execution the these steps  continue to be executed.

For example,

            builder
                .StartWith<SayHello>()
                    .Input(step => step.Data, data => data)
                .Then<DetermineSomething>(determineSomething => determineSomething
                   .Input(step => step.Data, data => data)
                   .If(outcome => outcome.Counter <= 10).Do(then => then
                       .StartWith<PrintMessage>()
                           .Input(step => step.Message, data => "Outcome is less than 10")
                       .Then(determineSomething)
                   )
                   .Then<SayGoodbye>()
                   .EndWorkflow()
                );   
.....
    public class DetermineSomething : StepBody
    {
        public MyData Data { get; set; }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Data.Counter++;
            Console.WriteLine($"DetermineSomething {Data.Counter}");
            return ExecutionResult.Outcome(Data.Counter);
        }
    }

The 'if' in this case is evaluated and then the next step is redirected to 'DetermineSomething'.  However, the 'if' step still gets executed, even after the 'SayGoodbye' is completed.  If persistence is enabled you can see the status of this step is set to 2 (running) after the workflow is completed.  

Another observation, if EndWorkflow() is omitted the SayGoodbye step is executed for every iteration of the loop (counting up to 10).   That doesn't seem correct.

Log

Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step SayGoodbye on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Goodbye
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672
Starting step  on workflow ee6faacb-8c6e-4de8-9979-ece768c8b672

**Comment by danielgerlag** [comment]
I am not able to recreate your scenario with the code you have attached. If you could attach the full compilable project I could debug it for you.  But on the surface, I'm not sure why you are using outcomes, perhaps try using an output on the step

**Comment by tatejones** [comment]
I believe the behaviour is recursion, which is probably intentional by design.   I will pull some code to demo the output.

**Comment by danielgerlag** [comment]
Nope, I think it's because you are using an outcome in your step implementation, without a `When`, so I will not be able to select the appropriate next step.  Try change the `.Outcome` to `.Next` and use an output on the step data instead

**Comment by tatejones** [comment]
I found the issue.   Since the Then(determineSomething) is causing recursion I shouldn't be terminating the workflow (EndWorkflowbefore), as there are incomplete child ExecutionPointers.
