### ISSUE TITLE
Building in a "Start" step

### ISSUE THREAD

**Issue by jeremycook** [danielgerlag/workflow-core#152]
I find myself frequently using `workflowBuilder.StartWith(context => ExecutionResult.Next())` followed by what I actually want to do. What are your thoughts on providing a built-in (extension) method that essentially wraps that? Something like:

    public static IStepBuilder<TData, InlineStepBody> Start<TData>(this IWorkflowBuilder<TData> builder)
    {
        return builder.StartWith(context => ExecutionResult.Next());
    }

It would be used like:

    workflowBuilder.Start().Recur(...)....
    workflowBuilder.Start().WaitFor(...)....
    workflowBuilder.Start().Parallel()....

Not sure if "Start" is the best word for general usage. That is just how I would use it.

**Comment by danielgerlag** [comment]
I get what you're saying... Let me think about it, as I would prefer a cleaner option where one does not have to create a dummy step

**Comment by softwareguy74** [comment]
Would be a  LOT cleaner.
