### ISSUE TITLE
Assign workflow instance name/identifier

### ISSUE THREAD

**Issue by Miggleness** [danielgerlag/workflow-core#153]
I’ve a need to explicitly set an IT Ops friendly identifier for my workflow instances for searching and investigatory purposes. 

Is this supposed to be the purpose of the Workflow Instance Reference property?  If so, we should be able to assign a value to it when starting a new workflow. 

If that isnt the case we can come up with a solution and i can submit a PR

**Comment by danielgerlag** [comment]
Yes, that was the intention of the `Reference` field, however, I never got around to exposing it anywhere.
A PR would be most welcome 😃
