### ISSUE TITLE
[ExecutionPointer] table having more records while using Recur option

### ISSUE THREAD

**Issue by Veeramani41** [danielgerlag/workflow-core#154]
I trying to use Recur option in my workflow to check the status of external api. its working fine. this Recur step creating more records in [ExecutionPointer] table. it create size issue in database. Any suggessions. how can I handle this issue.

**Comment by danielgerlag** [comment]
How often are you running the recur and how long does your workflow live for?

**Comment by Veeramani41** [comment]
Every 15 seconds and workflow live around 24 hrs( this is based on the parameter max 24 hrs)

**Comment by danielgerlag** [comment]
Every time the recur fires it will create a new execution pointer, we could look at options to optimize how many execution pointer records get read from the DB when running a workflow.
What is your use case... do you really need to fire it every 15 seconds?

**Comment by Veeramani41** [comment]
Use case: we are sending Invite code like (OTP) using third party api to start a process from mobile. the invite code's expire time will vary from 1h to 1day(it is configurable). So we need to know status and device details from third party api(internet exposed) ours internal one. so every 15 seconds we are calling the third party api to know the status.

**Comment by danielgerlag** [comment]
Does the 3rd party have webhooks that you could wire up to a `PublishEvent`?  If not, could you write a wrapper around the 3rd party service that polls it and then calls a `PublishEvent` to trigger a `WaitFor`?

**Comment by Veeramani41** [comment]
I just split my workflow into two part and I written the wrapper for polling the 3rd party service, now it is working fine, what you suggested also a good option, let me try.
