### ISSUE TITLE
PublishEvent / SqlServer provider.

### ISSUE THREAD

**Issue by numbus999** [danielgerlag/workflow-core#155]
Hello,

I am trying to use sqlServer persistence.
but when I publish an event 
ex:
int myData = 1; 
host.PublishEvent("Niv1ApprovalEvent", anID , myData);_

I get an error entry in the wfc.ExecutionError table with the following message:  'Object of type 'System.Int64' cannot be converted to type 'System.Int32'.
#
This work if I don't use a persistence provider.

An idea about that ?
 #Thanks.

**Comment by danielgerlag** [comment]
I have deployed a new version (1.6.5) to Nuget that should resolve this issue

**Comment by numbus999** [comment]
great ! works fine.
Many Thanks.
