### ISSUE TITLE
Azure

### ISSUE THREAD

**Issue by peterkozak** [danielgerlag/workflow-core#157]
Hi Daniel,

i'm using Azure for DLM and Queueing support.

Unfortunately when the service starts, I'll get a Exception:

2018-07-12T11:30:50|DE-SFLAB-03|ERROR|P:14172|T:16||Program|C:|A:|T:|Unhandled Exception occured!
EXCEPTION: System.Net.WebException: The remote server returned an error: (409) Conflict.
Request Information
RequestID:c66d0eaf-c01e-0021-0bc3-19610a000000
RequestDate:Thu, 12 Jul 2018 09:30:49 GMT
StatusMessage:The specified container already exists.
ErrorCode:ContainerAlreadyExists
ErrorMessage:The specified container already exists.
RequestId:c66d0eaf-c01e-0021-0bc3-19610a000000
Time:2018-07-12T09:30:50.0449712Z

Do I do something wrong? Or doesn't WF Core realize that it created the Azure Objects already during the first start?

Another error message during startup and after start of a workflow is

2018-07-13T07:27:57|DE-SFLAB-01|ERROR|P:22364|T:6||Program|C:|A:|T:|Unhandled Exception occured!
EXCEPTION: System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> System.Data.SqlClient.SqlException: Invalid column name 'CreatedOn'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)

The DB Structure has been created by WF Core...

Thanks for a hint,

--Peter

**Comment by danielgerlag** [comment]
That Azure log is just the response from Azure Storage indicating that the container already exists.  Is you app failing to start?

With regards to the Sql error, we do not have a column with the name `CreatedOn`, are you using another version of Entity Framework side by side? 

see https://stackoverflow.com/questions/12193465/entity-framework-4-3-invalid-column-name-createdon
