### ISSUE TITLE
If I have multiple wait events, why can I only trigger the first one after I register?

### ISSUE THREAD

**Issue by zhangxiaopeng2** [danielgerlag/workflow-core#158]
public void Build(IWorkflowBuilder<MyDataClass> builder)
        {
            builder
                .StartWith(context => ExecutionResult.Next())
                //.Parallel().Do(then =>
                //        then.StartWith(context =>
                //            ExecutionResult.Next()).WaitFor("MyEvent1", (data, context) => context.Workflow.Id, data => DateTime.Now).Output
                //            (data => data.StrValue, step => step.EventData).Then<CustomMessage>().Input(step => step.Message, data => "第一步中的第1小步完成了")
                //           )
                //.Do(then => then.StartWith<PrintMessage>().Input(step => step.Message, data => "第一步中的第二小步完成了")).Join()

                .WaitFor("MyEvent", (data, context) => context.Workflow.Id, data => DateTime.Now)
                    .Output(data => data.StrValue, step => step.EventData)
                .Then<CustomMessage>()
                    .Input(step => step.Message, data => "The data from the event is " + data.StrValue)

                .WaitFor("MyEvent1", data=>"0")
                .Output(data => data.StrValue, step => step.EventData)
                .Then<CustomMessage>()
                .Input(step => step.Message, data => "The data from the event is " + data.StrValue)

                .Then(context => Console.WriteLine("workflow complete"));
        }
//register
            host.PublishEvent("MyEvent" +
                              "", workflowId, "121");
            host.PublishEvent("MyEvent1" + "",
                workflowId, "11");

**Comment by danielgerlag** [comment]
Could you please clarify what you are trying to achieve?
