### ISSUE TITLE
Error processing inputs or outputs that are string and the property type is Guid?

### ISSUE THREAD

**Issue by germandb** [danielgerlag/workflow-core#159]
Hi Daniell I'm  found a bug in the implementation of the ProcessInputs and ProcessOutputs methods 
when you define the inputs or outputs in the Json file the WorkflowCore trate this values as strings, the problem with this is that the properties of type Guid, Byte Array or any nullable type give and exception when you try to use setValue.

To solve this I add the following code to the ProcessOutputs method, for the  ProcessInputs it's the same but change the data.GetType() for step.BodyType.
 
                Type propertyType = data.GetType().GetProperty(member.Member.Name).PropertyType;
                propertyType = Nullable.GetUnderlyingType(propertyType) ?? propertyType;

                TypeCode typeCode = Type.GetTypeCode(propertyType);

                object value = resolvedValue;

                switch (typeCode)
                {
                    case TypeCode.Object:
                        if (propertyType == typeof(Guid) || propertyType == typeof(Guid?))
                        {
                            switch (resolvedValue)
                            {
                                case string stringValue:
                                    value = new Guid(stringValue);

                                    break;
                                case byte[] byteValue:
                                    value = new Guid(byteValue);

                                    break;
                                default:
                                    value = resolvedValue;

                                    break;
                            }

                            value = Convert.ChangeType(value, propertyType);
                        }

                        data.GetType().GetProperty(member.Member.Name).SetValue(data, value);

                        break;
                    default:
                        data.GetType().GetProperty(member.Member.Name).SetValue(data, resolvedValue);

                        break;
                }

**Comment by danielgerlag** [comment]
The JSON inputs and outputs are actually expressions, not strings.  You should be able to define a Guid in the expression.  See https://github.com/StefH/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#expression-language
