### ISSUE TITLE
Add Step "Name" to Persistence

### ISSUE THREAD

**Issue by jonfairchild1** [danielgerlag/workflow-core#16]
How difficult would it be to add the Step Name to the persistence model?  We have 16 steps, and are showing them in a dashboard, but "Step 12" doesn't mean anything to the viewer.

It looks like a property needs added to the ExecutionPointer model based on a quick glance?

**Comment by danielgerlag** [comment]
Absolutely, I'm currently working on reorganizing the relational DB persistence models, I'll add this in to my branch.  New packages should be released by the weekend.

Just out of interest, could you tell me a little about the project you are using this for?  I'm really interested to see how people are using it.

**Comment by jonfairchild1** [comment]
We are creating artifacts to support an application, and have several long-running processes - i.e. create a SQL database in the cloud, then create a "blob storage" account, and so on.
By the way, we will probably do some cloud queue management, so we may extend your Queue management for Azure queues.  Will keep you posted.
