### ISSUE TITLE
Any way to determine workflow progress

### ISSUE THREAD

**Issue by ronnyek** [danielgerlag/workflow-core#163]
So I've been able to create some fairly complex workflows that effectively have waits and are persisted etc. 

My question is whether or not there is a way to get an instance of a workflow run, and determine which steps have been executed and what the current step is? (for display say in a workflow diagram for debugging purposes)

We've executed these 3 steps, and now waiting for these events... or something like that?

**Comment by danielgerlag** [comment]
You could inject `IPersistenceProvider` into your class and use it to fetch a workflow instance, which will have a collection of `ExecutionPointers`... everytime a step is scheduled to execute, it gets an entry in this collection, and you can track the state of each execution pointer instance here.

**Comment by ronnyek** [comment]
Yep, this will work, not the most straightforward of methods, but I think I can derive everything I need to know from this.
