### ISSUE TITLE
WaitFor with timeout action

### ISSUE THREAD

**Issue by ronnyek** [danielgerlag/workflow-core#164]
I've got a long running transactional workflow, where I wait on outside external events. The workflow works as expected, but wondering how I may be able to say something along the lines of...

WaitFor("someEvent", "key"), and if it 5 days have passed, execute some alternative action or something along those lines. I see effective date, and see how its useful, but that seems like that's almost there to filter old events if the eventKey doesnt have some unique way of specifying the workflow instances.

Please let me know if there are other means to do this already, or if this is something that would need additional code.

**Comment by danielgerlag** [comment]
You could try putting the `WaitFor` inside a `Parallel` and have a `Delay` on the other parallel branch?
