### ISSUE TITLE
Is there a way to go back to any previous step?

### ISSUE THREAD

**Issue by deepakmega** [danielgerlag/workflow-core#167]
Is there a way to define the next step using the fluent api, I somehow managed this in the JSON format using the next step ID, but is it possible using the fluent api ?
Below flow is my requirement..
```
START
step1
step2
Loop condition1
    step3
    if(condition2) 
         GOTO Step1/2   // ( go back to start/step 1/2)
END

```
Am I missing any primitive step here or is there a hack to do the above flow using loops/other steps ?

**Comment by deepakmega** [comment]
Thanks a lot, splitting up the fluent chain gives me the flexibility to do the above workflow requirement.

**Comment by phuchm** [comment]
If we want to set up a finite loop number, for example, if loop number > 5, break and finish workflow, I think it will be more flexible.
Besides that, could we combine a "wait" event with if/else step? For example, wait an approval, if success -> DoA, if failure, do B?
