### ISSUE TITLE
Feature Request : Add custom validation for DefinitionLoader

### ISSUE THREAD

**Issue by Kahbazi** [danielgerlag/workflow-core#168]
I am registering workflow at runtime with `DefinitionLoader` and i want to validate `WorkflowDefinition` with some custom rule  before registering it.

Something like this : 

    public WorkflowDefinition LoadDefinition(string json, Func<WorkflowDefinition, bool> validator)
        {
            var source = JsonConvert.DeserializeObject<DefinitionSourceV1>(json);
            var def = Convert(source);
            if (validator(def))
            {
                _registry.RegisterWorkflow(def);
            }
            return def;
        }

What do you think?

**Comment by danielgerlag** [comment]
Could you give some concrete examples of some real world validations, just so I can better understand this?

**Comment by Kahbazi** [comment]
I have a 'HttpStep' which would send http request. This step needs 'url', 'method', 'body' as inputs. I want to make sure that the inputs are set.

I guess I could deserialize the json myself and check this.

What's your opinion?

**Comment by danielgerlag** [comment]
Maybe if one could add a `[Required]` attribute to the properties on the step implementation?

**Comment by Kahbazi** [comment]
Well in this case you are right, but things can get more complex. For example I don't want the body to be set when method is get, or I want to make sure that body is a valid json

**Comment by danielgerlag** [comment]
I think any validation for step inputs should live with that step rather than be attached to the workflow definition?

**Comment by Kahbazi** [comment]
Well I need to prevent registering a workflow with an invalid step

**Comment by danielgerlag** [comment]
but I don't think it should be up to the broader workflow to determine if a step is configured in a valid way, each step should be able to define what makes a valid config for it.  Also, you won't be able to validate the content of any inputs at registration time, only when you actually create a workflow that has data to pass into it, so that limits the type of validations you could do at registration time.
