### ISSUE TITLE
Can I use workflow-core as an alternative to InfoPath? 

### ISSUE THREAD

**Issue by feldrim** [danielgerlag/workflow-core#171]
I'd like to upgrade my existing infrastructure with a major rewrite. Instead of defining workflows using InfoPath, I want to use 3rd party and open source solutions. By implementing workflows using an editor that outputs json file for workflows and process them with workflow-core, I believe it's possible yet difficult.

So do you have any suggestions or critiques?

**Comment by danielgerlag** [comment]
A visual workflow designer that outputs JSON is something we would like to incorporate into this project.  Would you be interested in taking this project on?

**Comment by feldrim** [comment]
I'd like to try but I'm not sure if I can. Since my short time goal is to rewrite the SharePoint intranet portal of the workplace, I may not have time for it. Yet I'd like to participate in when a UI project launches.

**Comment by Rjkulkarni** [comment]
Did anybody developed UI for this?

Thanks.
