### ISSUE TITLE
Error Encountered When Running XUnit Test

### ISSUE THREAD

**Issue by za8950** [danielgerlag/workflow-core#174]
I added the TestSample01 project to the WorkflowCore solution and then added a TestFixture as detailed by documentation.

However, when I run a new test I get the following error when hitting the base.Setup() method from the WorkflowTest class

Method not found: 'Void Microsoft.Extensions.DependencyInjection.ServiceCollectionExtensions.AddWorkflow(Microsoft.Extensions.DependencyInjection.IServiceCollection, System.Action`1<WorkflowCore.Models.WorkflowOptions>)'.

The TestSample01 project is using .NET Core 2.0, I did not alter anything in the sample except for the addition of the TestFixture class.

I am referencing the most recent WorkflowCore.Testing package. When I add the Workflow.Testing project directly to my UnitTest solution, I have no issues and both sample testes complete successfully

**Comment by danielgerlag** [comment]
Are you able to attach a project that has this issue?

**Comment by jotamorais** [comment]
I'm experiencing the same issue.

![image](https://user-images.githubusercontent.com/5201388/44873225-3ec78800-ac5d-11e8-893e-b6f15be39e93.png)

**Comment by za8950** [comment]
Thanks that worked!
