### ISSUE TITLE
Retrieve result data from Build method after workflow is completed

### ISSUE THREAD

**Issue by adamkjonesmesh** [danielgerlag/workflow-core#176]
Hello.

First off, great work on this library.  Is there a way that we can retrieve a result from a completed workflow?  For example, suppose I have a workflow method as below:

```
public void Build(IWorkflowBuilder builder)
{
  builder
  .StartWith<SomeStartClass>()
  .When(data => true).Do(then => then.StartWith<SomeOtherTaskClass>())
  .When(data => false).Do(then => then.StartWith<SomeFailureTaskClass>())
  .Then<FinalReturnWithResultClass>();
}
```

In the above scenario, what I really want to do is the following:

1. Fire off a start class that returns an outcome (that is working).
2. Use the outcome to determine my next step (works fine).
3. Once all my steps have completed, I need a result to send back to a calling class.

Imagine a scenario where you have an API.  The user executes a request to the API and they need a result.  So...in the background, we take the request and fire off the workflow and wait for it to complete.  Based on the completion result, we need to get a response back to the client.  Therefore, I need a response back from the workflow.  Is there a way to do this?

Thank you.

**Comment by shao200** [comment]
Oh, I also have this idea, is depressed, I want to define the control process in the "builder" method, but how can not do.
  In my case, I tried to use:
        Public Mydataclass CurrentData {get; set;}
        public void Build (Iworkflowbuilder<MyDataClass> builder)
            {
                   var MStar = Builder .
                   Startwith (Context =>
                       {
                       Console.WriteLine ( "Starting workflow..."); CurrentData = context.
                       Workflow.data as Mydataclass;
                   return Executionresult.next ();
            });
        var tempda = CurrentData;

if (tempda==xxx) { MStar.
Then<AddNumbers>()
........ I don't know what can be achieved.
Depressed dead.

**Comment by shao200** [comment]
For now, I only have to split a complete workflow into a few small workflows and then control the different workflows to do it.

**Comment by germandb** [comment]
There is a #166  pending for merge that allow this. But in my case I resolve this using RabbitMQ, I create a queue and add a CompleWorkflowStep that send a specific message to the queue and my microservices are listening to this message.

**Comment by adamkjonesmesh** [comment]
Since this is now referenced out on #166 then I will just close this one.  Will await the new release.  Thank you.
