### ISSUE TITLE
Question about loading JSON workflow definition 

### ISSUE THREAD

**Issue by Tizzo1980** [danielgerlag/workflow-core#178]
Hi, 
first of all thanks for the good job!
Though I read many time sthe documentation I still didn't get how to load JSON workflow definition correctly. 
If I understood I have to load the definition in the `Configure` method of the `Startup` class

            var loader = app.ApplicationServices.GetService<IDefinitionLoader>();

            string jsonString = "json string definition for workflow...";

            loader.LoadDefinition(jsonString);

And now? Can I already use the workflow or I have to bind it to the host entity (like what we do with the code defined workflow) 

             host.RegisterWorkflow<SampleWorkflow>();

What's the next move?!?
Thx in advance

**Comment by ScarletyCapone** [comment]
I'm additionally curious, is there a JSON export that can be ran on a current Workflow to keep from reinventing the wheel?

**Comment by roja** [comment]
> I'm additionally curious, is there a JSON export that can be ran on a current Workflow to keep from reinventing the wheel? I would like to transition to using a JSON definition that I can modify dynamically.

It would be good to understand if this was possible?

**Comment by danielgerlag** [comment]
Currently we don't have that feature

**Comment by softwareguy74** [comment]
+1 for this feature.  We're already doing JSON -> Workflow, but having the option to do Workflow -> JSON would REALLY help out in the situation where we're struggling to model a particular workflow, such as "When" (I can't get that to work in JSON) and see how it would be done on a Workflow -> JSON export.

**Comment by tcochunk** [comment]
+1 on the Workflow to JSON feature

**Comment by mohanguttikonda** [comment]
+1 on the Workflow to JSON feature. thanks

**Comment by zhenl** [comment]
+1 on the Workflow to JSON feature. thanks

**Comment by hm-ch** [comment]
Hi @Tizzo1980 

Do you have a full example how to load workflow from JSON and start it using this library.

Thanks,

**Comment by elahelolaki** [comment]
+1 on the Workflow to JSON feature. thanks

**Comment by squarezx** [comment]
+1 on the Workflow to JSON feature. thanks

**Comment by khushwaqt** [comment]
Where can I find a working example of Workflow to JSON?
