### ISSUE TITLE
Parallel Tasks

### ISSUE THREAD

**Issue by ScarletyCapone** [danielgerlag/workflow-core#179]
I looked at sample 13 for parallel tasks but they seem to be running on the same thread synchronously. I added a "Long running task" with a sleep in the body for task 2.1. This sleep held up tasks 3.1 from starting and even 1.2 from starting as well. Originally thought it may be because the tasks don't Implement StepBodyAsync, but that didn't seem to help either. Any suggestions for true parallelism so one can run multiple tasks for each item in a collection? Simple example: Customer purchases 5 items, each item has 3 tasks that need to be completed for purchase. Spin off each item in their own thread to start working through their own subsequent tasks, then join back on completion of all to run a final / next task.

**Comment by danielgerlag** [comment]
That is by design. Since workflows are long running background processes, parallel in this context means that each parallel branch will not block another branch. So if you have a WaitFor or a Delay, etc... in one of the parallel branches, the others will still be free to execute.

**Comment by pangmer** [comment]
i have the same situation,can you share how to design:
Simple example: Customer purchases 5 items, each item has 3 tasks that need to be completed for purchase. Spin off each item in their own thread to start working through their own
