### ISSUE TITLE
about Injecting dependencies question

### ISSUE THREAD

**Issue by shao200** [danielgerlag/workflow-core#180]
Hello, this project is very good and I am using him. But, I have a question about dependency injection. I follow the case using Dependency Injection service no problem, but I use the same method EntityFramework, will dbcontext into the stepbody, but, this will be an error, excuse me, how to do it?
Request guidance, thank you.

**Comment by shao200** [comment]
Sorry, after a half-day, now can. Just don't know how to use dependency injection to get persistence inside the dbcontext, there is no thoroughly understand project.

The more you use it, the more you feel the project is too great, and really thank the author for his selfless dedication.

**Comment by danielgerlag** [comment]
Do you still need assistance here?

**Comment by shao200** [comment]
Thank you so much. Because of the author's deep technical skills, I can not grasp the design ideas in a short time, so the use is not very smooth. If you can introduce the usage of executionpointer in detail, thank you very much.

**Comment by shao200** [comment]
we   can compose the fluent call chains into variables and reuse it,I see these split chains are action, can I define some basic variables and then be called by these actions, or are they called within these procedures?
      such as: Var m= "mystring";
... input (Data=>data.value,context=m) 
@danielgerlag can you help me?

**Comment by shao200** [comment]
@danielgerlag Thank you so much.
 Perhaps I did not understand the skills, the use of Fluent API is still very difficult. For example Executionresult.outcome (Nextcan) How to use the conditional API? Wait, all need to grope
