### ISSUE TITLE
Question: Recommended Way for Recurring Workflow

### ISSUE THREAD

**Issue by tameyer1** [danielgerlag/workflow-core#181]
Apologize if this has been answered before.
What is the recommended way to create a recurring workflow like:
- Every Tuesday and Thursday at 9:00 am do an event (eg send an email) if some data value (lets say account paid) is not met
- Can a recurring workflow be coded and loaded as a JSON format?

I'm trying to reconcile this workflow system with some of the common types of business flows I've seen and wrap my head around how a UI might allow a user to create workflows from a given library of steps and data objects.

**Comment by tameyer1** [comment]
answering myself
Setup a recurring workflow to run at a regular interval to check for data object value
add conditional step to run if current day of week and time is tues\thurs 9am, execute a step to send email

yes recur can be setup via json

**Comment by dbhc** [comment]
@tameyer1  Sorry, I realize it's been a full year but do you mind posting the resulting JSON + snippet of conditional step?
I'm mainly wondering what you meant by "regular interval".   (ie. Check every minute to see if the current time is tues\thurs 9am?)
