### ISSUE TITLE
Question on WorkflowController Get action

### ISSUE THREAD

**Issue by Tizzo1980** [danielgerlag/workflow-core#183]
Hi, although I can't exactly understand what happens  in the back I can use the Get action passing the workflow id

` [HttpGet("{id}")]`
`      public async Task<IActionResult> Get(string id)`
` {  var result = await  _workflowStore.GetWorkflowInstance(id);  return Json(result); }`

What about using the other Get action? Can you have an example of which parameters to pass?
I tried debugging for long but I still get errors...

`[HttpGet]`
`        public async Task<IActionResult> Get(WorkflowStatus? status, string type, DateTime? createdFrom, DateTime? createdTo, int skip, int take)`
`        {
            var result = await _workflowStore.GetWorkflowInstances(status, type, createdFrom, createdTo, skip, take);`
`            return Json(result.ToList());
        }
`

My goal is to search for workflows not only bi id but also against workflow's data; my first thought went to simply query the repository but I'd like to know if I can somehow use the GetWorkflowInstances method.

Thanks in advance for replies

**Comment by danielgerlag** [comment]
the webapi extension package is just a simple wrapper around the underlying workflow host and persistence services... unfortunately it does not support searching by custom data.  You could also implement your own API that can reach deeper into the data if you know the structure of it.

**Comment by Tizzo1980** [comment]
Ok I've got it. Thank you very much
