### ISSUE TITLE
How to add new JSON dynamically from Any action Method

### ISSUE THREAD

**Issue by GopiWilco** [danielgerlag/workflow-core#184]
Hi,

We want to feature that, a user can configure workflow and created JSON on the fly. 
For that how to add new JSON dynamically from Any Method call. 

Public void AddWorkFLow()
{
-------------------------------- Need to load JSON
}

And the JSON works only when loaded Configure method in StartUp Classs, Like following,

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            // Start the workflow host
            host = app.ApplicationServices.GetService<IWorkflowHost>();

            var loader = app.ApplicationServices.GetService<IDefinitionLoader>()

            string filePath = env.ContentRootPath + "/JSON/JSON.json";

            loader.LoadDefinition(System.IO.File.ReadAllText(filePath));
            host.Start();
}

How to add JSON in any action to load workflow on the fly.
Please advice.

Thanks and Regards,

Gopi.S

**Comment by germandb** [comment]
If you use dependency injection you can pass into your method the IDefinitionLoader, that interface expose the LoadDefinition method.

**Comment by GopiWilco** [comment]
Hi,

Thanks for your great help, it saved my lot of time.

Thanks and Regards,

Gopi.S
