### ISSUE TITLE
Regarding Wait For

### ISSUE THREAD

**Issue by GopiWilco** [danielgerlag/workflow-core#185]
Hi,

We are planning to develop the website to handle user actions by using the workflow core. We have found that it can be done by using the "WaitFor" event, Is there any way to handle the user action apart from "WaitFor" event?

Also where will be the "WaitFor" events will be maintained, Is it under processes or services? Can we able to see it visually? Is there any memory consumption problem, if we have multiple "WaitFor" events in the application.

Please advice.

Thanks and Regards,

Gopi.S

**Comment by danielgerlag** [comment]
They are maintained in the persistence store of your choice, SQL Server, MongoDB, etc....
You could use the implementation of `IPersistenceProvider` to query the persisted state and build a visual tool around that.

**Comment by GopiWilco** [comment]
Hi Daniel,

Thanks for your help
