### ISSUE TITLE
Use other dependency injection framework

### ISSUE THREAD

**Issue by marius-stanescu** [danielgerlag/workflow-core#186]
How can I use your WorkflowCore with a different dependency injection framework?
I tried to add an extension method similar to the one you have in `ServiceCollectionExtensions`, but I noticed that `WorkflowOptions` depends on `IServiceCollection`. Can I somehow register workflow options with a different DI container?

Thanks

**Comment by germandb** [comment]
Quoting @danielgerlag 

>  it is not necessary to have any IoC specific extensions since we only depend on a set of abstractions from Microsoft.Extensions.DependencyInjection.Abstractions and leave the selection of a concrete IoC container to the consumer of the library.
You can take a look at  this article https://kristian.hellang.com/third-party-dependency-injection-in-asp-net-core/

**Comment by marius-stanescu** [comment]
I am using SimpleInjector and the way it is integrated with .NET Core is different (https://simpleinjector.readthedocs.io/en/latest/aspnetintegration.html).

**Comment by eddie3716** [comment]
If i'm understanding WorkflowCore's DI system correctly, it only depends the base Microsoft DI abstractions......which conveniently comes with a Unity-light base implementation!  If you need to use another DI system, then you'll need to find an existing set of extensions for that framework that implement Microsoft.Extensions.DependencyInjection.Abstractions, or you'll have to create those extensions yourself.  Either way, you'll probably have perform some experimentation and perhaps delve into how WorkflowCore bootstraps itself.

**Comment by danielgerlag** [comment]
@marius-stanescu looking at the SimpleInjector example by following your link

```c#
private void IntegrateSimpleInjector(IServiceCollection services) 
{       
    services.AddWorkflow();
    ...
}
```

**Comment by Kahbazi** [comment]
WorkflowCore depends on `Microsoft.Extensions.DependencyInjection.Abstractions` and `simpleInjector` will not have an implementation for it, here's the reason why. https://simpleinjector.org/blog/2016/06/whats-wrong-with-the-asp-net-core-di-abstraction/

And the integration of `simpleinjector` and `AspNetCore` is that you register your application services to `simpleinjector` container and `simpleinjector` would resolve MVC `Controllers` and and all the other services that are registered by Microsoft container (ex workflowCore, all the Microsoft.Extensions packages) is resolved by microsoft container, through `simpleInjector` Crosswire.
So even if you follow the integration `simpleInjector` would do nothing for resolving workflowCore services.

So the only way that you can get workflowCore from `simpleInjector` is what @eddie3716 suggested.

**Comment by danielgerlag** [comment]
Yeah, I don't agree with the blog by the Simple injector guy.. very much an opinion.
There is a bridge for `Microsoft.Extensions.DependencyInjection.Abstractions` and `simpleInjector`... but Simple Injector is also finicky about mixing components with different lifetime scopes... not my favorite IoC container... if the basic IoC you get out of the box with .Net Core is not enough... look into Autofac.
