### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by bryanvam** [danielgerlag/workflow-core#187]
is there a dashboard that we can use to monitor the state of workflows similar to hangfire dashboard
http://docs.hangfire.io/en/latest/configuration/using-dashboard.html

**Comment by danielgerlag** [comment]
Not currently, but this is something I'd like to bundle as an add-on feature.  If you are willing to contribute this feature, that would be lekker boet 😉

**Comment by Miggleness** [comment]
Paging @peterkozak

**Comment by lankaapura** [comment]
@danielgerlag  great work with the repo. I'd like to help you with the implementation if you are still planning to work on it.

**Comment by aecuman** [comment]
Indeed great work. I'm also interested in this add on

**Comment by mary-perret-1986** [comment]
@danielgerlag why this issue has been closed?

**Comment by Adulti** [comment]
> @danielgerlag why this issue has been closed?

^^
