### ISSUE TITLE
Filter by reference in PersistenceProvider

### ISSUE THREAD

**Issue by marayfirth** [danielgerlag/workflow-core#188]
We lack an argument in some IPersistenceProvider functions to retrieve workflow instances by reference. Could it be possible to add this parameter to GetWorkflowInstances?

**Comment by danielgerlag** [comment]
Yes that should be fairly easy... pull requests are welcome 😃

**Comment by danielgerlag** [comment]
see https://github.com/danielgerlag/workflow-core/pull/243
