### ISSUE TITLE
Question on ForEach

### ISSUE THREAD

**Issue by ScarletyCapone** [danielgerlag/workflow-core#189]
Was there a particular reason that the ForEach iterates the entire collection for the first listed task, then once task 1 has ran for each item, it attempts the second task for each? Typical use of a loop would have you think that it would attempt task 1, then task 2 for the first item in the collection before moving to the next item in the collection.

My use case has (n) number of people that will have 4 or 5 tasks ran against their information, but each task in the chain may or may not be dependent on a successful run of a previous task for that person. I'm taking more of a distributed saga approach where my workflows and tasks are idempotent. Allowing the rerun of workflows containing errors so that I am always rolling data forward instead of trying to roll back data in a compensating action (all tasks must be able to complete eventually). 

Current implementation I'm using a Dictionary to persist task results for the entire workflow which passes in and out of each task, but I ran into this issue where collections are not being processed in the order I was expecting. Any insight on the current ForEach implementation and or suggestions in processing data in this manor using workflow-core?

**Comment by danielgerlag** [comment]
The existing `ForEach` implemenation is actually a parallel for each.  The best solution is to look at implementing a serial for each, in the meantime, you could try implement it with a `While`, which is serial.

**Comment by ScarletyCapone** [comment]
I inquired about the .Parallel before, but you expressed that it wasn't true parallelism in the since that all the subsequent Do statements fire at the same time, rather it allowed for tasks not to be held up when doing actions such as a WaitFor. Is that the same case here, or does it actually run each flow of tasks in the ForEach simultaneously for all item in the collection?

**Comment by danielgerlag** [comment]
It's not parallel in the sense that a single workflow instance will only execute on one thread at a time, so no 2 steps could be executing concurrently... however, it does schedule all the iterations of the foreach to run at the same time... so while they won't run on parallel threads, they will be scheduled together, and so will appear to run in parallel for long running processes.  When the workflow host picks a workflow to run, it enumerates all the steps that are ready to run... in the case of the foreach, it would be all the iterations, and then runs each step in serial (only 1 thread per workflow)... I hope that makes sense?

**Comment by ScarletyCapone** [comment]
Absolutely makes sense! I just wanted to clarify and make sure I was on the right page. I'd like to add that you've been great with the responses, it is much appreciated. I Implemented a While loop for my case and it seems to be working perfectly! Thanks again!
