### ISSUE TITLE
Access to ILoggerFactory in StepBody classes

### ISSUE THREAD

**Issue by KannaKaranam** [danielgerlag/workflow-core#19]
Would it possible to added the ILoggerFactory instance to StepBody through IStepExecutionContext?

If it is possible with the existing code base, can you please extend one of the samples to leverage the same logger in StepBody derived classes?

**Comment by danielgerlag** [comment]
If you register your StepBody class with the service provider, it will inject any dependencies declared in the constructor.  I have updated the "GoodByeWorld" step in sample 01.

Add this when configuring the service provider
```C#
services.AddTransient<GoodbyeWorld>();
```

and change the step like this

```C#
public class GoodbyeWorld : StepBody
{
    private ILogger _logger;

    public GoodbyeWorld(ILoggerFactory loggerFactory)
    {
        _logger = loggerFactory.CreateLogger<GoodbyeWorld>();
    }

    public override ExecutionResult Run(IStepExecutionContext context)
    {
        Console.WriteLine("Goodbye world");
        _logger.LogInformation("Hi there!");
        return ExecutionResult.Next();
    }
}
```

**Comment by KannaKaranam** [comment]
Thank you. it makes sense.
