### ISSUE TITLE
WorkflowDbContext missing constructor with options

### ISSUE THREAD

**Issue by joshdanko** [danielgerlag/workflow-core#190]
I'm unable to use AddDbContext or implement IDesignTimeDbContextFactory to pass DbContextOptions for my Migrations, because WorkflowDbContext is missing a constructor to pass those options.  

I am getting it to work by overriding OnConfiguring method and putting my logic to get the connection string , UseSqlServer and other misc options.

Using IWorkflowDbContextFactory I run into the same issues of having to create multiple OnConfiguring functions.  Is there a better way to do it that I am missing?

**Comment by danielgerlag** [comment]
Are you able to attach a sample project that illustrates this problem?
