### ISSUE TITLE
Change compensate order in Saga Workflow

### ISSUE THREAD

**Issue by georgepaoli** [danielgerlag/workflow-core#191]
In the sample, `Task4` will throw an exception, then rollback order is: `UndoTask4`, `UndoTask1`, `UndoTask2` and `UndoTask3`.

```c#
builder
    .StartWith<LogStart>()
    .Saga(saga => saga
        .StartWith<Task1>()
            .CompensateWith<UndoTask1>()
        .Then<Task2>()
            .CompensateWith<UndoTask2>()
        .Then<Task3>()
            .CompensateWith<UndoTask3>()
        .Then<Task4>()
            .CompensateWith<UndoTask4>()
    )
    .OnError(Models.WorkflowErrorHandling.Retry, TimeSpan.FromMinutes(10))
    .Then<LogEnd>();
```

How change order to:  `UndoTask1`, `UndoTask2`, `UndoTask3` and `UndoTask4`.

Thank you for this great job!

**Comment by danielgerlag** [comment]
Hi,

This sounds like a bug... I would imagine the order should be `UndoTask4`, `UndoTask3`, `UndoTask2`, `UndoTask1`?  Do you think there would be value in allowing the library consumer to explicitly specify the order?  Would love to hear your thoughts.

**Comment by georgepaoli** [comment]
Sorry, I meant default order should be `UndoTask4`, `UndoTask3`, `UndoTask2` and `UndoTask1`.

See this sample: https://github.com/georgepaoli/workflow-core-test
The compensate order is 4, 1, 2 and 3. This is a bug?

`Do you think there would be value in allowing the library consumer to explicitly specify the order?`
No, really no make sense change order.

Thanks.

**Comment by danielgerlag** [comment]
Ok, yes this is definitely a bug... I will look into it.

**Comment by danielgerlag** [comment]
Pull request #192

**Comment by georgepaoli** [comment]
Thanks Daniel!
