### ISSUE TITLE
Constructor in Workflow Step

### ISSUE THREAD

**Issue by GopiWilco** [danielgerlag/workflow-core#193]
Hi Daniel,

We want to publish an event from the Workflow Step and in order to achieve the publish we need to call the following from workflow step,

workflowHost.PublishEvent("EventName", "EventKey", null);

So in order to use the workflow Host, we are trying to use IWorkflowHost using the constructor like following,

    public class Step3TriggerWaitForCompleteParent : StepBody
    {
        private readonly IWorkflowHost workflowHost;

        public Step3TriggerWaitForCompleteParent(IWorkflowHost workflowHost1)
        {
            this.workflowHost = workflowHost1;
        }

        public override ExecutionResult Run(IStepExecutionContext context)
        {

            workflowHost.PublishEvent("EventName","1", null);

            return ExecutionResult.Next();
        }
    }

But the step is not executing, And if we remove the constructor then it works as expected.

But we need to publish the event from the Workflow Step. 

Please help with this.

Thanks and Regards,

Gopi.S

**Comment by danielgerlag** [comment]
Try registering the actual step class with your IoC container... it first tries to resolve it via the IoC container, if that fails then it will search for a parameter-less constructor.

**Comment by GopiWilco** [comment]
Hi Daniel,

Thanks for your great help.

Thanks and Regards,

Gopi.S
