### ISSUE TITLE
Feature Request: Additional overload for IWorkflowController.RegisterWorkflow

### ISSUE THREAD

**Issue by Miggleness** [danielgerlag/workflow-core#195]
### Requested Feature
Update IWorkflowController with additional methods

```
void RegisterWorkflow(IWorkflow workflow)
void RegisterWorkflow<TData>(IWorkflow<TData> workflow) : where TData : new()
```

### Why
The current RegisterWorkflow creates an instance of concrete implementation of IWorkflow.  In my project, I'm creating a wrapper around WorkflowCore due to additional metadata that I require and I'm forced to create an instance of my custom IWorkflow interface, hence creating the object twice for each registration.

I can submit a PR for this quickly, just need thoughts before then.

**Comment by danielgerlag** [comment]
Could you expand on what you mean by metadata?

**Comment by danielgerlag** [comment]
I am just trying to understand the bigger picture here... could you describe how you intend to consume this metadata and how you would populate it?

**Comment by Miggleness** [comment]
I've a wrapper on top of WorkflowCore which includes additional properties specific to our domain.

I follow the same registration steps made by WorkflowCore to capture the value of these properties and store them in my own WorkflowDefinition.

In retrospect, this isn't a very important feature request and I could always override the WorkflowCore implementation instead of just creating a wrapper around it.

**Comment by danielgerlag** [comment]
Just curious, how were you wanting to consume and populate these values?

**Comment by Miggleness** [comment]
We have workflows that are basically a sequence of steps detailing how to deliver stuff to third party subscribers or how we process stuff we receive from them.  Low volume stuff.

The additional properties such as `RestrictedParties` are set design time for composed workflows (_i.e. _implementing `IMyWorkflow`_).  We have an admin page which allows users to set triggers such as "_when we receive email from this mailbox with this pattern in the email message, then we identify this as __Party X__ and start running __Workflow A___".  `RestrictedParties` is then used to inform the user that they can only map a subset of parties to a workflow.  It's a way of us saying, "_Sorry user, you cannot run __Workflow A__ for __Party X___."

I'm following your pattern of storing workflow metadata in a workflow definition class (e.g. `MyWorkflowDefinition`) which includes our custom properties.  Again, following your pattern I create an instance of `IMyWorkflow` to map these properties into our workflow definition object.

The reason I raised this request is our system creates two instances of `IMyWorkflow`; once when we get the definition, and again in `WorkflowCoreHost`.

**Comment by danielgerlag** [comment]
Could you achieve this using annotations on the class?

**Comment by Miggleness** [comment]
I hadnt considered that. Thanks for the tip. Im closing this issue.
