### ISSUE TITLE
How to set a When step via JSON

### ISSUE THREAD

**Issue by bautigaraventa** [danielgerlag/workflow-core#197]
Hello! 
I'm trying to create a flow via JSON. I have a Wait step that waits for an specific Event to be published. Based on the EventData of the published event, I have to decide between three different steps. 
I think the best way to do it is using the "When" primitive, but I can't find the documentation to see an example in JSON.

Thank you very much.

By the way, it's a great library!

**Comment by danielgerlag** [comment]
Hi,
I am actually considering deprecating the `When` primitive as I feel the same functionality can be achieved with the `If` and it would be more readable.  I believe you could select the correct response step by outputting the `EventData` to a field on your data object and then using `If` steps to select to correct path.

**Comment by bautigaraventa** [comment]
Perfect, I did this! Thank you very much.
