### ISSUE TITLE
How to create unit tests for steps with dependency injection?

### ISSUE THREAD

**Issue by georgepaoli** [danielgerlag/workflow-core#198]
Hi Daniel,

How to register dependencies for steps, using `WorkflowCore.Testing` package?

Thanks.

**Comment by georgepaoli** [comment]
Do override Setup() method is best way?

**Comment by danielgerlag** [comment]
override the `ConfigureServices` method

**Comment by georgepaoli** [comment]
Works fine!

Thank you.
