### ISSUE TITLE
Objects as StepBody Inputs

### ISSUE THREAD

**Issue by bschaeublin** [danielgerlag/workflow-core#199]
Hi

First, I would like to thank you for your great library.
I consider using it for my practical thesis at a tech school.

What I'm trying to do is providing a dynamic user-interface, where user can arrange their steps to a workflow. I thought, it is going to be easy - I'll just saving the JSON representation of the users-workflow and load the definition on server side.

But i just realized, that it's not possible to enter objects as input parameters, like following:
```
{
  "Id": "MyWorkflow",
  "Version": 1,
  "DataType": "MyApp.MyDataClass, MyApp",
  "Steps": [
    {
      "Id": "Hello",
      "StepType": "MyApp.HelloWorld, MyApp",
      "NextStepId": "Add"
    },
	{
      "Id": "PostToAzureFunction",
      "StepType": "MyApp.HttpRequestStep, MyApp",
      "NextStepId": "Bye",
      "Inputs": { 
          "Url": "https://azure.com/sampleapi/",
          "Method": "POST",
	  "Headers": {
		"Authorization": "Bearer 123",
		"Content-Type": "application/json"
	  },
	  "Parameters": { // this is the post-body
		"Foo": 123,
		"Bar": "564654"
	  }
       },
      "Outputs": { 
          "Answer": "step.Result" 
      }
    },    
    {
      "Id": "Bye",
      "StepType": "MyApp.GoodbyeWorld, MyApp"
    }
  ]
}
```

Is there a way, where I could achieve the HttpRequestStep with this library? 

PS:
I saw a PR, that seems to partially fullfill my request (?):
https://github.com/danielgerlag/workflow-core/pull/169

**Comment by danielgerlag** [comment]
Hi, sorry for the delayed response.  This is something I need to dive deeper into, unfortunately, I am in the middle of moving this week... I will try look into the various solutions for this next week.

**Comment by danielgerlag** [comment]
PR #173 added support for dictionary style inputs.  Here is an integration test where it is used with a JSON defined workflow. https://github.com/danielgerlag/workflow-core/pull/173/files#diff-4932dbb877079e9e877e982d25bdb383
Would this enable you to solve your problem?

**Comment by bschaeublin** [comment]
Thank you for responding. 
I've figured out a workaround, with serializing the complex properties as jsonstring. To bind every step-inputs (like in your sample) of my 50-60 workflow steps against a single data class would result in a mess.

I have to say, I realized that i cannot use this library without making many wrappers (ex. you can deserialize a json to a definitionsource but if you want to serialize it back to json - to send it to the frontend -, you have to make pretty much extra code, to have the stepbodies and their properties included), so I decided to write my own little library for my usecase. I think this library is great, but i cannot use it that way, that i would like to. 

Thank you for taking time for my question.
