### ISSUE TITLE
Have 2 DI errors: "Unable to resolve service..." and "Cannot resolve... from root provider because it requires scoped service" 

### ISSUE THREAD

**Issue by bautigaraventa** [danielgerlag/workflow-core#200]
Hi. I'm using DI in a Step where I'm injecting a Repository Interface. The implementation of that interface has DI of AutoMapper and a DBContext (Entity Framework Core) to access the DB.

When I Start a flow instance the step never runs. I see the errors shown in the title via console. If I comment the code of the DI of AutoMapper and DBContext it works (but i'm not achieving the access to the DB). The first error is because of AutoMapper, and the second one is because of DBContext.

I think it's a problem of IoC container but I tried everything.
I have my steps added as Transient, I have the DBContext also configured.

Need help pls!

Thank you so much.
Bauti.

**Comment by danielgerlag** [comment]
Could you include the code where in configure your DI container and the Step in question?

**Comment by bautigaraventa** [comment]
Hi Daniel! 
I have this in my IoC
```
//WorkFlowCore
services.AddSingleton<IWorkflowRegistry, WorkflowRegistry>();
services.AddSingleton<IWorkflowCore, WorkflowCore.Implementations.WorkflowCore>();
//Steps
services.AddTransient<SendEmail>();
services.AddTransient<NewFinding>();
services.AddTransient<UpdateFinding>();
```

I also configured AutoMapper and SQLDBContext in my startup this way:
```
services.AddWorkflow(x => {
                x.UseSqlServer("DEFAULTCONNECTION", false, true);
            });
services.AddAutoMapper();

services.AddDbContext<MyDBContext>(options =>
{
            options.UseSqlServer(_config.GetConnectionString("DefaultConnection"));
});
```

The problem is that the execution never goes into the step which has an IRepository injected. This IRepository has AutoMapper and SQLDBContext injected via constructor.

This is the injection of the Step:
```
private readonly IFindingRepository _findingRepository;

public NewFinding(IFindingRepository findingRepository)
{
      _findingRepository = findingRepository;
}
```


I found a solution for this but I don't know if it is the best one. I would like to hear your opinion.

The code of the Repository class that wasn't working was:
```
private readonly MyDBContext _ctx;
private readonly IMapper _mapper;
public FindingRepository(MyDBContext ctx, IMapper mapper)
{
_ctx = ctx;
_mapper = mapper;
}

public MyMethod(string Id)
        {
                ...
        }
```

And it works like this:
```
private readonly IServiceProvider _serviceProvider;
        public FindingRepository(IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

public MyMethod(string Id)
        {
            using (var scope = _serviceProvider.CreateScope())
            {
                var _mapper = scope.ServiceProvider.GetService(typeof(IMapper)) as IMapper;
                var _ctx = scope.ServiceProvider.GetService(typeof(MyDBContext)) as MyDBContext;

                ...
            }  
         } 
```

Thank you so much for your time!

**Comment by danielgerlag** [comment]
I'm not sure about this
```c#
//WorkFlowCore
services.AddSingleton<IWorkflowRegistry, WorkflowRegistry>();
services.AddSingleton<IWorkflowCore, WorkflowCore.Implementations.WorkflowCore>();
```

What is `IWorkflowCore`?  
Are you using the `.AddWorkflow` extension method anywhere in your IoC setup?

**Comment by bautigaraventa** [comment]
IWorkflowCore is an own Interface that exposes some WorkflowCore methods. We are working like this because we treat the library as a services which can be used with Dependency Injection.

I have the .AddWorkflow with the connection string in my Startup.

**Comment by danielgerlag** [comment]
Could you include the code where you call `.AddWorkflow` and show the method that calls it?

**Comment by bautigaraventa** [comment]
Yes, here it goes:
```
public void ConfigureServices(IServiceCollection services)
        {
            ConfigureContexts(services);

            AddSwaggerService(services);

            services.AddMemoryCache();
            services.AddWorkflow(x => {
               x.UseSqlServer(@"Server=SERVER;Initial Catalog=DB;Persist Security Info=BOOLEAN;User ID=ID;Password=PASS;MultipleActiveResultSets=BOOLEAN;Encrypt=BOOLEAN;TrustServerCertificate=BOOLEAN;Connection Timeout=TIME;", false, true);
            });
}
```

**Comment by myhfw003** [comment]
I have encountered the same problem, is there a solution?

**Comment by myhfw003** [comment]
Here is my code, thank you。
`    public class DoSomething : StepBody
    {
        private readonly IServiceProvider _serviceProvider;
        private IRepository<MessageLog> _messageLogRepository;
        private ILogger _logger;

        public DoSomething(IServiceProvider serviceProvider,ILogger logger)
        {
            _serviceProvider = serviceProvider;
            _logger = logger;
        }
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            //using (var scope = _serviceProvider.CreateScope())
            //{
            //    _messageLogRepository = scope.ServiceProvider.GetService(typeof(IRepository<MessageLog>)) as IRepository<MessageLog>;
            //    _messageLogRepository.Insert(new MessageLog { Content = "xxxxxx", CreatedTime = DateTime.Now, UpdatedTime = DateTime.Now, Remarks = "" });

            //    _logger = scope.ServiceProvider.GetService(typeof(ILogger)) as ILogger;
            //    _logger.InsertLog(LogLevel.Information,"日志测试");

            //}
            _logger.InsertLog(LogLevel.Information, "日志测试");

            return ExecutionResult.Next();
        }
    }`

**Comment by martinbianchi** [comment]
> Here is my code, thank you。
> ` public class DoSomething : StepBody
> {
> private readonly IServiceProvider _serviceProvider;
> private IRepository _messageLogRepository;
> private ILogger _logger;
> 
> ```
>     public DoSomething(IServiceProvider serviceProvider,ILogger logger)
>     {
>         _serviceProvider = serviceProvider;
>         _logger = logger;
>     }
>     public override ExecutionResult Run(IStepExecutionContext context)
>     {
>         //using (var scope = _serviceProvider.CreateScope())
>         //{
>         //    _messageLogRepository = scope.ServiceProvider.GetService(typeof(IRepository<MessageLog>)) as IRepository<MessageLog>;
>         //    _messageLogRepository.Insert(new MessageLog { Content = "xxxxxx", CreatedTime = DateTime.Now, UpdatedTime = DateTime.Now, Remarks = "" });
> 
>         //    _logger = scope.ServiceProvider.GetService(typeof(ILogger)) as ILogger;
>         //    _logger.InsertLog(LogLevel.Information,"日志测试");
> 
>         //}
>         _logger.InsertLog(LogLevel.Information, "日志测试");
> 
>         return ExecutionResult.Next();
>     }
> }`
> ```

Don't Inject dependency of ILogger in constructor, only IServiceProvider. Then use the commented lines to get the service and use them.
Your error may also be in the IRepository<MessageLog> if this class have Services injected by constructor. To solve this, inject the services via IServiceProvider with an scope instead by constructor

**Comment by ssougnez** [comment]
Hello,

I was having the same issue when trying to inject a DbContext in a step. I tried with the code commented above and it did fix the issue. However, could anyone be kind enough to explain me a bit why it works with the commented code and how come I can't just inject my DbContext in the constructor of my step?

I also tried to create my DbContext with a "transient" lifetime but it was not possible either. The only custom service I can inject in my step is a singleton one. I guess it has to do with the lifetime but if someone has a short explanation, I'm interested!

Thanks

**Comment by CQJonnyLin** [comment]
### My Extensions
```
   public static class ContextMigratorExtensions
    {
        public static IApplicationBuilder RunMigrations(this IApplicationBuilder app)
        {
            if (app == null)
                throw new ArgumentNullException(nameof(app));
            var migrations = app.ApplicationServices.GetServices<IContextMigrator>();
            foreach (IContextMigrator migration in migrations)
            {
                migration.Migrate();
            }
            return app;
        }
        public static IServiceCollection AddDbContextWithMigration<TContext>(this IServiceCollection serviceCollection, Action<DbContextOptionsBuilder> optionsAction = null, ServiceLifetime contextLifetime = ServiceLifetime.Scoped, ServiceLifetime optionsLifetime = ServiceLifetime.Scoped) where TContext : DbContext
        {
            serviceCollection.AddTransient<IContextMigrator, ContextMigrator<TContext>>();
            return serviceCollection.AddDbContext<TContext, TContext>(optionsAction, contextLifetime, optionsLifetime);
        }
    }
```
#### Service
```
public interface IContextMigrator: IDisposable
 {
        void Migrate();
 }
```
#### Implementation
```
   public class ContextMigrator<T> : IContextMigrator
    where T : DbContext
    {
        private readonly T _context;

        public ContextMigrator(T context)
        {
            _context = context;
        }

        public void Dispose()
        {
            throw new NotImplementedException();
        }

        public void Migrate()
        {
            try
            {
                _context.Database.Migrate();
            }
            catch (Exception e)
            {
                //throw new MigrationException(context.GetType().Name, e);
                throw e;
            }
        }
    }
```
#### Describe the error
![AAA](https://user-images.githubusercontent.com/29520329/59615861-e1ea7f00-9155-11e9-8dfa-0dd47d729b26.png)

> Why that can't resolve service.

**Comment by myhfw003** [comment]
需要如下形式，关键代码 using (var scope = service.CreateScope()
祝调试成功！
public async static Task InitDB(IServiceProvider service)
        {
            using (var scope = service.CreateScope())
            {
                var _rolesRepository = scope.ServiceProvider.GetService(
typeof(IRepository<Roles>)) as EfRepository<Roles>;
                var _usersRepository = scope.ServiceProvider.GetService(
typeof(IRepository<Users>)) as EfRepository<Users>;

向洪林 <notifications@github.com> 于2019年6月17日周一 下午11:17写道：
