### ISSUE TITLE
Pass an Object in EventData property with JSON

### ISSUE THREAD

**Issue by martinbianchi** [danielgerlag/workflow-core#202]
Hi Daniel, thanks for your work on this awesome project. I'm trying to implement this library via JSON and I have many problems, I hope you can help me.
I'm trying to pass an object as EventData in a WaitFor primitive, I looked the issue #121 but this doesn´t work for me, maybe i'm doing something wrong in steps:

This is a part of my JSON Workflow:

```
{
    "Id": "Finding",
    "Version": 1,
    "DataType": "Hoshin.CrossCutting.WorkflowCore.Finding.Data.FindingWorkflowData, Hoshin.CrossCutting.WorkflowCore",
    "Steps": 
    [
      {
          "Id": "NewFinding",
          "StepType": "Hoshin.CrossCutting.WorkflowCore.Finding.Steps.NewFinding, Hoshin.CrossCutting.WorkflowCore",
          "NextStepId": "SendEmail1",
          "Inputs": {
              "Description": "data.Description",
          },
          "Outputs": {
              "EmailAddresses": "step.EmailAddresses"
          }
      },
      {
          "Id": "SendEmail1",
          "StepType": "Hoshin.CrossCutting.WorkflowCore.GenericSteps.SendEmail, Hoshin.CrossCutting.WorkflowCore",
          "NextStepId": "WaitApproval",
          "Inputs": {
              "EmailAddresses": "data.EmailAddresses",
              "Subject": "\"Subject\"",
              "Message": "\"Message\""
          },
          "Outputs": {
              "EmailAddresses": "step.EmailAddresses"
          }
      },
      {
          "Id": "WaitApproval",
          "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
          "NextStepId": "IfApproved",
          "Inputs": {
              "EventName": "\"Approve\"",
              "EventKey": "context.Workflow.Id",
              "EffectiveDate": "DateTime.Now",
          },
          "Outputs": {
              "EventData": "step.EventData.EventData",
              "Description": "step.EventData.Description"
          }
      },
      {
          "Id": "IfApproved",
          "StepType": "WorkflowCore.Primitives.If, WorkflowCore",
          "Inputs": { "Condition": "data.EventData == \"Approve\" || data.EventData == \"ApproveWithPDCA\"" },
          "Do": [[
              {
                  "Id": "Approved",
                  "StepType": "Hoshin.CrossCutting.WorkflowCore.Finding.Steps.ApproveFinding, Hoshin.CrossCutting.WorkflowCore",
                  "Inputs": {
                      "State": "data.State"
                  },
                  "Outputs": {
                      "EmailAddresses": "step.EmailAddresses"
                  }
                }
          ]]
      }
    ]
  }

```

I was trying declared EventData as an Object in my FindingWorkflowData class but i have this error when register the workflow: 

> No property or field 'EventData' exists in type 'Object'

Also, I try to declare EventData as FindingWorkflowData, but I have this error in runtime:

> Object must implement IConvertible in class

I'm really lost with that, thank you very much for your help.

Martin.

**Comment by martinbianchi** [comment]
I changed my way of approaching and create my own WaitFor with a few modifications:

```
            if (!context.ExecutionPointer.EventPublished)
            {
                DateTime effectiveDate = DateTime.MinValue;
                // TODO: This will always execute.
                if (EffectiveDate != null)
                {
                    effectiveDate = EffectiveDate;
                }

                return ExecutionResult.WaitForEvent(EventName, EventKey, effectiveDate);
            }

            EventData = (context.ExecutionPointer.EventData as MyWorkflowClass).EventData;
            context.Workflow.Data = context.ExecutionPointer.EventData;
            return ExecutionResult.Next();
```

Now, I can send information from outside the flow into him, in the prop EventData I have an object of type MyClassWorkflow and use this to update the context data.
This works for me but I don't know if it is the way to implement this feature, I would be grateful if you give me a feedback of this approach.

Thanks and regards. 
Martin.

**Comment by danielgerlag** [comment]
I would avoid reaching into the workflow's main data object from within the step, as this would create coupling between your step and the workflow, making it difficult to use the step in other workflows.
Instead, I would rather add additional public properties on the step class and populate those at the same time as `EventData`

**Comment by maddymbm** [comment]
Thanks Daniel for this project , i love the design and how the code is written and decided to choose this. Concerning this issue, I found in another issue a possible solution to this.
I hope this will be helpful to others as well. As pointed out "avoid reaching into the workflow's main data object",
 you could use (step.EventData as MyWorkflowClass).EventData in the json itself instead of extending WaitFor
