### ISSUE TITLE
Using workflow-core in Web API application

### ISSUE THREAD

**Issue by danieltaiber** [danielgerlag/workflow-core#204]
Hi,

Did anyone try using workflow-core in a Web API application.

Any idea how i can use ServicesCollection?

Thanks

**Comment by provanguard** [comment]
I am also thinking about using workflow-core in my Web API application. But the scenario is a bit more complex than the provided samples, which are great by the way. I would like to shortly describe the requirements and would like to ask you for your opinion on whether workflow-core is a feasible solution.

In an Web API application, a request comes in via controller to create an object. The creation of the objects raises an event and an event handler initiates notifications for other applications. This is where the workflow part comes into play, as I would like to be able to orchestrate notifications (as workflow steps) of different external systems. These systems will be notified via service bus and a confirmation for each of them is expected to be received after these systems are done doing their tasks.
The goal is to ensure that all workflow steps succeeded, or at least to get information back which of them succeeded and which of them failed. So, if it happens that my application that runs the workflow is restarted, it should automatically resume processing of the workflow initiated before the restart.

Please let me know if the above can be done with workflow-core, and if so, then how I should go about it. In particular the last requirement of resuming the workflow is a puzzle for me right now.

**Comment by danielgerlag** [comment]
You can use a `WaitFor` within your worklfow to wait on an external event, and then inside your service bus listener, you can use the `WorkflowController.PublishEvent` method to broadcast the event to any interested workflows.

**Comment by emardini** [comment]
Daniel, we have a similar scenario that was implemented using azure webjobs, but I'm not sure how will the saga work in case the webjob is restarted. In such a case the message will still remain in the queue, will be received by the workflow, how does the workflow know this is the same old message or a new one?
