### ISSUE TITLE
DeferSampleWorkflow can not completed

### ISSUE THREAD

**Issue by qazq** [danielgerlag/workflow-core#21]
Launch Sample05, console show "Workflow started" and after 20 seconds it don't go to next step.

The `context.PersistenceData` always is null, so it can not fire Next()

**Comment by danielgerlag** [comment]
Thanks for letting me know, I'll look into it

**Comment by danielgerlag** [comment]
Fixed, was a problem with the ExecutionResult.Sleep method, setting the outcome value instead of the persistence data value.
