### ISSUE TITLE
Package Installation error

### ISSUE THREAD

**Issue by SruthyJohn** [danielgerlag/workflow-core#216]
Getting error while installing WorkflowCore package.
Specs:
-VS2013
-.net framework- 4.6
-Windows 10

Install-Package : Could not install package 'WorkflowCore 1.6.8'. You are trying to install this package into a project that targets 
'.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with 
that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package WorkflowCore -Version 1.6.8
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand

**Comment by kpko** [comment]
Hi,

could you try to install the package via `Install-Package WorkflowCore -Version 1.6.8 -Verbose` and see if this command produces a more detailed error message? WorkflowCore should work just fine with .NET Framework 4.6 and 4.6.1.

**Comment by SruthyJohn** [comment]
I had tried with 4.6 and 4.6.1 still same error. With '-Verbose' error we same more or less. 

`PM> Install-Package WorkflowCore -Version 1.6.8	-Verbose
Installing 'WorkflowCore 1.6.8'.
Added file 'WorkflowCore.dll' to folder 'WorkflowCore.1.6.8\lib\netstandard1.3'.
Added file 'WorkflowCore.1.6.8.nuspec' to folder 'WorkflowCore.1.6.8'.
Added file 'WorkflowCore.1.6.8.nupkg' to folder 'WorkflowCore.1.6.8'.
Successfully installed 'WorkflowCore 1.6.8'.
Adding 'WorkflowCore 1.6.8' to WorkFlow01.
Uninstalling 'WorkflowCore 1.6.8'.
Removed file 'WorkflowCore.dll' to folder 'D:\WorkflowCore\WorkFlow01\packages\WorkflowCore.1.6.8\lib\netstandard1.3'.
Removed folder 'D:\WorkflowCore\WorkFlow01\packages\WorkflowCore.1.6.8\lib\netstandard1.3'.
Removed folder 'D:\WorkflowCore\WorkFlow01\packages\WorkflowCore.1.6.8\lib'.
Removed file 'WorkflowCore.1.6.8.nuspec' to folder 'D:\WorkflowCore\WorkFlow01\packages\WorkflowCore.1.6.8'.
Removed file 'WorkflowCore.1.6.8.nupkg' to folder 'D:\WorkflowCore\WorkFlow01\packages\WorkflowCore.1.6.8'.
Removed folder 'D:\WorkflowCore\WorkFlow01\packages\WorkflowCore.1.6.8'.
Removed folder 'D:\WorkflowCore\WorkFlow01\packages'.
Successfully uninstalled 'WorkflowCore 1.6.8'.
Install failed. Rolling back...
Install-Package : Could not install package 'WorkflowCore 1.6.8'. You are trying to install this package into a project that 
targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are 
compatible with that framework. For more information, contact the package author.
At line:1 char:1
+ Install-Package WorkflowCore -Version 1.6.8    -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 `

**Comment by germandb** [comment]
The last version of WorkflowCore 1.6.8 its compiled against .Net Standard 2.0 that make it compatible only with .Net Framework 4.6.1.  In top of that you need to install the compatibility package but that package its only supported in VS2015.4.4 or latter.

**Comment by kpko** [comment]
Interesting, that might explain why it worked with .NET 4.6 as I tried the procedure with VS2017.

**Comment by danielgerlag** [comment]
Please make sure you are installing the correct package...
Someone else published an 'alternate version' of workflow core as `St2forget.WorkflowCore`, which is built against .Net Standard 2.0.  

The 'Official version' still targets .Net Standard 1.3

**Comment by SruthyJohn** [comment]
No hope with VS2013. Moved to _vscode_.
Working fine with .net core 1.1, .net framework 4.6 in vscode.
