### ISSUE TITLE
Guidance for EFCore extension

### ISSUE THREAD

**Issue by ssougnez** [danielgerlag/workflow-core#219]
Hello,

I'm creating an ASP.NET Core web app using workflowCore. Basically, users can trigger workflows via web forms. Most of the workflows create some task in a custom tables and wait for a user to approve this task. On the "task" web form, I want to display the data the workflow has been started with (basically, the column "Data" from the "Workflow" table).

However, I'm not sure what's the best way of storing the custom data. Basically, I see two solutions: create tables in the database used by workflowCore, create a new database.

**New database**

The only drawback with this solution that I see is that I have to duplicate information. Indeed, when a task is created, I should put the workflow data in this table. Not doing that would mean that to retrieve all the task assigned to a user, I should retrieve all the task, then for each of them query the workflowCore database to retrieve workflow data... Not very nice...

**Extend the workflow core database**

I could try to create a DbContext that inherits from WorkflowDbContext but it does not seem that easy. Moreover, there are some questions I have no response to. For example, what about migrations ? What about "when to create the database", etc..

What would be your general thought about it?

**Comment by ssougnez** [comment]
Unfortunately, the data of the workflow instance are not enough. Indeed, I need, for example, to create some tasks assigned to people, etc... So I need to create additional table, so my question was about creating custom table in the database used by workflow core. For now, I have a different db but it's a bit weird to have a "workflowInstanceId" field that contain the guid of a workflow instance located in another database so I was wondering if there were some supported mechanism to extend the schema of the database.

Another issue is transactions. If I start a workflow through a web API call, it needs to create a task as well in a custom table. I can only create a transaction for the task creation, not the workflow start (I don't know if i'm being clear).

**Comment by danielgerlag** [comment]
The idea is to avoid traditional ACID transactions - 
https://dzone.com/articles/saga-pattern-how-to-implement-business-transaction

https://martinfowler.com/bliki/BoundedContext.html

**Comment by ssougnez** [comment]
Interesting, I’ll read that, thanks ;-)
