### ISSUE TITLE
Synchronous Step Execution and Returning Step Result

### ISSUE THREAD

**Issue by OnderBoz** [danielgerlag/workflow-core#224]
Hi,

I have a case where I need to execute a step with given WorkflowId and return the step output.

I tried a solution with events but publishing an event does not return anything.

```
builder
    .StartWith<SendOneTimePasswordStep>()
        .Output(data => data.WorkflowId, step => step.WorkflowId)
    .WaitFor("VerifyOneTimePassword", data => data.WorkflowId)
        .Output(data => data.OneTimePassword, step => step.EventData)
    .Then<VerifyOneTimePasswodStep>
    ....
    ....
```

In this example, user calls my controller(or publishes an event) for verification.
VerifyOneTimePassword triggers VerifyOneTimePasswodStep. There, I need to return the step result to user and move on to the next step.

Or, If there is a way to do it, I need to execute VerifyOneTimePasswodStep directly, return the result and move on to the next step.

How can I implement this functionality?

**Comment by danielgerlag** [comment]
I'm not sure I understand this statement

```
I tried a solution with events but publishing an event does not return anything.
```

Could you please explain what you mean by this?
