### ISSUE TITLE
How to Pass Value Through PublishUserAction to WithOption()

### ISSUE THREAD

**Issue by Curarpika** [danielgerlag/workflow-core#225]
Hi,
I want to pass a custom value like 'comment' from PublishUserAction() method to internal data of workflow.
Is there any way to do this?
Thx.

**Comment by danielgerlag** [comment]
I think the Users extension package would need to be extended to support this feature, but the underlying workflow engine can support it... just need to build this layer on top of it.

**Comment by Curarpika** [comment]
I think I will use Events to accomplish it for now.
Appreciate!
