### ISSUE TITLE
How to re-enter specific step

### ISSUE THREAD

**Issue by Curarpika** [danielgerlag/workflow-core#226]
Hi,
I need to re-enter previous or specific step based on different condition, is it not supported?

**Comment by danielgerlag** [comment]
it is possible but the syntax is wierd

```c#
var step1 = builder.StartWith<HelloWorld>();
var step2 = step1.Then<GoodbyeWorld>();
step2.Then(step1);
```

**Comment by Curarpika** [comment]
Oh yes, Thanks man.

**Comment by lightluomeng** [comment]
Hi, i'm new to workflowcore and it cost me lots time to figure out how to 're-enter' step. Below is my solution. Hope this will help others who have the same problem.
define extension methos:

` public class ApprovalCommands
    {
        public static INamedItem AgreeToNext = new ApprovalCommand
        {
            DisplayName = "同意",
            UniqueName = "Agree"
        };

        public static INamedItem Disagree = new ApprovalCommand
        {
            UniqueName = "Disagree",
            DisplayName = "不同意"
        };

        public static INamedItem Fallback = new ApprovalCommand
        {
            UniqueName = "Fallback",
            DisplayName = "打回"
        };
    }

   public static class BuilderExtension
    {
        public static IStepBuilder<T, InlineStepBody> AddApprovalStep<T>(
            this IStepBuilder<T, InlineStepBody> builder,
            string stepId, string displayName, string userKey,
            out IStepBuilder<T, InlineStepBody> resultHead,
            Dictionary<string, string> optionalSteps = null,
            IStepBuilder<T, InlineStepBody> preApproval = null) where T : ApprovalFlowData
        {
            var agree = ApprovalCommands.AgreeToNext; 
            var disagree = ApprovalCommands.Disagree;
            var fallback = ApprovalCommands.Fallback;

            //如果上一步审批流程指定的节点和当前节点不匹配，则忽略执行
            var head = builder.Then(_ => ExecutionResult.Next());
            var body = head.If(data => data.MatchExecutionStep(stepId))
                .Do(dCtx =>
                {
                    var tempUserTask =
                        dCtx.StartWith(_ => ExecutionResult.Next())
                            .If(data => data.CheckFallbackStep(stepId) == false)
                            .Do(then =>
                            {
                                if (preApproval != null)
                                {
                                    //如果当前已经触发了打回，但是打回路径又不符合，那么打向上一层
                                    //重要：这要求流程必须是一个顺序流
                                    then.StartWith(_ => { }).Then(preApproval);
                                }
                            })
                            .If(data => data.CheckFallbackStep(stepId) == true)
                            .Do(then =>
                            {
                                //如果命中了打回路径，那么需要重置标记
                                then.StartWith(sContext =>
                                {
                                    var data = GetData<T>(sContext);
                                    data.CompleteFallback(stepId);
                                });
                            })
                            //注册用户任务的同意选项和不同意选项
                            .UserTask(displayName, data => userKey)
                            .WithOption(agree.UniqueName, agree.DisplayName)
                            .Do(then =>
                            {
                                //选项---同意
                                then.StartWith(context =>
                                {
                                    var data = GetData<T>(context);
                                    //将当前步骤入栈
                                    data.MarkCurrentStep(stepId);
                                    data.RestNextStep(stepId);
                                });
                            })
                            .WithOption(disagree.UniqueName, disagree.DisplayName)
                            .Do(then =>
                            {
                                //选项---不同意
                                then.StartWith(context =>
                                {
                                    //将工作流结束
                                    context.Workflow.Status = WorkflowStatus.Terminated;
                                });
                            });

                    if (preApproval != null)
                    {
                        //如果当前节点允许打回，那么注册一个打回选项
                        tempUserTask = tempUserTask.WithOption(fallback.UniqueName, fallback.DisplayName)
                            .Do(then =>
                            {
                                then.StartWith(sContext =>
                                {
                                    var data = GetData<T>(sContext);
                                    data.RestNextStep(stepId);
                                    //标记开始打回，本次执行不入栈
                                    data.MarkFallback();
                                }).Then(preApproval);
                            });
                    }

                    if (optionalSteps != null)
                    {
                        foreach (var step in optionalSteps)
                        {
                            tempUserTask = tempUserTask.WithOption(step.Key, step.Value)
                                .Do(then =>
                                {
                                    //选项---转到特定步骤
                                    then.StartWith(sContext =>
                                    {
                                        var data = GetData<T>(sContext);
                                        data.MarkNextStep(step.Key);
                                        //将当前步骤入栈
                                        data.MarkCurrentStep(stepId);
                                    });
                                });
                        }
                    }
                });

            var end = body.Then(_ => ExecutionResult.Next());
            resultHead = head;
            return end;
        }

        public static IStepBuilder<T, ActionStepBody> FinishApproval<T>(
            this IStepBuilder<T, InlineStepBody> builder, Action action = null)
            where T : ApprovalFlowData
        {
            return builder.Then(context =>
            {
                action?.Invoke();
                context.Workflow.Status = WorkflowStatus.Complete;
            });
        }

        public static IStepBuilder<T, InlineStepBody> BeginApproval<T>(
            this IWorkflowBuilder<T> builder, Action action = null)
            where T : ApprovalFlowData
        {
            return builder.StartWith(_ =>
            {
                action?.Invoke();
                return ExecutionResult.Next();
            });
        }

        private static T GetData<T>(this IStepExecutionContext context)
            where T : ApprovalFlowData
        {
            var data = context.Workflow.Data as T;
            if (data == null)
            {
                throw new InvalidOperationException();
            }

            return data;
        }
    }`

and then use them:

`    public class Flow1 : IWorkflow<ApprovalFlowData>
    {
        public void Build(IWorkflowBuilder<ApprovalFlowData> builder)
        {
            builder.BeginApproval(() => { Console.WriteLine("审批启动"); })
                .AddApprovalStep("first", "初审", "u1", out var head1,
                    new Dictionary<string, string> {{"third", "送3审"}, {"final", "送终审"}})
                .AddApprovalStep("second", "再审", "u2", out var head2,
                    new Dictionary<string, string> {{"final", "送终审"}}, head1)
                .AddApprovalStep("third", "三审", "u3", out var head3, preApproval: head2)
                .AddApprovalStep("final", "终审", "u4", out _, preApproval: head3)
                .FinishApproval(() => { Console.WriteLine("审批完成"); });
        }

        public string Id => nameof(Flow1);

        public int Version => 1;
    }`

Since the code is short,  I suppose those chinese comments won't matter.
