### ISSUE TITLE
Loop Back or return to previous step in WF via JSON definition

### ISSUE THREAD

**Issue by rlanesPnnl** [danielgerlag/workflow-core#229]
This question is related to #62  #167 and #76 

We are creating a service that can orchestrate any number of workflow processes.  These processes include user interaction, as well as reaching out to external systems.

I'm very impressed by the work you have done, but I need help figuring out the best approach to implement the below workflow (this is just a sub-section of the overall workflow, also status is the document status, not the internal workflow status):
![drawing1](https://user-images.githubusercontent.com/46462539/50796544-cfa31580-1286-11e9-8218-724ed719ff7c.gif)

What I can't figure out is the best way to implement the loop back if the review returns the document to the author for revision.  Do you have any suggestions?

I should also mention that we want to use the JSON Document Loader to Load our definitions

**Comment by danielgerlag** [comment]
You could just set the `NextStepId`

This should create an infinite loop:
```json
{
  "Id": "HelloWorld",
  "Version": 1,
  "Steps": [
    {
      "Id": "Hello",
      "StepType": "MyApp.HelloWorld, MyApp",
      "NextStepId": "Bye"
    },        
    {
      "Id": "Bye",
      "StepType": "MyApp.GoodbyeWorld, MyApp",
      "NextStepId": "Hello"
    }
  ]
}
```

**Comment by rlanesPnnl** [comment]
Thx @danielgerlag  it was so obvious.  I am requesting permission to contribute to this project (it takes time) but I'd suggest adding this as an example in the docs.

**Comment by gonengf** [comment]
Is there a way to do the same thing with the fluent API in C#?
