### ISSUE TITLE
ExecutionResult.Persist runs the activity in an infinite loop.

### ISSUE THREAD

**Issue by devinmartin** [danielgerlag/workflow-core#23]
This could well be a misunderstanding, but when I return ExecutionResult.Persist(context.PersistenceData); The activity that returns this just runs and re-runs indefinitely in a loop. I had expected this to suspend the workflow until a host.ResumeWorkflow is called. It is more than possible that I don't understand what ExecutionResult.Persist is supposed to do, but it feels like it is doing the wrong thing by re-running the activity in an infinite loop.

**Comment by devinmartin** [comment]
using System;
using WorkflowCore.Interface;
using WorkflowCore.Models;
using WorkflowCore;
using WorkflowCore.Services;
using Microsoft.Extensions.DependencyInjection;


namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            IServiceCollection collection = new ServiceCollection();
            collection.AddLogging();
            collection.AddWorkflow();
            var provider = collection.BuildServiceProvider();

            var host = provider.GetService<IWorkflowHost>();

            host.Start();
            host.RegisterWorkflow<HelloWorldWorkflow>();

            var t = host.StartWorkflow("test", 1, null);

            Console.ReadLine();
            host.ResumeWorkflow(t.Result);

            Console.ReadLine();
            host.Stop();
        }
    }

    public class HelloWorldWorkflow : IWorkflow
    {
        public string Id => "test";

        public int Version => 1;

        public void Build(IWorkflowBuilder<object> builder)
        {
            builder
                .StartWith<HelloWorld>()
                .Then<GoodbyeWorld>();
        }
    }

    public class HelloWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("Hello world");
            return ExecutionResult.Persist(context.PersistenceData);
        }
    }

    public class GoodbyeWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("Goodbye world");
            return ExecutionResult.Next();
        }
    }
}

**Comment by devinmartin** [comment]
I had hoped that hello world would run and suspend the workflow, then resuming it at the host would run goodbye world. The infinite loop behavior feels like a bug even if I am using it wrong.

**Comment by danielgerlag** [comment]
That is what ExecutionResult.Persist is supposed to do, simply persist the state of the workflow with some data specific to that step.  You might be looking for ExecutionResult.Sleep, which would sleep the WF for a given interval, or you could look at the .WaitFor step together with host.PublishEvent

What is your use case?

**Comment by devinmartin** [comment]
I figured I was using it wrong, but it does seem odd to keep re-running the same activity. I'm assuming then that the activity would need to read the persisted state and know that it already persisted then return a next instead on subsequent runs of that activity.

I'm trying to re-write a workflow system I did in standard .net WF. Basically the workflow coordinates stuff between a bunch of third party systems that I don't really control. The idea is that the activities (or steps in your parlance) can delegate things to a system when the activity deems it appropriate without the workflow itself having to worry about it. That way a workflow creator can compose the process experience without worrying about which system is doing what and when. This was achieved by allowing certain pre-built activities to delegate tasks to other systems and a layer for each of those third party systems to resume the persisted workflow when the delegated task was complete.

Using waitfor would work if it could be included in an activity step rather than the workflow itself. Sleep doesn't help as it is delegating a task elsewhere and the step is merely the workflow representation thereof so the time is unknown.

**Comment by devinmartin** [comment]
Thanks for the ideas. At this point this thread is about what you want to do with your workflow engine. I can solve this by creating workflow composer classes that I can pass the builder or stepbuilders into. It will add the pre-step, WaitFor, and even a post step-without requiring the workflow composer to always consistently build a workflow, but instead to delegate composing multiple steps in a consistent way off to something else.

I will then by convention have the steps and the workflow composers built by the same group that understands the delegation process. And require those that compose the workflows without understanding (or needing to worry about) the underlying details to use the provided workflow composers.

Adding first class support for re-usable workflow pieces made of multiple steps could solve quite a few use cases. It is also nice as the execution engine doesn't change, and steps are still nice and light. It could also help with use cases in standard WF where they allow for composite activities made up of sub activities or even trees. Supporting that at the step level would be heavy and cumbersome. Allowing even complex pieces of the workflow to be pre-packaged would allow for any number of steps and control flow operations within could meet a lot of the same needs.

A few notes FWIW, these aren't criticisms or requests. Just thoughts.

Steps can defer execution by time, or invoke persistence, but can't suspend a workflow entirely or defer to an external event. This feels inconsistent to me.

**Comment by devinmartin** [comment]
More specifically on inconsistencies, it feels like either WaitFor should be put into the step, or sleep should be pulled out of the result and added as a special step like WaitFor.

**Comment by danielgerlag** [comment]
These are some great ideas!  I'm in the process of cleaning up the code to make it easier for other people to come in and work of this project... I will be making a major release in the next few days... but I will definitely try to incorporate some of your ideas in over the next few weeks.
