### ISSUE TITLE
Error executing Sample12 System.ArgumentException: Object of type 'System.Object' cannot be converted

### ISSUE THREAD

**Issue by germandb** [danielgerlag/workflow-core#234]
Hi Daniel I'm executing the WorkflowCore.Sample12 with the last source code 1.6.9. when the workflow executor tries to run the StepId 3 it fails in the proccesInputs method. The `Workflow.Data = {object}` and the  `input.Source = {Convert(2, Object)} `when the dynamic expression gets executed the following exception arraises, `System.ArgumentException: Object of type 'System.Object' cannot be converted to type 'WorkflowCore.Sample12.MyData'`

**Comment by danielgerlag** [comment]
should be resolved with https://github.com/danielgerlag/workflow-core/pull/237
