### ISSUE TITLE
WebJob and single execution

### ISSUE THREAD

**Issue by cristiamz** [danielgerlag/workflow-core#236]
Hi Daniel, I'm trying to use your code on a WebJob, and I'm using json workflows that will get loaded and executed each time a message on a Azure Service bus is received. The issue I'm having is that when I have multiple the requests are done in a short period of time to each other, the steps get executed multiple times per execution. 

Here is the code I have right now 

        public async Task ExecuteWorkflowAsync(dynamic DataObject, string WorkflowDef) {

            IServiceProvider serviceProvider = ConfigureServices();

            //start the workflow host
            var Workflowhost = serviceProvider.GetService<IWorkflowHost>();
            var _registry = serviceProvider.GetService<IWorkflowRegistry>();
            var loader = serviceProvider.GetService<IDefinitionLoader>();

            loader.LoadDefinition(WorkflowDef);
            Workflowhost.Start();

            dynamic wfDef = JsonConvert.DeserializeObject(WorkflowDef);
            string Id = wfDef.Id;
            int Version = wfDef.Version;

            var def = _registry.GetDefinition(Id, Version);

            if ((DataObject != null) && (def.DataType != null))
            {
                var dataStr = JsonConvert.SerializeObject(DataObject);
                object dataObj = JsonConvert.DeserializeObject(dataStr, def.DataType);
                var Workflowid = await Workflowhost.StartWorkflow(workflowId: Id, version: Version, data: dataObj);
            }

            await Task.Delay(5000);
            Workflowhost.Stop();

        }

        private static IServiceProvider ConfigureServices()
        {
            //setup dependency injection
            IServiceCollection services = new ServiceCollection();
            services.AddLogging();
            services.AddWorkflow();
            
            var serviceProvider = services.BuildServiceProvider(true);
            serviceProvider.CreateScope();

            return serviceProvider;
        }

My intention is to use your library as a one time execution, I send the json workflow def on the parameter WorkflowDef and the object assigned to that workflow on DataObject. 

Also notice that I had to put that  await Task.Delay(5000); to wait some time for the workflow to execute and then stop the host because it kept running and the next time I run the workflow it duplicate some steps. 

Let me know if you have any Ideas

Thanks!

_Originally posted by @cristiamz in https://github.com/danielgerlag/workflow-core/issue_comments#issuecomment-453342948_

**Comment by danielgerlag** [comment]
Don't start and stop the host for every workflow... start it once when your app starts up, and stop it when your app shuts down.  Everytime you start it again, it will poll the persistence store for older workflows that have not yet completed.
