### ISSUE TITLE
WorkflowCore.Sample07 - Razor Error

### ISSUE THREAD

**Issue by MasallahOZEN** [danielgerlag/workflow-core#238]
Hi, at first;thnx for your efforts, this is an awesome project. 

If I run "WorkflowCore.Sample07" project, I give this error:  (Last Release : workflow-core-1.7)

System.IO.FileLoadException: 'Could not load file or assembly 'Microsoft.AspNetCore.Razor.Runtime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)'

Thnx

**Comment by cbossie** [comment]
@MasallahOZEN - I literally just fought through this issue like an hour ago while trying to test some stuff out! I updated Sample07 to use the package Microsoft.AspNetCore 2.2.0 (and updated the associated libraries) and the WorkflowCore.WebAPI project to .NET Standard 2.0, and it all ran fine. I know it's just a little stopgap, but at least it allows you to run it for now...

**Comment by MasallahOZEN** [comment]
Excellent, thnx for quick response.

Have any compare for future with "https://github.com/aelassas/Wexflow" ? What's diff ?

Thnx.

**Comment by cbossie** [comment]
Interesting - never seen that one before... looks like it's a little more enterprise-y.... I think workflow-core seems good for a small to medium size project. It has some pretty good basic features.

**Comment by MasallahOZEN** [comment]
Have any project plan for Rule engine on wf core?

**Comment by MasallahOZEN** [comment]
> @MasallahOZEN - I literally just fought through this issue like an hour ago while trying to test some stuff out! I updated Sample07 to use the package Microsoft.AspNetCore 2.2.0 (and updated the associated libraries) and the WorkflowCore.WebAPI project to .NET Standard 2.0, and it all ran fine. I know it's just a little stopgap, but at least it allows you to run it for now...

Each package is licensed to you by its owner. NuGet is not responsible for, nor does it grant any licenses to, third-party packages. Some packages may include dependencies which are governed by additional licenses. Follow the package source (feed) URL to determine any dependencies.

Package Manager Console Host Version 4.9.0.5661

Type 'get-help NuGet' to see all available NuGet commands.

PM> Microsoft.AspNetCore 2.2.0 
Microsoft.AspNetCore : The term 'Microsoft.AspNetCore' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and 
try again.
At line:1 char:1
+ Microsoft.AspNetCore 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.AspNetCore:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PM> update Microsoft.AspNetCore 2.2.0 
update : The term 'update' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ update Microsoft.AspNetCore 2.2.0
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (update:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
PM> Install-Package Microsoft.AspNetCore -Version 2.2.0
Restoring packages for C:\Projects\Workflows\workflow-core-master\src\extensions\WorkflowCore.WebAPI\WorkflowCore.WebAPI.csproj...
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore/index.json 219ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore/2.2.0/microsoft.aspnetcore.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore/2.2.0/microsoft.aspnetcore.2.2.0.nupkg 220ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hostfiltering/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iis/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.commandline/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.usersecrets/index.json
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.eventsource/index.json
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hostfiltering/index.json 211ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hostfiltering/2.2.0/microsoft.aspnetcore.hostfiltering.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.commandline/index.json 335ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.commandline/2.2.0/microsoft.extensions.configuration.commandline.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.usersecrets/index.json 545ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.usersecrets/2.2.0/microsoft.extensions.configuration.usersecrets.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iis/index.json 663ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iis/2.2.0/microsoft.aspnetcore.server.iis.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.hostfiltering/2.2.0/microsoft.aspnetcore.hostfiltering.2.2.0.nupkg 576ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration/index.json 875ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration/2.2.0/microsoft.aspnetcore.server.iisintegration.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.commandline/2.2.0/microsoft.extensions.configuration.commandline.2.2.0.nupkg 621ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/index.json 1008ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/2.2.0/microsoft.extensions.configuration.json.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.usersecrets/2.2.0/microsoft.extensions.configuration.usersecrets.2.2.0.nupkg 647ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.eventsource/index.json 1241ms
  GET https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.eventsource/2.2.0/microsoft.extensions.logging.eventsource.2.2.0.nupkg
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iis/2.2.0/microsoft.aspnetcore.server.iis.2.2.0.nupkg 786ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.aspnetcore.server.iisintegration/2.2.0/microsoft.aspnetcore.server.iisintegration.2.2.0.nupkg 605ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.logging.eventsource/2.2.0/microsoft.extensions.logging.eventsource.2.2.0.nupkg 556ms
  OK https://api.nuget.org/v3-flatcontainer/microsoft.extensions.configuration.json/2.2.0/microsoft.extensions.configuration.json.2.2.0.nupkg 942ms
Installing Microsoft.Extensions.Configuration.Json 2.2.0.
Installing Microsoft.Extensions.Logging.EventSource 2.2.0.
Installing Microsoft.AspNetCore.Server.IIS 2.2.0.
Installing Microsoft.AspNetCore.Server.IISIntegration 2.2.0.
Installing Microsoft.Extensions.Configuration.UserSecrets 2.2.0.
Installing Microsoft.Extensions.Configuration.CommandLine 2.2.0.
Installing Microsoft.AspNetCore.HostFiltering 2.2.0.
Installing Microsoft.AspNetCore 2.2.0.
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Diagnostics 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Routing 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.Extensions.Logging 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Server.IISIntegration 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Hosting 2.2.0 -> Microsoft.Extensions.Hosting.Abstractions 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Server.Kestrel 2.2.0 -> Microsoft.AspNetCore.Server.Kestrel.Core 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Server.Kestrel.Https 2.2.0 -> Microsoft.AspNetCore.Server.Kestrel.Core 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.HostFiltering 2.2.0 -> Microsoft.AspNetCore.Hosting.Abstractions 2.2.0 -> Microsoft.Extensions.Hosting.Abstractions 2.2.0 -> 
Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Server.IIS 2.2.0 -> Microsoft.AspNetCore.Authentication.Core 2.2.0 -> Microsoft.AspNetCore.Authentication.Abstractions 2.2.0 -> 
Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Server.IIS 2.2.0 -> Microsoft.AspNetCore.Hosting.Abstractions 2.2.0 -> Microsoft.Extensions.Hosting.Abstractions 2.2.0 -> 
Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : NU1605: Detected package downgrade: Microsoft.Extensions.Logging.Abstractions from 2.2.0 to 1.1.2. Reference the package directly from the project to select a different version. 
 WorkflowCore.WebAPI -> Microsoft.AspNetCore 2.2.0 -> Microsoft.AspNetCore.Server.Kestrel 2.2.0 -> Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets 2.2.0 -> Microsoft.AspNetCore.Hosting.Abstractions 2.2.0 -> 
Microsoft.Extensions.Hosting.Abstractions 2.2.0 -> Microsoft.Extensions.Logging.Abstractions (>= 2.2.0) 
 WorkflowCore.WebAPI -> Microsoft.Extensions.Logging.Abstractions (>= 1.1.2)
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'WorkflowCore.WebAPI'.
At line:1 char:1
+ Install-Package Microsoft.AspNetCore -Version 2.2.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:00:09.1137240
PM>

**Comment by EyalIsr** [comment]
> @MasallahOZEN - I literally just fought through this issue like an hour ago while trying to test some stuff out! I updated Sample07 to use the package Microsoft.AspNetCore 2.2.0 (and updated the associated libraries) and the WorkflowCore.WebAPI project to .NET Standard 2.0, and it all ran fine. I know it's just a little stopgap, but at least it allows you to run it for now...

@cbossie Thanks!
I also had to "unlock" `WorkflowCore.WebAPI` `netstandard` from a specific version in order to compile.
The `WorkflowCore.WebAPI's .csproj` NetStandardImplicitPackageVersion should be modify to successfully build `netstandard2.0`.

**Comment by MasallahOZEN** [comment]
Thnx
