### ISSUE TITLE
Question: dynamic step properties

### ISSUE THREAD

**Issue by AlexTkatch** [danielgerlag/workflow-core#239]
Hi,

Thanks for providing this library, Daniel!

I'm evaluating it for one of the projects I'm working on. Similar to issue #199, I'm trying to model a "dynamic" workflow. In my case, both the set of properties of the workflow data **and** the set of properties of some of the steps need to be dynamic. Like below, where a set of properties "name1", "name2" as well as "wf-name1", "wf-name2" is variable while class definitions for steps and workflow are fixed.

```
workflow<DynamicData>
  step 1
    inputs
      step-data["name1"] = workflow-data["wf-name1"]
      step-data["name2"] = workflow-data["wf-name2"]
      ...
    outputs
      workflow-data["wf-name3"] = step-data["name3"]
      ...
```

The part for resolving the workflow data side is already working well by exposing indexer from the DynamicData-like class as added in PR #173.

How difficult do you think would it be to support setting/getting properties on step dynamically? I can imagine a fall-back to using some sort of indexer in the code inside ProcessInputs:

```
"Inputs": {
        "StepData[\"name1\"]": "data[\"wf-name1\"]"
}
```

Of course in the meantime it's possible to use one-off string-based mapping rules, but it would be nice to use Inputs and Outputs mapping for this!

Best regards,
Alex.

**Comment by danielgerlag** [comment]
I'm looking into this... should get something out within a week or so.

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/releases/tag/1.8

**Comment by federicorOT** [comment]
@danielgerlag  Sorry if is not here the best place to make this question, but I'm using this DynamicData feature, I already registered a workflow like the ones in the tests
 `{
"Definition":
       {
		  "Id": "Test",
		  "Version": 1,
		  "Description": "",
		  "DataType":"WorkflowEngine.Logic.Workflows.Data.DynamicData, WorkflowEngine.Logic",
		  "Steps": [
		    {
		      "Id": "Step1",
		      "StepType": "WorkflowEngine.Logic.Workflows.Steps.Counter, WorkflowEngine.Logic",
		      "Inputs": { "Value": "data[\"Counter1\"]" },
		      "Outputs": { "Counter1": "step.Value" },
		      "NextStepId": "Step2"
		    },
		    {
		      "Id": "Step2",
		      "StepType": "WorkflowEngine.Logic.Workflows.Steps.Counter, WorkflowEngine.Logic",
		      "Inputs": { "Value": "data[\"Counter2\"]" },
		      "Outputs": { "Counter2": "step.Value" },
		      "NextStepId": "Step3"
		    },
		    {
		      "Id": "Step3",
		      "StepType": "WorkflowCore.Primitives.If, WorkflowCore",
		      "NextStepId": "Step4",
		      "Inputs": { "Condition": "object.Equals(data[\"Flag1\"], true)" },
		      "Do": [
		        [
		          {
		            "Id": "Step3.1.1",
		            "StepType": "WorkflowEngine.Logic.Workflows.Steps.Counter, WorkflowEngine.Logic",
		            "Inputs": { "Value": "data[\"Counter3\"]" },
		            "Outputs": { "Counter3": "step.Value" },
		            "NextStepId": "Step3.1.2"
		          },
		          {
		            "Id": "Step3.1.2",
		            "StepType": "WorkflowEngine.Logic.Workflows.Steps.Counter, WorkflowEngine.Logic",
		            "Inputs": { "Value": "data[\"Counter4\"]" },
		            "Outputs": { "Counter4": "step.Value" }
		          }
		        ],
		        [
		          {
		            "Id": "Step3.2.1",
		            "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
		            "NextStepId": "Step3.2.2",
		            "CancelCondition": "object.Equals(data[\"Flag2\"], true)",
		            "Inputs": {
		              "EventName": "\"Event1\"",
		              "EventKey": "\"Key1\"",
		              "EffectiveDate": "DateTime.Now"
		            }
		          },
		          {
		            "Id": "Step3.2.2",
		            "StepType": "WorkflowEngine.Logic.Workflows.Steps.Counter, WorkflowEngine.Logic",
		            "Inputs": { "Value": "data[\"Counter5\"]" },
		            "Outputs": { "Counter5": "step.Value" }
		          }
		        ]
		      ]
		    },
		    {
		      "Id": "Step4",
		      "StepType": "WorkflowEngine.Logic.Workflows.Steps.Counter, WorkflowEngine.Logic",
		      "Inputs": { "Value": "data[\"Counter6\"]" },
		      "Outputs": { "Counter6": "step.Value" }
		    }
		  ]
       },
       "CustomerId": "8b3bb542-5c47-4e6d-9831-fb9c9e76e4f3",
       "DatabaseId": "8b3bb542-5c47-4e6d-9831-fb9c9e76e4f3"
}`
But I'm not being able to pass the data when initiating it, sure that its something easy, but I'm blocked 
the error is when deserializing the object my dataObj is getting null
`var dataStr = JsonConvert.SerializeObject(data);
                    var dataObj = JsonConvert.DeserializeObject(dataStr, def.DataType);
                    workflowId = await _workflowService.StartWorkflow(id, version, dataObj, reference);`

I'm sending this in my request to initiate it
`{  

	   "Counter1":100,
	   "Counter2":200,
	   "Counter3":300,
	   "Counter4":400,
	   "Counter5":500,
	   "Counter6":600,
	   "Flag1":true,
	   "Flag2":true,
	   "Title":"Virsraksts",
	   "Dict":{  
	      "one":"first",
	      "two":"second"
	   }

}`

Really thank you if can help me
