### ISSUE TITLE
Dynamic Workflow - ExecutionPointer step matching Json StepId 

### ISSUE THREAD

**Issue by MasallahOZEN** [danielgerlag/workflow-core#240]
Hi, I'm testing libraries for understanding that how works :) At this time, i found something that may be usefull; "Execute workflow from stored JSON definition" named test unit, use dynamic workflow from json.

How can I understand for which step name math with ExecutionPointer step ?

Sorry for my English :) I'm from Turkey and i am still learning.

![image](https://user-images.githubusercontent.com/811777/51246704-0ae6c800-199c-11e9-87a6-fb61aca760fe.png)

**Comment by danielgerlag** [comment]
You can set the `Name` property within the JSON for each step, and there is a `StepName` column for the SQL Server persistence provider

**Comment by MasallahOZEN** [comment]
Thnx daniel.

**Comment by ShaoYir** [comment]
@danielgerlag  The stepid in the executionpointer persistence table is not the stepid defined in JSON. It seems to be the sequence ID of the step. However, I need this data. How can I get it?
