### ISSUE TITLE
QUESTION : SagaScenario - Compensation

### ISSUE THREAD

**Issue by MasallahOZEN** [danielgerlag/workflow-core#242]
Hi, I'm testin and learning about Compensation with SagaScenario. My question;

- Compansation5Fired is true but  Compansation1Fired is false, Why ? Becasue, in SagaContainer,
Compansation2Fired and Compansation3Fired are true.

I couldn't find detail doc about it in site, or I may not have seen sorry :(

Thnx

![image](https://user-images.githubusercontent.com/811777/51257674-27ddc400-19b9-11e9-9aca-17c41ab6c83f.png)

**Comment by danielgerlag** [comment]
Compansation5 is for the overall Saga transaction... Compansation1 is outside of the scope of the saga

**Comment by MasallahOZEN** [comment]
So, can I say ;

if an exception occured 
  - in a step, before and after Compansation execute 
  - in a sagacontainer, only after Compansation execute

**Comment by MasallahOZEN** [comment]
Hi again, what's different about compansation, between saga transaction and "then" step ?

**Comment by mukesh-shobhit** [comment]
Sorry for commenting on closed issue, but I found issue in CompensateWithSequence. It does not call all the steps in CompensateWithSequence method.
