### ISSUE TITLE
Feature Request: Example load from json project

### ISSUE THREAD

**Issue by incompletude** [danielgerlag/workflow-core#251]
Hey guys,

Thank you for the library.

Is it possible to have a working example using the load from json feature using a Web API project? I'm having a hard time putting this together from the docs only.

**Comment by peterkozak** [comment]
We're storing the JSON Workflows in a Database. As we're running workflow core in Service Fabric, we have multiple nodes that need registration for each in the DB stored workflows. Please find a sample attached.

      private void RegisterWorkflows(SqlConnectionStringBuilder cs)
        {
            var amWDbRegistry = new WorkflowTemplateRegistry(cs);
            var amWDbTemplates = new WorkflowTemplateDefinition(cs);

            // Get All Templates with the newest versions
            var dbWfList = amWDbTemplates.GetUnregistered(Context.NodeContext.NodeName, false);
            if (dbWfList.Count > 0)
            {
                Logger.Trace($"Found {dbWfList.Count} unregistred Workflows for Node {Context.NodeContext.NodeName}");
            }

            // register each workflow
            foreach (var wf in dbWfList)
            {
                Logger.Info($"Registering {wf.WorkflowName} | Version: {wf.Version} for tenant {wf.TenantId}");
                try
                {
                    // register with service
                    var loader = serviceProvider.GetService<IDefinitionLoader>();
                    var wfd = loader.LoadDefinition(wf.WorkflowJson);


                    // mark in database  as registered for this node
                    amWDbRegistry.Add(wf.Id, Context.NodeContext.NodeName);
                    Logger.Info(
                        $"Workflow {wf.WorkflowName} | Vers: {wf.Version} registered for tenant {wf.TenantId} on Node {Context.NodeContext.NodeName}");
                }
                catch (Exception e)
                {
                    Logger.Error(e,
                        $"Could not register Workflow {wf.WorkflowName} registered for tenant {wf.TenantId} on Node {Context.NodeContext.NodeName}");
                    LogManager.Flush();

                }
            }
        }

**Comment by danielgerlag** [comment]
@incompletude were you able to make it work?

**Comment by incompletude** [comment]
@danielgerlag This is good enough, I was able to build some prototype.

It would be nice to have something like this in the docs.

Thx.
