### ISSUE TITLE
Question: Set step property from json workflow definition

### ISSUE THREAD

**Issue by incompletude** [danielgerlag/workflow-core#255]
I have a step like:

```
    public class Hello : StepBody
    {
        public string Property { get; set; }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("Hello");
            return ExecutionResult.Next();
        }
    }
```

I understand I can use a `Data` class to pass data to the step, but I wonder if I can set the `Property` value during the workflow definition, something like:

```
{
  "Id": "HelloWorld",
  "Version": 1,
  "Steps": [
    {
      "Id": "Hello",
      "StepType": "MyApp.HelloWorld, MyApp",
      "Property": "value",
      "NextStepId": "Bye"
    },        
    {
      "Id": "Bye",
      "StepType": "MyApp.GoodbyeWorld, MyApp"
    }
  ]
}
```

If this is a not a feature, is it easily achievable? I'm thinking about a fork to support this. 

I have lots of steps that require some kind of value that doesn´t make sense to carry around the workflow using inputs. Is there a way around this?

**Comment by danielgerlag** [comment]
Yes you can, you don't need to map the property to a member on the `Data` object, you could just specify a static value

**Comment by incompletude** [comment]
Ok, that was kinda of lame. Thx Daniel.
