### ISSUE TITLE
Workflow Core with Angular

### ISSUE THREAD

**Issue by dexterhussain** [danielgerlag/workflow-core#256]
Hello, We are creating an application in.Net Core with its separate frontend running in Angular 6. Now we are adding a Sales Module in the Application which has around 6 forms and each form needs to be approved and in 2 forms a form is divided in more than 4 parts each part needs to be approved by a specific person. 
Now I cannot figure out how I will implement this workflow using WorkFlow Core and Send/Get Results from a Rest API in Angular. Like if Step 1 is Get approved by Sales Coordinate as soon as he Approves a form how backend will get notified. 
kind help will be appreciated :)

**Comment by dexterhussain** [comment]
This is not an issue, but a query.

**Comment by dexterhussain** [comment]
One thing More , I also need that a User can edit the Workflow from a GUI , like change steps change the person who sends an approval can figure out how to do that as well, Thanks

**Comment by dexterhussain** [comment]
My WorkFlow is more of Human Work Flow. I also have users , now do I have to Load all Groups using the Nuget Package you provided?

**Comment by danielgerlag** [comment]
You can use the `WaitFor` within your workflow and then use the 'PublishEvent` behind your API to pass data back into an in-flight workflow.  The `Users` package is more of a demo of what you can build on top of WorkflowCore, if your requirements are complex, it may be worth implementing custom primitives for your use case.

**Comment by muzzammilhussain** [comment]
Yes I also do think So , that I have implement Custom Primitives. Thanks alot for your reply . Your engine is great i Really liked it
