### ISSUE TITLE
Versioning Workflows

### ISSUE THREAD

**Issue by FBettati** [danielgerlag/workflow-core#257]
Hello @danielgerlag, thanks for writing this library, it's fantastic! The one question I have centers around versioning.

Let's say we're running workflow A, which contains a 'DoSomething' step. Now we'd like to deploy a new version of the workflow, B, with an updated 'DoSomething' step, but without impacting already running versions of workflow A. 

Is there no versioning story for steps? As far as I can tell, if we wanted to change step functionality without disrupting previously running workflows, we'd have to create a new workflow version, create a new step with the updated functionality with a different name, and then reference that step in the new workflow version.

Is the suggested solution to do this? As time goes by we'll probably end up with a collection of steps for each modified step to differentiate them in the workflow engine, i.e. 'DoSomething3', 'DoSomething4', etc...

**Comment by danielgerlag** [comment]
That is correct, if you have any idea's on what features we could develop to better manage versioning on this level of granularity, I'd love to hear them 😄

**Comment by softwareguy74** [comment]
Correct me if I'm wrong, but aren't workflows already "versioned" by having a Version property?  Or am I totally missing something?

**Comment by danielgerlag** [comment]
That is correct, you can version workflows, but if you change a step that is used by a workflow, it is not automatically versioned, so you need to be careful in that regard.
