### ISSUE TITLE
Multi server environement

### ISSUE THREAD

**Issue by ssougnez** [danielgerlag/workflow-core#259]
Hello,

I'm currently building a whole application around workflow-core and the infrastructure side of the company I'm working for wants it not to be a single point of failure, so I have to use a multi front end environment. The cloud is currently not an option.

I checked the document and I found this: https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Providers.Redis

It seems to fit perfectly for what I want for but there is not much documentation. Do I just have to apply what's written under "Usage" and poof, everything work directly? How reliable is this?

For now, I'm using EF Core provider to store workflow data, is the Redis provider a replacement for this?

Maybe my question is stupid as everything seems to be manager by the Redis provider but I want to be sure.

Thanks for the enlightenment

**Comment by danielgerlag** [comment]
Hi,

You do not need to stop using the EF provider as your datastore... but you will need a queue and lock provider to coordinate the nodes.  So, you only need to configure these Redis providers:
```
cfg.UseRedisLocking("localhost:6379");
cfg.UseRedisQueues("localhost:6379", "app-name");
```
The Redis persistence provider is only if you want to use Redis as the main data store.

see https://github.com/danielgerlag/workflow-core/wiki/08.-Multi-node-clusters

**Comment by ssougnez** [comment]
So does that mean that just by adding the two lines of code you mentioned, I'll be sure that I can have as many servers as I want in my cluster, there won't be any risk that two servers handle the same workflow at the same moment ? 

If the answer is yes then wfcore is really an awesome library...

**Comment by danielgerlag** [comment]
That is correct, provided you use the same config for every node

**Comment by ssougnez** [comment]
I already told it but the work you did on that library is absolutely awesome. Every time I need something I found out that it is already supported.

Really good job !

**Comment by ssougnez** [comment]
I have one last question about this (and I don't want to open a new thread for this).

I'm considering using Redis as a QM and DLM but I saw that it's also possible to use it as an EventHub.
What is it exactly ? Is it required in a multi cluster environment and can I do without?

**Comment by danielgerlag** [comment]
It's just a way of publishing messages when things like a workflow start / finish, etc... so that you can subscribe to them and hook in some custom logic.
see https://github.com/danielgerlag/workflow-core/releases/tag/1.6.9

**Comment by rashmy-git** [comment]
Hi,
I just started experimenting with your library to setup a multi-node cluster on the cloud. Thank you for the great library.

A question on the behavior in multi-node setup. For my use case, I'm registering the workflow on-demand. It appears that the workflow definition registrations are only stored in-memory. So the concern is when I start a workflow, the other nodes are not able to pick up and execute the steps since they do not have the workflow registrations. Is there a way to move the workflow registrations into a common persistence like Redis so that all nodes can lookup from the same common registry?

Thanks!
