### ISSUE TITLE
Question about JOIN workflow steps

### ISSUE THREAD

**Issue by clanghir** [danielgerlag/workflow-core#26]
Hi Daniel,

thank you for your awesome work!  I have a question regarding implementing a "JOIN" workflow step which means a workflow step that waits until all predecessor steps are finished.

Another question is about an "END" step which terminates the current workflow. For example if there are multiple paths within a workflow and one path hits an END step this step should terminate the current WF.

Do have examples for such steps? Or could you at least describe how to implement this?  

Regards,
Christian

**Comment by danielgerlag** [comment]
Hi,

At present, those scenarios are not possible but they make total sense to me added to the core library.  The "END" step should be fairly trivial to implement and I will try get this done sometime next week.  With regards to the "JOIN" step, that is definitely something I would like to support but I want to think about the best way to implement it first so if you can hang in there for a couple of weeks I can add it.

**Comment by danielgerlag** [comment]
Hi Christian,

I have just released a new version that adds parallel foreach constructs and while loops as new features.
Have a look at this example and let me know if you could implement your solution with something like this?

https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample09

**Comment by danielgerlag** [comment]
Version 1.2.2 also has the .EndWorkflow method

**Comment by clanghir** [comment]
Hi Daniel,

Thanks a lot for your efforts - it just works ;-).

Regards,
Christian

**Comment by danielgerlag** [comment]
Also, just added parallel steps, see sample
https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample13
