### ISSUE TITLE
Question: about ProcessExecutionResult and EventSubscription

### ISSUE THREAD

**Issue by MasallahOZEN** [danielgerlag/workflow-core#260]
Hi, first of all thanks for the good job! This project is very good and I am using it with . 

My question is; when I start workflow for HumanWorkflow in "WorkflowCore.Sample08" test lib, for same event in the step of workflow instance has more subscription records in the table. Is this right, cannot understand it :( 

Thnx

![image](https://user-images.githubusercontent.com/811777/52846035-a1341800-3119-11e9-994f-2bdc1d59d291.png)

![image](https://user-images.githubusercontent.com/811777/52845988-82ce1c80-3119-11e9-801e-25e3f6d433a5.png)

**Comment by danielgerlag** [comment]
I don't see this on my side.... what version are you using?

**Comment by MasallahOZEN** [comment]
resolved with "#262" issue.
