### ISSUE TITLE
Humanworkflow with mssql in Sample.08

### ISSUE THREAD

**Issue by MasallahOZEN** [danielgerlag/workflow-core#262]
Hi again, I have a problem about Humanworkflow. When workflow persistence is memory there are no problem but when persistence is Mssql , then openuseraction hasnot result. Because, not creating executionpoint for useraction event.

Help please :(

![image](https://user-images.githubusercontent.com/811777/52864791-0143b200-314c-11e9-92cd-9294e5afc046.png)

**Comment by danielgerlag** [comment]
I am not able to reproduce this on my side... what versions of each library are you using?

**Comment by MasallahOZEN** [comment]
I'm using latest versions. I found the problem. This problem occurs when "ExtensionAttribute" cannot be insert.

I was looking "ExtensionAttribute" changes for what's happining when escalation occuring with sql trigger.  Sql trigger was firing exception and insert cannot be applied. 

But now, there is a another problem for me :) While I'm testing "WorkflowCore.Sample08" app,   in the debug console,something caught my attention. 
I'm registering one workflow but another wf as if trying to add to itself. Is this a problem ?
 

![image](https://user-images.githubusercontent.com/811777/52931022-e5aef600-335b-11e9-8375-0b35cfcbdc6c.png)

**Comment by danielgerlag** [comment]
it sounds like you've modified the sample somehow?

**Comment by MasallahOZEN** [comment]
No I havent modified. Onlye db tables have dirty data. But is the dirty data problem for wf core?

**Comment by danielgerlag** [comment]
are you 100% sure you are running the correct sample?

**Comment by MasallahOZEN** [comment]
Yes, thnx for quick response. Attached my dirty db :)

[wf_testdata_script.zip](https://github.com/danielgerlag/workflow-core/files/2876977/wf_testdata_script.zip)

**Comment by MasallahOZEN** [comment]
Hi daniel, could you check that, is this a bug?

**Comment by danielgerlag** [comment]
Could you start with a clean copy of the code and a clean db and test again?

**Comment by danielgerlag** [comment]
I cannot reproduce your issue, I will try look at your db on the weekend

**Comment by MasallahOZEN** [comment]
You can reproduce that issue, just adding a after insert trigger on ExtensionAttribute and throw an exception in it. 

Thnx

**Comment by danielgerlag** [comment]
I had a look at your DB... it seems you have modified the schema of the workflow core tables (indexes are missing, additional tables, triggers, etc...)  
This is basically the same as modifying the library and unfortunately not something that I can support.
