### ISSUE TITLE
page transitions based on defined workflows

### ISSUE THREAD

**Issue by fatagun** [danielgerlag/workflow-core#265]
Hello

Is it possible to use workflow core for page transitions?

For example:

I have a dynamic form wizard with multiple steps. I would like to define the steps as following:

```
public class MyWorkFlow : IWorkflow
    {
        public string Id => "1";

        public int Version => 1;

        public void Build(IWorkflowBuilder<object> builder)
        {
            builder.StartWith<PageStep1>()
                   .Then<PageStep2>()
                   .Then<PageStep3>();
                   
        }
    }
```

I am hoping to have a solution that starts with pagestep1 then goes to pagestep 2 and then finally to pagestep3 respectively. 

For example:

```
FooController
{
   Action:PageStep1();
}

BarController
{
  Action:PageStep2();
}

CarController
{
  Action:PageStep3();
}
```
How and where should I manage transitions and state?

I am using .net core mvc project with server side rendering. 

What do i need to add to my project to have this working?

Thanks.

**Comment by danielgerlag** [comment]
you would need to use the `WaitFor` steps and `PublishEvent` to achieve something like this.
see: https://github.com/danielgerlag/workflow-core/wiki/04.-Responding-to-external-events
