### ISSUE TITLE
services.AddAutoMapper fails during unit testing (by using WebApplicationFactory) due to version mismatch of EFCore in WorkflowCore.Persistence.PostgresSQL (with System.Reflection.ReflectionTypeLoadException)

### ISSUE THREAD

**Issue by uskorc** [danielgerlag/workflow-core#268]
Greetings,

Not related to the code, but I just wanted to report this in case someone else gets a similar error in a similar scenario.

If **WorkflowCore.Persistence.PostgresSQL** is referenced and other projects in the target solution use the **2.2 version of EFCore.Tools, EFCore.Design**, a 'strange' exception occurs during unit test run (by using **WebApplicationFactory**) on the **services.AddAutoMapper** line. (Please note that **during normal run this exception does not occur**.)

```
System.Reflection.ReflectionTypeLoadException : Unable to load one or more of the requested types.
Could not load type 'Microsoft.EntityFrameworkCore.Metadata.Internal.RelationalFullAnnotationNames' from assembly 'Microsoft.EntityFrameworkCore.Relational, Version=2.2.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.
```

I tried to resolve it by calling Mapper.Reset() or by adding the newest version of the EFCore packages to the project where WorkflowCore.Persistence.PostgresSQL is used, but no luck. The same if I add those to the unit test project. (I tried it due to hints I got from other similar issues I found on AutoMapper and Entity repos).

If I download your code and update the Npgsql.EntityFrameworkCore.PostgreSQL, Microsoft.EntityFrameworkCore.Design and Microsoft.EntityFrameworkCore.Tools to latest version and  build the postgres persistence project and use those binaries (WorkflowCore.Persistence.PostgreSQL.dll, WorkflowCore.Persistence.EntityFramework.dll) in my solution, the problem goes away.

I do not know whether/when you plan to update but, as said, just wanted to report it in case someone else comes across a similar problem in a similar scenario.

Thank you for your time and effort!
Regards, Uros.

**Comment by danielgerlag** [comment]
Thanks for finding this, I think the `AddAutomapper` extension method that automapper provides has some overloads to constrain the assemblies that it performs reflection on, you could probably try that as well.

**Comment by uskorc** [comment]
Hey, thank you for the reply and the hint, the problem is solved as well if, as suggested, I simply constrain the assemblies when calling Automapper.

`.AddAutoMapper(typeof(Startup));`
