### ISSUE TITLE
Error handling JSON，I Can not get error 

### ISSUE THREAD

**Issue by yuzhaoMR** [danielgerlag/workflow-core#270]

**Comment by yuzhaoMR** [comment]
I register like this
var loader = app.ApplicationServices.GetService<IDefinitionLoader>();
loader.LoadDefinition(WorkflowJsons.GetWorkflowJsons());

**Comment by danielgerlag** [comment]
How do you know there is an error?

**Comment by yuzhaoMR** [comment]
I can get workflow instance,when WaitFor the event ,I can not into the NextStep,no corresponding

**Comment by yuzhaoMR** [comment]
this my code

`
 builder
                .StartWith<InitWorkFlow>()
                .WaitFor("DepartmentAuditedEvent", (data, context) => context.Workflow.Id)
                    .Output(data => data.WorkflowDataJson, step => step.EventData)
                .Then<UpdateWorkflow>()
                    .Input(step => step.WorkflowDataJson, data => data.WorkflowDataJson)
                    .Output(data => data.State, step => step.State)
                .If(data => data.State == "true").Do(then => then
                    .StartWith<InitWorkFlow>()
                    .WaitFor("CompanyAuditedEvent", (data, context) => context.Workflow.Id)
                        .Output(data => data.WorkflowDataJson, step => step.EventData)
                    .Then<UpdateWorkflow>()
                        .Input(step => step.WorkflowDataJson, data => data.WorkflowDataJson));
`
when i convert to json,it can not run WaitFor
`
{
  "Id": "AskForLeaveWorkflow",
  "Version": 1,
  "DataType": "WorkflowCoreTestWebAPI.Models.WorkflowData, WorkflowCoreTestWebAPI",
  "Steps": [
    {
      "Id": "InitialStep",
      "StepType": "WorkflowCoreTestWebAPI.Steps.InitWorkFlow, WorkflowCoreTestWebAPI",
      "NextStepId": "WaitForStep"
    },
    {
      "Id": "WaitForStep",
      "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
      "NextStepId": "UpdateStep",
      "Inputs": {
        "EventName": "\"DepartmentAuditedEvent\"",
        "EventKey": "context.Workflow.Id"
      },
      "Outputs": {
        "WorkflowDataJson": "step.EventData"
      }
    },
    {
      "Id": "UpdateStep",
      "StepType": "WorkflowCoreTestWebAPI.Steps.UpdateWorkflow, WorkflowCoreTestWebAPI",
      "NextStepId": "IfStep",
      "Inputs": {
        "WorkflowDataJson": "data.WorkflowDataJson"
      },
      "Outputs": {
        "State": "step.State"
      }
    },
    {
      "Id": "IfStep",
      "StepType": "WorkflowCore.Primitives.If, WorkflowCore",
      "Inputs": {
        "Condition": "data.State == \"true\""
      },
      "Do": [
        [
          {
            "Id": "IfInitialStep",
            "StepType": "WorkflowCoreTestWebAPI.Steps.InitWorkFlow, WorkflowCoreTestWebAPI",
            "NextStepId": "IfWaitForStep"
          },
          {
            "Id": "IfWaitForStep",
            "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
            "NextStepId": "IfUpdateStep",
            "Inputs": {
              "EventName": "\"CompanyAuditedEvent\"",
              "EventKey": "context.Workflow.Id"
            },
            "Outputs": {
              "WorkflowDataJson": "step.EventData"
            }
          },
          {
            "Id": "IfUpdateStep",
            "StepType": "WorkflowCoreTestWebAPI.Steps.UpdateWorkflow, WorkflowCoreTestWebAPI",
            "Inputs": {
              "WorkflowDataJson": "data.WorkflowDataJson"
            }
          }
        ]
      ]
    }
  ]
}
`

**Comment by yuzhaoMR** [comment]
I forget host to start
