### ISSUE TITLE
workflow-core Users

### ISSUE THREAD

**Issue by Nokecy** [danielgerlag/workflow-core#271]
We appreciate you support if you or your organization is using workflow-core. You are welcome to leave replies about your product and organization here, which could became the confidence of maintiners, communication and undecided watchers.

**Comment by jannikbuschke** [comment]
We are currently evaluating workflow core as a workflow solution for our on-premise applications. We are using it now in our first project and overall are happy with the results so far. We are a small Software Company in Germany/Hamburg.
