### ISSUE TITLE
Get All Workflow Definitions

### ISSUE THREAD

**Issue by LyonBlecher** [danielgerlag/workflow-core#274]
I would like to be able to retrieve all workflow definitions that have been registered.

`public List<WorkflowDefinition> GetDefinitions()
{
                return _registry.Select(i => i.Item3).ToList();
}`

**Comment by germandb** [comment]
You can use the elastic search engine, please read [
Elasticsearch plugin for Workflow Core](https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Providers.Elasticsearch)

**Comment by LyonBlecher** [comment]
I thought the elastic search functionality was to search for instances of workflows, not the actual definitions? I'm looking for a registry implementation that returns the definitions , not instances, or is my understanding incorrect?

**Comment by danielgerlag** [comment]
That sounds like a reasonable need... I would approve a PR that implement this feature

**Comment by dbhc** [comment]
Is anyone looking into implementing this?
This would be very useful for JSON implementations.
