### ISSUE TITLE
load balancing environment

### ISSUE THREAD

**Issue by Shubbi** [danielgerlag/workflow-core#276]
How can I use the workflow-core in a web application which sits behind a load balancer on multiple nodes?

Do I need to have it on  a single application server which is accessible to all the instances of web application on various nodes?

**Comment by germandb** [comment]
Take a look to this [RabbitMQ Queue Provider](https://github.com/danielgerlag/workflow-core/blob/master/src/providers/WorkflowCore.QueueProviders.RabbitMQ/README.md)

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/wiki/08.-Multi-node-clusters

**Comment by Shubbi** [comment]
I see SqlServerQueue Provider  also in the code. 
Is there any reason not to use SQL Server ServiceBroker?

**Comment by danielgerlag** [comment]
You can use any queue provider you wish but you also need a shared lock provider.
