### ISSUE TITLE
Joining workflow paths after multiple outcomes

### ISSUE THREAD

**Issue by rdivossen** [danielgerlag/workflow-core#28]
Hello @danielgerlag 

I'm just figuring out how to use workflow-core but I have problems joining workflow paths after branching the workflow due to multiple outcomes of a step.  What I need is the following:

`builder
                .StartWith<A>(x => x.Name("Switch"))
                    .When(true)
                        .Then<B>()
                        .Then<C>()
                        .End<A>("Switch")
                    .When(false)
                        .Then<D>()
                        .End<A>("Switch")
                .Then<E>();`

Unfortunately Step "E" is never reached.
How would I get A-B-C-E for A=true and A-D-E for A=false ?
I do not want to add step E to both paths to avoid redundancy.

Your help would be greatly appreciated.
Regards,
René

**Comment by danielgerlag** [comment]
Hi,

Your current workflow would only reach E if the result of A was null or `ExecutionResult.Next`...
I have other requests to create join functionality as described above and am currently investigating how best to implement it.  I should have this feature added in the next couple of weeks.

Daniel

**Comment by geraldcampilla** [comment]
Hi, 

Are there any progress on this? I have the same problem with the op to avoid redundancy. If yes, can you give me a snippet of the code on how to do this?

Your work is such a beauty. Works likes charm.

Thanks,
Gerald
