### ISSUE TITLE
Using .Recur logs error from CancellationProcessor

### ISSUE THREAD

**Issue by easchmitz** [danielgerlag/workflow-core#280]
If I pass in a model value as the TimeSpan interval in the .Recur step
`.Recur(data => TimeSpan.FromSeconds(data.ConfigSettings.EscalationInterval)`
 I get the following log error:
 `[ERR] [W.S.CancellationProcessor] Exception has been thrown by the target of an invocation.`
The code still works, but I would rather not see these error alerts.  I have set the log level to "Fatal" on that class, but was wondering if this is expected behavior.

Thanks!

**Comment by danielgerlag** [comment]
What is the second parameter you are passing to recur?
I think there is an underlying problem with your workflow... I won't remove the logging.

**Comment by easchmitz** [comment]
Here is the .Recur with second parameter. 

.Recur(data => TimeSpan.FromSeconds(data.ConfigSettings.EscalationTime),
                    data => data.MessageIds.Count > data.ConfigSettings.EscalationCount || data.IsAlertAck).Do(recur => recur

**Comment by danielgerlag** [comment]
I believe the `data => data.MessageIds.Count > data.ConfigSettings.EscalationCount || data.IsAlertAck` lambda is throwing the exception when it get's evaluated.

**Comment by easchmitz** [comment]
Yes, you are correct.  I was loading the ConfigSettings from appSettings in Step 1 of the workflow.
The exception was logged because it the CancellationProcessor check ran before that data was loaded.
I reworked the code so the ConfigSettings returns an empty instance if it is null and that resolved the issue.

Thanks for the help in getting to the cause of the problem.
