### ISSUE TITLE
Can we use a Logging abstraction other than Microsoft.Extensions.Logging?

### ISSUE THREAD

**Issue by Shubbi** [danielgerlag/workflow-core#283]
For using the workflow core I've to always put the following line of code
private IServiceProvider ConfigureServices()
        {
            IServiceCollection services = new ServiceCollection();
            services.AddLogging(); 
            ......
        }
which kinds of make it dependent on Microsoft.Extensions.Logging.
Our team is using a logging abstraction LibLog (https://github.com/damianh/LibLog)
My question is, do I need to modify the way the logging is getting configured. 
If yes, how?

**Comment by danielgerlag** [comment]
you can use any logging library that implements `microsoft.extensions.logging.abstractions`

eg. https://github.com/serilog/serilog-extensions-logging
