### ISSUE TITLE
Users extension doesn't validate users/groups?

### ISSUE THREAD

**Issue by jannikbuschke** [danielgerlag/workflow-core#284]
In this example https://github.com/danielgerlag/workflow-core/tree/master/src/extensions/WorkflowCore.Users the defined user in the workflow definition ( "MYDOMAIN\\user") differs from the one given when invoking host.PublishUserAction ("MYDOMAIN\\someuser"). Also in my tests providing different or same users doesn't change the observable behavior (at least from what I could tell). It seems these values are just ignored.

Is this by design? If so, how would I allow only certain users to execute an action on a specific workflow instance?

**Comment by danielgerlag** [comment]
That kind of logic is up to you to build around the library, you can use the `GetOpenUserActions` to determine what is possible and then build whatever auth logic you want around it.

**Comment by jannikbuschke** [comment]
Hi thanks for clarifying so quickly.
As I looked first at the core Event/Notification/WaitFor feature - where a string comparison with a run-time value determines if the WaitFor condition is met -  I would _expect_ that user/group values in the User workflow also modify the execution path (maybe this should be addressed in the doc/sample).

Followup question: Setting these values seem to not change the Workflow execution, but are just logged to the database? Their purpose is **logging who did what**, and possibly can be retrieved via the search feature?

**Comment by danielgerlag** [comment]
You can make the result of a WaitFor cause the workflow to take a different path, simply map the data returned onto a field on your workflow data object and then use it in an `If` step, etc...

The `Users` package is mostly meant as an example of how one can build extension modules around the core library... the results are stored in the workflow's execution pointer `ExtensionAttribute` values, you should be able to see this in your DB and when you retrieve a workflow view the persistence service.

**Comment by jannikbuschke** [comment]
Awesome, thanks for clarifying!
