### ISSUE TITLE
Saga doesn't skip over steps if error occurs within If

### ISSUE THREAD

**Issue by rosspace** [danielgerlag/workflow-core#288]
In the following scenario if an error occurs within the If block at step4 I'd expect the workflow to continue on after the CompensateWith step but it actually picks up after the if at step6. If this is how sagas are supposed to work how would I get the behavior I would want where the workflow would pick up after the compensate step?

```C#
builder.StartWith<step1>()
  .Saga(saga => saga
    .StartWith<step2>()
    .If(data => someCondition)
      .Do(inner => inner
        .StartWith<step3>()
        .Then<step4>() // error occurs here
        .Then<step5>()
      )
    .Then<step6>() // after compensate workflow picks up here
    .Then<step7>()
  )
  .CompensateWith<MarkError>()
  .Then<FinalStep>() // I'd expect the workflow to pick up here after compensate
```

**Comment by danielgerlag** [comment]
Thanks for logging this... are you able to wrap this scenario into a failing integration test?

**Comment by danielgerlag** [comment]
Would you say this test mirrors your issue?
https://github.com/danielgerlag/workflow-core/blob/master/test/WorkflowCore.IntegrationTests/Scenarios/NestedRetrySagaScenario.cs

**Comment by rosspace** [comment]
I'm honestly having a difficult time following that test. I don't think it is exactly what I'm talking about since I only have the one compensate step for the entire saga. Do you want me to fork this project and add a test for my situation or just create a small project with a unit test?

**Comment by danielgerlag** [comment]
if you could even just paste a Test in the format of the one linked here, that would help me get to the bottom of it faster... I will spend some time drilling into it regardless, but that would be a huge help.

**Comment by rosspace** [comment]
Here's a gist that recreates the issue: https://gist.github.com/rosspace/4ddc44a86b01e5648ab1b7d2a09173de

**Comment by danielgerlag** [comment]
Which version are you using?

**Comment by rosspace** [comment]
1.6.8

**Comment by danielgerlag** [comment]
Try upgrading to the latest version and let me know if that helps.

**Comment by rosspace** [comment]
Looks like that fixed the issue. I guess this had already been handled. Thanks for your help.
