### ISSUE TITLE
Concat multiple UserSteps

### ISSUE THREAD

**Issue by rdivossen** [danielgerlag/workflow-core#29]
Hello Daniel,

how can multiple UserSteps be concatenated?

`builder
                .StartWith(context => ExecutionResult.Next())
                .UserStep("Do you approve A", data => "MYDOMAIN\\user", x => x.Name("Approval Step A"))
                .UserStep("Do you approve B", data => "MYDOMAIN\\user", x => x.Name("Approval Step B"))`

does not do the trick. Calling "host.GetOpenUserActions(workflowId)" will only return one openItem.

Again, your help would be appreciated.

Regards,
René

**Comment by rdivossen** [comment]
Another thing probably related to the above:
If I add a "Then" step after the "UserStep", an Option "Proceed" will be added to the UserStep.
Do I have to "close" the UserStep somehow before being able to add further steps?

Regards,
René

**Comment by danielgerlag** [comment]
Hi, this functionality could be achieved as part of the Join step functionality I am currently working on... I will update you once implemented.

**Comment by danielgerlag** [comment]
Hi Rene,

I have just released a new version that adds parallel foreach constructs and while loops as new features.
Have a look at this example and let me know if you could implement your solution with something like this?

https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample09

**Comment by rdivossen** [comment]
Hi Daniel,

thanks for your replies to this and my other request.  Since our project is quite time critical, we had to move along and are now using a state machine implementation for our solution.  If we ever need workflows again for some other project we might get back to workflow-core.
Thanks for providing your work here!

Regards,
René
