### ISSUE TITLE
Multiple instance based on one workflow definition

### ISSUE THREAD

**Issue by Balu2** [danielgerlag/workflow-core#292]
Hi

I am using your WorkflowCore library in my own workflow project. This project should have the following functionality:
- create a json workflow definition dynamically, lets say def.json;
- based on def.json multiple workflow instances must be created;
- those workflow instances must be persisted in a SQLServer dbase;
- the workflow instances can be long running (months);
- after restart of the server the long running workflow instances should come back in status they had before the server was restarted;

I have the following questions:
- when I have loaded the workflow definition with _loader.LoadDefinition(workflowJson), how should I created multiple instances based on the same definition? (Using _workflowService.StartWorkflow(workflowDef.Id) is only possible once)
- what must be done to get the running instances in their state again after server / core website restart?

Kind regards
Luc

**Comment by danielgerlag** [comment]
You can start as many instances as you want with `StartWorkflow`, there are no limits.
When your app starts, you simply call `WorkflowHost.Start` and it will find running workflows and execute them, you just need to use one of the persistence providers as explained here: https://github.com/danielgerlag/workflow-core/wiki/07.-Persistence-Providers

**Comment by Balu2** [comment]
hello Daniel

Thanks for your quick response. 
Your samples and tests project gives a lot of information how to work with WorkflowCore. And yes I implemented the SQLProvider for persistence. But imagine the following scenario:
a long running workflow is started where after a couple of steps (lets say step 1 and step 2) have been carried out, a long running wait step 3 (lets say 1 month) is activated.
When the app restarts, how does the WorkflowHost know at which step to proceed with the long running workflow? The workflowhost should not carried out Step 1 and Step 2 again, but should go on with Step 3.

Hope to hear from you

Kind regards
Luc

**Comment by danielgerlag** [comment]
That's kind of the whole point of a workflow engine 😄 
That's what it does... keeps track of the state of a workflow.

**Comment by apphost** [comment]
I have the same question.

**Comment by danielgerlag** [comment]
This is the core of what this library does, is there something not working on your end?

**Comment by apphost** [comment]
I just didn't know how to activate an exists workflow instance. Is it activated by events?

**Comment by danielgerlag** [comment]
> When your app starts, you simply call `WorkflowHost.Start` and it will find running workflows and execute them

**Comment by fayush20** [comment]
Hello @danielgerlag , I am using  WF Core in my project I have one issue, whenever we update or delete a WF definition, if some of the WF instances are running and we update the WF definition or delete it, we see a lot of errors from WF core and it retries infinitely for those WF instances with the deleted or previous versions of WF definitions, so can we handle this particular case  in WF core somewhere to "Terminate" those running WF instances if WF core doesn't found the previous version of WF definition ??
