### ISSUE TITLE
Workflow core app is not working properly in azure app service

### ISSUE THREAD

**Issue by shekarpolasa** [danielgerlag/workflow-core#293]
Hi,

I have created a dotnet core application and used workflow-core packages. The workflows are running properly in local environment but **when we host the app as Azure App service the workflows are not running properly** such as workflows are being terminated/suspended automatically without any error message.

Apart from that, the **changes are not reflected when we release new workflow version in azure app**.

Am I missing any configurations in azure app service?

Help would be appreciated. Thanks in advance!

**Comment by danielgerlag** [comment]
This sounds like the steps in your workflow could be failing because of some kind of misconfiguration...
Did you setup logging?... what do the logs say?
