### ISSUE TITLE
human workflow & attach

### ISSUE THREAD

**Issue by mehdizz** [danielgerlag/workflow-core#294]
.If(data => data.SelectRoute == "18").Do(then => then
                        .StartWith(context => ExecutionResult.Next())
                        .Id("step2")
                            .Output(data => data.WFId, step => 3)
                            .Output(data => data.WFName, step => "MyWF")
                            .Output(data => data.WfStateId, step => 18)
                            .Output(data => data.WFStateName, step => "done")

                            .UserTask("usretask6", data => data.WfStateId.ToString())
                                .WithOption("1", "back").Do(then2 => then2
                                    .StartWith(context => ExecutionResult.Next())

                                    .Attach("start")
                                )
                                .WithOption("2", "approve").Do(then2 => then2
                                    .StartWith(context => ExecutionResult.Next())

                                    .Output(data => data.SelectRoute, step => "21")
                                )
                    )
                    .If(data => data.SelectRoute == "21").Do(then => then
                        .StartWith(context => ExecutionResult.Next())
                        .Id("step3")
                            .Output(data => data.WFId, step => 3)
                            .Output(data => data.WFName, step => "MyWF")
                            .Output(data => data.WfStateId, step => 21)
                            .Output(data => data.WFStateName, step => "Approve N")

                            .UserTask("usretask7", data => data.WfStateId.ToString())
                                .WithOption("1", "back").Do(then2 => then2
                                    .StartWith(context => ExecutionResult.Next())

                                    .Attach("step2")
                                )
                                .WithOption("2", "approve i").Do(then2 => then2
                                    .StartWith(context => ExecutionResult.Next())

                                    .Output(data => data.SelectRoute, step => "22")
                                )
                                .WithOption("3", "approve p").Do(then2 => then2
                                    .StartWith(context => ExecutionResult.Next())

                                    .Output(data => data.SelectRoute, step => "23")
                                )
                    )
Hi
 This is part of my workflow, this work fine when use forward
but when back to ("step2") and then go next step ("step3") after that It does not find the route!
thanks alot for workflow engine

**Comment by danielgerlag** [comment]
Could you wrap your expectations into a failing integration test?

**Comment by mehdizz** [comment]
If i apply step 3 inside .WithOption("2", "approve") , it will be correct. As below

 .If(data => data.SelectRoute == "18").Do(then => then
                    .StartWith(context => ExecutionResult.Next())
                    .Id("step2")
                        .Output(data => data.WFId, step => 3)
                        .Output(data => data.WFName, step => "MyWF")
                        .Output(data => data.WfStateId, step => 18)
                        .Output(data => data.WFStateName, step => "done")

                        .UserTask("usretask6", data => data.WfStateId.ToString())
                            .WithOption("1", "back").Do(then2 => then2
                                .StartWith(context => ExecutionResult.Next())

                                .Attach("start")
                            )
                            .WithOption("2", "approve").Do(then2 => then2
                                .StartWith(context => ExecutionResult.Next())

                    .Id("step3")
                        .Output(data => data.WFId, step => 3)
                        .Output(data => data.WFName, step => "MyWF")
                        .Output(data => data.WfStateId, step => 21)
                        .Output(data => data.WFStateName, step => "Approve N")

                        .UserTask("usretask7", data => data.WfStateId.ToString())
                            .WithOption("1", "back").Do(then2 => then2
                                .StartWith(context => ExecutionResult.Next())

                                .Attach("step2")
                            )
                            .WithOption("2", "approve i").Do(then2 => then2
                                .StartWith(context => ExecutionResult.Next())

                                .Output(data => data.SelectRoute, step => "22")
                            )
                            .WithOption("3", "approve p").Do(then2 => then2
                                .StartWith(context => ExecutionResult.Next())

                                .Output(data => data.SelectRoute, step => "23")
                            )                                
                            )
                )

However, the problem was solved, but I think there's a problem in the first case.
