### ISSUE TITLE
Question about Json representation and dictionaries w/ JSON workflow definition

### ISSUE THREAD

**Issue by wyrn73** [danielgerlag/workflow-core#298]
We are using the equivalent of a Dictionary<string,object> datatype in our workflowcore workflows as a generic datatype.

In this case data["emailTemplateParameters"] is a Dictionary<string,string>.

I am having an issue figuring out how to express

data["emailTemplateParameters"]["rejectingActor"] as an output variable. 

I know this doesn't work:

             {
                  "Id": "Get_RejectedActor",
                  "NextStepId": "Failed_Notification",
                  "StepType": "<stepType>",
                  "Inputs": {
                    "ApprovalResponse": "data[\"approvalStatus\"]"
                  },
                  "Outputs": {
                    "emailTemplateParameters[\"rejectingActor\"]": "step.LastActor"
                  }
                }

Is there a way to do this in the json representation or am I wasting my time? :)

**Comment by danielgerlag** [comment]
I'm not sure nested dictionaries would work at the moment... this test should show how it works on the top level.

https://github.com/danielgerlag/workflow-core/blob/master/test/WorkflowCore.TestAssets/stored-dynamic-definition.json#L11

https://github.com/danielgerlag/workflow-core/blob/master/test/WorkflowCore.IntegrationTests/Scenarios/StoredScenario.cs#L58

**Comment by brettwinters** [comment]
#899
