### ISSUE TITLE
When re-start the workflow. How can I start after the last step executed?

### ISSUE THREAD

**Issue by kcleto** [danielgerlag/workflow-core#299]
Hi,

Let's assume that the service that runs the workflows has been closed.

When restarting the service and loading the workflows, how can I continue from where they left off?

It is possible? How?

**Comment by danielgerlag** [comment]
Make sure you're using one of the persistence providers as mentioned here:

https://github.com/danielgerlag/workflow-core/wiki/07.-Persistence-Providers

and then just start the host again, and it will look for workflows saved in your persistence store that need to run.
