### ISSUE TITLE
Stuck in the last step at multi steps workflow definition from Json

### ISSUE THREAD

**Issue by galipcevrik** [danielgerlag/workflow-core#301]
Hi Daniel,
first of all thanks for the good job!

I have a problem. I create workflow definition from json like that ; 

```
{
  "Id": "galip_test",
  "Version": 1,
  "Steps": [
    {
      "Id": "StartStep101",
      "StepType": "..StartStep, ..App",
      "Inputs": {
        "Request": "\"{...}\""
      },
      "NextStepId": "DataUpdateStep135"
    },
    {
      "Id": "DataUpdateStep135",
      "StepType": "..DataUpdateStep, ..App",
      "Inputs": {
        "Request": "\"{...}\""
      },
      "NextStepId": "NotificationStep131"
    },
    {
      "Id": "NotificationStep131",
      "StepType": "..NotificationStep, ..App",
      "Inputs": {
        "Request": "\"{...}\""
      }
    }
  ]
}
```

Everything so oke here but  always "NotificationStep131" is working repeatedly when it is time for and there isn't any error log on PostgreSql. I created multi step other definition. But when I do other experiments, the last step is constantly repeating itself.

I wonder what I may be doing wrong? I'll be glad if you help me. Thanks u.

**Comment by danielgerlag** [comment]
Have you configured detailed logging?... What do your logs say?
