### ISSUE TITLE
Event table is locked and WF doesn't continue

### ISSUE THREAD

**Issue by andresarroyave** [danielgerlag/workflow-core#303]
Hello,

I have a Workflow that calls an external service that could take long to answer back (minutes, hours), So I'm waiting for an event in the Step until the service responses.

```
public override async Task<ExecutionResult> RunAsync(IStepExecutionContext context)
{
      if (context.ExecutionPointer.EventName == Constants.EventName.RunExeCompleted)
      {
          return ExecutionResult.Next();
      }

      await _action.ExecuteAsync(Parameters...);

      return ExecutionResult.WaitForEvent(Constants.EventName.RunExeCompleted, eventCallbackId, DateTime.Now);
}
```

The external service runs and then publishes the event in order to continue with the next step:

```
public void PublishEvent(string eventName, Guid callbackId)
        {
            _workflowHost.PublishEvent(eventName, callbackId.ToString(), null);
        }
```

The process continues with the next step most of the times, but sometimes the same workflow doesn't moves to the next step. It just get stuck in the step. I went to the WFC's Event and Subscription tables to see if the event was processed, but I noticed that the Event table is blocked and the SELECT statement gets running forever:

![image](https://user-images.githubusercontent.com/39885574/56053848-dc6a5600-5d1a-11e9-8320-38b68af6b191.png)

If I use WITH(NOLOCK) in the SELECT I'm able to retrieve all records:

![image](https://user-images.githubusercontent.com/39885574/56059135-ff9c0200-5d28-11e9-84c4-637edfd5d992.png)

This is how I initialize WFC:

`services.AddWorkflow(x => x.UseSqlServer(ConfigurationManager.ConnectionStrings["ConnectionString"].ConnectionString, true, true));`

Could you please help.

**Comment by danielgerlag** [comment]
can you run `sp_who2` to determine what is blocking it?

**Comment by andresarroyave** [comment]
This is the response of the `sp_who2` command:

![image](https://user-images.githubusercontent.com/39885574/56059023-ae8c0e00-5d28-11e9-9583-97b70db231cd.png)

**Comment by danielgerlag** [comment]
I think it would be better to use the custom step to invoke the external system and use a separate standard WaitFor step to wait for the result rather try build your own WaitFor primitive.

Something like this
```c#
public override async Task<ExecutionResult> RunAsync(IStepExecutionContext context)
{
      await _externalService.ExecuteAsync(Parameters...);

      return ExecutionResult.Next();
}
```

```c#
builder
  .StartWith<CallExternalSystem>()
  .WaitFor("MyEvent", data => data.Id))

```

**Comment by andresarroyave** [comment]
I'm not using my own WaitFor primitive . I'm using ExecutionResult's standard WaitForEvent.

![image](https://user-images.githubusercontent.com/39885574/56674872-6eaa1c80-6680-11e9-8b38-b9b927978609.png)

**Comment by danielgerlag** [comment]
This sounds like an async messaging pattern, if this is the case, you need to create an extra step in the workflow to wait for the response from the external system, so that the workflow can persist it's state in between.

If you want to try build your own compound step, rather use `EventPublished` instead of `EventName`
Have a look at
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Primitives/WaitFor.cs#L19

This is what happens immediately after returning `ExecutionResult.WaitForEvent`
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/ExecutionResultProcessor.cs#L42
