### ISSUE TITLE
Change data on running workflow instance

### ISSUE THREAD

**Issue by Balu2** [danielgerlag/workflow-core#304]
Hello Daniel,

I start a defined workflow with following data object:

var data = new WorkflowData
{
    Lead = new Lead
    {
        LeadName = "John Johnson",
        LeadEmail = "john@johnson.com"
    }
};
var workflowId = _workflowCoreController.StartWorkflow(workflowTemplateId, data).Result;
 
Is it possible to change the specific data for a running workflow, for instance when the LeadEmail has been changed? Is there a specific function available or is changing the Data field in the Workflow table in the database the only option?

Kind regards
Luc

**Comment by danielgerlag** [comment]
Instead of storing all the data in the workflow, I would save it in your own database and just store the ID in the workflow, then each step can access the DB with the latest data.

**Comment by Balu2** [comment]
Of course it is possible that a step accesses the dbase. But there are situations that a workflow is started with a specific data object and changes to this data object are necessary afterwards because something happens. Is that possible?

**Comment by danielgerlag** [comment]
You'd have to design your workflow to be able to change it's data, possibly by running a parallel event or something and then using the `Output`s to change it... I would not recommend directly modifying the data in the workflow core tables.  
If you really wanted to go down that path though, rather create a service the take `IDistributedLockProvider` and `IPersistenceProvider`, then lock the workflow ID and use the Persistence Provider to modify the data.

**Comment by Balu2** [comment]
Hi Daniel

Thx for your input. I will see if we can extend each designed workflow with a parallel event step to update  the data object.

regards
Luc

**Comment by softwareguy74** [comment]
Having worked with several workflow systems in my career, I can tell you that you want to keep data to a minimum inside the workflow itself and as suggested, just keep a reference ID to the record in a database.  You'll make your life MUCH easier doing it this way, trust me.
