### ISSUE TITLE
Workflow core architecture with connected systems

### ISSUE THREAD

**Issue by ponugotisumanrao** [danielgerlag/workflow-core#305]
Hi @danielgerlag ,

Here is my example application where we are trying to use Workflowcore

An application (call it as : App-A : .Net core Web Api). 
When a particular end point is called which writes a event to Queue (one of the queue providers supported by workflow core  and libraries from workflow core) 
There is a console application written in .net core (call it as App-B) which is an workflow engine where the workflow is executed and state/instances are managed.
Now the App-B has to communicate (sending a REST request and wait for them to finish - long running process. 
some manual action needed like kind of approve) with applications as part of the workflow steps
(calle as App-C & App-D .Net core applications)
App-C & App-D also uses the libraries from workflow core and writes the events to queue
Based on the events coming from App-C & App-D , now the workflow has to be resumed from workflow engine.

Is this possible and my understanding correct. 

Any suggestions on this are really appreciated.

Let me know if you have any questions.

Thanks,

**Comment by danielgerlag** [comment]
That sounds reasonable... you can publish events to a workflow by calling the `PublishEvent` method on the workflow host, internally workflow core uses queues and distributed locks to the push that event to the underlying workflows and execute them.  

In your instance, it sounds like App B would listen for queue messages and then publish corresponding events to the workflow host.

**Comment by ponugotisumanrao** [comment]
Hi Daniel, 
Thanks for the response. Some more details: In my scenario, App-b listen for queue messages and App-A, App-C & D are the ones writing to queue. 

Based on your comment my understanding is that: App-B listen for queue messages and when it receives then publishes an event. which will start the work flow with in App-B (App-B is kind of workflow execution engine)

Thanks,
Suman
