### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by geraldcampilla** [danielgerlag/workflow-core#306]
Hi Daniel,

Are there any progress on this issue? Can you let us know how to implement this? 

Thanks,
Gerald

Hi,

Your current workflow would only reach E if the result of A was null or `ExecutionResult.Next`...
I have other requests to create join functionality as described above and am currently investigating how best to implement it.  I should have this feature added in the next couple of weeks.

Daniel

_Originally posted by @danielgerlag in https://github.com/danielgerlag/workflow-core/issues/28#issuecomment-298178326_

**Comment by danielgerlag** [comment]
We did add `.Join` for parallel paths.

https://github.com/danielgerlag/workflow-core/wiki/06.-Control-Structures#parallel-paths

Is this what you are looking for?

**Comment by geraldcampilla** [comment]
Parallel is for running multiple steps at the same time. What I am after is for multiple outcome (using When()). So let's say I have two routes (When(true) and When(false) after performing their own task routes, it will eventually go to ContinuationStep()). I am attaching a diagram for better understanding. Hopefully it makes sense.

![image](https://user-images.githubusercontent.com/12004711/57588976-4ff0c480-7560-11e9-8f62-e209759bfb63.png)

Thanks,
Gerald

**Comment by danielgerlag** [comment]
Could you achieve that with `Attach`?

https://github.com/danielgerlag/workflow-core/releases/tag/1.8.3

**Comment by geraldcampilla** [comment]
I am not sure if it's possible with my scenario or I am having trouble using the attach method. So my code goes like the one in below:

public void Build(IWorkflowBuilder<BusinessCase> builder)
        {

            var businessCaseCreation = builder
                    .StartWith<BusinessCaseCreation>()
                        .Input(step => step._businessCase, data => data)
                        .OnError(WorkflowErrorHandling.Terminate)
                    .Then<SendEmailRoute>()
                        .Input(step => step._MailTo, data => data.OwnerEmail)
                        .Input(step => step._Subject, data => $"New Business Case Submitted with ID { data.BusinessCaseNumber }")
                        .Input(step => step._Message, data => $"You have submitted a new busienss case for review.")
                        .OnError(WorkflowErrorHandling.Terminate);

            var businessCaseRequireApproval = businessCaseCreation.Then<CheckIfBusinessCaseNeedsApproval>()
                     .Then<CheckIfBusinessCaseNeedsApproval>(x => x.Name("CheckApproval"))
                         .Input(step => step.BusinessCaseId, data => data.ID)
                         .Input(step => step.BusinessCaseId, data => data.ID);

            businessCaseRequireApproval.Name("businessCaseApproval").When(data => true)
                .Do(then =>
                {
                    then
                        .StartWith<AssignBusinessCaseToUser>()
                            .Input(step => step.BusinessCase, data => data)
                            .Input(step => step.User, data => data.ProjectLeadName)
                            .Input(step => step.StatusId, data => 1)
                            .OnError(WorkflowErrorHandling.Terminate)
                        .Then<SendEmailRoute>()
                            .Input(step => step._MailTo, data => data.ProjectLeadEmail)
                            .Input(step => step._Subject, data => $"{ data.BusinessCaseNumber }: Request for Approval")
                            .Input(step => step._Message, data => $"{ data.BusinessCaseNumber } is pending for your approval")
                        .OnError(WorkflowErrorHandling.Terminate)
                        .WaitFor($"ApprovalEvent_{1}", (data, context) => context.Workflow.Id, data => DateTime.Now)
                            .Output((step, data) =>
                            {
                                data.StatusId = (step.EventData as StatusUpdate).Status;
                                data.ModifiedBy = (step.EventData as StatusUpdate).UserId;
                                data.ModifiedDate = (step.EventData as StatusUpdate).ModifiedDate;
                            })
                        .OnError(WorkflowErrorHandling.Terminate)
                        .Then<AssignBusinessCaseToUser>()
                            .Input(step => step.BusinessCase, data => data)
                            .Input(step => step.User, data => "CAPEX_CHIEFOFTECHNOLOGY")
                            .Input(step => step.StatusId, data => 2)
                            .OnError(WorkflowErrorHandling.Terminate)
                        .Then<SendEmailRouteToGroup>()
                            .Input(step => step._MailTo, data => "CAPEX_CHIEFOFTECHNOLOGY")
                            .Input(step => step._Subject, data => $"{ data.BusinessCaseNumber }: Request for Approval")
                            .Input(step => step._Message, data => $"{ data.BusinessCaseNumber } is pending for your approval - Chief of Technology.")
                        .OnError(WorkflowErrorHandling.Terminate)
                        .WaitFor($"ApprovalEvent_{2}", (data, context) => context.Workflow.Id, data => DateTime.Now)
                            .Output((step, data) =>
                            {
                                data.StatusId = (step.EventData as StatusUpdate).Status;
                                data.ModifiedBy = (step.EventData as StatusUpdate).UserId;
                                data.ModifiedDate = (step.EventData as StatusUpdate).ModifiedDate;
                            })
                        .OnError(WorkflowErrorHandling.Terminate)
                        .Then<AssignBusinessCaseToUser>()
                            .Input(step => step.BusinessCase, data => data)
                            .Input(step => step.User, data => "CAPEX_CAPITALANDEXPENDITURES")
                            .Input(step => step.StatusId, data => 2)
                            .OnError(WorkflowErrorHandling.Terminate)
                        .Then<SendEmailRoute>()
                            .Input(step => step._MailTo, data => "CAPEX_CAPITALANDEXPENDITURES")
                            .Input(step => step._Subject, data => $"{ data.BusinessCaseNumber }: Request for Approval")
                            .Input(step => step._Message, data => $"{ data.BusinessCaseNumber } is pending for your approval - Capital and Expenditures.")
                        .OnError(WorkflowErrorHandling.Terminate)
                        .WaitFor($"ApprovalEvent_{3}", (data, context) => context.Workflow.Id, data => DateTime.Now)
                            .Output((step, data) =>
                            {
                                data.StatusId = (step.EventData as StatusUpdate).Status;
                                data.ModifiedBy = (step.EventData as StatusUpdate).UserId;
                                data.ModifiedDate = (step.EventData as StatusUpdate).ModifiedDate;
                            })
// SendToSupply
                        .OnError(WorkflowErrorHandling.Terminate);
                })
                .When(data => false).Do(then =>
                {
                    then.StartWith<UpdateBusinessCaseStatus>()
                                .Input(step => step.BusinessCase, data => data)
                                .Input(step => step.UserId, data => "Supply")
                                .Input(step => step.StatusId, data => 5)
// SendToSupply
                            .OnError(WorkflowErrorHandling.Terminate);
                })
                .Then<SendToSupply>()
                    .Input(step => step.BusinessCase, data => data);

Note that When(true) routine will involve WaitForEvent, but when I run the code above, it will not wait for any WaitForEvent but will execute the last step (Then<SendToSupply>()) immediately. Is there a way to like assign the Then<SendToSupply>() to a variable and then attach it to When() subroutines so that it will only execute when I attach them in my workflow step?

Thanks and appreciate your help.

**Comment by danielgerlag** [comment]
Since your diagram above is easier to reason about, I think you're looking for something like this?

```c#
        builder
            .StartWith<HelloStep>()
            .Then<DecisionStep>()
                .When(data => "Yes").Do(then => then
                    .StartWith<Task1>()
                    .Then<Task2>()
                )
                .When(data => "No").Do(then => then
                    .StartWith<Task3>()
                )
            .Then<ContinueTask>();
```

```c#
    public class DecisionStep : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            if (<<condition>>)
                return ExecutionResult.Outcome("Yes");
            else
                return ExecutionResult.Outcome("No");
        }
    }
```

Also see this sample: https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample12

**Comment by geraldcampilla** [comment]
Thanks for the update.

That is what I've done however, if I insert a WaitFor inside When() clause, the ContinueTask will get executed without waiting for any external events.

builder
            .StartWith<HelloStep>()
            .Then<DecisionStep>()
                .When(data => "Yes").Do(then => then
                    .StartWith<Task1>()
                    .Then<Task2>()
                    **.WaitFor("MyEvent", data => "0"))
                        .Output((step, data) => {
                        }).Then(context => ExecutionResult.Next)**
                )
                .When(data => "No").Do(then => then
                    .StartWith<Task3>()
                )
            .Then<ContinueTask>();

Is there a way to wait for external events before going to the ContinueTask when it's inside the When() clause?

**Comment by geraldcampilla** [comment]
Please disregard last message. I was able to make it work now. 

Great library by the way and excited to see it evolve in the future.

I'm gonna close this thread now.

**Comment by Balu2** [comment]
Hello Daniel

At the moment I am working on an integration of a visual designer with workflow core. I convert the visual design to a json workflow that can be run in workflowcore. For this I need an if-then-else step like described in the diagram above. Till now I converted the true-false step in the design to a parallel step with two if steps in workflow core. But I don't like this implementation.
Is it possible to convert the true-false step in the design to one (custom) if then else step in workflow core? When a specific condition is true go to true path, otherwise go to false path.
The 'When' primitive would be an option but you write in issue 197 (https://github.com/danielgerlag/workflow-core/issues/197) that you want to deprecate the 'when' primitive. 
Any idea how to implement the if then else step for usage in a json description?
 
Kind regards
Luc
