### ISSUE TITLE
Events and workflow multiple instances

### ISSUE THREAD

**Issue by DiegoSestito** [danielgerlag/workflow-core#307]
Let's imagine the following scenario: I have a workflow definition that will be instantiated multiple times, and each of these instances depends on external events to continue the flow. These external events are executed according to user actions for a particular "entity" of the system. The question that gets is: When I trigger an event, which has been set to be listened to in the definition, how is it guaranteed that the due workflow instance will be continued?

**Comment by danielgerlag** [comment]
You have to match the event name and key, and set the effective date of the event to after the effective date of the "wait for".  Then all workflows waiting for that event name + key within the date range will resume with the data passed via the event.
