### ISSUE TITLE
Return task data with StartWorkflow invoke

### ISSUE THREAD

**Issue by sagar2dumbre** [danielgerlag/workflow-core#309]
I have a requirement where I want to initiate a workflow for each request, execute a couple of tasks in a synchronous way (output of one task could be input for the next task but this is not for all the task) and return the output of the last task back to the caller. This has to be done in a single request.

Here is a workflow which I created. I am not sure how can I retrieve the value of the `Message` variable back to the caller.

```
public class TestWorkflow : IWorkflow<MyDataClass>
    {
        public string Id => "TestWorkflow";

        public int Version => 1;

        public void Build(IWorkflowBuilder<MyDataClass> builder)
        {
            builder
                .StartWith<AddNumbers>()
                .Input(step => step.Input1, data => data.Value1)
                .Input(step => step.Input2, data => data.Value2)
                .Output(data => data.Value3, step => step.Output)
                .Then<Task1>()
                .Then<Task2>()
                .Then<CustomMessage>()
                .Input(step => step.Message, data => "The answer is " + data.Value3.ToString());
        }
    }

    public class Task1 : StepBody
    {
        public Task1()
        {
            Thread.Sleep(2000);
        }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            return ExecutionResult.Next();
        }
    }

    public class Task2 : StepBody
    {
        public Task2()
        {
            Thread.Sleep(2000);
        }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            return ExecutionResult.Next();
        }
    }

    public class MyDataClass
    {
        public int Value1 { get; set; }
        public int Value2 { get; set; }
        public int Value3 { get; set; }
    }

    public class AddNumbers : StepBody
    {
        public int Input1 { get; set; }

        public int Input2 { get; set; }

        public int Output { get; set; }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Output = (Input1 + Input2);
            return ExecutionResult.Next();
        }
    }

    public class CustomMessage : StepBody
    {
        public string Message { get; set; }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            System.Diagnostics.Debug.WriteLine(Message);
            return ExecutionResult.Next();
        }
    }
```

This is the code I am using to start the workflow.

`workflowId = await _workflowService.StartWorkflow(id, version, dataObj, reference);`

Any thoughts?

**Comment by danielgerlag** [comment]
Workflows are suited to long running background processes... not sure this matches your use case?
Could you not just do this with regular code instead of wrapping it in a workflow?

**Comment by george-weare8** [comment]
I believe I have the same requirement, the last step of the Saga has a result of a newly created object that I want to return to the caller. It is not supported?

**Comment by seroche** [comment]
Same here. We want to use the SAGA pattern to orchestrate the communication between micro services. Ultimately we want to get the final result and return it to our caller. 

Is this something we can achieve with your great workflow system/

**Comment by danielgerlag** [comment]
The has been released - https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0
