### ISSUE TITLE
Multiple event subscription

### ISSUE THREAD

**Issue by nurhat** [danielgerlag/workflow-core#31]
Hello @danielgerlag,
   Thanks all your hard work done and  sharing it here. I want to know whether is it possible to subscribe a step to multiple events and provide a loopback as sample shown below.
`builder
                .StartWith<CreateUser>()
                    .Input(step => step.Email, data => data.Email)
                    .Input(step => step.Password, data => data.Password)
                    .Output(data => data.UserId, step => step.UserId)
                .Then<SendConfirmationEmail>(sendConfirmation =>
                    {
                        sendConfirmation
                        .WaitFor("confirmation", data => data.UserId)
                        .Then<UpdateUser>()
                        .Input(step => step.UserId, data => data.UserId)
                        .EndWorkflow();
                        sendConfirmation.WaitFor("resendConfirmation", data => data.UserId).Then(sendConfirmation);
                    });`

Best Regards,
Nurhat

**Comment by danielgerlag** [comment]
Hi,

I'm not 100% sure of your exact use case here, but would something like this work?
```c#
builder
        .StartWith<CreateUser>()
            .Input(step => step.Email, data => data.Email)
            .Input(step => step.Password, data => data.Password)
            .Output(data => data.UserId, step => step.UserId)                
            .While(data => !data.Confirmed)
               .Do(x => x
                   .StartWith<SendConfirmationEmail>()
                   .WaitFor("confirmation", data => data.UserId)
                   .Then<UpdateUser>()
                       .Input(step => step.UserId, data => data.UserId)
                       .Output(data => Confirmed, step => Confirmed)
                    )
```

**Comment by nurhat** [comment]
Hi,
In my case, managing the flow with using the data  is not the optimum way , because we have a bit more complicated workflows(state based, many approval states, sub workflows, etc...) built on microsoft wf, and we would like to migrate to a simpler, open source and cleaner solution. And this project seems promising.   

For the case, it may make more sense (at least for us), if the event data can be used  just like as stepoutcome. Beside, in some cases due to workflow changes(new versions), we will need to update existing workflows to an older state( or step ), and we would like to use events(just like as workflow transitions) for such changes. Any opinions?

Best Regards,
Nurhat

**Comment by danielgerlag** [comment]
Hi,
Using the EventData as a StepOutcome sounds like a good idea... I will see if I can build that in somehow... will keep you posted.

Would you be able to share a description of one of your more complex workflows, I'd like to understand what my users goals are so that I can build a library that people will want rather than what I think they want.

When I started this project, I definitely had version migrations in mind for a future version... but my focus at the moment has been based on the current feedback from users... I can push that up on the priority list if it's a big issue for you?

**Comment by qazq** [comment]
Hi @danielgerlag ,

In your example:
```cs
builder
        .StartWith<CreateUser>()
            .Input(step => step.Email, data => data.Email)
            .Input(step => step.Password, data => data.Password)
            .Output(data => data.UserId, step => step.UserId)                
        .While(data => !data.Confirmed)
           .Do(x => x
               .StartWith<SendConfirmationEmail>()
               .WaitFor("confirmation", data => data.UserId)
               .Then<UpdateUser>()
                   .Input(step => step.UserId, data => data.UserId)
                   .Output(data => Confirmed, step => Confirmed)
                )
```

When entering WaitFor() second times, it will trigger event and go next step immediately. 

In WorkflowThread.cs

```cs
        private async Task SubscribeEvent(EventSubscription subscription)
        {
            //TODO: move to own class
            _logger.LogDebug("Subscribing to event {0} {1} for workflow {2} step {3}", subscription.EventName, subscription.EventKey, subscription.WorkflowId, subscription.StepId);
            
            await _persistenceStore.CreateEventSubscription(subscription);
            var events = await _persistenceStore.GetEvents(subscription.EventName, subscription.EventKey, subscription.SubscribeAsOf);
            foreach (var evt in events)
            {
                await _persistenceStore.MarkEventUnprocessed(evt);
                await _queueProvider.QueueWork(evt, QueueType.Event);
            }
        }
```

The variable `events` aren't empty because of the function _persistenceStore.GetEvents() didn't ignore processed event. I don't know should I add `.Where(x => !x.IsProcessed)` in the  _persistenceStore.GetEvents(), because you call _persistenceStore.MarkEventUnprocessed(evt) if the evt isn't null.

You can modify Sample04 for quick test

```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WorkflowCore.Interface;
using WorkflowCore.Models;
using WorkflowCore.Sample04.Steps;

namespace WorkflowCore.Sample04
{
    public class EventSampleWorkflow : IWorkflow<MyDataClass>
    {
        public string Id => "EventSampleWorkflow";
            
        public int Version => 1;
            
        public void Build(IWorkflowBuilder<MyDataClass> builder)
        {
            builder
                .StartWith(context => ExecutionResult.Next())
                .WaitFor("MyEvent", data => "0")
                    .Output(data => data.StrValue, step => step.EventData)
                .Then<CustomMessage>()
                    .Name("Print custom message")
                    .Input(step => step.Message, data => "The data from the event is " + data.StrValue)
                //++++++++++++++++++++
                .WaitFor("MyEvent", data => "0")
                    .Output(data => data.StrValue, step => step.EventData)
                .Then<CustomMessage>()
                    .Name("Print custom message 2")
                    .Input(step => step.Message, data => "The data from the event2 is " + data.StrValue)
                //++++++++++++++++++++
                .Then(context =>
                {
                    Console.WriteLine("workflow complete");
                    return ExecutionResult.Next();
                });
        }
    }
}
```

BTW, I have another question about the event. Is it possible to register an event for a specific workflow ID? e.g. `host.PublishEvent(workflowId, eventName, eventKey, eventData)`.

For some situations, maybe register the same event name(e.g. DocApproval) by different workflow instance(e.g. Doc1, Doc2), even have the same event key(e.g. user ID: "Jackie")

**Comment by danielgerlag** [comment]
Hi @qazq , so you can specify an effective date for both .WaitFor() in the workflow and .PublishEvent() in the host... I think the default .WaitFor(), will look for all events ever, unless you specify the effective date as DateTime.Now

Also, currently you can't publish directly to a specific workflow instance... could you describe your use case for this in some detail?

**Comment by qazq** [comment]
I have an e-form workflow

```cs
            builder
                .StartWith<CreateForm>()
                    .Input(step => step.UserId, data => data.UserId)
                    .Output(data => data.Approvers, step => step.Approvers)
                    .Output(data => data.State, step => EFormState.WaitingApproval)
                    .Output(data => data.FormId, step => step.FormId)
                .While(data => data.State == EFormState.WaitingApproval)
                    .Do(x => x
                        .StartWith<InformApprovers>()
                            .Input(step => step.Approvers, data => data.Approvers)
                        //.WaitFor("approval", data => data.UserId, data => DateTime.Now)
                        .WaitFor("approval", data => data.FormId, data => DateTime.Now) // use unique form ID as event key
                        .Then<CheckApproval>()
                            .Input(step => step.Approvers, data => data.Approvers)
                            .Output(data => data.State, step => step.State)
                        )
                .Then<EndForm>();
```

```cs
using System;
using System.Collections.Generic;
using System.Text;

namespace WorkflowCore.SampleEForm
{
    public class EFormData
    {
        public string FormId { get; set; }

        public string UserId { get; set; }

        public float LeaveHours { get; set; }

        public EFormState State { get; set; }

        public List<Approver> Approvers { get; set; }
    }

    public class Approver
    {
        public string UserId { get; set; }
        public FormApprovalResult? Result { get; set; }
        public string Comment { get; set; }
        public bool Informed { get; set; }
    }

    public enum FormApprovalResult
    {
        Approved = 1,
        Returned = 2,
        Rejected = 3,
    }

    public enum EFormState
    {
        Editing,
        WaitingApproval,
        Approved,
        Returned,
        Rejected,
    }
}
```

In the `CreateForm`, it will assign approvers depends on user ID. One user might create many forms (Absent form, Travel application form, etc.), and each form is waiting for approval. If I use user ID as event key, every form will go next step once an approver publishes the event. In the case, it should specific form go next step. I use a unique ID as event key, and the ID comes from workflow ID. I cannot get workflow ID in WaitFor(), so I assign it in the `CreateForm`

```cs
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            ...

            FormId = context.Workflow.Id;
            return ExecutionResult.Next();
        }
```

**Comment by qazq** [comment]
In my design, I keep all the related data in the `EFormData` and it will be stored in the persistence database. But I cannot modify approval result for specific approver easily.

```cs
.WaitFor("approval", data => data.FormId, data => DateTime.Now)
    .Output(data => data.Approvers[N], step => step.EventData)  // N is dynamic
```
The N is dynamic depends on which approver published the event.
My current solution is to modify EFromData in the database directly and then publish the event.

```cs
            var workflow = _host.PersistenceStore.GetWorkflowInstance(workflowId).Result;
            var form = workflow.Data as EFormData;

            form.Approvers.Find(a => a.UserId == approverUserId).Result = FormApprovalResult.Approved;
            _host.PersistenceStore.PersistWorkflow(workflow);

            _host.PublishEvent("approval", form.FormId, null);
```
I think this is not a good approach. Do you have any suggestions? Thank you.

**Comment by danielgerlag** [comment]
@qazq you could maybe store the workflow id in your data object to use as a wait key later.

```c#
public class GetWorkflowId : StepBody
{
    public string WorkflowId { get; set; }

    public override ExecutionResult Run(IStepExecutionContext context)
    {
        WorkflowId = context.Workflow.Id;
        return ExecutionResult.Next();
    }
}

...
.WaitFor("approval", data => data.WorkflowId, data => DateTime.Now)
```

This also seems like something pretty standard... so I might just add this to the core library as well, or maybe also expose the workflow context in the lambda for determining the event key... but this should work for now?

**Comment by danielgerlag** [comment]
@qazq I have just released v1.2.9, which enables access to the context object when resolving an event key.
```c#
.WaitFor("event", (data, context) => context.Workflow.Id)
```

**Comment by qazq** [comment]
@danielgerlag Thanks a lot. I'll try it.

**Comment by nursjson** [comment]
How can I use "SuspendWorkflow" in mvc? Could anybody help?

**Comment by vaclavpfeifer** [comment]
> ```cs
> StrValue
> ```

Hi Daniel,

We get into similar issue. Our Use-Case is as follows:
We are waiting for 1-N incoming events (all with same Key, but differs in event data) and the last one with a flag denoting its last (which will stop the loop). We have a short workaround with the effective date, but its not enough though.
When two events are published at a same time only one is being processed by the WF.

Are there any reasons behind the persistence provider takes all events rather then only all unprocessed events?

Thank you for reply,
Vasek

**Comment by danielgerlag** [comment]
> Are there any reasons behind the persistence provider takes all events rather then only all unprocessed events?

So that the same event can be consumed multiple times by multiple workflows.  An event is not a command, it's describing something that happened, not instructing something specific to happen.

**Comment by vaclavpfeifer** [comment]
> So that the same event can be consumed multiple times by multiple workflows. An event is not a command, it's describing something that happened, not instructing something specific to happen.

Thank you, are there any recommendations on how to solve above problem?

**Comment by danielgerlag** [comment]
Could you vary the key by making it compound?
