### ISSUE TITLE
Question about While inside a Foreach

### ISSUE THREAD

**Issue by DiegoSestito** [danielgerlag/workflow-core#311]
I have a foreach with a list of objects that must be interacted, and for each of these objects the workflow must enter a while loop waiting for each object to change its status. My question is: How do I get the object in the foreach context to use it as a conditional while loop?

**Comment by danielgerlag** [comment]
The while expression you use in the `While` unfortunately can't access the `context` object, that is something we could look into adding.  A workaround would be to write a custom step that exposes the `context.Item` on it's output, and then map that output back to a field on the main workflow data object.

**Comment by gonengf** [comment]
Hi @danielgerlag ,

Could you give an example of this workaround? 

Thanks a lot!

**Comment by danielgerlag** [comment]
```c#
    public class Data
    {
        public int Value { get; set; }
    }

    public class ExtractContext : StepBody
    {

        public object Value { get; set; }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Value = context.Item;
            return ExecutionResult.Next();
        }
    }

        public void Build(IWorkflowBuilder<Data> builder)
        {
            builder
                .StartWith<SayHello>()
                .ForEach(data => new List<int>() { 1, 2, 3, 4 })
                    .Do(x => x
                        .StartWith<ExtractContext>()
                            .Output(data => data.Value, step => step.Value)
                        .Then<DisplayContext>()
                            .Input(step => step.Item, data => data.Value)
                        )
                .Then<SayGoodbye>();
        }
```

**Comment by gonengf** [comment]
@danielgerlag Thanks a lot!!
