### ISSUE TITLE
If-then-else step

### ISSUE THREAD

**Issue by Balu2** [danielgerlag/workflow-core#312]
Hello Daniel

At the moment I am working on an integration of a visual designer with workflow core. I convert the visual design to a json workflow that can be run in workflowcore. For this I need an if-then-else step like described in the diagram above. Till now I converted the true-false step in the design to a parallel step with two if steps in workflow core. But I don't like this implementation.
Is it possible to convert the true-false step in the design to one (custom) if then else step in workflow core? When a specific condition is true go to true path, otherwise go to false path.
The 'When' primitive would be an option but you write in issue 197 (#197) that you want to deprecate the 'when' primitive.
Any idea how to implement the if then else step for usage in a json description?

Kind regards
Luc
![ifthenelse](https://user-images.githubusercontent.com/47588367/58152651-591f1700-7c6d-11e9-9338-95b892f0fe21.jpg)

**Comment by germandb** [comment]
You need to use the if step, the json would be something like this:
```
{
"Id": "Condition1",
"StepType": "WorkflowCore.Primitives.If, WorkflowCore",
"NextStepId": "Task3",
"Inputs": { "Condition": "data.IsTrue"}
"Do": [
   [
     {
        "Id": "Task1",
        "Name": "Task1",
        "StepType": "MyTaskStep1"
     }
   ]
 ]
},
{
   "Id": "Task3",
   "Name": "This step represent the else condition",
   "StepType": "MyTaskStep3"
}
```

**Comment by Balu2** [comment]
Hello Germandb

I tried your suggestion, but when the condition is true Task1 as well as Task3 are executed. Task3 shouldn't be executed when condition is true.

This is my json workflow:

{
	"Id":"1",
	"Version":"1",
	"DataType":"WorkflowEngineApplication.Models.WorkflowData, WorkflowEngineApplication",
	"Steps":[
		{
			"Id":"1",
			"StepType":"WorkflowCore.Primitives.If, WorkflowCore",
			"NextStepId":"3",
			"Inputs":{"Condition":"(data.Index<=30)"},
			"Outputs":{},
			"Do":[
				[
					{
						"Id":"2",
						"StepType":"WorkflowEngineApplication.Steps.EmailStep, WorkflowEngineApplication",
						"Inputs":{"EmailFrom":"\"info@test.nl\"","EmailTo":"\"info@test.nl\"","Subject":"\"index < 30\"","Body":"\"\""},
						"Outputs":{}
					}
				]
			]
		},
		{
			"Id":"3",
			"StepType":"WorkflowEngineApplication.Steps.EmailStep, WorkflowEngineApplication",
			"Inputs":{"EmailFrom":"\"info@test.nl\"","EmailTo":"\"info@test.nl\"","Subject":"\"index > 30\"","Body":"\"\""},
			"Outputs":{}
		}
	]
}

Kind regards
Luc

**Comment by danielgerlag** [comment]
Currently there is no `else`... you could achieve it by using two oppossing `If` steps.

**Comment by Balu2** [comment]
Hello Daniel

That is what I have right now: a parallel step with two if steps. But I was wondering if there is no easier and more efficient way of implementing the if then else, converting  the design to only one step instead of three. For instance make use of step.OutCome, something like this:

public class IfThenElse : StepBody
    {
        public bool Condition { get; set; }    
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            if (Condition)
                return ExecutionResult.Outcome("Yes");
            else
                return ExecutionResult.Outcome("No");
        }
    }

regards
Luc

**Comment by danielgerlag** [comment]
You could use the When step to switch on outcome values. You also do not need to wrap multiple if steps inside a parallel.

**Comment by danielgerlag** [comment]
I don't think I will be removing the `when` primitive, it seems to be popular.

**Comment by softwareguy74** [comment]
> I don't think I will be removing the `when` primitive, it seems to be popular.

Yes, please do NOT remove the `when` primitive.  We definitely need something like this for the use of a "switch" or a "If-Then-ElseIf- Else" statement.
