### ISSUE TITLE
.NET Standard 2.0 milestone ?

### ISSUE THREAD

**Issue by rodius** [danielgerlag/workflow-core#313]
Hello Daniel 

I seethe previous issue related to .Net Core 2 was close. 

Looking at the current .Net core adoption and maturity . I think it is worth revisiting the idea of migrating all projects to .Net Standard 2.0 

to give the ability to refer newer and more secure dependencies for the providers projects.

**Comment by danielgerlag** [comment]
> to give the ability to refer newer and more secure dependencies for the providers projects.

There is nothing blocking you on this.  Even though Workflow Core targets NETStandard 1.3, does not mean your app can't target a higher framework or use newer versions of the dependencies.
