### ISSUE TITLE
What scheduling service is being used?

### ISSUE THREAD

**Issue by softwareguy74** [danielgerlag/workflow-core#314]
Is it something like Quartz.net?  I need to understand how resilient scheduling is such as what if the service completely bombs out for whatever reason.  Does the scheduling component gracefully recover from that failure and continue as if nothing happened such as executing steps that would have run if the service was up?

**Comment by danielgerlag** [comment]
It's internal to the workflow engine... the same mechanism that schedules the execution of running workflows tracks the next time it is meant to execute, which is persisted along with each workflow instance to your persistence store of choice.

**Comment by softwareguy74** [comment]
Great!  I tried it out the other day by creating a workflow that would repeat.  I used the PostgreSQL persistence provider.  I cut off the service and restarted it, and low and behold, it continued on where it left off!  This is great stuff!  Next up I will be trying multi-server environment by using RabbitMQ and Redis RedLock.  Thanks for the great work!

**Comment by danielgerlag** [comment]
With the latest update to the redis package, you don't need rabbit mq, you can use redis for both a locking mechanism and shared work queue.

**Comment by softwareguy74** [comment]
Ah, great!  Even better!  Thanks
