### ISSUE TITLE
Can we get an example of a When statement in JSON?

### ISSUE THREAD

**Issue by softwareguy74** [danielgerlag/workflow-core#315]
I'm not able to get this to work.  Thanks!

**Comment by danielgerlag** [comment]
There is some missing functionality when the JSON format that does not currently allow multiple `When` steps to be defined against a source step... This should be fixed in the near future.

**Comment by softwareguy74** [comment]
Ah, ok.  Glad it wasn't just me.  The "When" feature is very useful for us, so I look forward to this update.  Thanks.

**Comment by umeshpatra** [comment]
I also have similar requirement to use When with multiple outcome based steps. i have been struggling since many days without any luck.
@danielgerlag - please let me know if you are already on it. else i can start to extend this part if you can give me some hint.
Thanks.

**Comment by georgelichen** [comment]
I have the same request.  Hope this feature could be considered and implemented.  Thank you for the great effort.

**Comment by softwareguy74** [comment]
Any luck with this?  When is very useful and without this,  we are stuck. Thanks

**Comment by SSanthosh-SBT** [comment]
Any updates on this .I'm waiting for this feature to be implemented.Thanks in advance

**Comment by danielgerlag** [comment]
I apologize, unfortunately I do not have the bandwidth to look into this in the short term.  Perhaps early next year.

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/486
