### ISSUE TITLE
How to "Go To" a particular step?

### ISSUE THREAD

**Issue by softwareguy74** [danielgerlag/workflow-core#316]
The commercially available workflow systems I've worked with have had a very useful feature that allows you to Go To a particular step in an already running workflow.   So for example, let's say you have a workflow with 4 steps and it is currently sitting at step 2 waiting for an external event.  Sometimes in the real world it may be necessary to either jump ahead to the 4th step (completely bypassing step 3) or going back to step 1.

So having a GoToStep(stepName) function on a running workflow instance would be very helpful. 

Is this possible?

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/releases/tag/1.8.3

**Comment by softwareguy74** [comment]
Sorry, but I think I left out a critical part of the question.  This "Go To" would not be predefined in the workflow itself.  It would happen "on the fly" more like a management type function after getting a call from an employee asking if a workflow could be "pushed through" to another step (for whatever reason, sometimes because someone is out and can't respond to the actual step, etc).

So, there would be something like: host.Workflow("HelloWorld", instanceId).GoTo("Step1");

Is this possible?

**Comment by danielgerlag** [comment]
Not currently.  This is something that would require a fair amount of thought, simply going to another arbitrary step in the workflow could present some challenges on more complex workflows.

**Comment by kedach** [comment]
GoTo should be a special operation.  When executed this, other active step should be expired. 
         --> B(active) -- >C-->E
eg: A                                               -->F
         -->D(active) --> D
if goto(C)   B D are expired  and then  C is active.  and next is D line.....

so goto in workflow is a basic function.  it is very useful.
Goto function only support this,  the other effects should be thought by the invoker(developer).
eg. which step can't use goto or can goto step list.      ect.

**Comment by yue-fei** [comment]
```
var eventPointer = context.Workflow.ExecutionPointers.Find(x => x.StepName == "special step name");
if (eventPointer != null)
{
	context.Workflow.ExecutionPointers.Add(new ExecutionPointer()
	{
		Id = Guid.NewGuid().ToString(),
		PredecessorId = eventPointer.PredecessorId,
		StepId = eventPointer.StepId,
		Active = true,
		ContextItem = eventPointer.ContextItem,
		StepName = eventPointer.StepName
	});
}
```
I found a way, but I'm not sure what chain reaction will happen...

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/486
