### ISSUE TITLE
Is there a way to run the Saga IWorkflow immediately?

### ISSUE THREAD

**Issue by george-weare8** [danielgerlag/workflow-core#319]
Thank you for all the work you've done, the framework is really great but I would like to know if I can workaround the IWorkflowHost so that I can run an IWorkflow immediately by somehow calling it.

So I don't want to call IWorkflow.Start and I need something like `await IWorkflowProvider.GetWorkflow(ID).Run()`.

I believe that a Saga could be run immediately and also return some data, the second I can workaround using a Data object, but the first one seems like a bottleneck to me as I don't want a polling engine in the application, I also run in lambda so it is hard to maintain and spend money.

**Comment by danielgerlag** [comment]
Currently not, but one could implement a synchronous workflow runner.

**Comment by xplatsolutions** [comment]
Any hints where to start?

**Comment by danielgerlag** [comment]
You'd need to acquire a lock for the workflow instance id and then keep calling this method until the workflow state is completed: https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/WorkflowExecutor.cs#L40
Potentially also manually call PersistWorkflow on the Persistence implementation.

**Comment by danielgerlag** [comment]
I will be adding this as a feature shortly

**Comment by xplatsolutions** [comment]
Sounds like I could try it again when you're done. Thanks!

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/381

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0
