### ISSUE TITLE
Need a performance test report

### ISSUE THREAD

**Issue by quinvit** [danielgerlag/workflow-core#321]
@danielgerlag  This library is awesome! I just wonder do we have any performance test out there? I just do a pretty small performance test on my server, workflow-core can run 50-60  empty tasks per second (using redis with fsync=no). I also using the same environment same test but I test with Celery https://github.com/celery/celery. Celery can run 380+ tasks per second. What a huge difference! I think I haven't taken all advantage of workflow-core during the test. It would be great if you could provide your performance test result here. Thank you a lot.

**Comment by danielgerlag** [comment]
This is not an apples to apples comparison... the uses cases for these two technologies are quite different.  WorkflowCore tracks the state of a complex sequence of steps, rather than a high throughput simple task machine.

**Comment by quinvit** [comment]
@danielgerlag Thank you for your information. I also have look more detail on source code and I find out that the the default value
internal int MaxConcurrentWorkflows = Math.Max(Environment.ProcessorCount, 2);

It only count physical processor instead of number of cores. I increase that number to 16, that is the number of v-cores on my VPS. The final result of workflow-core now is 340 tasks/sec. That result is very impressive. I have 9 years experience on C#, if you want me help something on this library please don't hesitate to ask :)
