### ISSUE TITLE
Clarification on multi-node clusters with in-memory persistence provider

### ISSUE THREAD

**Issue by nullpainter** [danielgerlag/workflow-core#324]
After noticing some odd behaviour with our API cluster using SQL Server persistence, I found your page detailing multi-node cluster setup.

For our use-case, workflows are likely to be relatively short-lived (2-5 minutes). Can I clarify that if we use the `MemoryPersistenceProvider` instead, there is no need for a queue provider or distributed lock manager?

(I know that in-memory persistence providers aren't ideal - this is hopefully a short-term "fix")

**Comment by danielgerlag** [comment]
Could you give more details of odd behavior?

Using Memory persistence will not work in a multi cluster setup.

**Comment by nullpainter** [comment]
> Could you give more details of odd behavior?

I only had warn level logging enabled, but from timestamps on the data produced by our steps, it appears that a step had executed twice. There was also a database concurrency exception, and some logical errors in the mix (collections which are guaranteed by earlier steps to contain a single element, which now contain multiple).

Given that the exceptions were so odd, hadn't manifested themselves before we were in a cluster, and that I had absolutely no queue provider or distributed lock manager at play, I assumed that this was the culprit.

> Using Memory persistence will not work in a multi cluster setup.

We are using Workflow Core in a RESTful API. A single endpoint starts the workflow. Wouldn't in-memory persistence just be equivalent to each node being ignorant of each other node? For our use-case, this is good enough (for now)

**Comment by danielgerlag** [comment]
Yup, not having a shared queue and lock manager will cause a multi node setup to behave badly.
You could use it within a load balanced service where there is no shard queue, lock provider or persistence store... then each instance will act independently.

**Comment by nullpainter** [comment]
Thanks Daniel; I think I answered my own question with this one! Wonderful library, by the way. It's been great to use (even if I didn't read rather critical documentation until too late in the piece!)
