### ISSUE TITLE
Json - parallel construct expressiveness

### ISSUE THREAD

**Issue by Riccardo11** [danielgerlag/workflow-core#327]
Hi Daniel,

thank you for useful library. I have a problem defining particular workflows with parallel steps: this is an example (two outgoing arrows mean that the two next steps can be executed in parallel, while two incoming arrows mean that the step can be executed only after the two previous steps have finished).

![workflow](https://user-images.githubusercontent.com/28531958/59907865-5a7a6580-940c-11e9-9730-0e96e06786bf.png)

The main problem is that I can't find a way to use your parallel construct (I'm using the json format), to express the behavior of the workflow. The only idea I had was to use a global variable (external to the workflow) to check how many times a step is reached.

Thank you.

**Comment by danielgerlag** [comment]
This looks like a nested Parallel step.  Perhaps something like this? You have to declare F twice.
```json
{
  "Id": "A",
  "NextStepId": "Parallel 1",
},
{
  "Id": "Parallel B&C",
  "StepType": "WorkflowCore.Primitives.Sequence, WorkflowCore",
  "NextStepId": "G",
  "Do": [
	[
	  {
		  "Id": "B",
		  "StepType": "WorkflowCore.Primitives.Sequence, WorkflowCore",
		  "Do": [
			[
			  {
				"Id": "D",
				"StepType": "D"
			  }
			],			
			[
			  {
				"Id": "E",
				"StepType": "E",
				"NextStepId": "F-2"
			  },
			  {
				"Id": "F-2",
				"StepType": "F"
			  }
			]
		  ]
	  }
	],			
	[
	  {
		"Id": "C",
		"StepType": "...",
		"NextStepId": "F-2"
	  },
	  {
		"Id": "F-2",
		"StepType": "F"
	  }
	]
  ]
},
{
  "Id": "G"
  ...
},
```

**Comment by Riccardo11** [comment]
Thank you, Daniel.

I already tried something similar to your solution, but the problem is that "F" is executed twice: after "E" and after "C".

I would like "F" to be executed only once and it should be ensured that "E" and "C" have been executed before.

**Comment by danielgerlag** [comment]
Let me give this some more thought

**Comment by Riccardo11** [comment]
Any ideas?

**Comment by danielgerlag** [comment]
Sorry, I have been out of town, I will try look into this on the weekend.

**Comment by Riccardo11** [comment]
Maybe wasn't this kind of workflow planned in the library?

**Comment by Riccardo11** [comment]
Is there any update about this issue? Thanks.

**Comment by luoyanglihao** [comment]
I have the same problem. @danielgerlag

**Comment by danielgerlag** [comment]
You should be able to achieve this with the new branching feature - https://github.com/danielgerlag/workflow-core/releases/tag/3.1.0
