### ISSUE TITLE
json user task

### ISSUE THREAD

**Issue by federicorOT** [danielgerlag/workflow-core#329]
Hi I'm having some problems trying to run a user task being created with the json definition, I'm having the error 'Unable to construct step body WorkflowCore.Users.Primitives.UserTask'
`{
		"Definition":
		{
    "Id": "HumanWorkflowJson",
    "Version": 1,
    "DataType": "WorkflowEngine.Logic.Workflows.Data.ApprovalData, WorkflowEngine.Logic",
    "Steps": [
        {
            "Id": "UserTask",
            "StepType": "WorkflowCore.Users.Primitives.UserTask, WorkflowCore.Users",
            "Properties": {
                "Options": {
                    "I approve": "yes",
                    "I do not approve": "no"
                }
            },
            "Inputs": {
                "AssignedPrincipal": "\"Fede\"",
                "Prompt": "\"Data prompt kaka\""
            },
            "Do": [[
                {
                    "Id": "Choice: yes",
                    "StepType": "WorkflowCore.Primitives.When, WorkflowCore",
                    "Inputs": {
                        "ExpectedOutcome": "\"yes\""
                    },
                    "Do": [[
                        {
                            "Id": "Approve",
                            "StepType": "WorkflowEngine.Logic.Workflows.Steps.Approve, WorkflowEngine.Logic"
                        }
                    ]]
                },
                {
                    "Id": "Choice: No",
                    "StepType": "WorkflowCore.Primitives.When, WorkflowCore",
                    "Inputs": {
                        "ExpectedOutcome": "\"no\""
                    },
                    "Do": [[
                        {
                            "Id": "Disapprove",
                            "StepType": "WorkflowEngine.Logic.Workflows.Steps.Reject, WorkflowEngine.Logic"
                        }
                    ]]
                }
            ]]
        }
    ]
}
}`

here is my definition, what can Be wrong there?
Thank you!

**Comment by federicorOT** [comment]
Reviewing a little bit more I realized that this seems to not be the way to define a user task from a json definition, now I'm in the doubt if it is possible or not.
Would love to know it  in order to decide what would be the best solution for my implementation.

Sorry for the disturbances. Thank you!

**Comment by danielgerlag** [comment]
Sorry for the delayed response.  The Users package was intended to be an example of how to build your own extensions around the core library.  The current implementation was created before JSON workflows and as such, has some features that cannot be expressed in the JSON format.  The solution would be adapt the Users package to use `Inputs` for any parameters that it requires.  Unfortunately, I haven't had the time to look into this properly yet.
