### ISSUE TITLE
How to build a multiple Approve-Reject workflow?

### ISSUE THREAD

**Issue by apphost** [danielgerlag/workflow-core#330]
I want to build a workflow that have multiple Approve-Reject action.It can  return to the start node and continue to run.How to do that?

**Comment by danielgerlag** [comment]
You could build that on workflow core... if you would like some examples, please provide some more detail

**Comment by behiunforgiven** [comment]
Why there is no sample of Approve-Reject workflow in samples?

**Comment by danielgerlag** [comment]
The samples are focused on how to use the primitives within workflow core.  An approve / reject workflow would be a broader implementation, using a combination of several primitives depending on the particular use case.
