### ISSUE TITLE
Schema name hardcoded in WorkflowCore.Persistence.PostgreSQL

### ISSUE THREAD

**Issue by courosh12** [danielgerlag/workflow-core#332]
The persictence provider for postgres has its schema name hardcoded
` builder.ToTable("Subscription", "wfc");`
Is it possible to parameterize this?

**Comment by AlexeyDeev** [comment]
Ef core hardcode schema name in migrations "by design". If you want pass it from external (config e.g.) you can update migrations manually - set schema name in each migration and in snapshot. 
Basic concepts:

In migrations classes

```
private readonly string _schema = MigrationMetaInfo.DbSchema; // some singleton model which store schema name
protected override void Up(MigrationBuilder migrationBuilder)
{
migrationBuilder.CreateTable(
                name: _tablePrefix + "UnpublishedEvent",
				schema: _schema
				....
```
				
In snapshoot:
```
...
 b.ToTable("Event",_schema);
 ...
```
 
Next pass schema to dbContext and sets schema name for migration history table:

```
void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseNpgsql(_connectionString,
                options =>
                    options.MigrationsHistoryTable("MigrationTableName",
                        MigrationMetaInfo.DbSchema));
```
						
and for all Configure methods like this:

```
void ConfigureSubscriptionStorage(EntityTypeBuilder<PersistedSubscription> builder)
	...
		builder.ToTable("Subscription", _schema);
	...
```
	

But if you do this then each time you update a package with migrations, you need to manually “fix” it.

**Comment by danielgerlag** [comment]
I would be open to adding an optional parameter to allow this to be configured.

**Comment by courosh12** [comment]
The thing is i had changed the migrations schema name. But my problem was the nugetpackage that is used has its name set to "wfc". It is possible that have missed a parameter when starting the workflow host where u can configure this. Or else i have to fork this.

**Comment by hugowang-yicom** [comment]
I am having the same issue. I tried to add the workflow persistence table to a existing schema ```public``` with the following configuration:
```services.AddWorkflow(x => x.UsePostgreSQL("connection string", false, true, "public"));```

The migration is executed on  schema ```wfc``` but not ```public```

**Comment by courosh12** [comment]
i added the code  with the parameter for the name. https://github.com/danielgerlag/workflow-core/pull/354
Except for the IDesignTimeDbContextFactory. So i think if u use cli to migrate u get wfc. Otherwise if its done at runtime it should work.
