### ISSUE TITLE
finding Difficult to store and exchange complex data type among multiple steps

### ISSUE THREAD

**Issue by umeshpatra** [danielgerlag/workflow-core#334]
Hi Daniel,
this solutions sounds to be robust as a workflow solution to full fill complex business req. as well. I have 2 questions as of now (not able to find any clue):
- How to store complex data for each step result
- how to pass the result between steps
- Status and input supplied for each step with global view
- Any plan for UI Designer to model the workflow as drag n drop?

**Comment by ssougnez** [comment]
Hi,

Personally, I like to use `Input` and `Output` to exchange data between steps. Basically, every of your step will take input (most probably) and based on them will generate outputs that you can store in a public property of your step. These one can be as complex as you want as long as they can be serialized in JSON. 

Then, the idea is just to store these data in the model used by the workflow itself by using the `Output` method (so you take the content of the public property of your step and you put it in the model of the workflow). Beware that these data will be loaded as soon as the workflows needs to progress so pay attention not to put too many data in there. Indeed, storing the base64 of an image in the workflow data might not be a good idea ;-)

**Comment by danielgerlag** [comment]
Yes, I agree with @ssougnez here... you can also see this [sample](https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample03)
I don't have any short term plans for a UI designer, my focus at the moment is building a stand-alone server around workflow-core.
