### ISSUE TITLE
Request Feature: Fork and join step

### ISSUE THREAD

**Issue by hifeamin** [danielgerlag/workflow-core#339]
Hi, Is there a way that we have fork and join in workflow. I find that Parallel feature run steps synchronize and I want to run my steps in separate thread like flowing picture
![download](https://user-images.githubusercontent.com/10550147/60951675-e1857400-a30e-11e9-8a56-39cd588cf4d2.png)

**Comment by danielgerlag** [comment]
Is this what you are looking for?

https://github.com/danielgerlag/workflow-core/wiki/06.-Control-Structures#parallel-paths

**Comment by hifeamin** [comment]
[This](https://github.com/danielgerlag/workflow-core/wiki/06.-Control-Structures#parallel-paths) workflow runs in this way:
```SayHello -> Task1dot1 -> Task2dot1 -> Task3dot1 -> Task1dot2 -> Task2dot2 -> Task3dot2 -> SayGoodbye```
However I want to run in this way:
```SayHello -> ((Task1dot1 -> Task1dot2), (Task2dot1 -> Task2dot2), (Task3dot1  -> Task3dot2)) -> SayGoodbye```
In this run if `Task1dot1` completed sooner than `Task2dot1`, `Task1dot2` will run immediately although in current implementation `Task1dot2` wait to all `Task1dot1, Task2dot1, Task3dot1` complete.
My question is that, is there a way to run parallel as I said? Or is there a way to implement this feature in WorkflowCore?

**Comment by danielgerlag** [comment]
It sounds like you are trying to run them in serial?  The order of the parallel paths is non-deterministic... depending on what each branch looks like, it could vary wildly.

**Comment by hifeamin** [comment]
No, There is serial in each thread but they must be run as parallel. 
The main problem of your Parallel paths is that it does not run as parallel. In first picture 'Make ginger juice' and 'Make lemon juice' does not run in same time. 
So my question is that, is there a way to run them in same time and different thread?

**Comment by danielgerlag** [comment]
There is only 1 thread per workflow. Using parallel, will allow you to do blocking operations such as WaitFor or Delay in a branch without blocking the others.
