### ISSUE TITLE
Potential Use-case: Awaiting Workflows in an API Request

### ISSUE THREAD

**Issue by jamesbar2** [danielgerlag/workflow-core#344]
We have a web service that we would love to use Workflow Core for, given how feature-rich it is.

When a request is received, our obvious objective is to return a result as fast as possible. Below is an example of our workflow; one of the steps is a blocking call to an external API, while others are calls to internal microservices.

![Workflow Diagram](https://user-images.githubusercontent.com/828489/61420964-89c8a900-a8ca-11e9-8d74-daae0874e317.png)

I assume it's possible for me to subscribe to an event at the completion of the workflow.  But, is there any guarantee that this will run as fast as possible and won't be starved out by other requests that are in the workflow?

Is there a way to use Workflow Core in this way?  Would it be performant enough to handle something like this?  If so, _should_ we back it with a Redis store so we can scale it across nodes?

Thanks for your help!  Great work!

**Comment by ssougnez** [comment]
Personally, I wouldn't use wfcore for this. Indeed, when you start the workflow, it does not start immediately, it waits for the execution loop to fire (every 10s). Moreover, even if you have only one workflow executing, the steps won't be executed immediately. I have a project using wfcore communicating with a front end using web socket so I can see that there is some delay between steps. I suppose that the execution loop only execute on step at a time. It's totally fine in my case but in yours, I think it won't be as fast as you want.

**Comment by danielgerlag** [comment]
I would try to change the service to return a promise token, such as the workflow id instead and then have another endpoint to poll the status, thus making it async.  Workflows are really good at asynchronous background tasks, not so much synchronous tasks.

**Comment by danielgerlag** [comment]
Also, just to clarify, when you call startWorkflow, if there is a free worker, it will start immediately. The 10s poll is for workflows that have been explicitly slept using a delay or something.

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/381

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0
