### ISSUE TITLE
how Can I Get the DbContext？

### ISSUE THREAD

**Issue by crashsol** [danielgerlag/workflow-core#345]
`  //添加流程控制存储
            services.AddWorkflow(option =>
                option.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), true, true));
            services.AddScoped<StartStep>();
            services.AddScoped<AuditStep>();
            services.AddScoped<FinishStep>();      ``
            // My DbContext
            services.AddDbContext<AppDbContext>(option =>
            {
                //option.UseSqlite(Configuration.GetConnectionString("Sqllite"));
                option.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), opt => { opt.MaxBatchSize(2000);});
                //option.UseMySql(Configuration.GetConnectionString("Mysql"));
            });`
 is where a way to  get the workflow Dbcontext?   i inject IWorkflowDbContextFactory,but it don't work, Looking forward to your answer

**Comment by crashsol** [comment]
`  //添加流程控制存储
            services.AddWorkflow(option =>
                option.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), true, true));

 **services.AddScoped<SqlServerContext>(sp => new SqlServerContext(Configuration.GetConnectionString("DefaultConnection")))** `
I inject SqlServerContext  , then I can get SqlServerContext in ApiController, is there a batter way to solve this problem

**Comment by ssougnez** [comment]
Is there a reason why you want to retrieve the DbContext of Workflow Core?

**Comment by crashsol** [comment]
i need the workFlowDbContext do some search ,
eq:  i define the auditworkFlow ,in audit step, it wait for some user to audit , 
i put the eventKey like 'workflowId +'.'+ auditUser.id'
![微信截图_20190718161232](https://user-images.githubusercontent.com/17925647/61440788-e71a3400-a976-11e9-9330-485a1e1ca0f6.png)
with  the workflowDbContext , i can easy to query all workflows need i to audit, and do some other query,

**Comment by ssougnez** [comment]
Have you considered using the ElasticSearch provider: https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Providers.Elasticsearch ?

As a rule of thumbs, I would advice against talking directly with the database of workflowcore. It can come handy but at the end, if the library updates the schema of the database or something, your code will no longer work. By using the providers given by the author to do so, you leverage that risk.

**Comment by crashsol** [comment]
i never use ElasticSearch  before, i will try it ,thank you for suggestion,,this project is very helpfull !!

**Comment by Viktor-36** [comment]
> 
> 
> ` //添加流程控制存储
> services.AddWorkflow(option =>
> option.UseSqlServer(Configuration.GetConnectionString("DefaultConnection"), true, true));
> 
> **services.AddScoped<SqlServerContext>(sp => new SqlServerContext(Configuration.GetConnectionString("DefaultConnection")))** `
> I inject SqlServerContext , then I can get SqlServerContext in ApiController, is there a batter way to solve this problem

This helped me :) I used same workaround.
