### ISSUE TITLE
Horizontal scaling for the steps

### ISSUE THREAD

**Issue by courosh12** [danielgerlag/workflow-core#346]
Hi,

I am working with your library to make a distributed system where 1 application is in charge the so called "process manager" and where multiple containers have in them steps/processes that need be executed, defined by the workflow. This requirement is needed for the reason to scale out when a lot of workflows start and back when it is quieter.

I have used your library for the process management side of the application. So the steps in my workflow are nothing more than publishing events on my own queuing system. And after that registering an event (in the workflow core) for that step and waiting for it to be called so i can continue my workflow. The status handling of this part gets tricky.
Besides that I have also the requirement to display the workflow+steps in an ui and the corresponding statuses. I saw that the IWorkflowRegistery was only in memory and further development is needed to make this first work on different systems and display the workflows +steps through an api.

So my question is what is your advice about handling this. I was thinking to make it configurable if a workflowcore application has only a WorkflowConsumer (thus only executing steps) or also a WorkflowController(for starting workflows). But I assume there will be some technical challenges to accomplish this. So I am willing to help you implement this as I have a need for it.

**Comment by danielgerlag** [comment]
Yes, configuring it with separate nodes as only consumers or controllers would work.

**Comment by dbhc** [comment]
I'd like to accomplish the same thing but have the master controller not execute any workflows.    Is there a way to configure workflow-core to only queue workflows but not execute them?

**Comment by danielgerlag** [comment]
You can set the max concurrent workflows to zero on the controller node, when calling .UseWorkflow
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Models/WorkflowOptions.cs#L72

**Comment by courosh12** [comment]
One question i had. Does it mean that the workflow consumer also needs a connection to the persistence layer of the steps. Or do steps relay their messages back to the controller and it updates the database.

**Comment by courosh12** [comment]
Making it work like this does mean we need to have the same build for all the containers. As the IWorkflowregistery will hold the application logic(?).  How can we make the workflow and the steps(application logic) not dependable on each other?

**Comment by danielgerlag** [comment]
You should create each step as independent from a specific workflow implementation, and use workflow definitions to compose them together... so the workflow knows about the steps but the steps don't know about the workflow.
