### ISSUE TITLE
SQL Server Transaction rollback

### ISSUE THREAD

**Issue by bitbehz** [danielgerlag/workflow-core#347]
Hey,
Is it possible to share my db connection object with this library to be able to rollback changes in case of any failure in my domain logic?

**Comment by ssougnez** [comment]
Have a look at this : https://github.com/danielgerlag/workflow-core/issues/219 

Maybe you should do you business logic and only call workflow core if it worked ;-)

**Comment by bitbehz** [comment]
In some situations during execution of a transaction workflow is called more than once and rolling back the changes in domain and workflow is necessary in case of failure.
I think passing opened db connection (SQL Server) or database transaction object of DBContext  (Entity Framework) to the workflow persistence will make the life more easier (at least in non distributed environments).

**Comment by danielgerlag** [comment]
You will not be able to capture the transaction scope of a workflow... it works with an async work queue. Instead, make your workflow smart enough to do something different if something is amiss.
