### ISSUE TITLE
WF Pick activiey similar structure 

### ISSUE THREAD

**Issue by bitbehz** [danielgerlag/workflow-core#348]
Hey,
I'm looking for a Control Structure like Microsoft WF Pick activity which has two branches and workflow continues when any of the branches completed and wont wait for the other branch.
Is it possible with workflow-core ?

**Comment by ssougnez** [comment]
Yes, you have to use Parallel to create the two branches and CancelCondition to cancel a branch when the other is completed ;-)

**Comment by bitbehz** [comment]
Thank you.
