### ISSUE TITLE
Unnecessary database load when persisting a workflow instance with persistence providers based upon WorkflowCore.Persistence.EntityFramework

### ISSUE THREAD

**Issue by aphagel** [danielgerlag/workflow-core#349]
The extension method of release of June 30th 2019: WorkflowCore.Persistence.EntityFramework.ExtensionMethods.ToPersistable deletes  all 'PersistedExecutionPointer' and add new versions. This result unnecessary database load because the load can be limited to updating of changed ExecutionPointers and adding new ExecutionPointers.

**The root cause is the following piece of code:**

            persistable.ExecutionPointers = 
                new PersistedExecutionPointerCollection(instance.ExecutionPointers.Count);

            foreach (var ep in instance.ExecutionPointers)
            {
                var persistedEP = persistable.ExecutionPointers.FindById(ep.Id);

In line 1 the persistable.ExecutionPointers is set to a new PersistedExecutionPointerCollection. The result is that the .FindById in the last line will always result 'null' (cannot find because you start with empty collection).

**Solution**

Replace method WorkflowCore.Persistence.EntityFramework.ExtensionMethods.ToPersistable into the following (based upon limited testing it seems to work properly (note: the changes to the original are marked with region info)

        internal static PersistedWorkflow ToPersistable(this WorkflowInstance instance, PersistedWorkflow persistable = null)
        {
            if (persistable == null)            
                persistable = new PersistedWorkflow();                        

            persistable.Data = JsonConvert.SerializeObject(instance.Data, SerializerSettings);
            persistable.Description = instance.Description;
            persistable.Reference = instance.Reference;
            persistable.InstanceId = new Guid(instance.Id);
            persistable.NextExecution = instance.NextExecution;
            persistable.Version = instance.Version;
            persistable.WorkflowDefinitionId = instance.WorkflowDefinitionId;
            persistable.Status = instance.Status;
            persistable.CreateTime = instance.CreateTime;
            persistable.CompleteTime = instance.CompleteTime;

            #region Added
            var persistedExecutionPointers = persistable.ExecutionPointers ?? new PersistedExecutionPointerCollection(0);
            #endregion

            persistable.ExecutionPointers = new PersistedExecutionPointerCollection(instance.ExecutionPointers.Count);

            foreach (var ep in instance.ExecutionPointers)
            {
                #region changed
                //var persistedEP = persistable.ExecutionPointers.FindById(ep.Id);
                var persistedEP = persistedExecutionPointers.FindById(ep.Id);
                #endregion

                if (persistedEP == null)
                {
                    persistedEP = new PersistedExecutionPointer();
                    persistedEP.Id = ep.Id ?? Guid.NewGuid().ToString();
                    #region deleted
                    //persistable.ExecutionPointers.Add(persistedEP);
                    #endregion
                }
                #region Added
                persistable.ExecutionPointers.Add(persistedEP);
                #endregion

                persistedEP.StepId = ep.StepId;
                persistedEP.Active = ep.Active;
                persistedEP.SleepUntil = ep.SleepUntil;
                persistedEP.PersistenceData = JsonConvert.SerializeObject(ep.PersistenceData, SerializerSettings);
                persistedEP.StartTime = ep.StartTime;
                persistedEP.EndTime = ep.EndTime;
                persistedEP.StepName = ep.StepName;
                persistedEP.RetryCount = ep.RetryCount;
                persistedEP.PredecessorId = ep.PredecessorId;
                persistedEP.ContextItem = JsonConvert.SerializeObject(ep.ContextItem, SerializerSettings);
                persistedEP.Children = string.Empty;

                foreach (var child in ep.Children)
                    persistedEP.Children += child + ";";

                persistedEP.EventName = ep.EventName;
                persistedEP.EventKey = ep.EventKey;
                persistedEP.EventPublished = ep.EventPublished;
                persistedEP.EventData = JsonConvert.SerializeObject(ep.EventData, SerializerSettings);
                persistedEP.Outcome = JsonConvert.SerializeObject(ep.Outcome, SerializerSettings);

                persistedEP.Status = ep.Status;

                persistedEP.Scope = string.Empty;
                foreach (var item in ep.Scope)
                    persistedEP.Scope += item + ";";

                foreach (var attr in ep.ExtensionAttributes)
                {
                    var persistedAttr = persistedEP.ExtensionAttributes.FirstOrDefault(x => x.AttributeKey == attr.Key);
                    if (persistedAttr == null)
                    {
                        persistedAttr = new PersistedExtensionAttribute();
                        persistedEP.ExtensionAttributes.Add(persistedAttr);
                    }

                    persistedAttr.AttributeKey = attr.Key;
                    persistedAttr.AttributeValue = JsonConvert.SerializeObject(attr.Value, SerializerSettings);
                }
            }

            return persistable;
        }

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/commit/dd70ec4a13ca04abb2d9ef005a0e83211d87143c
