### ISSUE TITLE
subscription still alive after cancelled (sub)process containing a WaitFor

### ISSUE THREAD

**Issue by aphagel** [danielgerlag/workflow-core#350]
I encounter same issues as described in https://github.com/danielgerlag/workflow-core/issues/92. 

Based upon release 2.0 (June 30th 2019). The scenario I implemented is: wait for an event while parallel a timeout is planned (based upon Sleep). The timeout triggers the cancellation which is put immediately after the join. If the timeout occurs the subscription of the 'wait for' is not terminated.

**Comment by danielgerlag** [comment]
Can you provide a sample workflow that replicates this issue?

**Comment by aphagel** [comment]
Yes, but that will be tomorrow end of day.

**Comment by aphagel** [comment]
See the code in the attachment: "*SubscriptionAliveAfterCancelledSubprocess_350.zip*" containing the sample. You have to configure the persistence provider in program.cs (I used the sqlserver persistence provider).

The image below shows the result in the database after a timeout. As you can see the subscription is related to execution point of line 5 (with status 8 = cancelled).

<img width="1053" alt="PersistenceDataAfterTimeout" src="https://user-images.githubusercontent.com/49313667/61996483-07dc3b00-b095-11e9-89c9-50eee616cc6a.png">

**Solution in the attached file:**
[SubscriptionAliveAfterCancelledSubprocess_350.zip](https://github.com/danielgerlag/workflow-core/files/3438315/SubscriptionAliveAfterCancelledSubprocess_350.zip)

**Comment by danielgerlag** [comment]
This is correct behavior. The WaitFor will not fire, but the underlying subscription will not be terminated.  If you really want, you can also attach a cancel condition to the WaitFor.

**Comment by vaclavpfeifer** [comment]
Hi, we have encounter similar behavior. Basically, the same use-case:

```
.Do(p => p 
    .StartWith(i => { })
        .Output((s, wfm) => wfm.LastWorkflowMessage = "_____Started cancellation branch!")
    .WaitForSingle(nameof(CancelOrderRequestedEvent), (wfm, ctx) => wfm.OrderCode)
        .CancelCondition(pp => 
            pp.Status != Abstraction.Models.ReservationStatus.Reservation &&
            pp.Status != Abstraction.Models.ReservationStatus.Canceled, true)
        .Output(wfm => wfm.Status, s => Abstraction.Models.ReservationStatus.Canceled)
    .If(pp => pp.Status == Abstraction.Models.ReservationStatus.Canceled)
        .Do(pp => pp
            .StartWith<CloseReservationStep>()
                .Input(i => i.ReservationCode, d => d.StorageReservationCode)
            .Then<PublishOrderStatus>()
            .EndWorkflow()) // end WF
    .Then(i => { })
        .Output((s, wfm) => wfm.LastWorkflowMessage = "_____Finished cancellation branch!")
    )

```
Bellow is then join which waits for completion. The workflow runs successfully, but the subscriptions remains in database.

If this is be design then I would like to ask if you could provide us with some reason and further with some suggestions how to approach this.

Thank you,
V.
