### ISSUE TITLE
Installing package with .net 4.6

### ISSUE THREAD

**Issue by eddiehnocera** [danielgerlag/workflow-core#351]
I get this error while installing the library in my project (.net 4.6).

**Could not install package 'WorkflowCore 2.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.**

what can I do? what is the minimum .net version for this library?
Thank you

**Comment by germandb** [comment]
From the [.NET implementation support docs
](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) you can read that the minimum version of .NET Framework compatible with .NET Core 2.0 is 4.6.2 but they recomend use the 4.7.2 or higher.

**Comment by eddiehnocera** [comment]
Thank you
