### ISSUE TITLE
Dynamic workflow definitions

### ISSUE THREAD

**Issue by oliverw** [danielgerlag/workflow-core#352]
Glancing over the documentation I got the impression that all workflows need to be defined at application startup. Out of curiosity, would it even be possible to use workflow-core for something resembling the likes of IFTTT or Zapier where workflows are user created?

**Comment by danielgerlag** [comment]
There is no constraint that workflows need to be defined at startup... you can register JSON or YAML workflows at any time.

**Comment by oliverw** [comment]
@danielgerlag True but it looks like you unregistering a workflow that is no longer referenced (has no active instances) is currently not possible. I'd wager that a long running WorkflowHost process would accumulate quite some garbage over time by constantly registering new workflow definitions that result from multiple users create and editing workflows.

**Comment by danielgerlag** [comment]
I'd be open to a pull request that adds functionality to de-register workflows.

**Comment by softwareguy74** [comment]
Isn't this basically just versioning?  For example:

Workflow 1 Version 1: Do Something 

Workflow 1 Version 2: Do Something -> Do Something Else

So, all Workflow 1's excuted as Version 1 will continue to run even if new Workflow 1's excuted as Version 2 are executed.

I'm assuming that's all that Zapier and the likes are doing behind the scenes.

Having been working with an enterprise workflow system in a large corporate environment for some time now, I can tell you thats how it works as well.  I can't imagine how changing a workflow definition on the fly at execution time would even work.

**Comment by oliverw** [comment]
@softwareguy74 That's actually true.
