### ISSUE TITLE
Triggers - Question

### ISSUE THREAD

**Issue by tameyer1** [danielgerlag/workflow-core#353]
Quick question regarding triggers for workflows.
The doco and conversation I have seen seem to imply that one starts a workflow that contains a waitfor then once the awaited event occurs, that workflow runs.

I'm looking for something akin to Azure Logic App triggers where once the event (schedule, post, event) occurIs  a workflow is triggered.  When a new event occurs, the workflow triggers again.
In workflowcore, it seems like you need to start an instance with a waitfor and a final step preparing a new instance (?) so that when the event occurs again the workflow will fire. 

My goal is to create a workflow that is always waiting for an event, fires when the event occurs, and can fire again if the event occurs again.

Ideas on how this can be implemented in workflowcore are appreciated.

**Comment by danielgerlag** [comment]
That doesn't sound accurate... when a workflow reaches a WaitFor step, it will pause until the event it is waiting for has been published.  You could achieve the above scenario by putting a WaitFor inside a While loop, and using a new EffectiveDate each time.

**Comment by tameyer1** [comment]
Yes.  That worked.
