### ISSUE TITLE
In JSON workflow definition, can an Input value be a literal value?

### ISSUE THREAD

**Issue by georgelichen** [danielgerlag/workflow-core#355]
Can an Input value be a literal value, such as a literal string, integer or boolean?  For example, I want to set the Value property of the ApprovalStep step instance to a literal string "Hello Word".  But it seems this is not allowed at runtime.

{
  "Id": "ApprovalProcess",
  "Version": 1,
  "Description": "Testing Approval Process",
  "Steps": [
    {
      "Id": "ApprovalStep",
      "Name": "CMET Approval",
      "StepType": "WFLearning.ApprovalProcess.NotificationStep, WFLearning",
      "Inputs": { "Value": "Hello Word" },
      "ErrorBehavior": "Retry"
    }
  ]
}

**Comment by danielgerlag** [comment]
yes it can... if it's a string you need to enclose it in quotes (within the other quotes)

**Comment by georgelichen** [comment]
Thank you Daniel, I can pass literal value to the Input value now.
