### ISSUE TITLE
Create Workflow based on User Role

### ISSUE THREAD

**Issue by neosoft7** [danielgerlag/workflow-core#359]
Hi,
I have a case and wonder if your great engine can handle this.

I have requests created by the end user, so the request must take a specific workflow, for example: End user creates a new request> role1 is assigned to (role2 and role3)> Whenever Role2 and Role3 are finished, > Role4 may ask for some information from the end user> End User Answer the request> role 4 (accepts the answer > Return the request to role1) or (rejected the answer> Return back to the end-user).

So Is there a way to use Workflow Core in this way with user roles factor? If so, please let me know how to solve the case study.
Many thanks

**Comment by danielgerlag** [comment]
You could implement this with the `WaitFor`
https://workflow-core.readthedocs.io/en/latest/external-events/
