### ISSUE TITLE
Using While with WaitFor

### ISSUE THREAD

**Issue by aaronchambers** [danielgerlag/workflow-core#36]
Hi Daniel,

Thanks for your great work on this.  I am wanting to put a WaitFor Event in a While block and if a particular "Event" is received then Loop back to the beginning.  Something like this.

.While(data => data.Event == "loop")
        .Do(x => x
            .StartWith<DoSomething>()
            .WaitFor("Event", data => "Key")
                            .Output(data => data.Event, step => step.EventData)
            .Then<DoSomethingElse>()
.Then<SayGoodbye>();

I have tried this and it appears that the Events don't get evaluated because the Workflow is locked.  Is that expected, Can you advise an alternative workflow setup?

Thanks.  
Aaron

**Comment by danielgerlag** [comment]
Hi Aaron,

This seems to be a bug... I have deployed a fix, please update to 1.2.5
Also, you may want to include an effective date in your .WaitFor()... otherwise it will subscribe to all events in history with that name and key.
