### ISSUE TITLE
First event of first workflow is not correctly processed

### ISSUE THREAD

**Issue by acailly** [danielgerlag/workflow-core#362]
Hi,

## My Workflow

I have a workflow defined as follows: 

```
builder
	//===========================================================================================================//
	.StartWith<WaitForJsonEvent<SaisieAAAEvent>>()
	.Output(data => data.Saisie, step => step.EventData)
	//===========================================================================================================//
	.Then<WaitForJsonEvent<SaisieBBBEvent>>()
	.Output(data => data.Saisie, step => step.EventData)
	//===========================================================================================================//
	.Then<EnvoiMailStep>()
	.Input(step => step.Saisie, data => data.Saisie)
	//===========================================================================================================//
	.Then<EnvoiDemandeCCC<CCCDemandeFactory>>();
```

Versions : WorkflowCore.Persistence.SqlServer v2.0.1

To start a workflow I fill the web form and click the send button, this creates a workflow and send a SaisieAAAEvent

## My Bug

It occurs only when I fill the form for the first time after starting my app, it works well after.

- the workflow stays in the first step (in SqlServer DB, workflow is present in wfc.Workflow, data is empty)
- but the event is correctly registered and mark as processed (in SqlServer DB, event is present in wfc.Event, data is filled, isProcessed is 1)

I understand that the event has been processed but the workflow execution has not been updated.

## Some debugging

I use a `WaitForJsonEvent` which is defined as follows:

```
public class WaitForJsonEvent<EventType> : StepBody
{
	public EventType EventData { get; set; }

	public override ExecutionResult Run(IStepExecutionContext context)
	{
		string name = typeof (EventType).Name;
		if (!context.ExecutionPointer.EventPublished)
			return ExecutionResult.WaitForEvent(name, context.Workflow.Id, DateTime.Now);
		this.EventData = JsonConvert.DeserializeObject<EventType>(context.ExecutionPointer.EventData.ToString());
		return ExecutionResult.Next();
	}
}
```

When everything works, the `Run()` method is called 2 times, 1 time with context.ExecutionPointer.EventPublished = false then 1 time with context.ExecutionPointer.EventPublished = true

When it doesn't works (first workflow after starting app), the `Run()` method is called only 1 time with context.ExecutionPointer.EventPublished = false

But I don't know why.

## Need help

I don't know where to investigate, could you give me some directions?

**Comment by danielgerlag** [comment]
Is there a reason you can't use the built-in `WaitFor` primitive?
https://workflow-core.readthedocs.io/en/latest/external-events/

**Comment by acailly** [comment]
It misses the JSON deserialization for my use case, so I basically copied the `WaitFor` code and added the `JsonConvert.DeserializeObject`

I noticed `WaitFor` uses DateTime.MinValue instead of DateTime.Now, so I changed that in `WaitForJsonEvent`

**Comment by danielgerlag** [comment]
That supposed to be the default if an effective date is not set.
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Primitives/WaitFor.cs#L13

**Comment by acailly** [comment]
I think I found what was causing my issue.
I was creating the workflow and just after I was sending an event.

I think the event arrived before the workflow arrived in the step waiting for this event, so the event got processed but the workflow step was not validated.

Now when I create a workflow, I fetch the workflow instance until the nextExecution is null and then I send the event.

It seems to work well, I'm closing the issue.
