### ISSUE TITLE
Delete Events

### ISSUE THREAD

**Issue by OAlbrecht2407** [danielgerlag/workflow-core#364]
Hi,
i'm evaluating workflow-core for using it in our application. As i'm doing that i try to implement a PersistenceProvider for our database (SAP SQL Anywhere). 
In the interface IPersistenceProvider i didn't see a method to delete an event. 
How should the events beeing cleared after the corresponding workflow has terminated? 
In your UserTask extension you create an event for every workflowinstance. How should such events be deleted?

kind regards 
Oliver

**Comment by danielgerlag** [comment]
I would follow the reference in-memory implementation.
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/DefaultProviders/MemoryPersistenceProvider.cs

It is not true that we create an event for every workflow instance, we create subscriptions for those that match the event.
