### ISSUE TITLE
MemoryPersistenceProvider and DateTime-Values

### ISSUE THREAD

**Issue by OAlbrecht2407** [danielgerlag/workflow-core#365]
I'm using MemoryPersistenceProvider as blueprint to implement another PersistenceProvider.
Currently i'm confused by the use of DateTime-Values.

GetSubscriptions uses the parameter asOf as it is. GetRunnerableEvents uses the parameter asAt with asAt.ToUniversalTime(). And GetEvents uses asOf again as it is.

Should not at least GetRunningEvents and GetEvents use the same type of DateTime (local or utc)?

And GetRunnableInstances uses asAt.ToUniversalTime().Ticks.

In my opinion should all methods use UTC (ToUniversalTime()),

kind regards
Oliver

**Comment by danielgerlag** [comment]
Everything should use UTC. In some instances we use Ticks of UTC as well because you can store it as a long / BigInt
