### ISSUE TITLE
how to cancel schedule step if condition is met

### ISSUE THREAD

**Issue by devinWin** [danielgerlag/workflow-core#367]
Hi, I'm using the .Schedule step builder to schedule an acceptance period for a user to take action, if the user takes an action before the time period expires, then the step doesn't need to proceed.  I tried using the .CancelCondition, but the .CancelCondition is not being applied on the .schedule step, but is executed immediately and completes the workflow.

.Schedule(data => TimeSpan.FromSeconds(15)).Do(then => then
    .StartWith<NotifyUserOfAcceptancePeriodExpired>()
).CancelCondition(data => data.WorkRequestState != WorkRequestState.UserNotified.ToString())

**Comment by danielgerlag** [comment]
Could you include a demo project that replicates this issue?
