### ISSUE TITLE
Workflows finished deletion?

### ISSUE THREAD

**Issue by jchoplin** [danielgerlag/workflow-core#368]
Hi,

i'm using this wonderful workflow library for a core service in my application. Everything works very well but I still have a question. Maybe i'm missing something, but if I check the wcf.workflows collection, I can see all the instance of workflows finished correctly with a status=2, meaning that the workflow is complete. Now I don't want to keep these finished workflows forever. Is there a method to call to clean up things or should I go and develop myself a method to clean things up or use an Expire Data index on the wcf.workflows collection?

Thanks for your answer and regards

**Comment by danielgerlag** [comment]
There is not currently anything built-in to remove complete workflows... it would make sense to add this.

**Comment by danielgerlag** [comment]
I will look into this shortly

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/402

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/releases/tag/2.1.2
