### ISSUE TITLE
How to get JSON from an IWorkflowBuilder or others

### ISSUE THREAD

**Issue by zenglei286** [danielgerlag/workflow-core#369]
How to get JSON from an IWorkflowBuilder or others

**Comment by softwareguy74** [comment]
That would be very helpful.  That way if we had a problem creating the appropriate JSON for a complex workflow, you could do it via code and then spit out the equivalent JSON.   Might help to reduce questions about building workflows from JSON.

**Comment by danielgerlag** [comment]
The functionality does not exist at this time.
