### ISSUE TITLE
Stepping slow in Linux

### ISSUE THREAD

**Issue by marvelvang** [danielgerlag/workflow-core#374]
Hello,

maybe someone can help me out - I have develop workflows in Windows, running fine. Days ago I have deployed portable FW-dependant binaries which are running fine in Windows to Linux. I now have tried different installations in and outside of docker containers, but in Linux there are always like 5-10 seconds "gaps" between step executions when executing a workflow. In Windows steps are immediatly executed one after another. This is always repoducible. I also tried memory and MS-SQL-Persistence-Providers, no change.

I have added logging at the beginning and end of each step. I have attached logs of the execution of one of the smaller workflows (5 steps) in comparison as example.

Thanks in advance for any ideas.

[Windows.txt](https://github.com/danielgerlag/workflow-core/files/3549937/Windows.txt)
[Linux.txt](https://github.com/danielgerlag/workflow-core/files/3549938/Linux.txt)

PS: Windows 10, Linux Ubuntu 18.04, ASP.NET Core 2.2

**Comment by qazq** [comment]
similar issue #358 ?

**Comment by marvelvang** [comment]
Thanks, might be possible, however your Commit/PR is based on an ages old master branch, not much help there. If possible please create a commit based on current code. However, looks like not so much code changed since then, your point might be still valid, I cannot tell it.

**Comment by marvelvang** [comment]
This works fine! Thank you very much. Hope for your PR to get incorporated soon. I will close when this happens, ok?

**Comment by danielgerlag** [comment]
Try v2.0.1?

**Comment by marvelvang** [comment]
Works perfect, thanks.

Seeing WorkflowCore 2.0.1 is already some days old, as a sidenote I want to add,  I would not have run into this issue if the nuget pkg WorkflowCore.Persistence.SqlServer 2.0.1 would reference WorkflowCore 2.0.1 - up to today I always end up up with 2.0.0. Only additionally adding a dedicated (usually unneeded) reference to 2.0.1 gives me the real thing.
