### ISSUE TITLE
Logging each step execution

### ISSUE THREAD

**Issue by venugopalsjce** [danielgerlag/workflow-core#382]
Hello,
I am creating a workflow, and I need to log the workflow operations.
Can you please provide an example, wherein there is a mechanism to log the beginning and end of each workflow step?
How do I achieve the above ?

Regards,
Venu

**Comment by danielgerlag** [comment]
If you set you log level to DEBUG, the library already logs this

https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/WorkflowExecutor.cs#L142
