### ISSUE TITLE
Parallel Tasks don't work as expected (?)

### ISSUE THREAD

**Issue by fchristina** [danielgerlag/workflow-core#383]
Hello,

I try to simulate two tasks having a progressbar and  I have defined the workflow to call this tasks as parallel. The workflow runs the steps sequentally. Is it possible to run these parallel?
I have attached my sample project.

thanks and beste regards,
Christina

[ConsoleApp12.zip](https://github.com/danielgerlag/workflow-core/files/3573861/ConsoleApp12.zip)

**Comment by danielgerlag** [comment]
That is by design. Since workflows are long running background processes, parallel in this context means that each parallel branch will not block another branch. So if you have a WaitFor or a Delay, etc... in one of the parallel branches, the others will still be free to execute.
