### ISSUE TITLE
Is there any method transition between WorkflowDefinition and json string? 

### ISSUE THREAD

**Issue by cocosip** [danielgerlag/workflow-core#384]
Is there any method transition between WorkflowDefinition and json string? 
Our demand is a web page ,that can define workflow。So i should convert the web design page data to a model, then convert to WorkflowDefinition,and persistence it。

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/DefinitionStorage/DefinitionLoader.cs#L29

https://workflow-core.readthedocs.io/en/latest/json-yaml/

**Comment by cocosip** [comment]
Thank you!
