### ISSUE TITLE
To use Workflow-core is it compulsary to use Microsoft.Extensions.DependencyInjection IOC container in .net 4.7?

### ISSUE THREAD

**Issue by Reena-Patel** [danielgerlag/workflow-core#388]
I want to use Workflow-core library in .net 4.7 application. Currently, an application is using spring framework for the IOC container. so is it compulsory to use Microsoft.Extensions.DependencyInjection in .net 4.7 application for Workflow-core library integration in .net 4.7 application? or is it possible to integrate Workflow-core library with existing spring IOC container?

**Comment by danielgerlag** [comment]
The library does not require `Microsoft.Extensions.DependencyInjection`, but it does use `Microsoft.Extensions.DependencyInjection.Abstractions`, which is a set of interfaces for IoC.
It will work with any IoC container that implements these abstractions, of which, most of them do.
