### ISSUE TITLE
Issue with Navigation with Xamarin.Form Application

### ISSUE THREAD

**Issue by gufran786** [danielgerlag/workflow-core#389]
In our workflow, we require inputs from user then navigate and pass the output to other pages.
But, while Navigating from first page in first step to next page, the first step process should end and need to automatically execute next step. In this case, next step process is not starting because navigation is not working. 

Any help is appreciated !

**Comment by danielgerlag** [comment]
You would need to integrate the UI via external events
https://workflow-core.readthedocs.io/en/latest/external-events/

**Comment by gufran786** [comment]
Thanks,  for quick reply danielgerlag.
I will try ur suggestion and come back to you if I, stuck anywhere.

**Comment by gufran786** [comment]
I don't understand how can I integrate my UI with an external event. 
Sample only contains Console App.
Can you please, provide me Sample App for Xamarin.forms to integrate my Xamarin.Forms(UI) within Steps via external events.

Below is my scenario: 

My Workflow Defination:
		
		builder.
        StartWith<Page1Step>()
			.WaitFor("Page2Step", data => "0")  **// Subscribe for Page2Step external event.**
		.Then<Page2Step>()
			.WaitFor("Page3Step", data => "1")			
		.Then<Page3Step>();
		
		
		public partial class Page1 : ContentPage
		{
			public StartPage ()
			{
				InitializeComponent ();
			}

			private void BtnStart_Clicked(object sender, EventArgs e)
			{
				// Publishing Page2Step external event from Page1 code behind.
				Host.PublishEvent("Page2Step", "0", "");				
			}
		}
		
		Page2Step : StepBody // after publishing Page2Step step is executing.
		{
			public override ExecutionResult Run(IStepExecutionContext context)
			{
				**// Now trying to load Page 2 for next step here, but here Navigation does not work.**
				Navigation.PushAsync(new Page2());
				
				return ExecutionResult.Next();
			}
		}

Thanks, 
Gufran Ali
