### ISSUE TITLE
WaitFor() External Event  not working inside While loop

### ISSUE THREAD

**Issue by gufran786** [danielgerlag/workflow-core#391]
Hello,
I have a workflow wherein, I have to use while loop, and inside while loop, I want to use WaitFor() external event. But, inside while loop WaitFor() is not working and while loop steps continue to execute.

Below is my source code, Have a look and kindly, help me on this   👍 
builder.StartWith<StartLeaveRequestStep>()
    .Input(step => step.VM, data => data.VM)
    .WaitFor("GotoFillLeaveRequestFormStep", data => "0") // It is waiting and working here.
.Then<FillLeaveRequestFormStep>()
    .Input(step => step.VM, data => data.VM)
    .WaitFor("GotoManagerApprovalStep", data => "1") // It is waiting and working here.
    .Output(data => data.LeaveRequestData, step => step.EventData)
.Then<ManagerApprovalStep>()
    .Input(step => step.VM, data => data.VM)
    .Input(step => step.LeaveRequestDataReceived, data => data.LeaveRequestData)
    .WaitFor("MangerApprovalDone", data => "2")  **// It is waiting and working here.**
    .Output(data => data.ManagerApprovalComment, step => step.EventData)
    .While(data => data.ManagerApprovalComment == "CHANGE")

            .Do(x => x                                                                      
                    .StartWith<FillLeaveRequestFormStep>()
                         .Input(step => step.VM, data => data.VM)
                         .WaitFor("GotoManagerApprovalStep", data => "1") **// it never wait for this event. //executing next step always.**
                         .Output(data => data.LeaveRequestData, step => step.EventData)
                     .Then<ManagerApprovalStep>()
                         .Input(step => step.VM, data => data.VM)
                         .Input(step => step.LeaveRequestDataReceived, data => data.LeaveRequestData)
                         .WaitFor("MangerApprovalDone", data => "2") **// it never wait for this event. //executing next step always.**
                         .Output(data => data.ManagerApprovalComment, step => step.EventData)
               )// while loop ends here.

**Comment by danielgerlag** [comment]
Try adding an effective date to the `WaitFor`

**Comment by gufran786** [comment]
Thanks, Danielgerlag.
It worked for me !!! :)
