### ISSUE TITLE
How to write WaitFor and If condition in json

### ISSUE THREAD

**Issue by rizwika94** [danielgerlag/workflow-core#392]
I have written the code in c# and i need to write the same set of code in JSON. I don't find examples for using WaitFor and If condition. 

My Code:

>  .If(data => data.ApprovalComment == "NO")
>                                .Do
>                                (
>                                    then => then
>                                                .StartWith<FinalResultStep>()
>                                                .Input(step => step.VM, data => data.VM)
>                                                .Input(step => step.ManagerApprovalReceived, data => data.ManagerApprovalComment)
>                                                .WaitFor("EndTheWorkflow", data => "4")
>                                                .Then<EndRequestStep>()
>                                                .Input(step => step.VM, data => data.VM)
>                                )

Any help is appreciated !! Thanks in advance

**Comment by danielgerlag** [comment]
https://workflow-core.readthedocs.io/en/latest/json-yaml/#common-dsl

**Comment by rizwika94** [comment]
I couldn't understand this.

>  "Inputs": { "Condition": "<<expression to evaluate>>" },

What is condition how to evaluate expression ?

**Comment by OAlbrecht2407** [comment]
"Inputs":
{
   "Condition": "Data.ApprovalComment == \"NO\""
}

Data is the Data-object of the workflow-instance (the one you access in your sample with (data => )

**Comment by rizwika94** [comment]
@OAlbrecht2407  Thanks for your help.Now it works
