### ISSUE TITLE
Would it be possible to use Event sourcing using Exchange with RabbitMQ?

### ISSUE THREAD

**Issue by Reena-Patel** [danielgerlag/workflow-core#395]
Hi
I want to use the waitfor statement on exchange message waiting. So here my question is instead of using WorkflowCore.QueueProviders.RabbitMQ package can I write my own IQueueProvider implementation using rabbitmq to queue and dequeue messages in exchange queue? is yes then how can I register my concrete IqueueProvider implementation?

**Comment by danielgerlag** [comment]
Something like this
https://github.com/danielgerlag/workflow-core/blob/master/src/providers/WorkflowCore.QueueProviders.RabbitMQ/ServiceCollectionExtensions.cs#L15
