### ISSUE TITLE
Bug : Wrong order of steps when using "when"

### ISSUE THREAD

**Issue by OAlbrecht2407** [danielgerlag/workflow-core#399]
I have the following sample workflow:

```
                builder.StartWith(c => ExecutionResult.Next())
                    .Then<HelloWorld>()
                    .Then<IsLastCharacterOfIdADigit>()
                    .Output(d => d.IsDigit, c => c.IsDigit)
                    .Then<IfThenElse>(
                        c => c
                            .When(d => "yes").Do(d => d
                                .StartWith(c1 => ExecutionResult.Next())
                                .Then<Say>()
                                .Input(s => s.Message, s1 => "Is a digit")
                                .Then<Say>()
                                .Input(s => s.Message, s1 => "Is a digit 2")
                            )

                            .When(d => "no").Do(d => d
                                .StartWith(c1 => ExecutionResult.Next())
                                .Then<Say>()
                                .Input(s => s.Message, s1 => "Is no digit")
                                .Then<Say>()
                                .Input(s => s.Message, s1 => "Is no digit 2")
                            )
                    )
                    .Input(i => i.Condition, d => d.IsDigit)
                    .Then<GoodbyeWorld>();
```

IfThenElse is defined as:

`
public` class IfThenElse : StepBody
    {
        public bool Condition { get; set; }

        #region Overrides of StepBody

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            return ExecutionResult.Outcome(Condition ? "yes" : "no");
        }

        #endregion
    }
`

The output should be (if the result of the ifthenelse-condition is true):

Hello World
Is Digit
Is Digit 2
Goodbye World

but the output is:
Hello World
Goodbye World
Is Digit
Is Digit 2

The reason is that WorkflowExecutor.Execute does a foreach of the possible execution pointers.
It first calls the InlineStepBody ( .StartWith(c1 => ExecutionResult.Next()) ) and then the GoodByeWorld-step. After these steps it will execute the steps after the InlineStepBody (Say line 1 and Say line 2).

How to fix this?

kind regards 

Oliver

**Comment by danielgerlag** [comment]
This is expected, the `when` will fork the workflow, adding a `then` will not function as a join of forks.

**Comment by OAlbrecht2407** [comment]
Ok, i've found another way to implement the if-then-else functionality (similar to issue https://github.com/danielgerlag/workflow-core/issues/312 ).
