### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by ccpony** [danielgerlag/workflow-core#4]
Are there more detailed tests that you might be able to post yet?

**Comment by danielgerlag** [comment]
I will be adding a test suite in the next 1 - 2 weeks.  
Is there something specific you were looking for?

**Comment by ccpony** [comment]
Until you're able to produce more complete documentation, I'm hoping that tests on persistence, correlation and re-constitution of a specific long-running instance might help to understand how those processes work.

**Comment by danielgerlag** [comment]
Stay tuned, I should have something for you next week.
I'm also working on a Typescript port, for running on node or in browser, if you are interested.

**Comment by ccpony** [comment]
I am interested but mostly I'm interested in a server-based solution that easily rehydrates thousands of persisted instances through a REST API.  I hope that you follow this all the way through - - it's a great project.  Since it's become obvious that MS has abandoned WF, an enormous void currently exists in the .Net workflow space.
