### ISSUE TITLE
Possibility to use the context in the "new" Input syntax

### ISSUE THREAD

**Issue by ssougnez** [danielgerlag/workflow-core#400]
Hi,

when using the old `Input` syntax, it was possible to access the `context` object, which was useful in a `ForEach` (to access `context.Item`).

However, the new syntax of the `Input` does not have an overload giving access to the `context`. It would be nice to add this feature.

Thanks

**Comment by danielgerlag** [comment]
What do you mean by old and new syntax? It should not have changed?

**Comment by ssougnez** [comment]
Some time ago, the syntax was:

`step.Input(step => step.Foo, (data, context) => ...)`

Now, the syntax is more:

`step.Input((step, data) => { ... })`

Now, it would be nice to be able to do:

`step.Input((step, data, context) => { ... })`

**Comment by danielgerlag** [comment]
You should still be able to do that

https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Interface/IStepBuilder.cs#L92

**Comment by ssougnez** [comment]
Yes, I am...
But it's not consistent with the new syntax.
Since you introduced https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Interface/IStepBuilder.cs#L99, I'm only using that because it's way more elegant, however, I can't use it and have access to the `context` in the same time.

For now, I still reverted to the old syntax.

Is it clearer ? ;-D

**Comment by danielgerlag** [comment]
This should do it? https://github.com/danielgerlag/workflow-core/commit/79bc406d8c436753dcb2c2b90b25d81021989940

**Comment by danielgerlag** [comment]
Did the new version resolve this?

**Comment by ssougnez** [comment]
I'm gonna update it in my project and tell you what

**Comment by ssougnez** [comment]
Fixed
