### ISSUE TITLE
How to disable/remove 'Polling for runnable workflows' and 'Polling for unprocessed events' log messages

### ISSUE THREAD

**Issue by gonengf** [danielgerlag/workflow-core#403]
Is there a way to disable/remove 
- **Polling for runnable workflows** and 
- **Polling for unprocessed events**

log messages?

**Comment by marvelvang** [comment]
What I do in NLog is:

```
  <rules>
    <logger name="*" minlevel="Trace" writeTo="logallfile" />

    <!-- BlackHole without writeTo -->
    <logger name="WorkflowCore.*" maxlevel="Info" final="true" />

    <logger name="*" minlevel="Info" writeTo="logfile" />
  </rules>
```

This hides everything WF related from my normal log, but I log that to another special file in case I need it.

**Comment by gonengf** [comment]
Thanks a lot @marvelvang,
Do you know if there is there way to disable it in the console output?

**Comment by marvelvang** [comment]
Interesting question. I cannot help you but Google might e.g. [this one](https://stackoverflow.com/questions/10282144/suppress-console-writeline-for-portion-of-program) sounds promising. Good luck.

**Comment by danielgerlag** [comment]
set your log level to `warning`

**Comment by gonengf** [comment]
I could achieve it filtering the **WorkflowCore.Services.BackgroundTasks.RunnablePoller** category from the logs. Here is the code:
```
 services.AddLogging(x =>
{
      x.AddFilter((provider, category, logLevel) => logLevel != LogLevel.Debug && category != "WorkflowCore.Services.BackgroundTasks.RunnablePoller");
      x.AddConsole();
      x.AddDebug();
      x.AddNLog();
});
```

Thanks @danielgerlag for the help!

**Comment by DevsAnon** [comment]
@danielgerlag How can I set log level specific for workflow-core lib? I don't want my whole log level to be affected,

**Comment by DevsAnon** [comment]
I created a CR for this
https://github.com/danielgerlag/workflow-core/pull/904
to switch these to LogDebug instead of Info

**Comment by DevsAnon** [comment]
@danielgerlag can you please review the Pull request associated with this issue? There is no point in constantly logging polling events anywhere else but debugging.
