### ISSUE TITLE
How to write typecast statement inside Json Defination of workflow

### ISSUE THREAD

**Issue by 13atec030** [danielgerlag/workflow-core#405]
// This is my workflow data 
public class WorkflowData   
    {        
        public MasterDetailPage MainPage { get; set; }
 }

// This is the Step
 public class HelloWorldStep : StepBody
    {
        public MasterDetailPage MainPage { get; set; }
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            MainPage.Detail = new HelloWorldPage();
            return ExecutionResult.Next();
        }
    }

  public static void RunWorkflow(string configFilePath)
        {
            IServiceProvider serviceProvider = ConfigureServices();
            _globalHost = serviceProvider.GetService<IWorkflowHost>();
            var loader = serviceProvider.GetService<IDefinitionLoader>();
            var _json = LoadWorkflowDefinationFromJsonFile(configFilePath);
            var Defination = loader.LoadDefinition(_json, Deserializers.Json);
            _globalHost.Start();     

// Here I am Starting Workflow with Id and passing data                   
            _workflowId = _globalHost.StartWorkflow(Defination.Id, new WorkflowData() { MainPage = (MasterDetailPage)App.Current.MainPage }).Result; // This line I am starting the workflow 
        }

//This is my workflow json defination:
{
  "Id": "HellowWorldWokFlowJson",
  "Version": 1,
  "DataType": "WorkflowFrameworkTest.WorkflowData, WorkflowFrameworkTest",
  "Steps": [
    {
      "Id": "HelloWorldStep",
      "StepType": "WorkflowFrameworkTest.Samples.HelloWorld.Steps.HelloWorldStep, WorkflowFrameworkTest",
      "NextStepId": "GotoFillLeaveRequestFormStep",
      "Inputs": {
        "MainPage": "data.MainPage"   // Problem is here , How to write typecast here
      }
    }
]
}

Problem is workflow works well with C# code:
 builder
               .StartWith<HelloWorldStep>()
                   .Input(step => step.MainPage, data => data.MainPage)
                   .WaitFor("HelloWorldEventCompleted", data => "0")
               .Then<GoodbyeWorld>()
                    .Input(step => step.MainPage, data => data.MainPage);

But, with json defination it is not working as soon as I add
"Inputs": {
        "MainPage": "data.MainPage"   // Problem is here , How to write typecast here
      }

Please, suggest how to write this particular statement.

Thanks in advance !!

**Comment by danielgerlag** [comment]
I would strongly suggest that you do not pass UI components as workflow data.  It is terrible coupling and it needs to be serializable. You should abstract your data out in POCO objects and pass those in the workflow data and inputs.

**Comment by 13atec030** [comment]
Actually, I am just passing the UI reference and it is working fine with C# code workflow like below:
.StartWith()
.Input(step => step.MainPage, data => data.MainPage)

But, it is having some problem while json defination like below:
{
"Id": "HelloWorldStep",
"StepType": "WorkflowFrameworkTest.Samples.HelloWorld.Steps.HelloWorldStep, WorkflowFrameworkTest",
"NextStepId": "GotoFillLeaveRequestFormStep",
"Inputs": {
"MainPage": "data.MainPage"   **// Problem is here , How to write typecast here**
}

**Comment by danielgerlag** [comment]
As soon as you try to use one of the DB persistence providers, it won't work.

**Comment by 13atec030** [comment]
Thanks Daniel. I am able to set detail page like this:
  ((MasterDetailPage)App.Current.MainPage).Detail = new ScheduleTaskPage(Message);
// I added this code so that xamarin form developer can take reference.
