### ISSUE TITLE
Event Marked as Processed - Concurrent workflows

### ISSUE THREAD

**Issue by ponugotisumanrao** [danielgerlag/workflow-core#408]
Hi Daniel,

We have implemented workflow core in our project and what we noticed that at some stage we had lot (around close 1000). We have single mongo db instance as Persistence, Redis as Queue, locking. Every workflow starts and waits for events. In workflow level there a process / timer service which looks for a messages in the amazon SQS and then it publishes an event. In our case, as mentioned we have lot of running workflows waiting for events,  some workflows are not even created when en event is published. I Looked into implementation of EventConsumer, noticed there is complete boolean which is set to true by default. Then looping through subscriptions, in this case there are no subscriptions at that time but there is an event. Then because of Complete is set to true event is getting marked as processed. I think this is an issue. Also another thing, there could be situations that a subscriber available for an event marked as processed and later another workflow started and looking for same event, but as it's marked as processed then subscriber is not the event and getting stuck. Do you have any ideas / suggestions how this can be solved ? Also, Is there any recommendations in using the queue / locking technologies and also persistence with 1000's of workflows running at the same time ? I am also attaching the event consumer code where i think there is an issue.  
Infrastructure  details if it helps:
AWS cloud - 4 ecs containers for workflow execution, Redis - queue & locking - 3 instances (1 - primary and 2 - replicas), 1 - mongo db instance.

Thanks,
Suman

![EventConsumer_IsProcessed](https://user-images.githubusercontent.com/20192189/65757099-b98bfc80-e116-11e9-996f-7ce33168b262.JPG)

**Comment by danielgerlag** [comment]
Are you using effective dates inside the workflows when calling `WaitFor` and also using an effective date when calling `PublishEvent`?  You can use effective dates to create events before the workflow exists.
