### ISSUE TITLE
Schedule is not working as expected  in Json 

### ISSUE THREAD

**Issue by 13atec030** [danielgerlag/workflow-core#409]
Hi Daniel,

I have stuck , implementing schedule in json workflow. In C# it's working fine.

//This is my C# workflow, it is working fine:

    public class ScheduleWorkflow : IWorkflow<WorkflowData>
    {
        public string Id => "schedule-sample";
        public int Version => 1;
    
        public void Build(IWorkflowBuilder<WorkflowData> builder)
        {
            builder
          .StartWith<SayHello>()
          .WaitFor("StartScheduleEvent", data => "0")
          .Schedule(
                    data => TimeSpan.FromSeconds(10)).Do((IWorkflowBuilder<WorkflowData> 
          schedule) => schedule
                    .StartWith<ScheduleTask>()  // Call is going to "NormalTask" after 5 second it is 
                                                                   //executing "ScheduleTask".
                    .Input(step => step.Message, data => "Doing schecule tasks!")
                   )
          .Then<NormalTask>() //Before schedule task "NormalTask" is executing.
          .Input(step => step.Message, data => "Doing normal tasks!");
        }
    }

//I want to write similar kind of workflow in json format. But the problem is, step given inside //schedule is not executing. Execution is on hold for given time span after that it is going next //step i.e "NormalTask".
// This is my json code:
```
{
  "Id": "ScheduleWorkflow",
  "Version": 1,
  "DataType": "WorkflowFrameworkTest.WorkflowData, WorkflowFrameworkTest",
  "Steps": [
    {
      "Id": "SayHello",
      "StepType": "WorkflowFrameworkTest.Samples.Schedule.Steps.SayHello, WorkflowFrameworkTest",
      "NextStepId": "StartScheduleEvent"
    },
    {
      "Id": "StartScheduleEvent",
      "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
      "NextStepId": "ScheduleStep",
      "Inputs": {
        "EventName": "\"StartScheduleEvent\"",
        "EventKey": "\"0\"",
        "EffectiveDate": "DateTime.Now"
      }
    },
    {
      "Id": "ScheduleStep",
      "StepType": "WorkflowCore.Primitives.Schedule, WorkflowCore",
      "NextStepId": "NormalTask",//Call should go to "NormalTask" and after 5 second it should 
                                                   //execute "ScheduleTask" task.
      "Inputs": {
        "Interval": "TimeSpan.FromSeconds(5)"
      },
      "Do": [
        [
          {
            "Id": "do1",
            "StepType": "WorkflowFrameworkTest.Samples.Schedule.Steps.ScheduleTask, WorkflowFrameworkTest",
            "Inputs": {
              "Message": "\"Doing schecule tasks!\""
            }
          }
        ]
      ]
    },
    {
      "Id": "NormalTask",   //This should execute before "ScheduleTask".
      "StepType": "WorkflowFrameworkTest.Samples.Schedule.Steps.NormalTask, WorkflowFrameworkTest",
      "NextStepId": "StopNormalTaskEvent",
      "Inputs": {
        "Message": "\"Doing normal tasks!\""
      }
    }
  ]
}
```
Kindly help me out

**Comment by danielgerlag** [comment]
Can you provide a sample project that reproduces this issue?
