### ISSUE TITLE
Is it possible to wait for 2 events and proceed to the next step if any of the event is received?

### ISSUE THREAD

**Issue by Reena-Patel** [danielgerlag/workflow-core#412]
Hi,
We want to wait for the 2 events say EventA and EventB then StepX. and let's say EventA is received then I want to proceed to the next step StepY or say EventB is received then also proceed to StepY.

The reason we want this type of structure is to let's say I have published one event **CreatePayment** now after processing CreatePayment it can publish one event either **PaymentCreated** or **PaymentCreationFailed**. Now I want to wait for both the event and if any of the event is received then I want to execute NotifySeller step about payment success/failure.

**Comment by ssm-dev** [comment]
Hi,
 public class TestWorkflowData
    {
        public PaymentStatus PaymentStatus { get; set; }
    }

    public class TestWorkflow : IWorkflow<TestWorkflowData>
    {
        public void Build(IWorkflowBuilder<TestWorkflowData> builder)
        {
            builder.StartWith(x => ExecutionResult.Next())
                .Parallel()
                .Do(d => d
                    .StartWith(x => ExecutionResult.Next())
                    .WaitFor("PaymentCreated", d => "key", d2 => DateTime.UtcNow,
                        d3 => d3.PaymentStatus == PaymentStatus.CreationFailed)
                    .Then<SetPaymentStatus>()
                        .Input(s => s.Value, d => PaymentStatus.Created)
                        .Output(d => d.PaymentStatus, s => s.Value)
                )
                .Do(d2 => d2
                    .StartWith(x => ExecutionResult.Next())
                    .WaitFor("PaymentCreationFailed", d => "key", d2 => DateTime.UtcNow,
                        d3 => d3.PaymentStatus == PaymentStatus.Created)
                    .Then<SetPaymentStatus>()
                        .Input(s => s.Value, d => PaymentStatus.CreationFailed)
                        .Output(d => d.PaymentStatus, s => s.Value)
                )
                .Join()
                .Then(x =>  Console.WriteLine("Finished with status:" + ((TestWorkflowData)x.Workflow.Data).PaymentStatus));

        }

        public string Id => "TestWorkflow";
        public int Version => 1;
    }

**Comment by Reena-Patel** [comment]
Thanks for the response!!

We want to execute the .Then(x =>  Console.WriteLine("Finished with status:" + ((TestWorkflowData)x.Workflow.Data).PaymentStatus)); if any of the event is received. Here this will wait for both events. in our case only one event can be received either "PaymentCreated" OR "PaymentCreationFailed"

**Comment by ssm-dev** [comment]
Hi,


> Here this will wait for both events.

No. Here this wait for onle one event. Have you a look at last parameter for WaitFor( cancelCondition)?
```
.WaitFor("PaymentCreated", d => "key", d2 => DateTime.UtcNow,
                        d3 => **d3.PaymentStatus == PaymentStatus.CreationFailed**)
```
and 
```
 .WaitFor("PaymentCreationFailed", d => "key", d2 => DateTime.UtcNow,
                        d3 => **d3.PaymentStatus == PaymentStatus.Created**)
```
