### ISSUE TITLE
Getting an IndexOutOfRangeException on QueueConsumer 

### ISSUE THREAD

**Issue by siskender** [danielgerlag/workflow-core#414]
Hi,

Since yesterday (after a new deployment) of our workflow component were we are using this workflow core component we are getting the following exception:

```json
{"@t":"2019-10-04T11:45:07.7109233Z","@m":"Index was outside the bounds of the array.","@i":"da24d145","@l":"Error","@x":"System.IndexOutOfRangeException: Index was outside the bounds of the array.\n   at System.Collections.Generic.HashSet`1.SetCapacity(Int32 newSize)\n   at System.Collections.Generic.HashSet`1.IncreaseCapacity()\n   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)\n   at WorkflowCore.Services.BackgroundTasks.QueueConsumer.Execute()","SourceContext":"WorkflowCore.Services.BackgroundTasks.IndexConsumer","ExceptionDetail":{"Type":"System.IndexOutOfRangeException","HResult":-2146233080,"Message":"Index was outside the bounds of the array.","Source":"System.Collections"},"Stack":{"StackName":"******","Environment":"******","$type":"StackOptions"}}
```
Investigating it further I can pinpoint that in the QueueConsumer there is a HashSet for the second passes. But my question is what is the purpose of this and why do you think that this is giving an error.

For the QueueProvider we are using Redis.

**Comment by danielgerlag** [comment]
This is high priority, I will investigate this ASAP

**Comment by danielgerlag** [comment]
I can't reproduce this issue... are you able to send a sample project that replicates the issue?
Which version are you using? Could you describe your environment in more detail?

**Comment by siskender** [comment]
Hi,

It is very difficult to give an example (because of sensitivity and complexity). But I can describe it for you.

We have 2 main workflows running, that can conditionally trigger other workflows (as subworkflows). These subworkflows, when they are finished, send events to the main workflows and close them self. The main workflows will then continue doing there stuff. But we have a lot of concurrent workflows running at the same time (either main ones, either sub ones). These can stay open for several days before getting finished (with a WaitFor).

The stack we are using:
- .NET Core 2.2
- Workflow Core 2.0
- Redis for locking and events
- Mongo for persistence

We are running the workflows for months on environments outside of production and we never saw this error appearing. We saw this error appearing in production after doing an update to an existing running instance of the workflow.

**Comment by siskender** [comment]
An update on our side for this:
It seems that it happens with the QueueProvider (in our case Redis) containing a huge number of messages to be processed. Restarting Redis solves this issue (probably because Redis is cleared and can have a fresh start).
![image](https://user-images.githubusercontent.com/8503234/67195614-8aa53580-f3f9-11e9-92e6-197b585f5599.png)
