### ISSUE TITLE
Allow StartWorkflow without the need to register the Id

### ISSUE THREAD

**Issue by ThomasBergholdWieser** [danielgerlag/workflow-core#417]
Why does every workflow participant need to know about every registered workflow? That kinda makes it impossible to start workflows by name from outside participants and every part of the system has to know about your workflow files. Makes building a distributed workflow system impossible?

**Comment by danielgerlag** [comment]
That's not true... Workflow-Core is a library that enables your to **execute** your workflows in a distributed environment.  What it does not have, and leaves up the the consumer of the library, is a workflow definition repository.

One such project that adds the next layer of functionality around the library is [Conductor](https://github.com/danielgerlag/conductor), which uses Workflow-Core internally but also takes care of definition management, etc...

**Comment by ThomasBergholdWieser** [comment]
we did look at conductor, but since its still alpha i dont think its going to be a good fit for our project. Right now we have solved this issue by registering a "dummy" workflow with the same id (the host windows services picks it up just as usual).
