### ISSUE TITLE
How to get IPersistenceProvider from an StepBody

### ISSUE THREAD

**Issue by zenglei286** [danielgerlag/workflow-core#418]
How to get IPersistenceProvider from an StepBody

**Comment by ssm-dev** [comment]
Using DI.
``
public class MyStep : StepBody
    {
        public MyStep(IPersistenceProvider provider)
        {

        }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("OK!");
            return ExecutionResult.Next();
        }
    }


//Registration 

protected override void ConfigureServices(IServiceCollection services)
        {
//...
            services.AddTransient<MyStep>(); 
//...
   }

**Comment by zenglei286** [comment]
> Using DI.
> 
> ```
> public class MyStep : StepBody
>     {
>         public MyStep(IPersistenceProvider provider)
>         {
> //...
>         }
> 
>         public override ExecutionResult Run(IStepExecutionContext context)
>         {
>          //...
>         }
>     }
> 
> 
> //Registration 
> 
> protected override void ConfigureServices(IServiceCollection services)
>         {
> //...
>             services.AddTransient<MyStep>(); 
> //...
>    }
> ```

thanks
