### ISSUE TITLE
Override the DequeueWork method implementation instead of Pulling the messages from queue, Push the message to the application.

### ISSUE THREAD

**Issue by Reena-Patel** [danielgerlag/workflow-core#420]
```
 using (var channel = _connection.CreateModel())
            {
                channel.QueueDeclare(queue: GetQueueName(queue),
                                     durable: true,
                                     exclusive: false,
                                     autoDelete: false,
                                     arguments: null);

                channel.BasicQos(prefetchSize: 0, prefetchCount: 1, global: false);

                var msg = channel.BasicGet(GetQueueName(queue), false);
                if (msg != null)
                {
                    var data = Encoding.UTF8.GetString(msg.Body);
                    channel.BasicAck(msg.DeliveryTag, false);
                    return data;
                }
                return null;
            }
```
**Instead of this implementation would it be possible to use below implementation ?**
```
 using (var channel = connection.CreateModel())
                    {
                        channel.BasicQos(0, 1, false);
                        channel.QueueDeclare(queue, true, false, false, null);

                        var consumer = new EventingBasicConsumer(channel);

                        consumer.Received += (model, ea) => ProcessQueueMessageCore(ea, channel);

                        channel.BasicConsume(queue, false, consumer);
                        Thread.Sleep(Timeout.Infinite);
                    }
```

**Comment by danielgerlag** [comment]
What's the underlying problem you're trying to solve?

**Comment by Reena-Patel** [comment]
@danielgerlag IQueueProvider's DequeueWork method which is pulling the messages from the rabbitMQ queue by while loop. We do not want to pull the messages from the queue. 
when the message is received in the queue then invoke the application method. We want to override such type of implementation in the DequeueWork method.

**Comment by danielgerlag** [comment]
Sure, you could add a config option on the IoC extension method to let the consumer decide how they want it to poll?

**Comment by Reena-Patel** [comment]
``` public static class ServiceCollectionExtensions
    {
        public static WorkflowOptions UseRabbitMQQ(this WorkflowOptions options, IConnectionFactory connectionFactory)
        {
            options.UseQueueProvider(sp => new RabbitMQProvider(connectionFactory));
            return options;
        }
    }```
I have added this class and also a **RabbitMQProvider**  to provide the own implementation in **QueueWork** and **DequeueWork**
```
public class RabbitMQProvider : IQueueProvider
    {
        private readonly IConnectionFactory _connectionFactory;
        private IConnection _connection = null;
        private static JsonSerializerSettings SerializerSettings = new Newtonsoft.Json.JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All };

        public bool IsDequeueBlocking => false;

        public RabbitMQProvider(IConnectionFactory connectionFactory)
        {
            _connectionFactory = connectionFactory;
        }

        public async Task QueueWork(string id, QueueType queue)
        {
            if (_connection == null)
                throw new InvalidOperationException("RabbitMQ provider not running");

            using (var channel = _connection.CreateModel())
            {
                channel.QueueDeclare(queue: GetQueueName(queue), durable: true, exclusive: false, autoDelete: false, arguments: null);
                var body = Encoding.UTF8.GetBytes(id);
                channel.BasicPublish(exchange: "", routingKey: GetQueueName(queue), basicProperties: null, body: body);
            }
        }

        public async Task<string> DequeueWork(QueueType queue, CancellationToken cancellationToken)
        {
            if (_connection == null)
                throw new InvalidOperationException("RabbitMQ provider not running");

            using (var channel = _connection.CreateModel())
            {
                channel.QueueDeclare(queue: GetQueueName(queue),
                                     durable: true,
                                     exclusive: false,
                                     autoDelete: false,
                                     arguments: null);

                channel.BasicQos(prefetchSize: 0, prefetchCount: 1, global: false);

                var msg = channel.BasicGet(GetQueueName(queue), false);
                if (msg != null)
                {
                    var data = Encoding.UTF8.GetString(msg.Body);
                    channel.BasicAck(msg.DeliveryTag, false);
                    return data;
                }
                return null;
            }
        }

        public void Dispose()
        {
            if (_connection != null)
            {
                if (_connection.IsOpen)
                    _connection.Close();
            }
        }

        public async Task Start()
        {
            _connection = _connectionFactory.CreateConnection();
        }

        public async Task Stop()
        {
            if (_connection != null)
            {
                _connection.Close();
                _connection = null;
            }
        }

        private string GetQueueName(QueueType queue)
        {
            switch (queue)
            {
                case QueueType.Workflow:
                    return "wfc.workflow_queue1";
                case QueueType.Event:
                    return "wfc.event_queue1";
                case QueueType.Index:
                    return "wfc.index_queue1";
            }
            return null;
        }

    }
``` 

now here how can i 
```
 using (var channel = connection.CreateModel())
                    {
                        channel.BasicQos(0, 1, false);
                        channel.QueueDeclare(queue, true, false, false, null);

                        var consumer = new EventingBasicConsumer(channel);

                        consumer.Received += (model, ea) => ProcessQueueMessageCore(ea, channel);

                        channel.BasicConsume(queue, false, consumer);
                        Thread.Sleep(Timeout.Infinite);
                    }
``` this implementation this above code is not pulling the messages from the queue.
When message is received in the queue ProcessQueueMessageCore this method is invoked automatically.

**Comment by Reena-Patel** [comment]
@danielgerlag Could you please help in this issue?

**Comment by Reena-Patel** [comment]
@danielgerlag If you could help with this. So that application performance could be improved.
