### ISSUE TITLE
Implementing Oracle Provider

### ISSUE THREAD

**Issue by pbros** [danielgerlag/workflow-core#422]
Hello,

I'm trying to implement an Oracle Persistence provider using Oracle.EntityFrameworkCore (https://www.nuget.org/packages/Oracle.EntityFrameworkCore).

I've based myself on the MySQL/MSSQL/Posgtre providers to create it, which was pretty straightforward.

I also duplicated the Integration tests, but for some reason the following 3 are failing (all others pass)

- EventScenario
- RetrySagaScenario
- WhileScenario

In tried to debug the EventScenario:

```csharp
public class EventWorkflow : IWorkflow<MyDataClass>
        {
            public string Id => "EventWorkflow";
            public int Version => 1;
            public void Build(IWorkflowBuilder<MyDataClass> builder)
            {
                builder
                    .StartWith(context => ExecutionResult.Next())
                    .WaitFor("MyEvent", data => data.StrValue1, data => DateTime.Now)
                        .Output(data => data.StrValue1, step => step.EventData)
                    .WaitFor("MyEvent2", data => data.StrValue2)
                        .Output(data => data.StrValue2, step => step.EventData);
            }
        }
```
```csharp
var eventKey = Guid.NewGuid().ToString();
var workflowId = StartWorkflow(new MyDataClass() { StrValue1 = eventKey, StrValue2 = eventKey });
WaitForEventSubscription("MyEvent", eventKey, TimeSpan.FromSeconds(30));
Host.PublishEvent("MyEvent", eventKey, "Pass1");
WaitForEventSubscription("MyEvent2", eventKey, TimeSpan.FromSeconds(30));
Host.PublishEvent("MyEvent2", eventKey, "Pass2");
```

The `WaitForEventSubscription` never succeeds in finding a subscription. The subscription does get created (it shows up in the database momentarily), but gets deleted right away in `SeedSubscription` by the call to `await _persistenceStore.TerminateSubscription(sub.Id);`

I'm not yet familiar enough with the Workflow-Core framework to understand this, but if anybody has any ideas what to look at or why this would be happening, it would be greatly appreciated.

**Comment by pbros** [comment]
After more digging, it seems like an EF issue.

The problem I am seeing is in the PersistWorkflow

```csharp
        public async Task PersistWorkflow(WorkflowInstance workflow)
        {
            using (var db = ConstructDbContext())
            {
                var uid = new Guid(workflow.Id);
                var existingEntity = await db.Set<PersistedWorkflow>()
                    .Where(x => x.InstanceId == uid)
                    .Include(wf => wf.ExecutionPointers)
                    .ThenInclude(ep => ep.ExtensionAttributes)
                    .Include(wf => wf.ExecutionPointers)
                    .AsTracking()
                    .FirstAsync();

                var persistable = workflow.ToPersistable(existingEntity);
                await db.SaveChangesAsync();
            }
        }
```

I get these errors, one after the other:

> Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> System.InvalidOperationException: The instance of entity type 'PersistedExecutionPointer' cannot be tracked because another instance with the key value '{PersistenceId: 1}' is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached.

>Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: Database operation expected to affect 1 row(s) but actually affected 2282 row(s). Data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

Note that in the `ConfigureExecutionPointerStorage` method in the `OracleContext : WorkflowDbContext`

I have set
```csharp
builder.Property(x => x.PersistenceId).UseOracleIdentityColumn();
```

**Comment by bobcat1506** [comment]
Did you get this working?  Will this be an officially supported persistence provider?

**Comment by dviry** [comment]
Is this going to be submitted as a PR? Would be good to have Oracle support baked in... ;)

**Comment by danielgerlag** [comment]
I don't have any plans to do so but a PR from the community would be welcome.

**Comment by dviry** [comment]
sure my comment was directed at @pbros if he would share his code...

**Comment by pbros** [comment]
We dropped this work and instead moved to PostgreSQL, as we had found that the support and updates for the Oracle EF package was a bit lacking. It might be more stable now, so we might look into it again in the future.
