### ISSUE TITLE
IDefinitionLoader Documentation

### ISSUE THREAD

**Issue by ClarenceR89** [danielgerlag/workflow-core#425]
In the docs at

`https://workflow-core.readthedocs.io/en/latest/json-yaml/`

you make reference to `IDefinitionLoader` and indicate that using should be `using WorkflowCore.Services.DefinitionStorage;`

this is incorrect as the interfaces are at `WorkflowCore.Interface`

Also typos in this doc:
`WorklfowCore.Primitives` should be `WorkflowCore.Primitives`
`using using WorkflowCore.Services.DefinitionStorage;` should be `using WorkflowCore.Interface;`

**Comment by OAlbrecht2407** [comment]
I've created a pull request for for the fix for this issue
