### ISSUE TITLE
Parallel paths with events do not complete

### ISSUE THREAD

**Issue by bobcat1506** [danielgerlag/workflow-core#428]
This sample approval workflow is waiting for either an approval or a denial event which will yield different outcomes.  Without a Join() I would expect the instance to complete and delete the other subscription, however, once one event is received the other event subscription is not canceled, and the workflow is still in status 0.  

        public void Build(IWorkflowBuilder<MyWfContext> builder)
        {
            builder
                .StartWith(context => ExecutionResult.Next())
                .Parallel()
                    .Do(then =>
                    {
                        then.StartWith(context => ExecutionResult.Next())
                            .WaitFor("Approved", context => context.SigningCeremonyId)
                            .Then<Step1>()
                                .Input(step => step.MyContext, data => data)
                            .Then<Step2>()
                                .Input(step => step.MyContext, data => data);
                    })
                    .Do(then =>
                    {
                        then.StartWith(context => ExecutionResult.Next())
                            .WaitFor("Denied", context => context.SigningCeremonyId)
                            .Then<SendDenialLetter>()
                                .Input(step => step.MyContext, data => data);
                    });
        }

**Comment by danielgerlag** [comment]
The `Join` event works the same as calling join on a collection of threads... it waits for all of them to complete.  You can pass a `CancenCondition` to the `WaitFor` with an expression that gets evaluated to determine if the `WaitFor` should be cancelled and execution on that path to continue.

**Comment by bobcat1506** [comment]
What code would I pass in the CancelCondition to check if an event has been received/consumed?  When is that cancel condition evaluated?  Also please note the sample provided is not using a Join()

**Comment by danielgerlag** [comment]
It's just a lambda with the workflow data as a parameter, and you return a `true`/`false`
