### ISSUE TITLE
How to get next steps in workflow

### ISSUE THREAD

**Issue by andresbetin** [danielgerlag/workflow-core#43]
Hi, i'm using workflow-core as my workflow engine, but i have a blocker: I don't know how to get the next steps of my current instance workflow. I want, from a running workflow, get the possible next steps, and choose one response action. I´m using waitFor, and i want, from a response, to choose which way to go
here is my code.
```c#

            builder
                .StartWith(context => ExecutionResult.Next())
                .WaitFor("event1", data => data.GUID)
                .Output(data => data.Object, step => step.EventData)
                .Then(context =>
                {
                    return ExecutionResult.Outcome((context.Workflow.Data as Data).Object as string);
                })
                .When(data => "yes").Do(then => then
                      .StartWith(context =>
                    {
                        Console.WriteLine("yes");
                        return ExecutionResult.Next();
                    }))
                .When(data => "no").Do(then => then
                      .StartWith(context =>
                      {
                          Console.WriteLine("no");
                          return ExecutionResult.Next();
                      })
                .Then(context =>
                {
                    Console.WriteLine("end");
                    return ExecutionResult.Next();
                });
```

**Comment by danielgerlag** [comment]
Hi,

You might be looking for this extension package

https://github.com/danielgerlag/workflow-core/tree/master/src/extensions/WorkflowCore.Users

Let me know if this doesn't solve your problem and I can look into refining the library to support your use case.

**Comment by andresbetin** [comment]
Hi, thank you for your reply, It is useful, but the method When() used in this case is obsolete, and the new When(), does not show the options list. I will wait the improvements for this extension package, because it's the only way so far that it has worked for me. 

![image](https://user-images.githubusercontent.com/5275430/27376918-20872042-5639-11e7-9200-3267155c6523.png)

**Comment by danielgerlag** [comment]
@andresbetin I have just released a new version... please let me know if this helps.
https://github.com/danielgerlag/workflow-core/tree/master/src/extensions/WorkflowCore.Users

**Comment by andresbetin** [comment]
Hi @danielgerlag Thank you, it works perfectly.

**Comment by danielgerlag** [comment]
You are most welcome, let me know if there is anything else I can help with... Don't forget to star the repo 😃
