### ISSUE TITLE
If in ForEach loop

### ISSUE THREAD

**Issue by pscheicher** [danielgerlag/workflow-core#431]
Hi,
is it possible to have an If statement inside a ForEach loop, where the condition is based on the context.Item.
I hope this example clarifies the problem:
```
builder.StartWith<GenerateObjectsStep>()
    .Output(data => data.GeneratedObjectsList, step => step.GeneratedObjectsList)
    .ForEach(data => data.GeneratedObjectsList)
       .Do(branch =>
           branch.StartWith<AnalyzeObject>()
                     .Input(step => step.GeneratedObject, (data, context) => context.Item)
                     .If(data => data.IsObjectPrintable).Do(then => then
                          .StartWith<PrintObject>()
                          .Input(step => step.GeneratedObject, (data, context) => context.Item)
                     )
            )
            .Then<SaveObject>();
       )
```
I would like to execute several steps (in this example only one) based on the objects generated during the workflow.

**Comment by danielgerlag** [comment]
The JSON / YAML definitions do currently support this, but the fluent API does not have it exposed.... this is something we could add.

**Comment by pscheicher** [comment]
Thank you for your feedback.
Addning this feature would be great. For now I check at the begin of each of those steps, if the condition is matched and abort the execution. I will have a look on the JSON definitions. But I would prefer using it in fluent API.

**Comment by ChrisBertrand** [comment]
Has this been added?

**Comment by IvanJosipovic** [comment]
@ChrisBertrand, no, I have a PR for it https://github.com/danielgerlag/workflow-core/pull/1095
