### ISSUE TITLE
Event that already been processed still gets fired

### ISSUE THREAD

**Issue by liyuqihxc** [danielgerlag/workflow-core#432]
This is the test repo:
[https://github.com/liyuqihxc/workflow-core-test](https://github.com/liyuqihxc/workflow-core-test)

In this workflow example
```csharp
builder.StartWith<CreateTestProduct>()
		.Output(data => data.CreationTime, step => step.CreationTime)
		.Output(data => data.Inventory, step => step.Inventory)
	.While(data => data.Inventory != 0)
	.Do(x => x.
		StartWith(_ => ExecutionResult.Next())
		.WaitFor(Consts.StartShippingEvent, (data, context) => context.Workflow.Id, data => data.CreationTime)
			.Output(data => data.ShippingAddress, step => step.EventData)
		.Then<ShipToCustomer>()
			.Input(step => step.Inventory, data => data.Inventory)
			.Output(data => data.Inventory, step => step.Inventory)
	);
```
I want to make sure all _StartShippingEvent_ that published after _CreationTime_ gets processed, so I passed _CreationTime_ to _WaitFor_ method. But after I published the event ,the _WaitFor_ gets triggered again and again, even though I only published the event once.

Is this a bug or intentional?

**Comment by liyuqihxc** [comment]
did some debug, in src\WorkflowCore\Services\BackgroundTasks\WorkflowConsumer.cs
```csharp
private async Task SubscribeEvent(EventSubscription subscription, IPersistenceProvider persistenceStore)
{
    //TODO: move to own class
    Logger.LogDebug("Subscribing to event {0} {1} for workflow {2} step {3}", subscription.EventName, subscription.EventKey, subscription.WorkflowId, subscription.StepId);
            
    await persistenceStore.CreateEventSubscription(subscription);
    var events = await persistenceStore.GetEvents(subscription.EventName, subscription.EventKey, subscription.SubscribeAsOf);
    foreach (var evt in events)
    {
        await persistenceStore.MarkEventUnprocessed(evt);
        await QueueProvider.QueueWork(evt, QueueType.Event);
    }
}
```
why mark all the these event unprocessed instead of just queuing the unprocessed and ignore the others?

**Comment by danielgerlag** [comment]
That's by design, because you are waiting for the exact same event name / key combo... you should use a different key for each iteration inside the loop... or keep incrementing the effective date, since you always pass the creation date to the wait for... it will pick up all events with that name + key that occurred after the date you pass.  A WaitFor does not "consume" an event.

**Comment by liyuqihxc** [comment]
@danielgerlag thanks for your answer.
