### ISSUE TITLE
Question: async tasks

### ISSUE THREAD

**Issue by hisubbotin** [danielgerlag/workflow-core#435]
Hi, we have async long running tasks (minutes or hours) in our workflow.
We need to start task and wait for the result.

Am i correct that we need to use [Event sample - .WaitFor()](https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample04) ?
Can it wait for high amount of tasks? 
For example, we run million workflows and all of them will be waiting...

**Comment by danielgerlag** [comment]
`WaitFor` is for waiting for external events that need to explicitly call back.
If you just need to execute long running tasks without a callback, yes you can... it uses TPL internally.
https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl

**Comment by hisubbotin** [comment]
TPL for waiting million tasks? :) it's restricted by thread pool size.

**Comment by danielgerlag** [comment]
No, it can have I/O completion ports / epoll / kqueue (depending on the OS) under the covers, and those threads can be reused while waiting for external I/O.  We also use [TPL Dataflow](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/dataflow-task-parallel-library) to control the number of concurrent workflows that can be running at a time, the rest are queued.

https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/QueueConsumer.cs#L14
