### ISSUE TITLE
Question: HA Setup - workflow versioning

### ISSUE THREAD

**Issue by hisubbotin** [danielgerlag/workflow-core#436]
Suggest that we have the workflow in [HA multinode setup](https://workflow-core.readthedocs.io/en/latest/multi-node-clusters/). 
Suggest that we have stable load on our service.
We want to update workflow and remove/add some steps. 
We can't update all nodes at the same time (rolling update). 

So both version of the workflow will be active at the same time? How it will be work?

**Comment by danielgerlag** [comment]
If workflows are started on the higher version, they will only execute on nodes that have that definition... provided you are incrementing the `Version` on the workflow definition.
