### ISSUE TITLE
Kindly provide an example of executing multiple workflows

### ISSUE THREAD

**Issue by SSanthosh-SBT** [danielgerlag/workflow-core#440]
I have multiple workflows defined in seperate json files with an incremented version number and i looped through each file and load the definition in the Configure method of the Startup class.But after executing some of the steps in each of the WORKFLOWS the execution stopped.How to make a jump to the next version after completing current version last step??

**Comment by danielgerlag** [comment]
A workflow will always execute against the version it was started with, so you need to keep the older versions around until all the workflows that started on that version have finished.
