### ISSUE TITLE
Question: AzureStorageQueueProvider.cs robustness

### ISSUE THREAD

**Issue by osi-oswald** [danielgerlag/workflow-core#447]
Hi, I have a question regarding AzureStorageQueueProvider's robustness, particularly the following lines of code:

```c#
public async Task<string> DequeueWork(QueueType queue, CancellationToken cancellationToken)
{
    CloudQueue cloudQueue = _queues[queue];

    if (cloudQueue == null)
        return null;
    
    var msg = await cloudQueue.GetMessageAsync();

    if (msg == null)
        return null;

    await cloudQueue.DeleteMessageAsync(msg);

    // What if the worker crashes here? Ex. power outage, hardware failure, etc.

    return msg.AsString;
}
```

What happens when the worker crashes after the line `await cloudQueue.DeleteMessageAsync(msg)`, does it mean the message will be lost (forever)?

**Comment by danielgerlag** [comment]
The [Runnable Poller](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/RunnablePoller.cs) will re-queue any outstanding work every 10 seconds, so in the case above, the lost message will be re-created after 10 seconds anyway.

**Comment by osi-oswald** [comment]
Thx a lot for your answer, good to know :-) workflow core looks very impressive btw! 🤠

**Comment by osi-oswald** [comment]
Thx a lot for your answer. I am currently evaluating Workflow Core, and I must say, I am impressed so far! Keep it up :-)

I had a couple of questions, but looks like I could answer them all by myself (you can of course still correct me if I was wrong in my own answers).

**Is there a dashboard or did somebody else already did one?**

> Not currently, but this is something I'd like to bundle as an add-on feature. If you are willing to contribute this feature, that would be lekker boet 😉

**When to increase the workflow version / What happens when increasing the workflow version?**

> If workflows are started on the higher version, they will only execute on nodes that have that definition... provided you are incrementing the Version on the workflow definition.

> A workflow will always execute against the version it was started with, so you need to keep the older versions around until all the workflows that started on that version have finished.

**Question regarding cost for polling Azure Storage Queues**

In QueueConsumer.cs DequeueWork function I can see, that if the message/queue is empty, it polls it again after Options.IdleTime (default 100ms). 

In the [Azure Storage Queue pricing](https://azure.microsoft.com/en-us/pricing/details/storage/queues/) I read that 10k operations cost $0.0004. 

This means that (just) the [polling will cost](https://www.wolframalpha.com/input/?i=%281+operation+%2F+100ms%29+*+%280.0004%24+%2F+10000+operation%29+in+s): $12.61 per year, which would be fine I guess ;-)
