### ISSUE TITLE
Does StopAsync wait for step to complete ?

### ISSUE THREAD

**Issue by ssougnez** [danielgerlag/workflow-core#448]
Hi,

I'd like to implement some kind of switch to prevent the workflow host from executing workflows. Basically, the idea is to stop it before an update of the application to avoid that a step is interrupted in the middle of it.

I saw that there is a Stop method on workflow host but I was wondering if this method waits for all the current steps to finish before completing ?

**Comment by danielgerlag** [comment]
Yes it does, see [here](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/WorkflowHost.cs#L111) and [here](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/QueueConsumer.cs#L48)

**Comment by ssougnez** [comment]
Awesome, as usual.

**Comment by ssougnez** [comment]
Hi, I'm coming back with this because I'm experiencing an issue.

I created a simple step that inherits from `StepBodyAsync` and I added the following line of code inside:

`await Task.Delay(60000);`

To simply wait 1 minute. 

Then, while it's waiting, I call a web API route that simply call the `Stop` method of `WorkflowHost` and this one returns instantly.

Isn't it supposed to wait for the delay to be passed before returning? More generally, isn't it supposed to wait for the StepBodyAsync task to complete before returning ?

The goal here is to be able to stop the workflow host before stopping the server to execute a deployment. Therefore, I want to be sure that no workflow step are in the middle of their execution when I stop the server.

**Comment by danielgerlag** [comment]
That's concerning. I will test this as soon as I can.

**Comment by danielgerlag** [comment]
Sorry about that... I have deployed a fix.
https://github.com/danielgerlag/workflow-core/commit/d75fc2c63c7248c7b63470e1955b13e494aed169

**Comment by ssougnez** [comment]
I guess that there is no way to have to fix included in a version of wfc compatible .NET Core 2.2 ?

I can't upgrade my .NET Core version to 3.0 right now but I would like to have this fix and since the last versions, I can upgrade wfc anymore in my 2.2 project :-(

**Comment by danielgerlag** [comment]
Workflow Core does not target .Net core 3.0.... It targets .NET Standard 2... which is implemented by .NET Core 2.  Are you having issues installing it?

**Comment by ssougnez** [comment]
Maybe I'm misinterpreting the error but when I try to update from v2.1.2 to 3.1.3:

> Version conflict detected for Microsoft.Extensions.Configuration.Abstractions. Install/reference Microsoft.Extensions.Configuration.Abstractions 3.1.0 directly to project SFPD.Workflows to resolve this issue. 
>  SFPD.Workflows -> WorkflowCore 3.1.3 -> Microsoft.Extensions.Hosting.Abstractions 3.1.0 -> Microsoft.Extensions.Configuration.Abstractions (>= 3.1.0) 
>  SFPD.Workflows -> Microsoft.AspNetCore.App 2.2.0 -> Microsoft.Extensions.Configuration.Abstractions (>= 2.2.0 && < 2.3.0).

Or maybe it's another package that create that conflict

**Comment by danielgerlag** [comment]
`Microsoft.Extensions.Configuration.Abstractions 3.1` also targets .NET Standard 2.0... I think you just need to update that library as well.

**Comment by ssougnez** [comment]
I tried something like that but the main issue is that `Microsoft.AspNetCore.App 2.2.0` only seems to support `Microsoft.Extensions.*` (>= 2.2.0 && < 2.3.0).

I could manually install all packages with the version 3.1, but then I'll get a lot of error like this one:

> NU1107	Version conflict detected for Microsoft.Extensions.Primitives. Install/reference Microsoft.Extensions.Primitives 3.1.1 directly to project WebApplication2 to resolve this issue. 
>  WebApplication2 -> Microsoft.Extensions.Configuration.Abstractions 3.1.1 -> Microsoft.Extensions.Primitives (>= 3.1.1) 
>  WebApplication2 -> Microsoft.AspNetCore.App 2.2.0 -> Microsoft.Extensions.Primitives (>= 2.2.0 && < 2.3.0).

And as my web application is pretty big, I cannot just ignore these messages and hope for the best.
However, it's not very clear to me, my project supports .net standard 2.0, these packages as well but I can't install them in a clean way...

**Comment by danielgerlag** [comment]
Try uninstalling all of them... and then reinstalling them one by one

**Comment by ssougnez** [comment]
Hehe, I wish I could.

The issue is that I didn't install them at all ;-)

The only one installed is "Microsoft.AspNetCore.App" and the version is enforced y the project itself. Because of

`<TargetFramework>netcoreapp2.2</TargetFramework>`

I guess.

**Comment by ssougnez** [comment]
Hi,

I tried to upgrade my project to .NET Core 3.1 but long story short, I can't right now because I'm using Oracle provider that does not support .NET Core 3.1 yet.

But the conclusion of this is that it seems that wfcore does actually not support .NET Core 2.x anymore. To check this, I created a simple web application with .NET Core 2.2 and tried to install wfcore on it and I simply can't because of the dependency to 3.1 DLL (Visual Studio won't let me). Indeed, .NET Core 2.2 limits the version of these DLL to 2.3.0 max.

Therefore, I guess you should scope wfcore to 3.1 or try to downgrade all 3.1 DLL that you're using with version compatible with .NET Core 2.2, but I guess that you're using them for a reason, so the former solution will probably be the best (unless I'm wrong with my analysis).

**Comment by danielgerlag** [comment]
That's not true, it absolutely does work on .net core 2.

**Comment by danielgerlag** [comment]
It's the aspnet meta package that is limiting the versions, not the framework version itself. Did you try a console app?

**Comment by ssougnez** [comment]
> That's not true, it absolutely does work on .net core 2.

It was not an accusation ;-)

I tried with a console app and it does work indeed.

So I guess the solution for an ASP.NET Core web app would be to remove the meta package and install the ones I need one by one ?

**Comment by danielgerlag** [comment]
That should work. We can also look into downgrading some of the dependencies within wfc, which should make it less paonful.

**Comment by ssougnez** [comment]
I tried to remove the meta package but then, as you can expect, there are a loooooooot of packages to install to be able to compile. Two weeks away from the release of my app, I'm a bit reluctant in doing so.

However, by curiosity, I downloadd the master branch of wfc as a zip, opened it with visual studio, change all the "3.1.0" to "2.2.0" in the main project and the SqlServer provider, tried to rebuild everything and it built without any issue.

As I suspect that I won't be the only one having this issue, maybe it's a better idea to downgrade the packages instead of asking everyone using wfc in a web app to remove the meta package and install all required packages one by one (even though they might be forced to do so with .NET Core 3.1).

Of course, that's your (awesome) product so, I leave the final word to you :-)

**Comment by danielgerlag** [comment]
If it works, I am in favor of depending of lower versions of those packages. Let me do some testing.

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/492

**Comment by ssougnez** [comment]
I'm in bed right now so I can't test but I checked you PR quickly and I think that you need to do it as well in the SQL server project where you use the 3.1.0 version of EFCore because the issue is the same with these DLL.

I tried it during my tests earlier and it seems not to cause any issue.

**Comment by danielgerlag** [comment]
I can't downgrade EFCore... I had a lot of requests to upgrade it to 3.

**Comment by ssougnez** [comment]
If I'm not mistaken, does it means that wfc is compatible 2.2 but the EFCore provider is not ?

Now, I don't necessarily want to update this package as long as wfc stays compatible with the version of the EFCore package compatible with 2.2.

Maybe it would make sense to maintain a 2.2 compatible version of this package to ensure that people in 2.2 can use wfc with sql server without issue.

In few hours, I will try to use the latest wfc version with the latest 2.2 compatible version of EFCore package and see what happens.

It would be a shame to be stuck with wfc 2 just because I'm using the SQL server provider :-)

**Comment by danielgerlag** [comment]
It's not that the new ef core is incompatible with .net core 2, it is compatible. It just references libraries outside what the aspnet meta package allows.
I will spend some time this weekend looking for a solution that makes everyone happy.

**Comment by ssougnez** [comment]
Just for information, I confirm that wfc 3.1.4 can now be used with a 2.2 .net core web app. (+1) 

However, as expected, it cannot use the EFCore provider 2.2.0 and as we already know, this provider is still not compatible with .net core app 2.2.

**Comment by danielgerlag** [comment]
It is fine with the `netcoreapp 2.2` framework... it's not fine with the`Microsoft.AspNetCore.App 2.2` package.

**Comment by danielgerlag** [comment]
I think we need to open an issue with the EFCore team or the aspnet core, to make the dependencies of each compatible.  I'm also seriously considering rewriting all the EF core based providers to not use EF core... I've been really unhappy with some of the decisions of that team.

**Comment by ssougnez** [comment]
Yeah this versioning system is not always very consistent...

Anyway, I guess I'll have to wait for Oracle to release a provider compatible with 3.1 to upgrade my whole app to .net core 3.1 and enjoy the new feature of wfcore ;-)

Thanks anyway, keep up the good work.

And just for information, I've been working since 14 months on an application to manage human resources in a federal institution. Everyone will be able to trigger workflow to declare a leave, an illness or personal data modification, etc... and everything articulates around workflow core. 

This product is going live next week and the expected load if around 2500 users.

I couldn't have done this app without the more-than-awesome library you wrote and for that, I really thank you. The library is simple, yet powerful and easy to use, you did an impressive job.

**Comment by danielgerlag** [comment]
@ssougnez thanks for sharing that... I love hearing how people are using the library to solve real world problems :)

**Comment by ssougnez** [comment]
Hi,

as Oracle **finally** released their provider for EF Core 3.1 (in beta but the RC should be released in few days), I could upgrade workflow core and recheck this and... it still not to be working.

I created a custom step where I put this:

`await Task.Delay(60000);`

Then, I start a workflow with this step and I call an API route that does this:

`await _wfHost.StopAsync(new CancellationToken());`

And this call resumes immediately, not waiting for the `Task.Delay` to finish.
Is it a normal behavior? I expected `StopAsync` to wait for the `Delay` to finish, otherwise, it means that `StopAsync` is not graceful.

Cheers
