### ISSUE TITLE
Feature request: Markup extension: Add support for more fields for a step

### ISSUE THREAD

**Issue by igor-betin** [danielgerlag/workflow-core#449]
Please some dictionary field (same way as currently with Name) that can be deserialized and used in WorkflowStep object.
Currently only Name can be passed this way

**Comment by danielgerlag** [comment]
That's what `Inputs` are for

**Comment by igor-betin** [comment]
Inputs are evaluated only before the execution.
When I build a workflow from code, I sometimes want to know what the last step was - and the StepBuilder (when building) or WorkflowStep<> itself (when built) do not have any info accessible from code.
As for input - it's a delegate that is impossible to parse

**Comment by danielgerlag** [comment]
Could you explain the actual use case behind this?

**Comment by igor-betin** [comment]
I am trying to implement a visual editor for a workflow, and your engine was chosen as implementation.
Some scenarios that I can't currently implement are:
1) If (failcondition on stepA) go to stepB - because I can't reuse steps and I have to use the fluent builder for every case. And with the fluent builder, if stepB is before stepA, then I have to use While, and if it's after stepA, then I have to use if
It would be great if I could just read through steps collection and add links (Outcomes) in a plain, POCO way, like stepA.next = stepB. Like with Camunda's ports.

And with the const inputs I could use them to store the metadata, that is currently completely missing from steps and can't be added in any way except the Name field

**Comment by igor-betin** [comment]
2. I want to wait for user input with some timeout. If timeout strikes, I want one branch of execution, if not - want to continue. It's a block in visual designer.
Currently I have to add a monstruction of Parallell -> 1) Wait for input, set success flag, 2) Timeout, set failure flag, then 3) Join and
4) If -> Check the failure/success flags (in workflow data, because 1 and 2 are different steps)

If I could first construct the steps and then connect them as needed, it would be much more transparent and easy to debug

**Comment by igor-betin** [comment]
Another thing - when a step fails, I want to know to which block it corresponded in my markup. Again, no way to assign a Tag or any other meta

**Comment by danielgerlag** [comment]
The input on a workflow definition will always be a delegate, unless you use the JSON or YAML DSL to define your workflow.  The delegate is essentially the compiled version... you can't decompile it.
I'm not sure why you'd want to try pass data on the name parameter... but you could use it as a reference to map an actual workflow instance to the definition... the input values should be available on the workflow instance.
Honestly, it I think you should be using the JSON or YAML DSL for the visual editor.
