### ISSUE TITLE
Feature request: Typed Input objects with meta (not just Action delegate)

### ISSUE THREAD

**Issue by igor-betin** [danielgerlag/workflow-core#450]
Please extend IStepParameter. Currently there is no way to parse parameters from code, they are delegates.

Something like ParameterType == Literal / DataExpression / CustomExpression would be nice, with Literal value available right away.

I can create a pull request for this.

The general problem is that this library is designed for defining workflows from code, not from json - you can't do much from code with a workflow that you loaded from a definition, it's all delegates.
IMHO workflows are most often used when built from a designer or loaded from a storage, not defined in code. And when loaded from definition, there's almost no access to contents of the workflow. The worst part is that a workflow can't be serialized back into JSON or YAML definition.

I created a step that loads another workflow by ID - that is, before execution - and currently I can't pass that ID in any way other than in Name field in json.

**Comment by danielgerlag** [comment]
I'm not sure I follow you... could you provide an example?

**Comment by igor-betin** [comment]
It's all about parsing the workflow tree from code
Currently I have StepBuilder.Step.Inputs, and I can't check the input's value from code - it's always an ugly delegate. If there was another level in DOM, for example
Input1 = { Source = Const, Value = 123},
Input2 = {Source = Delegate, Value = Explession<Func<whatever>>>}

**Comment by danielgerlag** [comment]
It sounds like you are trying to extract a value from the workflow definition... not an actual workflow instance.  This will always be a delegate because it is just the workflow definition.

**Comment by igor-betin** [comment]
Yes, trying to walk the definition as I construct it

**Comment by danielgerlag** [comment]
That doesn't make any sense, there will be no value on the definition.

**Comment by igor-betin** [comment]
The problem is, in definition there is no definition-time info for a block except Name.
Using Input for this makes little sense indeed, but there's nothing else to use for metadata

**Comment by danielgerlag** [comment]
I honestly still don't understand what you are trying to do
