### ISSUE TITLE
[Question] How to setup scoped dependencies before step execution

### ISSUE THREAD

**Issue by kewinbrand** [danielgerlag/workflow-core#452]
Hey,

I need to setup some custom scoped dependencies before every step. I looked around and looks like WorkflowExecutor calls step.BeforeExecute before calling body.RunAsync. Is it the preferred way to hook in and configure some scoped deps?

Thank you

**Comment by danielgerlag** [comment]
The intent of that method is to return a `ExecutionPipelineDirective` value.  Why do the dependencies need to be scoped?
