### ISSUE TITLE
Questions: Audit feature &  documentation around the columns/tables 

### ISSUE THREAD

**Issue by cyyeap** [danielgerlag/workflow-core#454]
Hi there,

We're still new to this library.  It looks really cool, and thanks for building it. 

We've got a couple of questions.

We have requirements for our workflow engines to track any data changed within the workflow, who and when the data was changed. Is it already available in Workflow-Core currently? If not, is it under radar to develop such feature? How would you approach this requirement so it'd integrate nciely with workflow-core?

We wonder what the purpose/use-case of these columns in [wfc].[ExecutionPointer]. 
- PersistenceData
- WorkflowId 
- Scope

Do you have a documentation around the columns/tables? 

Thanks!

**Comment by danielgerlag** [comment]
I would not recommend that you couple your app to the DB schema... it's an internal implementation detail and could change at any time.  You could hook into the life cycle events - https://github.com/danielgerlag/workflow-core/releases/tag/1.6.9
You could also use the [Elastic Search plugin](https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Providers.Elasticsearch) to do analytics against workflows.  Nobody should be able to directly modify the internal workflow data, that should be only controlled by mapping outputs of steps to your data object.
