### ISSUE TITLE
Dependency Injection doesn't work in my project

### ISSUE THREAD

**Issue by artoo80** [danielgerlag/workflow-core#455]
I'm trying to inject something in a step. I followed the guide and I declared as transient service the step and the service I want to inject. I have the result that the step is never loaded and never launched from the workflow without any trace of what it's wrong. Can I get a log somewhere where I can read what is exactly the problem?

**Comment by artoo80** [comment]
The real problem is that I use StructureMap. Is there any way to tell Workflowcore to use another IoC?

**Comment by danielgerlag** [comment]
Workflow Core does not use any specific IoC.  It relies on `Microsoft.DependencyInjection.Abstractions`... any IoC library that implements these abstractions can be used.

**Comment by digitalsigi** [comment]
I just had a similar problem. Look at the registrations for your dependency provider, may be AddTransient<class> helps ...
