### ISSUE TITLE
 WorkflowCore.Persistance.Sqlite is throwing exception

### ISSUE THREAD

**Issue by 13atec030** [danielgerlag/workflow-core#456]
Error Details: 
Format of the initialization string does not conform to specification starting at index 0.

I want to use "WorkflowCore.Persistance.Sqlite". I have added below plugins:

a.  WorkflowCore.Persistance.Sqlite (1.9.1)
b. WorkflowCore(2.1.2)

while starting workflow like:
Host = serviceProvider.GetService<IWorkflowHost>();
Host .RegisterWorkflow<LeaveRequestWorkflow, MyWorkflowData>();
Host .Start();
_workflowId = Host .StartWorkflow("LeaveRequest", new MyWorkflowData() { VM viewModel}).Result;

Host .StartWorkflow() throwing exception. Please suggest me what are all plugins I should use and compatible versions.

Thanks,

**Comment by danielgerlag** [comment]
What does your connection string look like?
