### ISSUE TITLE
Not able to resume the Workflow using Sqlite

### ISSUE THREAD

**Issue by gufran786** [danielgerlag/workflow-core#458]
Hello, 

I want to use WorkflowCore SQLite Persistence in my workflow, but I am facing below problems:

Source Code: 
public async static void RunWorkflow()
        {
                IServiceProvider serviceProvider = ConfigureServices();
                Host = serviceProvider.GetService<IWorkflowHost>();
                Host.RegisterWorkflow<HelloWorldWorkflow, WorkflowData>();
                Host.Start();                
                var x = await _globalHost.ResumeWorkflow("140b8887-17ff-4558-8a92-52f9a7cdb972");  
        }

 public static IServiceProvider ConfigureServices()
 {
            IServiceCollection services = new ServiceCollection();
            services.AddLogging();           
            services.AddWorkflow(x => x.UseSqlite($"Data Source={ GetDBPath() };", true));
            var serviceProvider = services.BuildServiceProvider();
            return serviceProvider;
  }
private static string GetDBPath()
        {
            var sqliteFilename = "database.db";
            string documentsPath = Environment.GetFolderPath(Environment.SpecialFolder.Personal);
            var path = Path.Combine(documentsPath, sqliteFilename);
            return path;
        }

when I am StartWorkflow using below method:
await Host.StartWorkflow("HelloWorld");
It is creating database.db file in the given path in my android application
But, When I try to Resume the Workflow l am facing below problems:

1.  When I, use like below : 
var x = await _globalHost.ResumeWorkflow("140b8887-17ff-4558-8a92-52f9a7cdb972");  
It returns false and workflow does not resume.

2. var x = await _globalHost.ResumeWorkflow("1");  
Here, 1 is workflowId from database.db file in Workflow table.
I am getting System.Format Exception: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)

What is the correct way of using WorkflowCore Persistence in Sqlite? 
I am developing Xamarin.Forms App.

I have installed below NuGet packages to my project:
WorkflowCore : 2.0.0
WorkflowCore.Persistence.Sqlite  1.9.1

Thanks,

**Comment by danielgerlag** [comment]
Where are you suspending the workflow?
Resume only works on workflows that are in suspended state.
