### ISSUE TITLE
Async support to StepBody.Run

### ISSUE THREAD

**Issue by melih154** [danielgerlag/workflow-core#46]
Hi Daniel,

Thanks for all the great work.

I am trying to implement steps with calls to async methods. Eg. HttpClient.GetAsync
Calling those methods on overridden StepBody.Run method generates an issue as the method requires to be marked as async. Currently achieving by defining async methods and calling the Result property of the result.

So, is it possible to run async methods inside StepBody.Run overridden method and wait for the result before evaluating the output/outcome or the next steps?

**Comment by danielgerlag** [comment]
Hi,

>So, is it possible to run async methods inside StepBody.Run overridden method and wait for the result before evaluating the output/outcome or the next steps?

This can currently be achieved with what you described above, using the .Result method of the async task... That said, I can also like at implementing an async version of the step body to facilitate first class support for async methods?

**Comment by melih154** [comment]
>  I can also like at implementing an async version of the step body to facilitate first class support for async methods?

That would be great. As more and more external component API/REST calls(Http, WebHdfs, etc...) supporting Async methods, consuming async methods within StepBody.Run natively would be great feature on this library.

Many thanks again.

**Comment by danielgerlag** [comment]
I have released 1.3.0, which introduces the `StepBodyAsync` abstract class, simply inherit from this instead of the `StepBody` class.  I also reworked the internals to make use of TPL.

**Comment by melih154** [comment]
Wonderful! Thanks for quick turnaround.
