### ISSUE TITLE
Terminate workflow when condition is true otherwise continue

### ISSUE THREAD

**Issue by muk-shobhit** [danielgerlag/workflow-core#463]
Hi @danielgerlag , 
Thanks for the wonderful library. I am having a case where I want to terminate the workflow based on a condition. I don't think any such feature is available at the moment. I end up with this-

```
stepBuilder
                .Then(ValidationStepBuilder<ValidateLogic>())
                .If(x => x.ValidationMessages.IsAny())
                .Do(then => then.StartWith<HandleValidation>()
                    .Then<WorkflowEndStep>().EndWorkflow()
                )
```
Kindly suggest, is this right way?

**Comment by danielgerlag** [comment]
That should work
