### ISSUE TITLE
How many threads can be created if 50 workflows running which has wait for step in the workflow?

### ISSUE THREAD

**Issue by Reena-Patel** [danielgerlag/workflow-core#464]
Hi Guys,

I just wanted to know at the same time how many threads will be created to execute the defined workflow at the same time if 50 workflows are running?
If we registered workflow host using RabbitMQ as Queue provider, Redis as Persistence provider then how many rabbitMQ and Redis connections will be created for the workflow host instance?

**Comment by danielgerlag** [comment]
The actual number of threads is managed by [TPL](https://docs.microsoft.com/en-us/dotnet/standard/parallel-programming/task-parallel-library-tpl).  The maximum number of concurrent workflows running on a single node is usually constrained to the processor count but can be set in the configuration. see https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Models/WorkflowOptions.cs#L19
