### ISSUE TITLE
Approval Workflow

### ISSUE THREAD

**Issue by rabazit** [danielgerlag/workflow-core#465]
Hello,
Could you please point me on how to create an approval workflow in asp.net core with a submission form for vacation request. How we can use a sequential aroval of the employee manager and director.

Thanks in advance for your support.

**Comment by avrail** [comment]
we need something like this also

**Comment by danielgerlag** [comment]
You can use the `Wait for external event` feature to pause a workflow until an approval is submitted, see https://workflow-core.readthedocs.io/en/latest/external-events/

**Comment by man75** [comment]
> You can use the `Wait for external event` feature to pause a workflow until an approval is submitted, see https://workflow-core.readthedocs.io/en/latest/external-events/

Can we combine "external event" with humanWorkflow to have an approval workflow?

**Comment by danielgerlag** [comment]
Have a look at the new activity workers feature
https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample18

**Comment by xuyae573** [comment]
I have question about the worker1, how to get this value @danielgerlag

**Comment by danielgerlag** [comment]
https://workflow-core.readthedocs.io/en/latest/activities/
