### ISSUE TITLE
Load WorkflowCore.Primitives.When from JSON 

### ISSUE THREAD

**Issue by viniciussandin** [danielgerlag/workflow-core#467]
Hi,

I would like to congratulate you on the excellent framework created. He is amazing, congratulations! Thank you for sharing with us.

I am trying to load a step from a JSON file, but it is not working.

Maybe you are doing something wrong or this feature has not been implemented yet, see:

![image](https://user-images.githubusercontent.com/3455138/70482354-02bbdd80-1ac4-11ea-8b7f-f107955712f5.png)

Apparently the children of this step type are not loaded because the following error is displayed on the console:

![image](https://user-images.githubusercontent.com/3455138/70482633-c0df6700-1ac4-11ea-9352-de7fab1ac03c.png)

See:

![image](https://user-images.githubusercontent.com/3455138/70482671-e1a7bc80-1ac4-11ea-9cee-e2862989ca72.png)

Am I doing something wrong? Could you help me?

Sorry for the english, I'm using a translator.

Thank you!

**Comment by danielgerlag** [comment]
Have a look at the new proposed `Decision` step, this may better solve your use case.
https://github.com/danielgerlag/workflow-core/pull/486
