### ISSUE TITLE
How to unit tests UserTask & is it possible to have multiple assigned principal? 

### ISSUE THREAD

**Issue by cyyeap** [danielgerlag/workflow-core#468]
Hi Daniel

We wonder how to properly test UserTask step? 

It seems like it's impossible to change AssignedPrincipal, we've got over 100 users that can approve/reject a workflow. Some workflows are not approve-able by certain users. How do we incorporate permission check within the workflow? 

Thanks
Choonyin

**Comment by danielgerlag** [comment]
The Users package was mostly intended as an example of how to write extensions for workflow core...
Perhaps have a look at the new activity workers feature, which should give you a lot more flexibility for these sorts of use cases 

* https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample18
* https://workflow-core.readthedocs.io/en/latest/activities/
