### ISSUE TITLE
Can't install WorkflowCore.Persistence.SqlServer NuGet package to .Net Core 3.1 with EF 3.1 application

### ISSUE THREAD

**Issue by iVova** [danielgerlag/workflow-core#469]
I have ASP.NET Core 3.1 application with EntityFramework 3.1.  [Example](https://github.com/iVova/WorkflowCore.Core31.EF31)

When I try to install **WorkflowCore.Persistence.SqlServer** NuGet package next error occurs:

`Detected package version outside of dependency constraint: WorkflowCore.Persistence.EntityFramework 2.1.2 requires Microsoft.EntityFrameworkCore (>= 2.1.0 && < 3.0.0) but version Microsoft.EntityFrameworkCore 3.1.0 was resolved.	Test.WorkflowCore.Core31.EF31	H:\Development\Projects\Test.WorkflowCore.Core31.EF31\Test.WorkflowCore.Core31.EF31\Test.WorkflowCore.Core31.EF31.csproj	`

Is there have possible use **WorkflowCore.Persistence.SqlServer** NuGet package with EF 3.1?

**Comment by danielgerlag** [comment]
- You can use .NET Core 3.1
- You can't use EF Core 3, because it breaks compatibility with .Net Standard 2, which is not supported by .NET Framework.
EF Core will release an LTS version that supports .Net Standard 2, we will then update the package,
https://github.com/danielgerlag/workflow-core/issues/413#issuecomment-559647200

**Comment by iVova** [comment]
1. Yes. I used .NET Core 3.1 (See above and example to test project by [this ](https://github.com/iVova/WorkflowCore.Core31.EF31)link )
2. I don't use EF Core 3.0 
3. EF Core 3.1 already released. See this link [Announcing Entity Framework Core 3.1 and Entity Framework 6.4](https://devblogs.microsoft.com/dotnet/announcing-entity-framework-core-3-1-and-entity-framework-6-4/) 


I have a problem with installation **WorkflowCore.Persistence.SqlServer NuGet package**  into the application with the latest EF 3.1 in .Net Core 3.1.

**Comment by danielgerlag** [comment]
yes, because the upper version compatibility limit with EF core is < 3

**Comment by iVova** [comment]
Is there have possible use of WorkflowCore.Persistence.SqlServer NuGet package with EF 3.1?
Do you have the plan to add supporting of the LTS version of .Net Core 3.1?

**Comment by iVova** [comment]
@danielgerlag Thank you very much for the latest version of [WorkflowCore.Persistence.SqlServer 2.2.0](https://www.nuget.org/packages/WorkflowCore.Persistence.SqlServer/2.2.0).

I am very happy. My problem with this version of the package is going out.

Great job!
