### ISSUE TITLE
Is it possible to create useroption along with event ?

### ISSUE THREAD

**Issue by Faizal-Majeed** [danielgerlag/workflow-core#472]
Hi ,
   My scope is I want to initiate the workflow and provide list of user options to the client. when publish the user action i want to pass a user data along with that. (similar to event publish). So I'm wondering if i can create a workflow with the combination of useroption and events. Please advice.

**Comment by danielgerlag** [comment]
The Users package was mostly intended as an example of how to write extensions for workflow core...
Perhaps have a look at the new activity workers feature, which should give you a lot more flexibility for these sorts of use cases 

* https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample18
* https://workflow-core.readthedocs.io/en/latest/activities/

**Comment by Faizal-Majeed** [comment]
So, Can I define/register multiple activity worker within that workflow
eg: 
builder
    .StartWith<HelloWorld>()
    .Activity("get-approval", (data) => data.Request)
        .Output(data => data.ApprovedBy, step => step.Result)
    .Then<ApproveRequest>()
        .Input(step => step.Message, data => "Approved by " + data.ApprovedBy)
    .Activity("reject-approval", (data) => data.Request)
        .Output(data => data.RejectedBy, step => step.Result)
    .Then<RejectRequest>()
        .Input(step => step.Message, data => "Rejectedby " + data.Rejectedby)
// Execute below steps after any one of activity worker is done
    .Then<LogComment>()
    .Then<LogHistory>();

or I have to register multiple activity worker using Parallel process ?

**Comment by danielgerlag** [comment]
You could do either, it depends on your use case...
Looking at your example above, I'm not sure I would use 2 distinct workers... 1 worker could provide both the reject and accept actions and the workflow can do something different based on the response coming back from from the external activity worker.

**Comment by Faizal-Majeed** [comment]
Activity worker feature didn't solve my use case.
So my UI will be driven by backend (workflow), In my application, when supervisor opens a user vacation detail, the UI will show list of actions driven by workflow and supervisor choose any action with additional input to trigger desired workflow.

**Comment by danielgerlag** [comment]
You'd need to store the list of actions in your own DB, and set them up via a custom step.
