### ISSUE TITLE
WaitFor event error - No coercion operator is defined between types 'Newtonsoft.Json.Linq.JObject' and 'System.String 

### ISSUE THREAD

**Issue by anavgale** [danielgerlag/workflow-core#476]
Hi,

I am trying to implement WaitFor  event in my workflow and getting following error -
No coercion operator is defined between types 'Newtonsoft.Json.Linq.JObject' and 'System.String

I am using .net core 3.1

`{
  "@t": "2019-12-16T16:55:16.7847339Z",
  "@m": "Workflow \"35e4a15b-1150-4b64-928d-351e6d8761f7\" raised error on step 1 Message: \"No coercion operator is defined between types 'Newtonsoft.Json.Linq.JObject' and 'System.String'.\"",
  "@i": "515f5336",
  "@l": "Error",
  "@x": "System.InvalidOperationException: No coercion operator is defined between types 'Newtonsoft.Json.Linq.JObject' and 'System.String'.\r\n   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)\r\n   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)\r\n   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type)\r\n   at WorkflowCore.Models.MemberMapParameter.Assign(Object sourceObject, LambdaExpression sourceExpr, Object targetObject, LambdaExpression targetExpr, IStepExecutionContext context)\r\n   at WorkflowCore.Models.MemberMapParameter.AssignOutput(Object data, IStepBody body, IStepExecutionContext context)\r\n   at WorkflowCore.Services.WorkflowExecutor.ExecuteStep(WorkflowInstance workflow, WorkflowStep step, ExecutionPointer pointer, WorkflowExecutorResult wfResult, WorkflowDefinition def)\r\n   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow)",
  "SourceContext": "WorkflowCore.Services.WorkflowExecutor"
}`

Any pointer will be highly appreciated.

Regards,
Ajay

**Comment by danielgerlag** [comment]
Can you provide a sample project that reproduces this?

**Comment by anavgale** [comment]
1. To reproduce, Run the attached solution.
[DTSFlowTest.zip](https://github.com/danielgerlag/workflow-core/files/4002014/DTSFlowTest.zip)

2. Call API to start the workflow - https://localhost:44328/workflows/EventSampleWorkflow/1 posting data - 
{
    "Value1": "Ajay"
}

this will start the working and will get the workflow id.

3. You can call the API - https://localhost:44328/workflows/{{workdflowId returned in previous step}}
to see the workflow is started.

4. Call the API to trigger the event which in turn displays the custom message.

https://localhost:44328/events/MyEvent/e33eb89c-085c-4c74-9234-7447d57d7df8  - the key I used is from the step 3 API where I can see the workflow steps and see the event key.

In the serilog file, I get the following log, and custome message does not get triggered.

2019-12-26 14:32:05.682 +05:30 [ERR] Workflow e33eb89c-085c-4c74-9234-7447d57d7df8 raised error on step 1 Message: No coercion operator is defined between types 'Newtonsoft.Json.Linq.JObject' and 'System.String'.
System.InvalidOperationException: No coercion operator is defined between types 'Newtonsoft.Json.Linq.JObject' and 'System.String'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at System.Linq.Expressions.Expression.Convert(Expression expression, Type type, MethodInfo method)
   at WorkflowCore.Models.MemberMapParameter.Assign(Object sourceObject, LambdaExpression sourceExpr, Object targetObject, LambdaExpression targetExpr, IStepExecutionContext context)
   at WorkflowCore.Models.MemberMapParameter.AssignOutput(Object data, IStepBody body, IStepExecutionContext context)
   at WorkflowCore.Services.WorkflowExecutor.ExecuteStep(WorkflowInstance workflow, WorkflowStep step, ExecutionPointer pointer, WorkflowExecutorResult wfResult, WorkflowDefinition def)
   at WorkflowCore.Services.WorkflowExecutor.Execute(WorkflowInstance workflow)

**Comment by anavgale** [comment]
Please ignore this error. After creating the entire solution from scratch, this issue vanished. Will continue exploring this today. Thank you for great library.
