### ISSUE TITLE
How to pass ClaimPrincipal and IFormFIle into PublishEvent

### ISSUE THREAD

**Issue by Faizal-Majeed** [danielgerlag/workflow-core#477]
I have a workflow that wait for event, So, user submit a form with attachment. I'm getting an error when object contains ClaimPrinicpal and Attachment. 

 var data = new WorkflowInitialData { User = User, Comment = input.Comment, WorkId = input.WorkId, Attachment = input.Attachment};
 _workflowHost.PublishEvent("Submit", "Key", data).Wait();

Any help please

**Comment by danielgerlag** [comment]
Anything you pass would need to be serializable.

**Comment by Faizal-Majeed** [comment]
Thanks @danielgerlag for your response. I made a workaround
