### ISSUE TITLE
Issue with Log Correlation Workflow Core in ASP.NET Core 3

### ISSUE THREAD

**Issue by ybritol** [danielgerlag/workflow-core#478]
I am using Workflow Core in a ASP.NET Core 3 WEB API. 
I have 3 ASP.NET Core 3 WEB API (Orchestrate, Validate, Process). The Orchestrate API calls the Validate API and then the Process API. 
I am using Serilog with Elasticsearch sink for logs. 

The issue I found is that the distribute tracing information used by .Net Core is gone when a workflow is executing and any call done to the down stream APIs (Validate, Process) lacks the necessary information that allows the logs correlation in .Net Core.

If I don't use Workflow Core and I call manually every single step in the workflow I am able to have proper log correlation (shown in Image 1).

![Image 1](https://user-images.githubusercontent.com/58995231/71035333-38c31800-20e9-11ea-9c96-552c092d2e89.png)

**Comment by danielgerlag** [comment]
The workflow steps are not executed in the same scope as the original call that starts the workflow.
They may even be executed on other machines, it's an async process.

**Comment by phillip-haydon** [comment]
@danielgerlag I think that's the point of the issue. Without the ability to define a scope prior to the instance executing, all valuable logging information is lost, and left up to us to begin scope in every step, which doesn't allow correlation with logs that happen in WorkflowCore. 

If there was a pre hook we could do something like:

```csharp
builder.ExecutionScope((id, data, logger) => {
    return logger.BeginScope("WorkflowId: {workflow_id}, Banana: {banana}", id, data.Banana);
});
```

(I'm terrible with naming)

Where `ExecutionScope` expects `IDisposable` to be returned. 

Then you can execute this before invoking the step, all our logging will be scoped to the execution of this instance, and any logging that WorkflowCore does internally will also be scoped to this instance.

Right now I have to do this by implementing BeginScope in every single step and if WorkflowCore logs anything, well I donno how it relates to my workflow being executed.
