### ISSUE TITLE
workflow-core is suitable for my business logic

### ISSUE THREAD

**Issue by namnik** [danielgerlag/workflow-core#483]
Hello;
one of my scenarios: 

1- 'Employment employee' flow; this flow has n steps. each steps goes to a cartable[dashboard]  according by access level and Organization chart. and maybe wait for a week or month to confirm or reject.

2- 'Apply for a loan' flow; similar above flow maybe takes days or weeks and even months to finishing the flow.

**Comment by danielgerlag** [comment]
Yes, you should be able to achieve that
