### ISSUE TITLE
Parallel mode: is support run more than one step in same time?

### ISSUE THREAD

**Issue by zhoubo56** [danielgerlag/workflow-core#487]
for now, parallel mode, will run step one by one via 'do' list items.
is possible run steps in same time?

thanks.

**Comment by danielgerlag** [comment]
That is by design. Since workflows are long running background processes, parallel in this context means that each parallel branch will not block another branch. So if you have a WaitFor or a Delay, etc... in one of the parallel branches, the others will still be free to execute.
