### ISSUE TITLE
Workflow registrations in multi-node setup

### ISSUE THREAD

**Issue by rashmy-git** [danielgerlag/workflow-core#488]
Hi,
I just started experimenting with the workflow-core library to setup a multi-node cluster on the cloud. Thank you for the great library.

A question on the behavior in multi-node setup. For my use case, I'm registering the workflow definitions dynamically. So the call to register the workflow goes to node where it gets registered and the workflow is started. It appears that the workflow definition registrations are only stored in-memory. So, when I start the workflow, the other nodes in the cluster are not able to pick up and execute the steps since they do not have the workflow registrations. Is there a way to store the workflow registrations in a common persistence like Redis, so that all nodes can lookup the registration from the same common registry?

Thanks!

**Comment by danielgerlag** [comment]
There is currently not a feature in workflow core to do that natively, however [Conductor](https://github.com/danielgerlag/conductor) which is a child project of workflow core and uses it internally builds that functionality on top.  It might make sense to build this in as a core feature but I don't have the bandwidth right now.

**Comment by danielgerlag** [comment]
This is the conductor implementation: https://github.com/danielgerlag/conductor/blob/master/src/Conductor.Domain/Services/RedisBackplane.cs

**Comment by rashmy-git** [comment]
Thank you for the reply.

Looking at the conductor implementation, it appears that there is provision to store the definitions in database and also push these definitions to all other nodes. There is also provision to load all definitions from the database during startup.

My requirement is slightly different. First is that the conductor is a separate server by itself and I want to embed workflow into my current server. Secondly, I have 100s of workflow definitions and not all of them will be executed each day. So my need is to load and register the definitions only on need basis. Is there a possibility to allow a delegation to fetch and load the registry if the workflow definition is not found. For example, every time a workflow step is executed, if there is a delegation provided to register the definition if not found it registry, it would be great. Is there any other mechanism you can suggest that I can implement to achieve my requirement?

Thanks for your support!

**Comment by danielgerlag** [comment]
You could create your own implementation of [IWorklfowRegistry](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Interface/IWorkflowRegistry.cs) which manages the workflow definitions, and then override the default implementation in the IoC container so that workflow-core uses yours instead of it's own.

**Comment by rashmy-git** [comment]
Thanks! Overriding the IWorkflowRegistry worked fine for my use case.

**Comment by rashmy-git** [comment]
Hi,
I've currently overridden the IWorkflowRegistry.GetDefinition to fetch the definition from DB. But GetDefinition() is not async and results in a blocking call. Do you suggestions to populate the registry on-demand? With a multi-node cluster a workflow can be registered and started in one node but can get picked up by another node for one of the step execution at which time the required workflow definition needs to be made available in the other node as well. For this purpose, the custom implementation of IWorkflowRegistry was done. But the blocking call is concerning since we can have many definitions that needs to get loaded dynamically.

Thanks
