### ISSUE TITLE
Seperating Workflow Host and API

### ISSUE THREAD

**Issue by melih154** [danielgerlag/workflow-core#49]
Hi Daniel,

Thinking of having a Workflow Host Farm with multiple Runnable Pollers, which does the hard work, and a single instance of API, which only accepts API calls - has not Runnable Pollers. 

Trying to achieve this via below 2 approach. Do you reckon any quick way to achieve that? 

1. API calls not blocked with Runnable Pollers retrieving steps from persistance storage and working on that. (Eg. Setting the Runnable Poller count to 0 on WorkflowOptions)

2. API does not need to be changed whenever a new workflow or step introduced. 

For (# 2)

Having a quick look on code found out that Post method on WorkflowsController on WorkflowCore.WebAPI project requires to make main 2 calls(Registry.GetDefinition and WorkflowHost.StartWofklow). Both requires WorkflowHost has the registry list populated with workflow and step definitions.

(# 2) may be an overkill, but interested in your thoughts regarding both.

**Comment by danielgerlag** [comment]
I think it would be a good idea to split the methods to start new workflows out of the `WorkflowHost` serivce... this would make it possible to to start new workflows from the API with needing a running host.  This would not be difficult to do, I will aim to release a new version next weekend

**Comment by danielgerlag** [comment]
Sorry for the delay... unfortunately I need to push this back a couple of weeks, will keep you posted

**Comment by danielgerlag** [comment]
@melih154 
https://github.com/danielgerlag/workflow-core/releases/tag/1.3.2
