### ISSUE TITLE
Allow to purge workflow registry

### ISSUE THREAD

**Issue by stackia** [danielgerlag/workflow-core#491]
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/WorkflowRegistry.cs#L13

It looks we can only add new ones to the registry, but cannot delete any existing ones. In the long-running scenarios where tons of workflow definitions are getting constantly added (mostly the definition will only use once), there is no way to purge the registry. That caused a memory leak.

So is it possible to add methods to delete existing definitions?

**Comment by danielgerlag** [comment]
Yes, we can add that

**Comment by sorengranfeldt** [comment]
It would be very beneficial if we could also query if a certian definition was already loaded. Or at least get a 'already exist' status back if loading a definition instead of a throw. Even a specific DefinitionAlreadyExistException would be great so you could catch that and move on...

**Comment by danielgerlag** [comment]
implemented by #504
