### ISSUE TITLE
ForEach from JSON - exception while converting a collection

### ISSUE THREAD

**Issue by wolgasster** [danielgerlag/workflow-core#494]
There is an issue when ForEach is loaded from JSON definition.
I'm getting the "Object must implement IConvertible" exception while converting a collection from the data class property to the `WorkflowCore.Primitives.ForEach.Collection` step property. The issue is that during Inputs conversion `DefinitionLoader.BuildScalarInputAction` is called and it uses `System.Convert.ChangeType(object value, Type conversionType)` method which requires a convertible object implements `IConvertible` type. However, `WorkflowCore.Primitives.ForEach.Collection` is of `IEnumerable` which does not implement `IConvertible`.

By the way, I don't see any DefinitionLoader's unit test in the WorkflowCore solution which covers exactly this scenario. It is used `stored-definition.json` asset but it contains not all possible step types.

See a project with an example in attachment [ForEachDefinitionLoader.zip](https://github.com/danielgerlag/workflow-core/files/4070472/ForEachDefinitionLoader.zip).

_Originally posted by @wolgasster in https://github.com/danielgerlag/workflow-core/issues/393#issuecomment-575075637_

**Comment by danielgerlag** [comment]
Thanks for pointing that out... Please try updating to `WorkflowCore.DSL 3.1.5` and let me know if that solves the problem?

**Comment by wolgasster** [comment]
Works as expected using `WorkflowCore.DSL 3.1.5`! Thank you for quick fix :)

**Comment by wolgasster** [comment]
I have 2 more questions out of scope of this issue:
  1. Are you still planning to implement any workflow designer to build definitions?
  2. Are you going to implement a purger for the Redis based persistence storage?

**Comment by danielgerlag** [comment]
Those items are not currently on my short term radar
