### ISSUE TITLE
MethodNotFound when using WorkflowTest.WaitForWorkflowToComplete 

### ISSUE THREAD

**Issue by glucaci** [danielgerlag/workflow-core#496]
After update to latest versions:
- WorkflowCore.Persistence.MongoDB - 3.0.2
- WorkflowCore.Testing - 2.2.0

I receive in my test when calling `WaitForWorkflowToComplete` the following exception:
```
System.MissingMethodException: 'Method not found: 
'System.Threading.Tasks.Task`1<WorkflowCore.Models.WorkflowInstance> 
WorkflowCore.Interface.IPersistenceProvider.GetWorkflowInstance(System.String)'.'
```

**Comment by danielgerlag** [comment]
Sorry I forgot to publish a new version of the testing package to nuget. Please update and try again.
