### ISSUE TITLE
[Question] Always Running Workflow

### ISSUE THREAD

**Issue by dsbegnoche** [danielgerlag/workflow-core#498]
I am wanting to have a workflow triggered from messages on RabbitMQ from another service.  I am not finding a good way to have a workflow basically always run, and then trigger when a message comes in.  Currently, calling `StartWorkflow()` whenever an event comes in, but this feels wrong.

I have also tried using `WaitFor()` and firing an event when a message comes into RMQ, however this only fires the one time, and I have not figured out how to make it continue to run.

Any guidance here would be greatly appreciated. I'd be happy to submit a PR for a sample if this is something that can be achieved.

**Comment by Luqswe** [comment]
The answer is in the [Wiki](https://github.com/danielgerlag/workflow-core/wiki/04.-Responding-to-external-events) regarding [Sample04](https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample04)

`public class EventSampleWorkflow : IWorkflow<MyDataClass>
{
    public void Build(IWorkflowBuilder<MyDataClass> builder)
    {
        builder
            .StartWith(context => ExecutionResult.Next())
            .WaitFor("MyEvent", data => "0")
                .Output(data => data.StrValue, step => step.EventData)
            .Then<CustomMessage>() 
                .Input(step => step.Message, data => "The data from the event is " + data.StrValue)
            .Then(context =>
            {
                Console.WriteLine("workflow complete");
                return ExecutionResult.Next();
            });
    }
}`

**Comment by Luqswe** [comment]
I haven't tested this and i just started using workflow-core. But would this work?:

```c#
 public class HelloWorldWorkFlow : IWorkflow
    {
        public string Id => "HelloWorld";

        public int Version => 1;

        public void Build(IWorkflowBuilder<object> builder)
        {
            builder
                .StartWith<HelloWorld>()
                .Recur(interval => TimeSpan.FromSeconds(0), until => false /*no stopping condition*/).Do(recur => recur
                    .StartWith(context => Console.WriteLine("Waiting for MyEvent"))
                        .WaitFor("MyEvent", key => "0")
                        .Output(data => data, step => step.EventData))
                .Then<GoodbyeWorld>();

        }
    }

    public class HelloWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("Hello world");
            return ExecutionResult.Next();
        }
    }

    public class GoodbyeWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("Goodbye world");
            return ExecutionResult.Next();
        }
    }
```

**Comment by danielgerlag** [comment]
Those should work... but I'm not sure a workflow that lives forever would be a good idea... what is the underlying use case.

**Comment by dsbegnoche** [comment]
Thank you for the idea @Luqswe. I was able to get that working in some sample code at least.  Now the question is if this is something that should be done at all. 

@danielgerlag We have several services that will have workflows configured to run when an action happens with them. We are using RMQ to send these actions out, and our workflow engine will trigger the workflows when needed.  Was trying to get this to just work with the existing core functionality, but it seems that an always running workflow could cause lots of performance issues?  Do you have any other ideas on how to achieve this outside of calling StartWorkflow() when needed?

**Comment by danielgerlag** [comment]
Why is calling `StartWorkflow()` feel wrong?  Is that not what it is technically doing?

**Comment by dsbegnoche** [comment]
You are right, that is the exact result we are looking for. I think the reason it felt incorrect was because we are having to manage the definition outside of workflow core to handle the start/stopping of workflows.  But after implementing and refactoring, I think this is the best way forward.  Thank you for this great product and your responses!
