### ISSUE TITLE
Deserialization issue with mongodb provider

### ISSUE THREAD

**Issue by maddymbm** [danielgerlag/workflow-core#499]
Hi Daniel, Thanks for this project, loved the design and how it is written.
Not sure if i'm doing anything wrong, but encountered this issue when using mongodb provider.
I'm using WaitFor and the webapi to listen to events. The eventdata being declared as object in eventcontroller is unable to deserialize while retrieving. it serialize as JObject in mongdb by default. 
But figured out that if you do 'SetSerializer' in  registerclassmap of event model it works.
Now it introduces another glitch where, when the event is  retrieved , the eventdata is deserialized as ExpandoObject . In that case i can't cast the eventdata to a  another type in the output step because it's not object to the type, it is trying to cast expandoobject to type.  i.e i can't do .Output(data => data.Input, step => step.EventData as EventInput) when eventdata is passed as object in the eventcontroller post method.
But found a solution to it too,  fix is to specify defined type in the post method instead of object.
i.e Post(string eventName, string eventKey, [FromBody]EventInput eventData).
I just want to understand if i'm not setting it up correctly or is this a right finding and the workaround i mentioned is the correct approach.
I was trying to use it out of the box without any changes.
Your feed back is much appreciated. 
Thanks again for workflow core , it perfectly fits my requirement. Please let me know if you need more details.

**Comment by danielgerlag** [comment]
If you cast the event type to a .net class, before calling publishEvent, the serialization should work... because it can store that object type name when it serializes it.

**Comment by maddymbm** [comment]
Thanks for the response! 
 i guess this needs to be done: 
var dataStr = JsonConvert.SerializeObject(eventData);
var dataObj = JsonConvert.DeserializeObject(dataStr, typeof(EventInput)); 
Because .net core already deserializes it to JObject.
But I believe it is as good as changing the parameter type in the action method or may be, create some kind of mapping between eventname and a type to cast...

I observed one more thing with .net core 3.1, Hope,  this will be helpful others!
 By default the new system.text.json serializer is used and it is will be serialized to Jsondocument(not NewstonSoft.JObject)  
To continue to use Newtonsoft , need  to add Microsoft.AspNetCore.Mvc.NewtonsoftJson package and do services.AddControllers().AddNewtonsoftJson(); in the startup
