### ISSUE TITLE
[Question] Coding up several WorkFlows and WaitAll for them to complete before .Stop()ing the (I)WorkflowHost 

### ISSUE THREAD

**Issue by granadacoder** [danielgerlag/workflow-core#501]
I LOVE the WorkFlowCore setup, with the Steps, etc, etc.

I am writing a console application that will run .. let's say once a day.
Think "in the cloud" where I want my app to run, do what it has to do and get out!  (so I don't pay Micro$oft Azure for just hanging out !)

I am having an issue getting all of my WorkFlows to execute before exiting the console (Command line) application.

Most of the samples have Console.Readline() that are "hanging out" until everything runs.
WorkflowCore.Sample01.csproj through WorkflowCore.Sample18.csproj is what I mean.

I've tried 2 different ways.  Tasks and the string of the generated startworkflow. (see my code below)

What is the best way to .. code up N number of Workflows, start them, and WaitAll them and then exit?

THANK YOU FOR THIS GREAT LIBRARY!

Below are my 2 attempts.  Change tryItWithTasks  to false to see the second way.

```

   public class PassingDataWorkflowOrchestrator //// : IPassingDataWorkflowOrchestrator
    {

        private readonly IWorkflowHost workflowHost;
        public OnBoardDomainWorkflowOrchestrator(IWorkflowHost workflowHost)
        {
            this.workflowHost = workflowHost ?? throw new ArgumentException("IWorkflowHost is null", (Exception)null);
        }

        public void ExecuteWorkFlow()
        {

            bool tryItWithTasks = true; /* flip this value to see my 2 different attempts */
            bool tryItWithWorkFlowIds = !tryItWithTasks;

            ICollection<Task<string>> allTasks = new List<Task<string>>();
            ICollection<string> workFlowGeneratedIds = new List<string>();
            int count = 0;

            try
            {

                this.workflowHost.RegisterWorkflow<PassingDataWorkflow, MyDataClass>();
                this.workflowHost.Start();

                for (int i = 1; i < 6; i++)
                {
                    MyDataClass currentMyDataClass = new MyDataClass();
                    currentOnBoardDomainPassThroughData.Value1 = i;

                    /*
                     * PassingDataWorkflow and MyDataClass are a mimic of Sample03 (below breadcrumbs)
                     * 
                     *     public class PassingDataWorkflow : IWorkflow<MyDataClass>
                     *           Public void Build(IWorkflowBuilder<MyDataClass> builder)
                     */

                    if (tryItWithTasks)
                    {
                        allTasks.Add(this.workflowHost.StartWorkflow("PassingDataWorkflow", 1, currentMyDataClass));
                    }

                    if (tryItWithWorkFlowIds)
                    {
                        workFlowGeneratedIds.Add(this.workflowHost.StartWorkflow("PassingDataWorkflow", 1, currentMyDataClass).Result);
                    }
                }


                if (tryItWithTasks)
                {
                    count = allTasks.Count();
                    allTasks.ToList().ForEach(t => t.Start());
                }

                if (tryItWithWorkFlowIds)
                {
                    count = workFlowGeneratedIds.Count();
                    workFlowGeneratedIds.ToList().ForEach(r => allTasks.Add(this.workflowHost.StartWorkflow(r)));
                    count = allTasks.Count();
                }


                Task<string>[] taskArray = allTasks.ToList().ToArray();
                Task.WaitAll(taskArray);

                //// Console.ReadLine(); /* do NOT want this line to exist !! */
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message); /* I keep getting here ! */
            }
            finally
            {
                Console.WriteLine(System.Environment.NewLine + "********   Next line is STOP     ********" + System.Environment.NewLine);
                this.workflowHost.Stop();
            }
        }
    }
```

**Comment by granadacoder** [comment]
So I saw an example in the Unit Tests.


```

namespace WorkflowCore.Testing
{
    public abstract class WorkflowTest<TWorkflow, TData> : IDisposable

        protected void WaitForWorkflowToComplete(string workflowId, TimeSpan timeOut)
        {
            var status = GetStatus(workflowId);
            var counter = 0;
            while ((status == WorkflowStatus.Runnable) && (counter < (timeOut.TotalMilliseconds / 100)))
            {
                Thread.Sleep(100);
                counter++;
                status = GetStatus(workflowId);
            }
        }
```

and I tried to mimic my "Orchestrator" 


    using WorkflowCore.Interface;

    public class PassingDataWorkflowOrchestrator //// : IPassingDataWorkflowOrchestrator
    {
        private readonly IWorkflowHost workflowHost;
        private readonly IPersistenceProvider persistenceProvider;

        public PassingDataWorkflowOrchestrator(IWorkflowHost workflowHost, IPersistenceProvider ipp)
        {
            this.workflowHost = workflowHost ?? throw new ArgumentException("IWorkflowHost is null", (Exception)null);
            this.persistenceProvider = ipp ?? throw new ArgumentException("IPersistenceProvider is null", (Exception)null);
        }

        public void ExecuteWorkFlow()
        {

            bool tryPp = true;

            ICollection<string> workFlowGeneratedIds = new List<string>();
            int count = 0;

            try
            {
                this.workflowHost.RegisterWorkflow<PassingDataWorkflow, OnBoardDomainPassThroughData>();
                this.workflowHost.Start();

                for (int i = 1; i < 6; i++)
                {
                    OnBoardDomainPassThroughData currentOnBoardDomainPassThroughData = new OnBoardDomainPassThroughData();
                    currentOnBoardDomainPassThroughData.OnBoardDomainPassThroughDataDomainName = "PassingDataWorkflowOrchestrator.Domain." + Convert.ToString(i);
                    currentOnBoardDomainPassThroughData.OnBoardDomainPassThroughDataOrdinal = i;

                    /*
                     * PassingDataWorkflow and MyDataClass are a mimic of Sample03 (below breadcrumbs)
                     * 
                     *     public class PassingDataWorkflow : IWorkflow<MyDataClass>
                     *           Public void Build(IWorkflowBuilder<MyDataClass> builder)
                     */

                    string wfid = this.workflowHost.StartWorkflow("PassingDataWorkflow", 1, , currentOnBoardDomainPassThroughData).Result;
                    workFlowGeneratedIds.Add(wfid);
                }



                if (tryPp)
                {
                    ICollection<WorkflowCore.Models.WorkflowStatus> allStatuses = new List<WorkflowCore.Models.WorkflowStatus>();

                    int maxLoopCount = 100; /* provide some high value .. just in case the issue of a (lacking) IoC definition that leaves the WorkflowStatus in a Runnable state */
                    int counter = 0;

                    bool keepLooping = true;
                    while (keepLooping && (counter++ < maxLoopCount))
                    {
                        foreach (string workflowId in workFlowGeneratedIds)
                        {
                            WorkflowCore.Models.WorkflowInstance instance = this.persistenceProvider.GetWorkflowInstance(workflowId).Result;
                            WorkflowCore.Models.WorkflowStatus stat = instance.Status;
                            allStatuses.Add(stat);
                        }

                        if (allStatuses.Any(x => x == WorkflowCore.Models.WorkflowStatus.Runnable))
                        {
                            keepLooping = true;
                            allStatuses.Clear();
                        }
                        else
                        {
                            keepLooping = false;
                        }

                        if (keepLooping)
                        {
                            Console.WriteLine("About to sleep in Loop. (counter={0}, maxLoopCount={1})", counter, maxLoopCount);
                            System.Threading.Thread.Sleep(1000);
                        }
                    }

                    if (counter > maxLoopCount)
                    {
                        Console.WriteLine("Counter Exceeded.  Maybe something wrong with IoC. (counter={0}, maxLoopCount={1})", counter, maxLoopCount);
                    }
                }

                string temp = string.Empty;
                if (temp.Length > 0)
                {
                }

                //// Console.ReadLine(); /* do NOT want this line to exist !! */
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message); /* I keep getting here ! */
            }
            finally
            {
                Console.WriteLine(System.Environment.NewLine + "********   Next line is STOP  Did everything complete?   ********" + System.Environment.NewLine);
                this.workflowHost.Stop();
            }
        }
    }



Is this a decent way of accomplishing a "do everything, then let get out" ?


Note that I originally added my "maxLoopCounter" because of the behavior I saw (and reported) here : https://github.com/danielgerlag/workflow-core/issues/503


Thanks for any hints.

**Comment by danielgerlag** [comment]
I think you may be looking for the sync runner: https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0

**Comment by granadacoder** [comment]
@danielgerlag 

Yes, this was it... Thanks!

For future readers, 

namespace WorkflowCore.Interface
{
    public interface ISyncWorkflowRunner
    {
        Task<WorkflowInstance> RunWorkflowSync<TData>(string workflowId, int version, TData data, string reference, TimeSpan timeOut, bool persistSate = true) where TData : new();
    }
}
