### ISSUE TITLE
 can we add an instance-unique identity Id to the workflow instance to let us track it

### ISSUE THREAD

**Issue by shao200** [danielgerlag/workflow-core#507]
In daily development, we often multi-instantiate a type of workflow, such as leave, reimbursement, etc., multiple people at the same time to start a type of workflow, but the current system, although you can create multiple workflow instances, but can not track specific workflow instances, resulting in a lot of extra things to achieve the goal. I'm thinking, can we add an instance-unique identity Id to the workflow instance to let us track it? This will work better.

**Comment by danielgerlag** [comment]
It returns a GUID when you start a workflow that you can use to track each instance... you can also specify your own reference string.
