### ISSUE TITLE
Add new workflow to host dynamicaly

### ISSUE THREAD

**Issue by mo-esmp** [danielgerlag/workflow-core#51]
Hi Daniel. suppose I have a "Workflows folder" that contains workflow classes and I add them to the host by reflection and after that host will run then I add new workflow to the workflows folder when host is running. I was wondering if it's possible add new workflow at run time without stopping host when it is running.

**Comment by kalokamgit** [comment]
Hi Daniel,

First of all thanks for providing Workflow-core.

I am also looking for same feature, dynamic workflow.

Is there anyway to save dynamic workflow definition directly to the entity store?

**Comment by danielgerlag** [comment]
Hi,

@mo-esmp  Sorry the the delayed response... So, you could dynamically load assemblies and register workflows within them with the workflow host running (no need to restart it)... one issue may be with dependency injection, if some of your steps don't have a parameterless constructor and rely on it's dependencies to be injected, there is currently no way to add them to the service provider IoC container after it is built.

@kalokamgit When I started this project, I had the intention to be able to save and load workflow definitions to some kind of external store, and I'm still planning on doing it - perhaps for version 2, so I can't promise a time frame to implement this, but probably in a few months.

**Comment by mo-esmp** [comment]
Thanks for your response and I would like to contribute on this case so let me know if I can help you.

**Comment by danielgerlag** [comment]
@mo-esmp sorry for the delayed response... I would love it if you could contribute, I'm currently focusing on another project for a few weeks... but I will write down my thoughts on this issue in a gist and send you the link in a few days?

**Comment by melih154** [comment]
@danielgerlag Can you please share the gist with me and/or community as well? Happy to have a look and possibly come up with a pull request.

Including 'Saving workflow definitions to external store' as well.

**Comment by danielgerlag** [comment]
@mo-esmp @melih154 
here are some points to consider regarding the 'Saving workflow definitions to external store' feature

https://gist.github.com/danielgerlag/dacde376969323b0d88578a541f4c83d

Please attach your thoughts as comments to the gist, it would be awesome if someone could pick this up. 😄

**Comment by mo-esmp** [comment]
thanks @danielgerlag , I will share my thoughts on this ASAP.

**Comment by danielgerlag** [comment]
released, please see https://github.com/danielgerlag/workflow-core/releases/tag/1.4.0
