### ISSUE TITLE
Re-trigger Failed Step

### ISSUE THREAD

**Issue by sivavaddadi** [danielgerlag/workflow-core#510]
Hi Daniel, 

Thank you for a great library

We are configuring workflow using a json file.
Requirement is, if any step in workflow fails, we need to allow user to manually retry the failed step at a later point in time. 
This logic should be common and not tied to a step, so we can re-trigger any failed step and continue from that point 
Is there a way to do that?

Thanks,
Siva

**Comment by danielgerlag** [comment]
You can specify that the workflow suspends on error... then you'd have to manually resume it to retry.
