### ISSUE TITLE
Add If step with id and name by builder 

### ISSUE THREAD

**Issue by MasallahOZEN** [danielgerlag/workflow-core#511]
Hi,
Thank you for any one who work in this great library.

I want to add if step by StepBuilder with step Id/Name, how can I do this ?

For now, changed source code with below.

IContainerStepBuilder<TData, If, If> If(Expression<Func<TData, bool>> condition, int? id = null, string name = null);

Thanks
Best Regards

**Comment by danielgerlag** [comment]
you can chain a .Name() after the .If
