### ISSUE TITLE
Multiple Execution Result Wait For Event

### ISSUE THREAD

**Issue by erdemkaya** [danielgerlag/workflow-core#512]
Hello Daniel,

I have a business step inherited from StepBody. I want to create multiple execution pointer as wait for event result. In this way I think be able to ensure for one step executes N times triggering by the events.

So, while the flow triggered for each waiting event at that step executes again until all waiting events completed.

Is there a way to do it with the existing functions provided by Workflow Core? Thanks in advance.

For example structure of business:

BusinessStep => First execution pointer
  -- Waiting Event1 for user1
  -- Waiting Event2 for user1
  -- Waiting Event1 for user2
  -- Waiting Event2 for user2

Publish Event1 for user2 =>

BusinessStep => Second execution pointer
  -- Waiting Event1 for user1
  -- Waiting Event2 for user2

Publish Event2 for user1 =>

BusinessStep => all executions completed. ExecutionResult.Next()

**Comment by danielgerlag** [comment]
Would the Parallel step work or this use case?
https://workflow-core.readthedocs.io/en/latest/control-structures/#parallel-paths

**Comment by erdemkaya** [comment]
Thank you for your response. I examined the parallel function then I solve my issue with below return value.

return new ExecutionResult
{
    BranchValues = new List<object>() { null },
    PersistenceData = new ControlPersistenceData { ChildrenActive = true }                    
};
