### ISSUE TITLE
Problem- Multiple Call If Condition

### ISSUE THREAD

**Issue by MasallahOZEN** [danielgerlag/workflow-core#513]
Hi, I have a problem with IF step. Why multiple execution for If Condition?

My expectation is that, once execution when if step works

![image](https://user-images.githubusercontent.com/811777/74260682-07db1a00-4d0b-11ea-8cee-3e1259f96319.png)

Help me please

**Comment by danielgerlag** [comment]
The evaluation of the condition will happen whenever the engine needs it... but the body of the IF will only run once.

**Comment by MasallahOZEN** [comment]
- Why not happen evaluation of the condition when After execution of previous step  and reach if step?

**Comment by danielgerlag** [comment]
It evaluates it whenever the workflow instance is re-hydrated from persisted storage and it's doing something with that particular step.
