### ISSUE TITLE
Foreach calling startworkflow (how can i wait workflow execute before calling it again in a foreach)

### ISSUE THREAD

**Issue by luizclucas** [danielgerlag/workflow-core#516]
i have something like this, where data is a list of any kind of object, i need to wait the workflow "AnyName" to finish before calling it again.

   foreach (var t in data)
            {
                await _workflowHost.StartWorkflow("AnyName", t);
            }

**Comment by danielgerlag** [comment]
Use the SyncWorkflowRunner - https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0

**Comment by luizclucas** [comment]
> Use the SyncWorkflowRunner - https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0

I Had already found it, worked, thank you!!!
