### ISSUE TITLE
QUESTION: CompensateWith with limited "Undo"s

### ISSUE THREAD

**Issue by granadacoder** [danielgerlag/workflow-core#518]
In the Compensating example.........

Is there any way to fluent code up the situation where:

if Task3 throws an exception, it will run UndoTask3 but not UndoTask2 and UndoTask1?

The unit test(s)  in "public class CompensationScenario" .. are fairly simple, and I cannot make out the functionality.

Thanks.

```
namespace WorkflowCore.Sample17
{
    class CompensatingWorkflow : IWorkflow
    {
        public string Id => "compensate-sample";
        public int Version => 1;

        public void Build(IWorkflowBuilder<object> builder)
        {
            builder
                .StartWith(context => Console.WriteLine("Begin"))
                .Saga(saga => saga
                    .StartWith<Task1>()
                        .CompensateWith<UndoTask1>()
                    .Then<Task2>()
                        .CompensateWith<UndoTask2>()
                    .Then<Task3>()
                        .CompensateWith<UndoTask3>()
                )
                    .OnError(Models.WorkflowErrorHandling.Retry, TimeSpan.FromSeconds(5))
                .Then(context => Console.WriteLine("End"));
        }
    }
}
```

**Comment by danielgerlag** [comment]
Don't wrap the entire thing in a saga, if your goal is to only undo the 1 task

**Comment by granadacoder** [comment]
Thanks.  For future readers, the "non-saga" hint works as I was hoping for.  I missed this (the sample above being in a saga) as I started going through the samples.

Thanks Daniel.
