### ISSUE TITLE
Document Approval Sample with GUI

### ISSUE THREAD

**Issue by weedkiller** [danielgerlag/workflow-core#52]
Hi very nice work, wondering if there is a Web GUI planned.

Also, would be nice to see a document approval sample.

thanks

**Comment by danielgerlag** [comment]
Hi,

The closest approximation to a document approval sample would be the Users extension package.

https://github.com/danielgerlag/workflow-core/tree/master/src/extensions/WorkflowCore.Users

I've always had the intention of creating a web admin UI.  Unless more people put up their hands to contribute, this will probably only happen next year :(

**Comment by weedkiller** [comment]
@danielgerlag thanks for the response... I firmly believe that this a feature, which will get a lot people actively involved.

Its also a huge missing gap in the ASP side of things... so it would provide a much needed feature.
