### ISSUE TITLE
Allow specify queues name

### ISSUE THREAD

**Issue by hofline** [danielgerlag/workflow-core#521]
https://github.com/danielgerlag/workflow-core/blob/5bf34b1a69d22056f5563e5884165f8a3106be32/src/providers/WorkflowCore.Providers.AWS/Services/SQSQueueProvider.cs#L57

Hello, please. Allow pass queue prefix/name as parameters.

Thanks.

**Comment by keelerm84** [comment]
@danielgerlag if you haven't started work on this, and think it would be appropriate, I'd be happy to try and submit my first PR to this project to address this.

Do you want anything more than an additional queue prefix parameter added to SQSQueueProvider, or 3 separate strings for maximum control?

**Comment by danielgerlag** [comment]
That would be amazing. I think just a prefix would make sense?

**Comment by hofline** [comment]
Prefix should be work for me. Thanks guys!!
