### ISSUE TITLE
About Worflow-Core JSON 

### ISSUE THREAD

**Issue by samchenws** [danielgerlag/workflow-core#532]
Hello,Could you please give me a complete process JSON format？I want to develop a visual process designer，But I don't know how to write IF in the process.Thank you very much.
![image](https://user-images.githubusercontent.com/37535153/75940301-9df7ff80-5ec7-11ea-8907-b5de56d9c273.png)

**Comment by danielgerlag** [comment]
https://workflow-core.readthedocs.io/en/latest/control-structures/#if-conditions

**Comment by samchenws** [comment]
Thanks for you,Daniel.

**Comment by BeiMeng** [comment]
@samchenws workflow-core 的流程设计器做出来没，开源不啊

**Comment by ShaoYir** [comment]
能否提供一个联系方式，一起交流下？
