### ISSUE TITLE
Stopping the Workflow Host

### ISSUE THREAD

**Issue by karl-diggle** [danielgerlag/workflow-core#533]
Hi I am working with workflow-core and one of the requirements is the ability to stop the workflow host and then on restart any in-flight workflows should just pick up from where they left off.  I am aware the persistence allows for this but one thing I noticed is I have to trigger a new workflow for any instances using that workflow to complete where it left.  Is there an easy way of identifying active instances so I know on startup of the service to register the inflight workflows.

TIA

**Comment by danielgerlag** [comment]
It should pick them up when you restart. Just give it a few seconds, it might be coincidence that you are starting a new workflow at the same time, as that would not have any effect.

**Comment by karl-diggle** [comment]
Thanks Daniel

Let me give that another go then – will let you know.

Appreciate your response on this.

Thanks
Karl
