### ISSUE TITLE
if then else

### ISSUE THREAD

**Issue by Balu2** [danielgerlag/workflow-core#537]
Hello Daniel

Then if then else implementation I used in past doesn't seem to work anymore with the new version of workflow core. This json definitions we used:
`{
    "Id": "1",
    "Version": "75",
    "DataType": "WorkflowEngineApplication.Models.WorkflowData, WorkflowEngineApplication",
    "Steps": [{
            "Id": "51",
            "StepType": "WorkflowCore.Primitives.If, WorkflowCore",
            "Inputs": {
                "Condition": "(data.Index>=30)"
            },
            "Outputs": {},
            "Do": [[{
                        "Id": "52",
                        "StepType": "WorkflowEngineApplication.Steps.EmailStep, WorkflowEngineApplication",
                        "Inputs": {
                            "EmailFrom": "\"info@test.nl\"",
                            "EmailTo": "\"test@test.nl\"",
                            "Subject": "\"< 30\"",
                            "Body": "\"test\""
                        },
                        "Outputs": {}
                    }
                ]]
        }, {
            "Id": "false_51",
            "StepType": "WorkflowCore.Primitives.If, WorkflowCore",
            "Inputs": {
                "Condition": "!((data.Index>=30))"
            },
            "Outputs": {},
            "Do": [[{
                        "Id": "59",
                        "StepType": "WorkflowEngineApplication.Steps.EmailStep, WorkflowEngineApplication",
                        "Inputs": {
                            "EmailFrom": "\"info@test.nl\"",
                            "EmailTo": "\"test@test.nl\"",
                            "Subject": "\"> 30\"",
                            "Body": "\"test false\""
                        },
                        "Outputs": {}
                    }
                ]]
        }
    ]
}
`
But the false step is never executed. We have no idea why. Any idea?

Kind regards
Luc

**Comment by Balu2** [comment]
We also tried to use the decide primitive:

`{
    "Id": "1",
    "Version": "74",
    "DataType": "WorkflowEngineApplication.Models.WorkflowData, WorkflowEngineApplication",
    "Steps": [{
            "Id": "51",
            "StepType": "WorkflowCore.Primitives.Decide, WorkflowCore",
            "SelectNextStep": {
                "Branch1": "(data.Index<30)",
                "Branch2": "(data.Index>30)"
            }
        }, {
            "Id": "Branch1",
            "StepType": "WorkflowEngineApplication.Steps.EmailStep, WorkflowEngineApplication",
            "Inputs": {
                "EmailFrom": "\"test@test.nl\"",
                "EmailTo": "\"info@test.nl\"",
                "Subject": "\"< 30\"",
                "Body": "\"\""
            },
            "Outputs": {}
        }, {
            "Id": "Branch2",
            "StepType": "WorkflowEngineApplication.Steps.EmailStep, WorkflowEngineApplication",
            "Inputs": {
                "EmailFrom": "\"test@test.nl\"",
                "EmailTo": "\"info@test.nl\"",
                "Subject": "\">30\"",
                "Body": "\"\""
            },
            "Outputs": {}
        }
    ]
}
`
But there only the second branch1 is executed although index < 30

**Comment by randomsolutionsgit** [comment]
I dropped the **"StepType":"WorkflowCore.Primitives.Decide, WorkflowCore"**, from the json definition and converted the data.index to Int32 as follows **Int32.Parse(data.Index) < 30** and it worked. i hope this helps.

**Comment by Balu2** [comment]
Thanks randomsolutionsgit, I will give it a try.
