### ISSUE TITLE
Execute workflow from within another workflow

### ISSUE THREAD

**Issue by StuartMeeks** [danielgerlag/workflow-core#540]
Is there a way to execute one workflow from another? I see the SubWorkflowStepBody is not implemented yet.

[SubWorkflowStepBody.cs](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Primitives/SubWorkflowStepBody.cs)

**Comment by gtejeda** [comment]
+1

**Comment by dekrevedko** [comment]
+1

**Comment by wangshuai-007** [comment]
you can start workflow in stepbody.
with [Dependency Injection](https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample15)
you can add this in step:
```c#
private readonly IWorkflowHost _host;
public override ExecutionResult Run(IStepExecutionContext context)
{
            _host.StartWorkflow("[WorkflowName]");
            //ExecutionResult.
            return ExecutionResult.Next();
}
```
