### ISSUE TITLE
Nuget Package for WorkflowCore.Providers.Azure

### ISSUE THREAD

**Issue by ahumeniy** [danielgerlag/workflow-core#548]
It seems the Nuget package for WorkflowCore.Providers.Azure is outdated, is it deprecated? The latest version available as a Nuget package is for version 2.0 of WorkflowCore. Should I use that version? The documentation mentions an Azure Service Bus integration but it's missing from the Nuget version. 

Any advice about how to proceed?

**Comment by danielgerlag** [comment]
The Azure package has a queue provider using storage queues, a lock provider using blob leases and life cycle event support using service bus.
