### ISSUE TITLE
Listning to Azure Servicebus Queue like Azure storage Queue

### ISSUE THREAD

**Issue by chandraarora** [danielgerlag/workflow-core#549]
Hello, 

Could workflow started over service bus queue? We like to trigger work flow over service bus queue , I  could not find such feature. 

Thanks 
Chandra

**Comment by danielgerlag** [comment]
Your service bus queue worker can call `StartWorkflow`

**Comment by levimatheri** [comment]
@danielgerlag could we add a Azure ServiceBus QueueProvider similar to the RabbitMQ? I am happy to submit a PR for that.
