### ISSUE TITLE
How to explicitly choose which step to run next

### ISSUE THREAD

**Issue by giangnt15** [danielgerlag/workflow-core#550]
Hi danielgerlag, thank you for your great work.

I am sorry for my bad english but I want to know if I can explicitly choose which step to run next from another step and how to do it.
 Thanks in advance.

**Comment by Viktor-36** [comment]
Hello,

You can do it in workflow definition. Just use `.Then<YourStep>()` if using fluent API or `"NextStepId": "YourStep"` if using JSON definition.

You can find more info at [https://workflow-core.readthedocs.io/en/latest/getting-started/#steps](url)

Or do you need explanation for some complex case?

**Comment by giangnt15** [comment]
Hello Viktor, thank you for your support, not extractly what I need but I figured it out
