### ISSUE TITLE
workflow steps in Pending state

### ISSUE THREAD

**Issue by chaitanya-pal** [danielgerlag/workflow-core#553]
Team it would be glad to use this workflow-core. its covering all most all of our business scenarios.
just wanted to know one observation. one day we have seen that most of the workflow instance steps are struck with pending status. once we restart the application again all steps are polling and remaining steps execution is completed. may i know in what scenario this will happen ?

**Comment by danielgerlag** [comment]
Would need more information here, sounds like you application was unresponsive.
