### ISSUE TITLE
resuming workflows

### ISSUE THREAD

**Issue by gtejeda** [danielgerlag/workflow-core#559]
Greetings,
I am playing with the samples, and I tried the following which I don't understand:

In Sample04
I modified the program.cs to this:
`IServiceProvider serviceProvider = ConfigureServices();

            //start the workflow host
            var host = serviceProvider.GetService<IWorkflowHost>();
            host.RegisterWorkflow<EventSampleWorkflow, MyDataClass>();
            host.Start();

            var initialData = new MyDataClass();
            var workflowId = host.StartWorkflow("EventSampleWorkflow", 1, initialData).Result;
            
            Console.WriteLine("Enter value to publish");
            string value = Console.ReadLine();
            host.PublishEvent("MyEvent", workflowId, value);

            Console.ReadLine();
                        
            host.ResumeWorkflow("EventSampleWorkflow");
            host.Stop();`

In EventSampleWorkflow.cs I modified it to this:
`public void Build(IWorkflowBuilder<MyDataClass> builder)
        {
            builder
                .StartWith(context => ExecutionResult.Next())
                .WaitFor("MyEvent", (data, context) => context.Workflow.Id, data => DateTime.Now)
                    .Output(data => data.Value1, step => step.EventData)
                .Then<CustomMessage>()
                    .Input(step => step.Message, data => "The data from the event is " + data.Value1)
                .Then<GoodbyeWorld>()
                .Then(context => Console.WriteLine("workflow complete"));
        }`

Added GoodbyeWorld.cs from Sample02 unchanged (other than the namespaces) to Sample04

However, The Goodbye step is never executed and the host ends
<img width="671" alt="event-not-runned" src="https://user-images.githubusercontent.com/199282/80719759-ef88c900-8ac9-11ea-9316-22a816e3b6b9.png">

Any clues??
thanks

**Comment by danielgerlag** [comment]
`ResumeWorkflow` is used on suspended workflows that were suspended using `SuspendWorkflow`
What were your expectations here?
