### ISSUE TITLE
Possibility to create workflow in runtime?

### ISSUE THREAD

**Issue by makhin** [danielgerlag/workflow-core#56]
Are there such possibility? For example if I have external file with described workflow how I can create workflow in runtime?

**Comment by danielgerlag** [comment]
Hi there,

At the moment, we do not have this feature but it is definitely in the pipeline for the next major version.  You are welcome to participate in it's development. 
/cc
@aaronscribner 
@mo-esmp
@melih154

**Comment by danielgerlag** [comment]
Just to give an update, I have been working on the feature to load workflow definitions from file, and I plan to release in the next week or two.  Find the draft release notes here:

https://github.com/danielgerlag/workflow-core/blob/def-loading/ReleaseNotes/1.4.0.md

**Comment by danielgerlag** [comment]
released, please see https://github.com/danielgerlag/workflow-core/releases/tag/1.4.0
