### ISSUE TITLE
How is Workflow restart handled?

### ISSUE THREAD

**Issue by digitalsigi** [danielgerlag/workflow-core#560]
Hi,
I am rather new to workflowcore and workflow applications in general.
I am working on an application which should execute log running SQL Procedures and send notifications to users.
I manged to create a workflow for that and we are now curious about how to handle recovery situations, e.g. system went down and application restarts. I was digging into docs but didn't find much about it. It sounds that workflowcore restarts the workflow. 
My questions:

- Is there somewhere more info about it? 
- Does it just start from last incomplete step?
- Is there anything which need to be taken into account?

**Comment by ekersale** [comment]
Does it just start from last incomplete step?
-> Yes

Is there anything which need to be taken into account?
-> Like you said if system go down and you have an incomplete step that has not been persisted workflowcore will replay it from scratch. So if you send notifications to users, it's possible that users will receive duplicates. 

Step outcome is persisted at the end of the step. So if you need to shutdown your application you better stop workflowcore properly by calling the Stop() method. It will wait for the current steps to be persisted.

**Comment by digitalsigi** [comment]
Thx a lot. Helped me to plan restart&recovery.
