### ISSUE TITLE
steps not executing

### ISSUE THREAD

**Issue by deRightDirection** [danielgerlag/workflow-core#566]
Hi Daniel,

i have read the documentation i think quit thoroughly but I cant figure out why my steps are not executing. So i will post my code here:

Workflow

            builder
                .StartWith<GetNewVerzoekBericht>().
                    Output(data => data.Bericht, step => step.Bericht).
                    Output(data => data.Repository, step => step.Repository)
                .If(data => data.Bericht != null).Do(then => then
                    .StartWith<CreateVerzoekBerichtWorkspace>().
                    Input(data => data.Bericht, step => step.Bericht).
                    Input(data => data.Repository, step => step.Repository);

GetNewVerzoekBericht:
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            var verzoekBerichtEntity = Repository.GetNewZoekBericht();
            if (verzoekBerichtEntity != null)
            {
                Bericht = verzoekBerichtEntity;
            }
            return ExecutionResult.Next();
        }

CreateVerzoekBerichtWorkspace:
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            // not implemented yet
            return ExecutionResult.Next();
        }

Workflow data
    class STAMWorkflowData
    {
        public VerzoekBericht Bericht { get; set; }
        public VerzoekBerichtRepository Repository { get; internal set; }
    }

What do i wrong? It only visits the first step.

**Comment by danielgerlag** [comment]
Sounds like `verzoekBerichtEntity` is `null`?
