### ISSUE TITLE
MySqlException 

### ISSUE THREAD

**Issue by 463728946** [danielgerlag/workflow-core#568]
Hello @danielgerlag 

Exception:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'COLUMN `ConcurrentFork` TO `RetryCount`' at line 1

MyCode:

 class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");
            IServiceCollection services = new ServiceCollection();
            services.AddLogging();
            services.AddWorkflow(x => x.UseMySQL(@"server=172.20.1.205;uid=root;pwd=xxx;Database=workflow", true, true));

            var serviceProvider = services.BuildServiceProvider();
            var host = serviceProvider.GetService<IWorkflowHost>();
            host.RegisterWorkflow<HelloWorldWorkflow>();
            host.Start();
            host.StartWorkflow("HelloWorld");
            Console.ReadKey();
            host.Stop();
        }
    }

    public class HelloWorldWorkflow : IWorkflow
    {
        public string Id => "HelloWorld";

        public int Version => 1;

        public void Build(IWorkflowBuilder<object> builder)
        {
            builder
                .StartWith<HelloWorld>()
                .Then<ActiveWorld>()
                .Then<GoodbyeWorld>();
        }
    }
    public class HelloWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("Hello World!");
            return ExecutionResult.Next();
        }
    }

    public class ActiveWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("I am activing in the World!");
            return ExecutionResult.Next();
        }
    }

    public class GoodbyeWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("Goodbye World!");
            return ExecutionResult.Next();
        }
    }

![image](https://user-images.githubusercontent.com/40827525/82189275-f7a37f80-98a3-11ea-8a3e-e4a7501a7ceb.png)

**Comment by 463728946** [comment]
fixed
services.AddWorkflow(x => x.UseMySQL(@"xxx;Database=workflow", true, false));

**Comment by chen281147271** [comment]
Has this problem been solved?
