### ISSUE TITLE
Web front-end to admin/monitor workflows

### ISSUE THREAD

**Issue by danielgerlag** [danielgerlag/workflow-core#57]
* Search & query status of workflows
* Suspend & resume
* Terminate

**Comment by Diaskhan** [comment]
For monitoring process, it must be persisted to database !

**Comment by linkev44** [comment]
Comme je l'ai dit dans https://github.com/danielgerlag/workflow-core/issues/65 .. je peux créer une application angular5 frontend pour gérer l'administration.
visualiser en fonction des applications référencées les différents états de workflows.
Designer les nouveaux workflows en fonction des fonctions disponible dans le backend.

**Comment by danielgerlag** [comment]
@linkev44 thanks for your interest in getting involved.
I currently have a branch [admin-console](https://github.com/danielgerlag/workflow-core/tree/admin-console), where I have just started looking at building an admin front end for managing a workflow server.  My plan is to use Angular 5 which will be transpiled and embedded into a .NET assembly, which can then be installed via NuGet and hosted in any ASP.NET Core application.  I have just started and only created a scaffold in `src/admin-console`

I think a workflow designer front end should be a separate project though... which one interests you the most?

I will also need to do some work on the API project to enable this.

**Comment by linkev44** [comment]
Hi,

I will discuss with my dev team about this tomorrow and I will come back to
you.

Thanks for your reply

**Comment by linkev44** [comment]
Hi daniel,

I will continue to work with my team around workflow-core and Dynamic
creation by JSON ..
When i will be most skilled about that ... i will come back to you for
speak about our participation.
I need to prove the interest at my customers .. and it's not very easy :)

I just have a question about dynamic step "WaitFor' .. i try to bind the
input event value to my data property .. that's not work :

 {
      "Id": "WaitProposition",
      "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
      "NextStepId": "CreateDraft2",
      "Inputs": {
        "EventName": "\"ReceiveProposition\"",
        "EventKey": "\"ReceivePropositionKey\"",
        "EffectiveDate": "DateTime.Now"
      },
      "Outputs": {
        "EventDerogationValue": "step.EventData"
      }
    },

Can you help me about this ?

Thanks a lot for your work

Have a nice day



*Kevin MICHAUT*

*Expertise & Développement *
*Web Full Stack *

06.81.63.76.84







2017-12-26 18:30 GMT+01:00 Kevin Michaut <kevin.michaut44@gmail.com>:

> Hi,
>
> I will discuss with my dev team about this tomorrow and I will come back
> to you.
>
> Thanks for your reply
>

**Comment by linkev44** [comment]
Just a type conversion ... that's work .. sorry :)


*Kevin MICHAUT*

*Expertise & Développement *
*Web Full Stack *

06.81.63.76.84







2017-12-27 16:37 GMT+01:00 Kevin Michaut <kevin.michaut44@gmail.com>:

> Hi daniel,
>
> I will continue to work with my team around workflow-core and Dynamic
> creation by JSON ..
> When i will be most skilled about that ... i will come back to you for
> speak about our participation.
> I need to prove the interest at my customers .. and it's not very easy :)
>
> I just have a question about dynamic step "WaitFor' .. i try to bind the
> input event value to my data property .. that's not work :
>
>  {
>       "Id": "WaitProposition",
>       "StepType": "WorkflowCore.Primitives.WaitFor, WorkflowCore",
>       "NextStepId": "CreateDraft2",
>       "Inputs": {
>         "EventName": "\"ReceiveProposition\"",
>         "EventKey": "\"ReceivePropositionKey\"",
>         "EffectiveDate": "DateTime.Now"
>       },
>       "Outputs": {
>         "EventDerogationValue": "step.EventData"
>       }
>     },
>
> Can you help me about this ?
>
> Thanks a lot for your work
>
> Have a nice day
>
>
>
> *Kevin MICHAUT*
>
> *Expertise & Développement *
> *Web Full Stack *
>
> 06.81.63.76.84
>
>
>
>
>
>
>
> 2017-12-26 18:30 GMT+01:00 Kevin Michaut <kevin.michaut44@gmail.com>:
>
>> Hi,
>>
>> I will discuss with my dev team about this tomorrow and I will come back
>> to you.
>>
>> Thanks for your reply
>>

**Comment by Diaskhan** [comment]
First for all to make gui work, we must implement rest api.
After all we could do js client! 
**I could create spa client on vuejs, its very simple !**

**Comment by biapar** [comment]
How Can I help to build it?

**Comment by danielgerlag** [comment]
@biapar thanks for the offer... I started a branch for this a few months ago, but unfortunately I have not had much time to work on it since.  If you want to take a look at the branch it is here: https://github.com/danielgerlag/workflow-core/tree/admin-console

**Comment by weedkiller** [comment]
Here is an open [source sample](http://bit.ly/2MwI7Wk)  &  the [workflow objects](http://bit.ly/2tJAWSX), the issue there is that the maintainer does a bait and switch where you have to pay $$$

**Comment by biapar** [comment]
Better vue.js than jquery or angularjs.

**Comment by biapar** [comment]
My result of searching:

https://github.com/gwenaelp/vue-diagrams
https://github.com/projectstorm/react-diagrams
https://github.com/bpmn-io/diagram-js
https://www.graphdracula.net

This are a good examples on translating words into a diagram: https://github.com/bramp/js-sequence-diagrams and https://flowchart.js.org. 

This one to try to understand its functions https://github.com/clientIO/joint

**Comment by Diaskhan** [comment]
@biapar  its very hard to decide, which library cover all our needs ! 
For good understanding the creator of this workflow library must write some kind Business Requrments !

**Comment by weedkiller** [comment]
@biapar I agree, that way we can use in any app, like ASP MVC

**Comment by weedkiller** [comment]
for starter's RDBMS would be easy, we can port over after we have some place to store this like SqlExpress./Sql Server

**Comment by danielgerlag** [comment]
The `IPersistenceProvider` interface abstracts the underlying datastore from any internal consumer
