### ISSUE TITLE
workflowhost.GetOpenUserActions(...) returns empty array

### ISSUE THREAD

**Issue by Faizal-Majeed** [danielgerlag/workflow-core#577]
I'm using userflow interaction workflow. After starting the workflow I called the GetOpenUserActions, it is returning the empty array. Looks like workflowCore is taking time to create useroption.
```
{
    var workflowId = await _workflowHost.StartWorkflow("Test", 1, workflowData);
    actions = (List<OpenUserAction>) _workflowHost.GetOpenUserActions(workflowId);
}
```
If i added thread sleep for 500 or 1000, i get actions, Is there any way other than this. I dont want to hold the thread

**Comment by danielgerlag** [comment]
The workflows execute asynchronously... so, the user options will only appear when the workflow reaches that point,.
