### ISSUE TITLE
Nothing To Search For UseElasticsearch 

### ISSUE THREAD

**Issue by 463728946** [danielgerlag/workflow-core#579]
`services.AddWorkflow(cfg =>`
`    cfg.UseMySQL(conn, true, false);`
`    cfg.UseElasticsearch(new Nest.ConnectionSettings(new Uri("http://localhost:9200")), "index_name");`
`});`
`services.AddWorkflowDSL();`

`var result = await SearchIndex.Search("", 0, 10, StatusFilter.Equals(WorkflowStatus.Complete));`

I find `IndexWorkflow` In your `IntegrationTests`,Did I miss this step? If so, how can I get all the workflowinstances

**Comment by danielgerlag** [comment]
Do you have any workflows in complete status?
