### ISSUE TITLE
Workflow example for .net framework 4.52

### ISSUE THREAD

**Issue by SigiFromMettler** [danielgerlag/workflow-core#58]
Is it possible to get an example for a "classic" .net framework implementation?

Best regards
Sigi

**Comment by danielgerlag** [comment]
Hi,

To use the latest version, you will need at least .NET 4.6.
You could use `WorkflowCore 1.2.7`, that was the last version to support .NET 4.5.2

Kind regards,
Daniel

**Comment by SigiFromMettler** [comment]
Hi Daniel 
Thanks for the answer.

With .net61, I get following message
Error	CS0103	The name 'TypeExtensions' does not exist in the current context	WorkflowCore(net461)

Question: How is it possible to create a running workflow core 1.3.2 for the .net framework without major changes?
Best regards,
Sigi

**Comment by danielgerlag** [comment]
Could you share a project that can replicate this problem?

**Comment by SigiFromMettler** [comment]
Hi Daniel

The only thing you have to do is the following change in the workflow core project file
    <TargetFrameworks>netstandard1.3;net461</TargetFrameworks>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>

This is a modified version from the 1.2.7 workflow core

PS: Is it possible to get a .net framework example (e.g. sample 6)?


Best regards
Sigi

**Comment by SigiFromMettler** [comment]
Hi Daniel
The only thing you have to do is the following change in the workflow core project file

 `    <TargetFrameworks>netstandard1.3;net461</TargetFrameworks>

 <ItemGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <Reference Include="System" />
    <Reference Include="Microsoft.CSharp" />
  </ItemGroup>
`
This is a modified version from the 1.2.7 workflow core

PS: Is it possible to get a .net framework example (e.g. sample 6)?

Best regards
 Sigi

**Comment by SigiFromMettler** [comment]
Hi Daniel
Thanks for the answer.
I'm not able to generate a sample under .net framework. it's a pity but I have to implement a workflow engine under .net framework. I'll try another engine.
PS: I know this Microsoft page. This is theory
https://www.youtube.com/watch?v=qc2WFaMfdp8
Best regards
Sigi

**Comment by danielgerlag** [comment]
What version of visual studio are you running?

**Comment by SigiFromMettler** [comment]
For this case VS2017 normaly VS2015

Best regards,
Sigi

**Comment by danielgerlag** [comment]
Which update of VS2017 have you installed?

**Comment by SigiFromMettler** [comment]
I've installed the VS 2017community edition for this test. Normaly, we use VS2015 professional in our company.
Why?
Best regards, 
Sigi

**Comment by danielgerlag** [comment]
If you click `Help` -> `About`, what is the version number?
eg. `15.3.0`?

**Comment by SigiFromMettler** [comment]
Hmm, sorry but I'm at home now. I'm not sure but I've installed the software two weeks ago. 
Let me check the version at monday.
But what could possibly be the problem?
Best regards
Sigi

**Comment by danielgerlag** [comment]
Here is a working .NET 4.6.1 project

[ConsoleApp38.zip](https://github.com/danielgerlag/workflow-core/files/1345879/ConsoleApp38.zip)

**Comment by SigiFromMettler** [comment]
Hi Daniel
Thank you very much. 
Best regards
Sigi
