### ISSUE TITLE
WorkflowCompleted event is never published

### ISSUE THREAD

**Issue by smeile** [danielgerlag/workflow-core#580]
Hello @danielgerlag 

I would like to send an event to another service of mine whenever the workflow has completed. I tried using the lifecycle events. There I get WorkflowStarted, StepStarted, StepCompleted but never WorkflowCompleted.
Is this a bug or do I have to configure something? 
I am using the newest version (3.1.5) of WorkflowCore.

Thanks in advance for your help.

**Comment by danielgerlag** [comment]
If you're getting the other events, it should work. Can you confirm your workflow status is complete?
Otherwise, could you attach a project that replicates the issue or write a failing test?

**Comment by smeile** [comment]
Yes, the workflow status has the value 2 in the database. 
Also, I have a pretty simple workflow which looks like the following:
            builder
                .StartWith<Step1>()
                .Then<Step2>()
                .Then<Step3>()
                .Then<Step4>()
                .Then<Step5>()
                .Then<Step6>()
                .EndWorkflow();

What seems a bit strange to me is that there seems to be an additional step which is active even though the workflow is completed. It has value NULL for the following fields which otherwise have values: StartTime, EndTime, and StepName (!).

![image](https://user-images.githubusercontent.com/14358345/85266386-13d2a780-b474-11ea-9c2c-5cf98515fae3.png)
