### ISSUE TITLE
Get all running workflow instances not available?

### ISSUE THREAD

**Issue by markus-codechefs** [danielgerlag/workflow-core#585]
Would you be open to this new functionality? If yes I would see what it would take to implement it. We want to use Workflow.Core with OrchardCore CMS. But would love to have an overview of all the open instances.

Or do you have another way to get this data?

We know there is this:
[Obsolete]
Task<IEnumerable> GetWorkflowInstances(WorkflowStatus? status, string type, DateTime? createdFrom, DateTime? createdTo, int skip, int take);

but its obsolete.

**Comment by danielgerlag** [comment]
The issue is that not all databases support this kind of query, we could make it available for those that do, but I think the persistence provider should be an internal concern, so we should surface it via a more 'official ' API.

**Comment by markus-codechefs** [comment]
Thanks for the explanation. So the expectation is that the consumers of the library have to handle the workflow instance persistence themselves? Or tap into the persistence provider that we chose ourselves and get the data through that?

**Comment by markus-codechefs** [comment]
We circumvented the issue by tracking the workflows in our own table. Its not pretty but gets the jobs done.
