### ISSUE TITLE
Can a prefix be supplied to RedisLockProvider?

### ISSUE THREAD

**Issue by aparasur-github** [danielgerlag/workflow-core#586]
Hi,
We have 'workflow-core' set up to use Redis for queuing/locking and Mongo for persistence. Our Redis instance is shared with multiple services.  
When we list the keys in Redis, we see entries like this - "redlock:<id>". It appears that the RedisLockProvider uses the workflow ID when acquiring the lock in a multi-node setup.
Is it possible to provide a prefix to "RedisLockProvider" similar to how we provide one for "RedisQueueProvider", so that the lock keys will be scoped to a particular service e.g. "redlock:<service_prefix>-<id>"?
Thanks.

**Comment by danielgerlag** [comment]
That should be pretty easy to implement

**Comment by aparasur-github** [comment]
Can I expect this capability sometime soon? Just trying to understand the timeline so that I can figure out my infrastructure accordingly.
Thanks.

**Comment by danielgerlag** [comment]
I don't have plans to implement it myself, but if you'd like to submit a PR I could merge and deploy it.

**Comment by aparasur-github** [comment]
Okay, thank you. I will get back to you on this. Closing this issue for now.
