### ISSUE TITLE
Task synchronous option?

### ISSUE THREAD

**Issue by weare8** [danielgerlag/workflow-core#588]
Is there an option to `await _workflowHost.StartWorkflow` but await to actually finish the whole workflow before execution continues.

**Comment by danielgerlag** [comment]
Use the Sync runner
https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0

**Comment by jdevillard** [comment]
Yes exactly thanks @cryo75.

@danielgerlag it seems to not be documented yet, can we safelly use it ? (I can propose a pull request for the doc maybe?)
