### ISSUE TITLE
Steps with dependencies can't be unit tested?

### ISSUE THREAD

**Issue by phillip-haydon** [danielgerlag/workflow-core#589]
Looking at the base class for unit testing the `Setup` has:

```
        protected virtual void Setup()
        {
            //setup dependency injection
            IServiceCollection services = new ServiceCollection();
            services.AddLogging();
            ConfigureServices(services);

            var serviceProvider = services.BuildServiceProvider();

            //config logging
            var loggerFactory = serviceProvider.GetService<ILoggerFactory>();
            //loggerFactory.AddConsole(LogLevel.Debug);

            PersistenceProvider = serviceProvider.GetService<IPersistenceProvider>();
            Host = serviceProvider.GetService<IWorkflowHost>();
            Host.RegisterWorkflow<TWorkflow, TData>();
            Host.OnStepError += Host_OnStepError;
            Host.Start();
        }
```

Logging is added by default. 

So if I take the example from:

https://github.com/danielgerlag/workflow-core/blob/master/src/samples/WorkflowCore.TestSample01/xUnitTest.cs

And change the step to include logger:

```
    public class AddNumbers : StepBody
    {
        private ILogger<AddNumbers> logger;

        public AddNumbers(ILogger<AddNumbers> logger)
        {
            this.logger = logger;
        }

   ....
```

It causes the test to fail.

```
WorkflowCoreDemo.MyWorkflowTest.MyWorkflow

Expected GetStatus(workflowId) to be Complete, but found Runnable.
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message)
   at FluentAssertions.Execution.TestFrameworkProvider.Throw(String message)
   at FluentAssertions.Execution.DefaultAssertionStrategy.HandleFailure(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args)
   at FluentAssertions.Primitives.ObjectAssertions.Be(Object expected, String because, Object[] becauseArgs)
   at WorkflowCoreDemoTest.MyWorkflowTest.MyWorkflow() in /home/phillip/git/WorkflowCoreDemo/WorkflowCoreDemoTest/XUnitTest.cs:line 23

```

The step never gets executed, so I think it fails to resolve.

**Comment by phillip-haydon** [comment]
Woops I forgot to add that I tried calling `ConfigureServices(...)` but that doesn't help.

I assume* that your intention is that I override Setup and do it in there?

I changed the setup to:

```
        protected virtual void Setup(IServiceCollection services = null)
        {
            //setup dependency injection
            services ??= new ServiceCollection();
            services.AddLogging();
            ConfigureServices(services);
     
            .....
        }
```

This resolved the issue.

**Comment by ottarhenanger** [comment]
I resolved this issue by overriding ConfigureServices(IServiceCollection collection) in test class:

` protected override void ConfigureServices(IServiceCollection services)
        {
            base.ConfigureServices(services);

            services.AddTransient....
`

**Comment by wlinna** [comment]
Why is this closed? Both of these solutions include overriding undocumented methods. It's not even clear to me what was done exactly. `WorkflowTest` already adds logging, so why can't one then just add a logging dependency without overriding `Setup`?

I'm very confused

**Comment by ma586** [comment]
@ottarhenanger Hi there, any chance you could provide me with your full test. I struggle to replace get the workflow with the injected needed parameters. Thanks in advance.

**Comment by jordanwallwork** [comment]
In case it's helpful to anybody in the future, I had completely missed the fact that you have to had your steps to the service collection too.

I feel like an exception here saying something about being unable to resolve the step would be better than just not doing anything, I was very frustrated trying to figure it out (and yes, it does say it quite clearly in the docs, but somehow I read them over and over and kept missing it!)

**Comment by martin-hirsch** [comment]
Just stumbled across this. @danielgerlag, anything in the pipeline I'm not seeing?
