### ISSUE TITLE
Mluti-events for same event name/key

### ISSUE THREAD

**Issue by hsnuscars** [danielgerlag/workflow-core#59]
I put an event in a loop and it will keep going before it meets a condition.
like this:
```C#
builder
    .StartWith<SayHello>()
    .While(data => data.flag == true)
        .Do(x => x
            .StartWith<DoSomething>()
            .WaitFor("MyEvent", data => "0")
                .Output(data => data.Events, step => step.EventData)
            .Then<DoSomethingElse>())
    .Then<SayGoodbye>();
```
And event may published from multi-source.
It means it may come in very close time.
It tried and it will miss event if it's close enough.
The reason is the 2nd event come before loop go back to WaitFor step.

Is there any idea for this case?

--
Thanks for these.
It's really cool.

**Comment by danielgerlag** [comment]
Hi,

I'm not sure I understand exactly what you are asking, but have you tried the overloaded `.WaitFor` method that takes an effective date parameter at the end?

**Comment by hsnuscars** [comment]
Yes, I tried with Now, 5 secs ago, and 15 sec ago.
It will be re-triggered by older event if I set it to past time.
Maybe I should set it between the 2 events?

**Comment by danielgerlag** [comment]
Have you considered using a unique event key for each iteration (the second parameter where you are passing `"0"`)

**Comment by hsnuscars** [comment]
For example, there are 10 or more (not a fixed number) people to vote. Some of them (maybe 6) approval will accept this subject and continue to next step. They will not reply in order, so I should prepare for all response before step end. I understand that I can create multi-workflow and wait for all people to vote, and close unused one when this step finished. But maybe there is another way to do this simply.

**Comment by danielgerlag** [comment]
I think the easiest way to implement this currently, would be to have the voting records in an external data store and the workflow event is simply a "poke" for the workflow to check the vote tally in the external data store.

**Comment by hsnuscars** [comment]
Cool, seems it cannot be resolved directly but I will try something with this idea. Thanks for your suggestion.
