### ISSUE TITLE
WaitFor with Timeout?

### ISSUE THREAD

**Issue by phillip-haydon** [danielgerlag/workflow-core#590]
I've tried digesting these

https://github.com/danielgerlag/workflow-core/wiki/11.-Schedule-and-Recur
https://github.com/danielgerlag/workflow-core/pull/237
https://github.com/danielgerlag/workflow-core/issues/164
https://github.com/danielgerlag/workflow-core/issues/228

Looking at these it's not clear how to have a _simple_ timeout without the workflow getting complicated with parallel etc, or if things become blocking.

Ideally I want to do something along the lines of:

```
                .WaitFor("ExternalEvent", s => $"{s.Key}")
                    .Output(..)
                    .WaitTimeout(TimeSpan.FromHours(2), data => data.MyStatus == Status.Pending, false)
```

Where it would wake up after 2 hours, check the condition, and continue (true/false) based on the result

**Comment by phillip-haydon** [comment]
I'm not sure the Parallel scenario works. I don't know if it's a documentation issue or an incomplete feature. 


```
            builder
                .StartWith(() => ExecutionResult.Next())
                
                .Parallel()
                    .Do(x =>
                    {
                        x.StartWith(s => ExecutionResult.Next())
                         .Delay(y => TimeOut.FromSeconds(10));
                    })
                    .Do(x =>
                    {
                        x.StartWith(s => ExecutionResult.Next())
                         .WaitFor("ExternalEvent", s => $"{s.Key}")
                         .Output(y => y.Result, y => y.EventData);
                    })
                    .Join()
                .CancelCondition(y => y.Result != Status.Pending, true)
                .Then(() => ExecutionResult.Next())
                ;
```

So if I run a unit test for this. Where I do:

```
WaitForEventSubscription("ExternalEvent", $"{workflowInput.Key}", TimeSpan.FromSeconds(20))
```

I would expect the unit test to return 'completed' after ~10 seconds.

However it executely instantly with

> Expected GetStatus(workflowId) to be Complete, but found Runnable.

If I change `WaitForEventSubscription` to

```
WaitForWorkflowToComplete(workflowId, TimeSpan.FromSeconds(20))
```

It waits 20 seconds and fails with the same error message.

**Comment by phillip-haydon** [comment]
So the delay wont work with `CancelCondition`.

i.e
```
                        x.StartWith(s => ExecutionResult.Next())
                         .Delay(y => TimeSpan.FromSeconds(10))
                         .CancelCondition(y => y.Result == Status.Pending, false)
```

This causes the delay to be executed right away and `NextExecution` to be wiped out from the database.

```
                        x.StartWith(s => ExecutionResult.Next())
                         .Delay(y => TimeSpan.FromSeconds(10))
                         .If(y => y.Result == Status.Pending)
                         .Do(o => o.StartWith(_ => ExecutionResult.Next()).EndWorkflow());
```

Changing it to an `If` with a step to end the workflow however does result in the desired affect both in a live example and in a unit test.

But this leaves a really messy workflow definition in my opinion. It's not easy to understand.

**Comment by danielgerlag** [comment]
I think you meant to put the `CancelCondition` on the `WaitFor`

**Comment by phillip-haydon** [comment]
I tried. If the condition checks “status pending => false” it causes the workflow to complete instantly. 

It’s really confusing :(

**Comment by danielgerlag** [comment]
I will try put together some samples or scenario tests around this in the next few days

**Comment by phillip-haydon** [comment]
That would be awesome. If I want to contribute to documentation where’s the best place? Cos I see 3 places. The wiki, the samples, and docs.

**Comment by danielgerlag** [comment]
I don't think your workflow is completing... I think it's stuck... something needs to happen within the workflow on another step to cause the cancel condition to be re-evaluated... this is where having a parallel branch that manipulates the data that the cancel condition is watching comes in.  See this test: https://github.com/danielgerlag/workflow-core/blob/master/test/WorkflowCore.IntegrationTests/Scenarios/CancelledEventScenario.cs

The wiki documentation is old, focus on the /docs and samples.
