### ISSUE TITLE
Decide Json Question

### ISSUE THREAD

**Issue by chichung-star** [danielgerlag/workflow-core#592]
I  already read [official document ](https://workflow-core.readthedocs.io/en/latest/control-structures/#decision-branches)
My Json definition and code as below seems not working any suggestion? thank you.

`var loader = serviceProvider.GetService<IDefinitionLoader>();`
`var wf = loader.LoadDefinition(@"{
                                                ""Id"": ""AddWorkflow"",
                                                ""Version"": 1,
                                                ""DataType"": ""wfCore.DecisionData, wfCore"",
                                                ""Steps"": [
                                                            {
                                                              ""Id"": ""Hello"",
                                                              ""StepType"": ""wfCore.HelloWorld, wfCore"",
                                                                ""NextStepId"": ""decide""
                                                            },
                                                        {
                                                        'Id': 'decide',
                                                        'StepType': 'WorkflowCore.Primitives.Decide, WorkflowCore',
                                                        'Inputs': 
                                                                {
                                                                    'Expression': 'data.Value1'
                                                                },
                                                        'OutcomeSteps':
                                                                {
                                                                    'Branch1': '""one""',
                                                                    'Branch2': '""two""'
                                                                }
                                                    },
                                                    {
                                                        'Id': 'Branch1',
                                                        'StepType': 'wfCore.CustomMessage, wfCore',
                                                        'Inputs': 
                                                            {
                                                                'Message': '""Hello from 1""'
                                                            }
                                                     },
                                                     {
                                                        'Id': 'Branch2',
                                                        'StepType': 'wfCore.CustomMessage, wfCore',
                                                        'Inputs': 
                                                        {
                                                                   'Message': '""Hello from 2""'
                                                        }
                                                     }
                                                            ]
}", Deserializers.Json);`
`           var initialData = new DecisionData
            {
                Value1 = "two"
            };
            host.StartWorkflow(wf.Id, wf.Version, initialData);`

`public class CustomMessage : StepBody
    {
        public string Message { get; set; }
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine(Message);
            return ExecutionResult.Next();
        }
    }`

`public class HelloWorld : StepBody
    {
        public override ExecutionResult Run(IStepExecutionContext context)
        {
            Console.WriteLine("HelloWorld");
            return ExecutionResult.Next();
        }
    }`

**Comment by tingwei628** [comment]
@chichung-star  
https://github.com/danielgerlag/workflow-core/pull/630/files
