### ISSUE TITLE
Stop the execution of a flow

### ISSUE THREAD

**Issue by Riccardo11** [danielgerlag/workflow-core#594]
Hi Daniel,

is there a way to stop a flow when a particular condition is verified?

I found a workaround, but it leaves a pending thread waiting for an impossible event.

```
if (condition is verified) {
    return ExecutionResult.WaitForEvent("ImpossibleEvent", "ImpossibleKey", new System.DateTime());
}
else
{
    return ExecutionResult.Next();
}
```
Another possibility could be making the step sleep for a very long time, but I guess the problem would be the same.

I can't use the IF construct of workflow-core to achieve this goal, so is there something similar to an ExecutionResult.Stop()?

Thank you.

**Comment by dviry** [comment]
Personally I've been using the .EndWorkflow() Step to achieve that as part of the Workflow definition.
