### ISSUE TITLE
Nested Workflows

### ISSUE THREAD

**Issue by rsnj** [danielgerlag/workflow-core#60]
I just came across your library and it looks great! I am doing some research to see if it will fit my requirements.

This is a two part question:
1. Is it possible to nest workflows, so that one workflow starts another workflow and waits for it to finish with a result of some kind?

2. Is it possible to correlate a given workflow so that two workflows with a given correlation id cannot be started concurrently?

My use case is essentially a parent / child relationship with some long running processes.
I want to create a RegisterChildWorkflow and from within that workflow I want to kickoff the RegisterParentWorkflow, but there should only ever be one RegisterParentWorkflow running at a time. So that if I register two children they would both subscribe to the same RegisterParentWorkflow result.

Thanks!

**Comment by danielgerlag** [comment]
1. Currently, there is no built in functionality to explicitly nest workflows, but you could compose the aggregate the fluent call chains into variables that you could reuse as sort of "sub-workflows" - However, this is definitely on my radar as a first class feature.

2. You could write a custom locking step to achieve this but there is no built in feature for it.

**Comment by ewyuen** [comment]
You mention you can compose the fluent call chains into variables and reuse it.   Can you provide an example how to do it?

**Comment by danielgerlag** [comment]
Something like this

```c#
public void Build(IWorkflowBuilder<MyData> builder)
{
    var branch1 = new Action<IWorkflowBuilder<MyData>>(branch => 
        branch.StartWith<PrintMessage>()
            .Input(step => step.Message, data => "Value is less than 3"));

    var branch2 = new Action<IWorkflowBuilder<MyData>>(branch =>
        branch.StartWith<PrintMessage>()
            .Input(step => step.Message, data => "Value is less than 5"));

    builder
        .StartWith<SayHello>()
        .If(data => data.Counter < 3).Do(branch1)
        .If(data => data.Counter < 5).Do(branch2)
        .Then<SayGoodbye>();
}        
```

**Comment by ewyuen** [comment]
Thank you!  It works.

**Comment by ScarletyCapone** [comment]
Is it possible for these branches to utilize different context classes other than "MyData". EX the main workflow use a "MasterWorkflowDataContext" and the branches have "Branch1Context", "Branch2Context", etc. allowing us to pass some data back and forth between the master and branch data context classes? I'd like not to bloat "MyData" with too many properties that only pertain to a branch.

**Comment by danielgerlag** [comment]
That's a good suggestion... I will investigate what is involved to implement something like this

**Comment by rosspace** [comment]
I have a similar issue but mine relates to working within a loop. Essentially I am pulling a batch of data and looping through it and working on individual messages. Based on message type my logic branches to perform different tasks. In the end I create a new entity that gets saved. 

It is cumbersome passing data around via context.Item inside the loop and it would be nice if you could set up a different data class within the loop so I could pass more data between steps than just context.Item.

**Comment by ScarletyCapone** [comment]
Within your loop you still have access to the context class used for the entire workflow, you're not limited to just the item within a collection. So if your context class contains a class to persist data between the steps and a collection of classes for your messages to process, you can still get to everything.

**Comment by rosspace** [comment]
@ScarletyCapone but if I'm in a parallel ForEach I could set fields on the context class but wouldn't that not be thread safe? Since other iterations could be running on separate threads couldn't anything I assign be overwritten by another thread between steps? Or are you saying I should be using a While loop and just increment an index of the item I am working on that way I can set whatever I want on the main class?

**Comment by ScarletyCapone** [comment]
@rosspace If I understood right these are not parallel in the essence that they run on different threads; I had the same confusions over in issue 189 that I opened. I also learned this ForEach implementation doesn't iterate as one would think, it will do step 1 for all items in your collection before attempting step 2 for any of them, which is why I moved to a while loop for my solution. I needed to logically process all tasks for item 1 before attempting any for the next.

**Comment by rosspace** [comment]
@ScarletyCapone that is good to know. I would not have expected it to work that way. I don't think that would give me an issue but I think I will want to move to the while loop anyways because of the complexity of my workflow.

Thanks!

**Comment by ScarletyCapone** [comment]
@danielgerlag Circling back to this finally, did you have any additional thoughts on branches that can utilize different data contexts? Trying to build some reusable branches for common sets of tasks that may be shared among various workflows. The workflows all use different data types, but they all inherit from base classes / interfaces that would be utilized for the branches.

**Comment by danielgerlag** [comment]
@ScarletyCapone I have not spent much time on this yet but I think it is worthwhile

**Comment by gonengf** [comment]
I also think that would be great to have branches to utilize different context classes
There is no way at this point to pass a specific object in a ForEach loop to a re-usable sub-workflow apart from using one in the main data context class: 
```
[....]
 .ForEach(data => data.CompareResult.Install)
                            .Do(installModuleWorkflow)
```

**Comment by WalkeR321** [comment]
> 1. Currently, there is no built in functionality to explicitly nest workflows, but you could compose the aggregate the fluent call chains into variables that you could reuse as sort of "sub-workflows" - **_However, this is definitely on my radar as a first class feature._**

So, is native support for nested workflows planned?

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/pull/486

**Comment by mitbilal** [comment]
builder
                .StartWith<WorkFlowStarted>()
                .WaitFor("MyEvent1", (data, context) => "Key", data => DateTime.Now)
                    .Output(data => data.Value1, step => step.EventData)
                .Then((context) =>
                {
                    return ExecutionResult.Next();
                })
                .Decide(data => data.Value1)
                    .Branch((data, outcome) => data.Value1.ToLower() == CValue.ToLower(), level1User1);
