### ISSUE TITLE
what is the no threads used by multiple workflow core instance in asp.net core 3.1 app

### ISSUE THREAD

**Issue by jackdeesun** [danielgerlag/workflow-core#604]
Hi @danielgerlag ,

I have designed asp.net core 3.1 WebAPI application using workflow core as below, at some point (when multiple users are accessing my service) its constrained to make call synchronously till that point its making concurrent calls (i mean concurrent calls are happening in foreach step below), so what is the default no of thread grand we have for multiple workflow core instances to use with (in a given thread pool) ? Is there a way to increase it in workflow core?

//STEP 1: Call work flow in rest endpoint:
if (!_registry.IsRegistered("deaaswf", 1))
	{_workflowController.RegisterWorkflow<DigitizationWorkflow, WorkFlowData>();}
WorkFlowData workFlowData = new WorkFlowData();
.....
.....
var workflowID= await _workflowController.StartWorkflow<WorkFlowData>("deaaswf", workFlowData);

//STEP 2: workflow design:
builder
   .StartWith<ImageFilter>()
   .Input(step => step.S3FolderPath, data => data.S3FolderPath)
   .Output(data => data.IsImageFilterPassed, step => step.IsImageFilterPassed)
   .**ForEach**(data => data.lstTools)
	   .Do(x => x
		   .StartWith<CallDITool>()
			   .Input(step => step.Item, (data, context) => context.Item)
			   .Input(step => step.IsImageFilterPassed, data => data.IsImageFilterPassed)
			   .Input(step => step.S3FolderPath, data => data.S3FolderPath));

**Comment by danielgerlag** [comment]
It uses the TPL library, but we target to max number of concurrent workflows on a node to be the number of cores.
https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/QueueConsumer.cs#L15
