### ISSUE TITLE
Concurrency issues: The collection's state is no longer correct

### ISSUE THREAD

**Issue by andrx** [danielgerlag/workflow-core#607]
Using .net core 3.1 on unix, long running workflows.
Have been running the service on three nodes. two of them died (1st - after 5hrs, 2nd - after 8hrs) with the following exception.

	UnhandledExceptionTrapper - System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
	   at System.Collections.Generic.HashSet`1.Contains(T item)
	   at WorkflowCore.Services.BackgroundTasks.QueueConsumer.<>c__DisplayClass15_1.<<Execute>b__0>d.MoveNext()
	   --- End of stack trace from previous location where exception was thrown ---
	      at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__139_1(Object state)
	         at System.Threading.QueueUserWorkItemCallback.Execute()
	            at System.Threading.ThreadPoolWorkQueue.Dispatch()

Doesn't look like hard to fix. I can help. Do you prefer [ConcurrentHashSet nuget](https://github.com/i3arnon/ConcurrentHashSet) or just switching to ConcurrentDictionary? Another question would be why that happened?

**Comment by danielgerlag** [comment]
Good catch... I believe this is happening because we are manipulating the (non-thread safe) set inside an async task which could run in another thread.  I would opt to avoid adding more library dependencies if possible to keep this light-weight.

**Comment by andrx** [comment]
I can confirm switching to ConcurrentHashSet fixed the issue. 3 days under load - didn't happen anymore
