### ISSUE TITLE
How to deal with random collection of users?

### ISSUE THREAD

**Issue by oblin** [danielgerlag/workflow-core#61]
I got questions about Users extension, for multiple users approval list:

1. We had workflow for multiple users approve , but those users could change. It seems while loop might work, but could you give some suggestion if there's better way?

2. Could it be possible to add user in above approval list (by position)?

3. in sample:
`host.PublishUserAction(openItems.First().Key, @"domain\john", answer).Wait();`
I need to get the "domain\john" string in UserTask/WithOption, how could it be done?

Thanks for your great work!

**Comment by danielgerlag** [comment]
1 & 2. Would it make sense to use `User Groups` instead of users in this case?
3. Currently, this is stored in the `ExtensionAttributes` collection in the persistence store, but there is no easy way to access it programmatically... I will look into adding a feature to surface this data to the workflow.

**Comment by oblin** [comment]
Thanks for reply. 
But I wonder how to use User Groups? Is there any samples?

**Comment by oblin** [comment]
@danielgerlag But there's still a need to insert user/group to certain position. For example: A -> B -> C, but A might think add D between B & C.

Is there a workaround to achieve?

**Comment by danielgerlag** [comment]
not sure I understand the question?

**Comment by oblin** [comment]
That's all right, I might think the wrong way.
Thanks for your reply.

**Comment by Diaskhan** [comment]
In sipmle workflow there must be approval list, and one flow node must contain multiapprove! Without deep persistence with rdbms is hard to realize ! 

What iam trying to say in workflow library have one execution node, but for a many users! 
This node flow creates a many tasks for users ! And there must be some condition 
For example approve about 100 users! Every time when each user approves task, the condition code is executes! In condition have check if more than 50 users approved task! Condition checked to true ,then worflow is iterating to another node ! 

In bpmn it calls multiinstance behavior 
http://blog.maxconsilium.com/2013/09/process-patterns-p4.html?m=1
