### ISSUE TITLE
[Question] Is it possible to use WorkflowCore with separate diagramming tool?

### ISSUE THREAD

**Issue by cryo75** [danielgerlag/workflow-core#614]
I'm looking in implementing workflow management into my app. My app consists of an ASP.Net WebApi2 server and a .Net 4.8 Winforms client.

Currently I am building a diagramming tool which simply allows me to add shapes and connections and store the diagram info as xml. I would like to keep this tool. Now I need to extend this tool to support workflows.

So I came across WorkflowCore and it looks very interesting. My idea would be to only use WorkflowCore to build and execute workflows. I would need to map / translate my diagram to WorkflowCore workflows. I can do my own persistence, but if WorkflowCore has this option that allows me to integrate into my current database, I might use it too. Workflows will be executed client-side and/or server-side. Some custom client-side steps will need to show forms for data-entry.

Is something like this possible to do?

**Comment by cryo75** [comment]
I started with the diagramming tool and I already got a basic workflow with 2 simple steps.

Is it possible to have the DefinitionLoader serialize a workflow?

**Comment by xuzeyu91** [comment]
I think you can convert XML to JSON and use DSL to load it
