### ISSUE TITLE
How to use WorkflowCore with Autofac?

### ISSUE THREAD

**Issue by cryo75** [danielgerlag/workflow-core#615]
Is it possible to use Autofac as the Di instead of the ASP.Net implementation?

Also, I'm starting the host like this:

`            var host = app.ApplicationServices.GetService<IWorkflowHost>();
            host.Start();` 

If the workflows are always loaded from definitions, I guess I can't register them at this stage. Will they be registered when loaded?

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/issues/186

**Comment by sevencat** [comment]
use ContainerBuilder Populate
private static IServiceProvider ConfigureServicesAutoFac()
	{
		var builder = new ContainerBuilder();
		//your other ioc config
		ConfigAutofac(builder);
		{
			IServiceCollection services = new ServiceCollection();
			services.AddWorkflow();
			builder.Populate(services);
		}
		var container = builder.Build();
		return new AutofacServiceProvider(container);
	}
