### ISSUE TITLE
Parallel Foreach or not?

### ISSUE THREAD

**Issue by cryo75** [danielgerlag/workflow-core#616]
The document says that the foreach is parallel:
https://workflow-core.readthedocs.io/en/latest/control-structures/#parallel-foreach

But there the RunParallel field is not set in the in the example.

So is the foreach a parallel step or not?

**Comment by danielgerlag** [comment]
It's parallel by default
@dviry Do you want to answer this one, or provide some examples?

**Comment by dviry** [comment]
.RunParallel is per default True, so the Documentation is correct...
