### ISSUE TITLE
Visualize a workflow using BPMN?

### ISSUE THREAD

**Issue by cryo75** [danielgerlag/workflow-core#618]
Is it possible to visualize a workflow using BPMN?

I'm building a diagramming tool to work with WorkflowCore but I'm have issues trying to visualize control flow activities like while, foreach, etc...

Is it even possible to use BPMN with WorkflowCore or should I go with my own custom diagramming and notation?

**Comment by Diaskhan** [comment]
Its more Worflow fondation like, not like bpmn.
Play with library, then u colud make some designer, its not bpmn engine, maybe could possible to adopt.
