### ISSUE TITLE
Queueing Sequential Workflows

### ISSUE THREAD

**Issue by dbhc** [danielgerlag/workflow-core#619]
I'm sorry if this is answered somewhere but I couldn't find it in the wiki or open issues.

Is there a way to queue a workflow for sequential execution?
Particular workflows (ones that include steps that hit the database) can't be executed in parallel.

**Comment by cryo75** [comment]
I'm assuming a workflow runs sequentially unless explicitly stating that it's parallel, as show here:
[https://workflow-core.readthedocs.io/en/latest/control-structures/#parallel-paths](Parallel Paths)

**Comment by dbhc** [comment]
I mean the workflows in entirety instead of workflow steps.
For example, if I have a workflow with ID: DataPersister that has 10 steps, I want to schedule 100x DataPersister workflows to execute but each execution should start only after the previous DataPersister workflow has completed.

**Comment by dbhc** [comment]
apologies.   I just saw [SyncWorkflowRunner](https://github.com/danielgerlag/workflow-core/releases/tag/2.1.0)
I will go through that part of the code tonight
