### ISSUE TITLE
State machine workflow

### ISSUE THREAD

**Issue by supakit1** [danielgerlag/workflow-core#62]
Do you have any sample for state machine workflow? I 'm using SharePoint workflow 2010 before and families with state machine flow.  

Thanks,
Sup

**Comment by danielgerlag** [comment]
Not currently, but I will look into adding something like this

**Comment by oakdemirci** [comment]
Thanks for the library, any news on StateMachine workflow ? 
Regards

**Comment by danielgerlag** [comment]
it's still on my radar but unfortunately it's not started yet

**Comment by nanhishweta-26** [comment]
Any update on state machine workflow?
