### ISSUE TITLE
Event triggered workflows. Synchronization issue

### ISSUE THREAD

**Issue by xwrs** [danielgerlag/workflow-core#622]
I have a workflow which has to be initiated by an event. The code I have
Workflow:
```
builder.StartWith<StartStep>()
.Then(_ => Console.WriteLine("Waiting for onboarding event"))
 .WaitFor("Onboarding", (data, context) => data.CorrelationId, _=> DateTime.Now)
.Output(data => data.Onboarding, e => e.EventData)
...
```

Execution:

```
....
var model = new Workflows.Onboarding.Model { Onboarding = notification };
await workflowHost.StartWorkflow("OnboardingWorkflow", model);
// here workflow hasn't started yet, hence WaitFor for "Onboarding" is not subscribed to anything yet
notification.CorrelationId = model.CorrelationId; //isn't important. model has calculated property so it correlates alright
await workflowHost.PublishEvent("Onboarding", notification.CorrelationId, notification);
...

```
But the event is never processed if I set effective date in WaitFor. Due to traces, the workflow is started after the event is published. According to source code the internal event bus/hub is used to trigger the workflow so call of `workflowHost.StartWorkflow ` does not guarantee that workflow is in fact started.

When I set effective date in `workflowHost.PublishEvent ` to DateTime.Now + 5 seconds - everything works fine. Is there a better way of doing what I am doing? Thank you

**Comment by danielgerlag** [comment]
pass a MinDate to WaitFor
