### ISSUE TITLE
Please merge wiki change

### ISSUE THREAD

**Issue by tingwei628** [danielgerlag/workflow-core#624]
Hi, I added `.Decide` example into `10. Loading workflow definitions from JSON` in wiki.
My wiki fork link: `https://github.com/tingwei628/workflow-core.wiki.git`
Thanks in advance !
P.S. [Merge Wiki Changes From A Forked Github Repo](https://gist.github.com/larrybotha/10650410)

**Comment by cryo75** [comment]
Isn't `.Define` actually '.Decide' ?

**Comment by tingwei628** [comment]
> Isn't `.Define` actually `.Decide` ?

yes, I fixed typo.

**Comment by danielgerlag** [comment]
The wiki documentation is actually out of date... please make doc changes in `/docs` in the main repo... this will generate readthedocs documentation.  Thanks for the contribution!

**Comment by tingwei628** [comment]
I have already submitted a  [PR](https://github.com/danielgerlag/workflow-core/pull/630) to docs

closed this issue
