### ISSUE TITLE
What is the purpose of RegisterWorkflow?

### ISSUE THREAD

**Issue by cryo75** [danielgerlag/workflow-core#625]
I keep the workflow definitions (in JSON format) within my own DB.

What is the purpose of RegisterWorkflow (within the broader scenario of the workflow server implemented in a WebApi app) if registering the definition just adds it to a list? The app can be terminated and/or restarted at will and also recycled by IIS.

**Comment by danielgerlag** [comment]
It's an in-memory repository of workflow definitions.  If you have a long running workflow that say started in a previous cycle of an app, you would still need access to the original definition to complete it.

**Comment by cryo75** [comment]
If the definitions are persisted in-memory, how are they retrieved by those long-running workflow instances once the workflow host is restarted again?

**Comment by danielgerlag** [comment]
That's why you register your workflow definitions on startup.
