### ISSUE TITLE
Transaction support

### ISSUE THREAD

**Issue by Suriman** [danielgerlag/workflow-core#63]
As far as I can see, there does not seem to be support for transactions within a workflow. Do you have any plans? How can it be implemented with existing primitives?

**Comment by danielgerlag** [comment]
Currently this is only possible with a single workflow step, not across multiple steps, since the engine persists the workflow state after every step.

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/releases/tag/1.6.0
