### ISSUE TITLE
Compensation Support

### ISSUE THREAD

**Issue by Suriman** [danielgerlag/workflow-core#64]
Related to the [transaction support](https://github.com/danielgerlag/workflow-core/issues/63), there does not seem to be support to implement compensation mechanism in a workflow. Do you have any plans? How can it be implemented with existing primitives?

**Comment by danielgerlag** [comment]
see #63

**Comment by danielgerlag** [comment]
I want to tag this feature for the next major version

**Comment by danielgerlag** [comment]
@Suriman 
I have just released `v1.6.0` which has this feature

https://github.com/danielgerlag/workflow-core/releases/tag/1.6.0

**Comment by Suriman** [comment]
You are the best!. Thank you very much!.

**Comment by danielgerlag** [comment]
@Suriman let me know if you have any feedback or suggestions on how it works
