### ISSUE TITLE
Workflow Options Configurability

### ISSUE THREAD

**Issue by AustinMalpede** [danielgerlag/workflow-core#647]
Hello,

I have a service which is consuming workflow-core. It's using redis as its queueing provider. My service can scale up, but more importantly it can scale down. This can be concerning because we don't want a service which is shutting down to begin working on any new workflow items. After looking at the [QueueConsumer ](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/QueueConsumer.cs#L16) we can see that the number of concurrent items is equal to the number of processors. Upon detection of my service shutting down would it be possible to bring this MaxConcurrentItems down to 0 to ensure that no new workflow items are picked up?

Could allowing additional configurability in the [WorkflowOptions](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Models/WorkflowOptions.cs) class be useful? Gaining the ability to tweak the PollInterval, IdleTime, and ErrorRetryInterval could be very beneficial.

Any suggestions on how I can achieve graceful shutdown of a service consuming workflow core would be appreciated.

Thanks

**Comment by danielgerlag** [comment]
The queue consumers stop pulling new items from the queue once a shutdown has begun.
See: https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/BackgroundTasks/QueueConsumer.cs#L60

You also can already override the default poll interval on workflow options... use `UsePollInterval` on the config lamdba,
Error retry intervals can can configured per workflow and per use case.
