### ISSUE TITLE
Workflow Designer

### ISSUE THREAD

**Issue by Suriman** [danielgerlag/workflow-core#65]
Do you have any plans to create a workflow designer?

**Comment by danielgerlag** [comment]
Yes, but first we need to make it possible to read workflow definitions from file... once we have that, then we can create a designer.

**Comment by weedkiller** [comment]
Adding a sample with 1) document approval & nested workflow would be nice too..

**Comment by Suriman** [comment]
When do you foresee having implemented the possibility of saving the definitions of a workflow in a file?

**Comment by danielgerlag** [comment]
My goal is for before the end of the year... I'm currently focusing on another project but am hoping to jump back onto WorkflowCore in the next few weeks.

**Comment by danielgerlag** [comment]
Just to give an update, I have been working on the feature to load workflow definitions from file, and I plan to release in the next week or two.  Find the draft release notes here:

https://github.com/danielgerlag/workflow-core/blob/def-loading/ReleaseNotes/1.4.0.md

**Comment by danielgerlag** [comment]
https://github.com/danielgerlag/workflow-core/releases/tag/1.4.0

**Comment by linkev44** [comment]
Hi,
Very nice project, i think to use your nuget for my customer (French Company)
I need to create a designer so that my user can configure their WorkFlows ..
Do you have an idea of the technology you want to use ?
I think I create an angular5 project with ngrx state for manage WF configuration and become the client of my API. 

What do you think  about this ?

**Comment by phamtuanit** [comment]
This is nice project.
I'm looking for class diagram which will make me easy to understand. I hope that you can publish it soon.

**Comment by mcrustk2** [comment]
Any thoughts on moving the designer forward, It think providing an interface will seriously move this project forward and make it more viable for a larger swathe of people, im happy to help but only just getting to grips with WF.Core at the moment. Thanks for all the contributions though, great project!

**Comment by IvanCyber** [comment]
Hi there :)
The project is great.
Since I didn't find in the above posts... @danielgerlag did you create a designer, and if so, where is its documentation and examples (if there are any)?
Thank you.
