### ISSUE TITLE
Question - Use of QueueProvider

### ISSUE THREAD

**Issue by CreativeManix** [danielgerlag/workflow-core#656]
Just a clarification, we are going to deploy this awesome workflow-core in to multi node cluster.  We are using SQL for persistence, and we do not have any queue facility.

I understand "SingleNodeQueueProvider" Queues and dequeues from same process (in memory). So if I use the same for multi node cluster, I am assuming only problem is processing of  queued items are not distributed to all available nodes. Instead they are queued and processed by same node?

Will it create any other issue apart from above? such as step execution duplication?

I tested in 2 node cluster, I did not see any duplicate executions. 

My workflow defined as below
-> Step 1
-> Delay for 2 min
-> Step 2

Unfortunately I cant use SQL queue provider too (as it requires DB alteration to enable broker).

**Comment by danielgerlag** [comment]
Are you using a distributed lock manager?  That is the thing that will prevent duplicate execution.

**Comment by CreativeManix** [comment]
@danielgerlag yes I am using the distributed lock manager. I have tested with three different process (in same machine) could not simulate any duplicates. 

Thanks for the response. For now we will go with default in memory queue with distributed lock manager(sql) for multi node deployment.
