### ISSUE TITLE
Question - Storing a Workflow 'Result'?

### ISSUE THREAD

**Issue by bbollard** [danielgerlag/workflow-core#664]
I have poked around the code and I don't seem to see the concept of a Workflow 'Result' that native to the product. 

As an example, let's say you build a workflow that performs a complex set of steps for the purpose of validating if a system is in a correct state or not.

Once the the workflow has completed, the outcome of theses test will be, for simplicity, **true** (the system is in the correct state) or **false** (the system is not in the correct state).

We know the product supports outcomes as the means of implementing a branching / looping mechanism, but does the product have an overall 'outcome'? In other words, how can we store this workflow result true/false condition for querying from downstream processes? I know we can build a separate storage mechanism for storing the result in this very specific case but I was curious if there is a generic means of doing that within the product.

Thank you!

**Comment by danielgerlag** [comment]
There is no single "outcome" of a workflow, just the state of it's internal data at the end of the workflow.  You could publish this data in a final step.
