### ISSUE TITLE
Question - How do you set the Description field

### ISSUE THREAD

**Issue by dflor003** [danielgerlag/workflow-core#665]
Hi! This is more of a question than an actual issue. 

I see that there is a `Description` field on both the `WorkflowDefinition` and `WorkflowInstance` class. I read through some of the code and it seems to pass the `Description` value from the definition over to the instance when you start a workflow, but I could not find any way to set the `Description` field on the `WorkflowDefinition`. There don't seem to be any docs on this either. Is there any way to set this field?

For context, I'm building a light UI on top of the workflows to provide an easier way of keeping track of the statuses of all workflows and would like to encode some user-friendly information into this field.

**Comment by danielgerlag** [comment]
If you are using JSON defined workflows, you can set this value on the root level field in the JSON document.
It's not currently exposed for the fluent API, but that should be easy to fix.

**Comment by dflor003** [comment]
Yeah, the main goal for me would be to provide a user-friendly description of what the workflow instance is doing.

Ideally, these descriptions should be driven by the data passed into the workflow. For example, if I have a workflow that say provisions a virtual machine, I'd like to be able to setup the description on that workflow instance that says something to the tune of `Provisioning VM 'MyVirtualMachine'` based off the params to the workflow.

I've been able to work around this so far by introducing an interface called `IDescriptiveWorkflowParams` with a `Description` property that the workflow params can implement. I then do a cast to `IDescriptiveWorkflowParams` when retrieving the workflow instance and its params and then use that `Description` field if provided.

**Comment by danielgerlag** [comment]
Perhaps you are looking for the `Reference` field?

**Comment by dflor003** [comment]
What is the reference field supposed to be used for?

**Comment by dflor003** [comment]
I was able to use the new middleware feature to implement this quite nicely. Thanks for getting #678 merged and released!
