### ISSUE TITLE
Performing operations after a workflow completes in load balanced environment

### ISSUE THREAD

**Issue by fodiimre** [danielgerlag/workflow-core#667]
Hi,

I have `WorkflowCore` set up the following way (SQL Server persistence + Redis multi-node clusters):

```c#
private static void ConfigureWorkflowCore(this IServiceCollection services, IConfiguration configuration)
{
    string sqlConnectionString = configuration.GetConnectionString("DefaultConnection");
    RedisConfiguration redisConfiguration = configuration.GetSection("RedisConfiguration").Get<RedisConfiguration>();

    services.AddWorkflow(cfg =>
    {
        cfg.UseSqlServer(sqlConnectionString, true, true);
        cfg.UseRedisLocking(redisConfiguration.ConnectionString);
        cfg.UseRedisQueues(redisConfiguration.ConnectionString, redisConfiguration.QueuePrefix);
        cfg.UseRedisEventHub(redisConfiguration.ConnectionString, redisConfiguration.Channel);
    });

    services.AddWorkflowDSL();
}
```

I have multiple instances of the same web service using `WorkflowCore` for load balancing purposes. What I would like to achieve is to perform business operations when a workflow completes (e.g. send an email, create another workflow, etc.). 

I saw that `IWorkflowHost` has a global event (`OnLifeCycleEvent`), but because of the Redis `ILifeCycleEventHub` provider (`RedisLifeCycleEventHub`) the `WorkflowCompleted` event gets called on every web service instance which makes difficult to create a new instance of `WorkflowB` when `WorkflowA` completes (it would create a new workflow on every web service instance).

A possible solution what I've found is to add a final step to the end of `WorkflowA` which creates `WorkflowB`, but for design purposes it would be better to have a more loosely coupled solution. Creating a new workflow is just an example, multiple business operations are more likely to happen and an event driven solution is way more flexible, than adding a chain of steps to the end of each workflow definitions (not to mention error handling and making sure that every business operation step gets called).

Any ideas, best practices for this problem?

Thank you for the help!

**Comment by danielgerlag** [comment]
You have to make whatever process is responding to the workflow complete event, idempotent is it's design.

**Comment by DDzia** [comment]
I was catch the same exception into RedisPersistenceProvider when RedisValue.IsNull
