### ISSUE TITLE
Using in ASP.NET MVC 5....

### ISSUE THREAD

**Issue by natiki** [danielgerlag/workflow-core#67]
Hi,

A bit of a noob question here, I am sure. I want to use this in an MVC application. Is there an example on how to get this going? Ultimately I am not looking to return content to the connected client but rather to kick off back end processes as a consequence of a workflow.

Any pointers to get this going would be great.

**Comment by danielgerlag** [comment]
If you want to host the workflows in the same process as your MVC application, then you can setup and start the workflow host in the `Application_Start` method of the `Global.asax` file

**Comment by SudhirMangla** [comment]
this statement is not working in Asp.net MVC 5
IServiceCollection services = new ServiceCollection();

**Comment by danielgerlag** [comment]
you need to add the `Microsoft.Extensions.DependencyInjection - 1.1.0` NuGet package

**Comment by AsenLins** [comment]
。
