### ISSUE TITLE
StartTime Not Persisted on Workflow Steps in DB When Workflow Step Starts

### ISSUE THREAD

**Issue by dflor003** [danielgerlag/workflow-core#672]
It looks like the `StartTime` field does not persisted on `ExecutionPointer` when a workflow step gets initialized. The field only gets persisted to the persistence provider when the workflow step finishes or has an error. Until one of those things happens, the `StartTime` field's value is only in memory.

This has the effect that if you are trying to build a UI to track long-running workflows, you can not tell how long a particular step has been running for purely using the DB model.

Is there any work around for this? Are there any hooks into the workflow process I can use to persist the workflow state? If not, could I put together a PR to persist `ExecutionPointer.StartTime` whenever an `ExecutionPointer` is initialized?

**Comment by danielgerlag** [comment]
Which DB are you using?

**Comment by dflor003** [comment]
I am using MySql

**Comment by dflor003** [comment]
Another solution I'm considering is leveraging `ILifeCycleEventPublisher` to listen to the events coming from it and then manually updating the records in the DB. Would you recommend that?

**Comment by danielgerlag** [comment]
No, this sounds like a bug with the MySQL provider.

**Comment by dflor003** [comment]
I dug through the code a bit and looks like there is no call to the persistence provider to update the start time in the workflow executor after the step is initialized and the start time gets set.

**Comment by danielgerlag** [comment]
sorry, I think I misread the question... yes we don't update that value when starting the step... ideally the steps should be short running and the workflow long running.  If something is blocking on an external event, you could make it async with a wait for.

**Comment by dflor003** [comment]
My specific use case is to be able to track the run time of each step in an admin UI so if a step gets stuck, we can see how long it's been running for and kill it if necessary.

The steps themselves are interacting with a 3rd party system that unfortunately does not emit events we can listen to.

For the time being, I've been able to work around it by listening to the `StepStarted` event and manually updating the start time based off the event time.

This workaround has been working so far so this issue can be closed, but do you think it would be a good idea to persist that for others that may have the same use case?

```

**Comment by dflor003** [comment]
I was able to use the new middleware feature to implement this quite nicely. Thanks for getting #678 merged and released!
