### ISSUE TITLE
Suspend workflow not working when running in cluster mode

### ISSUE THREAD

**Issue by dflor003** [danielgerlag/workflow-core#675]
Hi! I've been trying to suspend a workflow that has been running for quite some time that is stuck in a permanent retry loop. Unfortunately, every time it tries to suspend, `IWorkflowController.suspend` returns false. There are multiple steps in this workflow that are stuck retrying forever.

A few other things to note:
- I am using MySQL for persistence
- Redis for locking
- Cluster mode with 2 nodes

Initially digging into the code, I see that in order to suspend, it first tries to acquire a lock as follows:

```
public async Task<bool> SuspendWorkflow(string workflowId)
{
  if (!await _lockProvider.AcquireLock(workflowId, new CancellationToken()))
    return false;
```

Does this mean that a workflow cannot be suspended when any of the steps are currently running? What happens if there are several steps running at the same time that each retry and you cannot get into a state where there are no running steps?

**Comment by danielgerlag** [comment]
This has nothing to do with cluster mode... if a workflow is currently executing, a distributed lock is taken, only 1 lock on an entire workflow instance at a time, only one node in a cluster can execute steps on a particular instance at a time... You could implement a back-off and retry suspending after waiting for a period.

**Comment by dflor003** [comment]
Hmmm... So then that means that when running in a cluster, you can only suspend the workflow if you get lucky and happen to hit the node that happens to be running that workflow at the time. Is that correct?

It would be nice to be able to treat the suspend as a request to suspend that will get fulfilled whenever the workflow frees up.

**Comment by danielgerlag** [comment]
No, like I said it has nothing to do with running in clusters, you would have the same behavior with a single node.
There are 2 things we could do here:
1. Modify the suspend to wait for the lock to open up with a timeout.
2. Implement a queued suspend command mechanism (a lot more involved)

**Comment by dflor003** [comment]
Yeah, I started looking at ways I could implement the queueing suspend command approach and it would be non-trivial.

I've been doing some thinking and I've got a feature proposal that may help with this as well as #672, #665, and a few other use-cases my team is looking to implement around Workflow Core. Give me a few and I will try to put the proposal together for discussion as a separate issue.

**Comment by dflor003** [comment]
I've documented the proposal in #678. Please take a look whenever you have some time.
