### ISSUE TITLE
Feature Proposal - Workflow and Step Middleware

### ISSUE THREAD

**Issue by dflor003** [danielgerlag/workflow-core#678]
## Proposal

My team has been experimenting with this library for a couple of projects and so far it's been quite a pleasure to work with, so thank you very much for that!

One area, though, where I see an opportunity for improvement around extensibility for various use-cases within the consuming apps. I propose adding a few additional hooks at the workflow and step level in the form of middleware to enable more extensibility for just about any use-case. Please take a look at the proposal below and if everything makes sense, I'd be happy to put together a PR to add this functionality.

These middleware would be similar in form to the type of middleware you would find around the [ASP.NET Core Controller middleware](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/middleware/write?view=aspnetcore-3.1) or [`HttpClient`'s `DelegatingHandler` middleware](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/httpclient-message-handlers) so it should feel familiar to enough to dotnet core users.

Here's an example of a few use-cases that this could help us solve:

* More robust retry strategies such as circuit breakers, exponential retry, and fallback using other libraries such as [Polly](https://github.com/App-vNext/Polly). There are a few existing issues that this may address: #654, #508 
* Injecting log correlation information into each workflow step so that we can view logs by workflow id.
* Appending additional metadata to workflow steps to support UIs. This would help with these issues: #672, #665
* Provide a general, unobtrusive hook into workflows and steps to make it easier to implement additional functionality without having to code for it in every step. 

## Examples

A line of code is worth a million pictures, so here are a few examples of how I think these middleware could look from the consumer perspective.

### Example 1 - Use a step middleware to add log correlation data to workflow steps

This is an example of how a middleware would look to add the workflow ID to log context using the [Serilog](https://serilog.net/) logging library and their built-in [logging context](https://nblumhardt.com/2016/08/context-and-correlation-structured-logging-concepts-in-net-5/#ambient-logging-contexts).

```cs
using Serilog;

public class SerilogCorrelationMiddleware : IWorkflowStepMiddleware {
  private const string WorkflowIdContextProperty = "workflowId";
  private readonly ILogger _log;

  public SerilogCorrelationMiddleware(ILogger logger) {
    _log = logger.ForContext<SerilogCorrelationMiddleware>();
  }

  public async Task<ExecutionResult> HandleAsync(
    IStepExecutionContext context, 
    IStepBody body, 
    WorkflowStepDelegate next
  ) {
    var workflowId = context.Workflow.Id;
    
    using (LogContext.PushProperty(WorkflowIdContextProperty, workflowId)) {
      return await next();
    }
  }
}
```

### Example 2 - Use a step middleware to implement robust retry policies via Polly

This is an example of integrating a fairly popular dotnet core resiliency library called [Polly](https://github.com/App-vNext/Polly) into Workflow Core to provide just about any kind of retry/circuit breaker policy you could think of. The example assumes that the step makes HTTP and SQL calls and is loosely based off the [Microsoft Docs here](https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly).

```cs
using Polly;

public class StepRetryMiddleware : IWorkflowStepMiddleware {
  private const string StepContextKey = "WorkflowStepContext";
  private readonly IPersistenceProvider _persistence;
  private static readonly TimeSpan[] RetryTimes = {
    TimeSpan.FromSeconds(1),
    TimeSpan.FromSeconds(2),
    TimeSpan.FromSeconds(3),
  };

  public StepRetryMiddleware(IPersistenceProvider persistence) {
    _persistence = persistence;
  }

  public IAsyncPolicy<ExecutionResult> GetRetryPolicy() =>
    Policy<ExecutionResult>
      .Handle<HttpRequestException>()
      .Or<SqlException>()
      .WaitAndRetryAsync(
        RetryTimes, 
        (exception, nextTime, retryCount, context) => 
          UpdateRetryCount(retryCount, context[StepContextKey] as IStepExecutionContext)
          // Based off the patterns here http://www.thepollyproject.org/2017/05/04/putting-the-context-into-polly/
      );

  public async Task<ExecutionResult> HandleAsync(
    IStepExecutionContext context, 
    IStepBody body, 
    WorkflowStepDelegate next
  ) {
    return await GetRetryPolicy().ExecuteAsync(() => next(), new Dictionary<string, object> {
      { StepContextKey, context }
    });
  }

  private async Task UpdateRetryCount(int retryCount, IStepExecutionContext stepContext) {
    var stepInstance = stepContext.ExecutionPointer;
    stepInstance.RetryCount = retryCount;
    _persistence.UpdateStep(stepInstance); // Note: I don't think this function exists, would need to discuss
  }
}
```

### Example 3 - Registering middleware with dotnet core's native DI

Each of these middleware should be able to be registered with DI just like any other dependency of your app. It would also be nice from a developer experience perspective if we expose some configuration helpers to register it such as the following:

```cs
// Startup.cs
public class Startup {
  public void ConfigureServices(IServiceCollection services) {
    // Use a helper to register middleware
    // Note: Would need to determine if it makes sense to register those under the hood
    // as transient, scoped, or singleton.
    services
      .AddWorkflowMiddleware<SerilogCorrelationMiddleware>()
      .AddWorkflowMiddleware<StepRetryMiddleware>();
  }
}
```

### Workflow Step Middleware

In analyzing this, I think that the best place to add the step hooks would be within `WorkflowExecutor.ExecuteStep` around this call:

```cs
var result = await body.RunAsync(context);
```

I think it could be done one of the following ways:

1. `WorkflowExecutor` would directly take in an `IEnumerable<IWorkflowStepMiddleware>` and implement all of the logic to build and run the middleware chain around the execution of a step body.
2. Rather than implementing the logic directly in `WorkflowExecutor`, there could be a class introduced to the tune of `WorkflowMiddlewareRunner` that handles all of the middleware logic. This would make things easier from a testing perspective and follows the single responsibility principle a bit better.

I'm more in favor of the latter approach.

### Overall Workflow Middleware

I haven't thought about this one as much as I couldn't find as many use-cases for this as for middleware around the individual steps.

Middleware at the overall workflow level would have to be split up into two parts since the entire process is not done within the context of a single method execution. You would basically need some "Beforeware" and "Afterware" to hook into before a workflow starts executing and once a workflow is done executing respectively.

Let's discuss more and see if this is even needed.

## Open Questions

If you are comfortable with us submitting a PR for this functionality, there's a few open questions we'd still need to answer to see what the behavior should be.

- What happens if a workflow step middleware raises an error? To best mimic the behavior of existing middleware implementations like controller middleware and http client delegating handlers, it sounds like it would be best to bubble the middleware up the chain. What would need to happen if it doesn't get handled by any middleware in the chain and bubbles up to the workflow executor?
- The examples above give a rough draft of what I think the API for these middleware should look like. What are your thoughts?
- How should we treat the DI lifetime of the middleware? Should they be scoped? Transient? Singleton? This will likely have to line up with the lifetime of the `WorkflowExecutor`.
- With this pattern, a middleware can now alter the outcome of the workflow step body execution. I think that this is good and can enable some interesting new patterns, but what (if any) implications does this have on the engine as a whole?
- Should this also include middleware for the overall workflow that gets called when it starts as well as when it finishes?
- As far as I'm aware, the `IPersistenceProvider` does not have a way to update the state of an `ExecutionPointer`. In many of the use-cases, it would be useful to update various properties of `ExecutionPointer` such as `ExtensionAttributes` and `PersistenceData`. Do you think it's a good idea to add that to the interface? What would be the implications of doing so?

**Comment by danielgerlag** [comment]
@dflor003 I absolutely love this idea!  This is exactly the direction this project needs to go.
The only thing that stands out to me in your examples is directly updating the persisted workflow from the middleware... I think it might be better to pass information and flags back to the executor which in turn will pass a result back to the queue worker which is responsible for persisting it.  That being said, I imagine there could be use cases where you'd want to update the persisted workflow prior to the step actually completing.. let's say storing the start time, etc...  so I'm open to debate on this.

**Comment by dflor003** [comment]
Thanks! Glad you're on board with it.

As for persisting workflow steps, I think it would definitely be useful to be able to update it prior to the step's completion. I'll have to play around with it while putting the PR together and see how it would look but right now two options come to mind.

1. What I mentioned about exposing some kind of `UpdateStep` method on `IPersistenceProvider`. 
2. Perhaps adding a `Persist` method to `IStepExecutionContext` that will persist any changes to the step. This could either be smart enough to detect changes to the model (i.e. via EFCore's `ChangeTracker`) or you could pass the step in directly. I haven't looked at the other persistence providers besides the EFCore one, so I would like to explore which option is better.

I should be able to have something testable within a week or two. Will post more questions here as they arise.

**Comment by dflor003** [comment]
Quick update. I was able to put together the handling for workflow step middleware fairly easily and it's working well. I'm working on workflow pre/post middleware now and need a little bit of guidance.

On the step middleware, if an exception is raised, I'm letting it bubble up to the workflow executor since that will allow it to get handled by the `IWorkflowErrorHandler` declared for the step.

With workflow instances, however, there is no error handler that can handle the errors and if we let errors bubble up, they will prevent the workflow from starting. What should happen in pre/post workflow middleware in the case that the middleware raises an exception?

My gut feeling is that we should prevent errors in workflow pre/post middleware from bubbling up and crashing the workflow, so I'm thinking of just logging the exceptions and proceeding with the workflow anyways. What are your thoughts?

**Comment by danielgerlag** [comment]
hmmm... my initial thoughts are that if an exception occurs in the pre-workflow middleware, it should bubble the exception up to the caller of `StartWorkflow`? (in that case it could not be async)
For post middleware, probably just fallback to the error handler defined at the workflow or global levels? (you can also define the same error handlers on a workflow or global level as you do a step)

**Comment by dflor003** [comment]
> it should bubble the exception up to the caller of StartWorkflow? (in that case it could not be async)

If we're looking to bubble it up to the caller of `StartWorkflow`, then looks like the best place to inject the middleware would be right before publishing the `WorkflowStarted` event. Around line 89 in `WorkflowController`. Since `StartWorkflow` is already asynchronous and returns a task, I think we should still be able to keep the middleware async, right?

I'm thinking of putting it before it persists the workflow on line 86. That way you can modify the workflow attributes if needed. Does that make sense? Something like this:

```cs
await _middlewareRunner.RunPreMiddleware(wf);
await _persistenceStore.CreateNewWorkflow(wf);
```

> For post middleware, probably just fallback to the error handler defined at the workflow or global levels?

Yep, sounds good. I think that would be best as well.

**Comment by dflor003** [comment]
PR is almost ready! Just writing a few integration tests at this point and I've also added a sample project with a few of the use-cases in the samples folder.

Last bit I need to figure out is the exception handling bit. I was able to get it to bubble up the exception as part of `StartWorkflow` just fine for the pre-workflow middleware.

The post-workflow middleware, however, is a bit trickier than I thought. So if we are to fallback to the error handler defined for the workflow... What should the behavior be for the possible values of `WorkflowErrorHandling`?

- `Retry` - Does this mean retry the entire workflow because of an error in the post workflow middleware?
- `Suspend` - The workflow is already finished. What would we suspend?
- `Terminate` - This one would make sense I guess. We could just set the workflow state to `Terminated`?
- `Compensate` - Is there a concept of a compensation at the workflow level?

Thinking about how we could handle all the possible scenarios, it seems like it may get a bit hairy. I'm wondering if it would be better just to handle the error and log it? Or do you have other suggestions?

**Comment by danielgerlag** [comment]
What if we also had an `OnException` method in the middleware class to enable the engineer to decide exactly what to do?

**Comment by dflor003** [comment]
So are you suggesting a virtual method in `IWorkflow` that will get called whenever we have an exception in the post workflow middleware? With default implementation just logging the exception? If so, that sounds reasonable. 

Since most of it is ready, I'm going to go ahead and submit the PR some time today and we can discuss more implementation details in the PR comments.

**Comment by danielgerlag** [comment]
Either that, or another method in addition to `Handle` on the middleware itself?

**Comment by dflor003** [comment]
Unfortunately, it looks like adding an `OnException` method to `IWorkflow` would break backwards compatibility with any existing workflows since they would all now have to implement that method.

As for adding an additional method to the middleware itself, would there be any benefit of this over just adding a `try/catch` block around the middleware body?

**Comment by danielgerlag** [comment]
It would force the developer to think about what should happen if it fails.  It could also flag an action back to the engine, like suspend, terminate, etc...

**Comment by dflor003** [comment]
Let's continue discussion on the PR that I just put out so that we have the code for context. #684
