### ISSUE TITLE
Parallel foreach inside Saga transaction.

### ISSUE THREAD

**Issue by winosaure** [danielgerlag/workflow-core#679]
Hi,

I have the following json declaration : 

```
{
   "Id":"MySagaTrx",
   "StepType":"WorkflowCore.Primitives.Sequence, WorkflowCore",
   "Saga":true,
   "Do":[
      [
         {
            "Id":"RetrieveData",
            "StepType":"WorkflowCore.Primitives.ForEach, WorkflowCore",
            "Inputs":{
               "Collection":"data.stuff"
            },
            "Do":[
               [
                  {
                     "Id":"DoSomething",
                     "StepType":"MyApp.DoSomething, MyApp",
                     "Inputs":{
                        "MyItem":"context.Item"
                     },
                     "CompensateWith":[
                        {
                           "Id":"UndoDoSomething",
                           "StepType":"MyApp.UndoDoSomething, MyApp",
                           "Inputs":{
                              "MyItem":"context.Item"
                           },
                           "NextStepId":"NextStep"
                        }
                     ]
                  }
               ]
            ]
         }
      ]
   ]
}
```

Let's assume `data.stuff` is string array with 10 items. If the step DoSomething fail and throw an exception with the first index in my array, the step UndoDoSomething will be called for all the other index in the loop. I don't understand why, I must miss something. Why UndoDoSomething will be called everytime in my loop if only 1 DoSomething fail ?

Thank you

**Comment by danielgerlag** [comment]
The `DoSomething` is actually being called 10 times too and throwing 10 exceptions and then undoing 10 times.
This is because the ForEach will create 10 parallel forks of the workflow, that join up again at the end.

**Comment by winosaure** [comment]
Hi Daniel, 
thank you for your answer.
I understand that DoSomething is called 10 times, but I don't understand why it's throwing 10 exceptions if only 1 item fail? if with the 9 others items nothing went wrong it should not throw any error right?
Maybe in my case Saga transaction does not fit my need.

Thank you very much for your time!

**Comment by danielgerlag** [comment]
It's not correct that 1 item failed. 10 items failed, hence 10 exceptions.

**Comment by winosaure** [comment]
Ok I see, Thank you for the information, I close the ticket.
