### ISSUE TITLE
Data cannot be persisted

### ISSUE THREAD

**Issue by markus-codechefs** [danielgerlag/workflow-core#680]
We are trying to update values in the WorkflowInstance.Data which is json serialized in the DB. 
We manage to deserialize it just fine and we update it but when we try to serialize with the code below the old values remain.

` public async Task SaveWorkflowData<T>(string workflowInstanceId, T data) where T : class
        {
            var wfcEntity = await _persistence.GetWorkflowInstance(workflowInstanceId).ConfigureAwait(false);
            wfcEntity.Data = data;
            await _persistence.PersistWorkflow(wfcEntity).ConfigureAwait(false);
        }`

in the Repo code I did not see anything specific that would stop an update. We are using the SQL Server provider.

**Comment by danielgerlag** [comment]
I would advise to rather let WorkflowCore update that data from the `Output` mappings from your steps.  Reaching into the internals like this could have concurrency issues and coupling risks.

**Comment by markus-codechefs** [comment]
Thanks for that. We thought we could use the instance as a vessel for the relevant data being used on the steps. We have a deadline that can change outside of the workflow. But then I guess that data does not belong on the instance.
