### ISSUE TITLE
Schedule used inside While loop block loop iteration

### ISSUE THREAD

**Issue by kostekczwk** [danielgerlag/workflow-core#687]
.NET Core 3.1
WorkflowCore version: 3.2.2
WorkflowCore persistence: PostgreSQL

Hello, I'm trying to implement some reminders for my workflow using `Schedule` operation but I notice taht after add `Schedule` for my workflow, it now not work as I expected. Here is my workflow definition:

```
builder
    .UseDefaultErrorBehavior(WorkflowErrorHandling.Terminate)
    .StartWith<InitializationStep>()
    .Then<SetCurrentStageStep>()
    .While(data => data.CurrentStage != null)
        .Do(bilder => bilder
            .StartWith<NotifyApproverAboutDepartureFormReviewStep>()
            .Schedule(data => data.CurrentStage.Reminder.Timespan)
                .Do(bilder => bilder.StartWith<ApproversReminderStep>())
            .While(data => !data.CurrentStageIsApproved())
                .Do(bilder => bilder
                    .StartWith<MarkDepartureFormAsApprovalPendingStep>()
                    .WaitFor(EventNames.ApproverDecision, data => data.DepartureFormId.ToString(), data => DateTime.UtcNow)
                        .Output((e, data) => { data.RegisterApproverDecision((ApproverDecisionEventData)e.EventData); })
                    .Then<RegisterApproverDecisionStep>()
                    .If(data => data.CurrentStageIsRejected())
                        .Do(bilder => bilder
                            .StartWith<MarkDepartureFormAsRejectedStep>()
                            .Then<NotifyAboutDepartureFormRejectionStep>()
                            .Then<FinalizationStep>()
                            .EndWorkflow())
                    .If(data => data.CurrentStageIsPending())
                        .Do(bilder => bilder
                            .StartWith<MarkDepartureFormAsCorrectionPendingStep>()
                            .Then<NotifyTravelerAboutIncompleteDepartureFormStep>()
                            .WaitFor(EventNames.TravelerCorrections, data => data.DepartureFormId.ToString(), data => DateTime.UtcNow)
                            .Then<NotifyApproverAboutCorrectDepartureFormStep>()))
            .Then<SetCurrentStageStep>())
    .Then<MarkDepartureFormAsApprovedStep>()
    .Then<NotifyAboutApprovedDepartureFormStep>()
    .Then<FinalizationStep>()
    .EndWorkflow();
```

I have problem with second `While` loop which should work until current stage is not approved. Inside second `While` Ioop workflow wait for `ApproverDecision` event and after get it call `data.RegisterApproverDecision` which will cause to set data object as approved (data.CurrentStageIsApproved() will return `true` which should cause to leave second `While` loop). But after success approve my stage, workflow not leave second `While` loop until `ApproversReminderStep` will not be executed. After `ApproversReminderStep` execution workflow leave second `While`, call `SetCurrentStageStep` and continue work. Also in next iteration of main/first `While` loop the situation repeats itself (each time workflow wait for executing `ApproversReminderStep` before leave second `While` loop)

I except that `Schedule` part will be executed independently from rest of workflow - it's a bug or I should change my approach?

**Comment by danielgerlag** [comment]
`Schedule` is meant to run independent of the scope that initiates it.
