### ISSUE TITLE
Distributed queueing and locking using Redis cluster

### ISSUE THREAD

**Issue by aparasur-github** [danielgerlag/workflow-core#689]
Hi,
I using v2.0.0 of "workflow-core" in a multi-node workflow cluster setup .
I am using AWS Elasticache (which is a Redis cluster) as the queue and distributed lock provider. 

The RedisQueueProvider and RedisLockProvider take in just a connection string and not multiple Redis endpoints.
Will this work for my set up? Can the connection string be the Elasticache cluster endpoint or do I need to implement my own version?

The reason I am asking this question is that I am randomly seeing some steps being picked up multiple times for execution and am wondering if it has to with me using a Redis cluster and not a single node Redis.

Thanks.

**Comment by danielgerlag** [comment]
You can specify multiple hosts in the connection string... we use the StackExchange library
see https://stackexchange.github.io/StackExchange.Redis/Configuration

**Comment by aparasur-github** [comment]
Thanks, will try it out.
