### ISSUE TITLE
about the sqlserver 

### ISSUE THREAD

**Issue by hellozhang** [danielgerlag/workflow-core#69]
services.AddWorkflow(x => x.UseSqlServer(@"Server = 117.169.87.18;Database = workflow;User ID = sa;Password = jlkj207.;Trusted_Connection = False;", true, true));

can you show me , where  the sql database structure  file. how can it work ?  and  the data will record  the  **every step ?  maybe  you can  give  a full  example**

**Comment by hellozhang** [comment]
waiting  your  anwser

**Comment by qazq** [comment]
Please refer to [WorkflowInstance.cs](https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Models/WorkflowInstance.cs). The `List<ExecutionPointer> ExecutionPointers` record all the steps of this workflow.

To get `WorkflowInstance` please refer to [WorkflowsController.cs](https://github.com/danielgerlag/workflow-core/blob/master/src/extensions/WorkflowCore.WebAPI/Controllers/WorkflowsController.cs) and see `_workflowStore.GetWorkflowInstances()`, `_workflowStore.GetWorkflowInstance()`

**Comment by danielgerlag** [comment]
@hellozhang this persistence provider uses entity framework core migrations

https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet

You can use the `dotnet ef migrations script` CLI command to generate a SQL script with the schema or the `Script-Migration` command from the package manager console in Visual Studio.

You can use the repository methods as shown by @qazq in the comment above to access it programatically, regardless of which persistence provider you choose to use.
