### ISSUE TITLE
Dynamic loading of workflow definitions

### ISSUE THREAD

**Issue by rashmy-git** [danielgerlag/workflow-core#693]
Hi,
I've currently overridden the IWorkflowRegistry.GetDefinition to fetch the definition from DB. But GetDefinition() is not async and results in a blocking call. Do you suggestions to populate the registry on-demand? With a multi-node cluster, a workflow can be registered and started in one node but can get picked up by another node for one of the step execution, at which time the required workflow definition needs to be made available in the other node as well. For this purpose, a custom implementation of IWorkflowRegistry was done where the method GetDefinition() is overridden to get the relevant workflow definition from DB and load it to the workflow registry.

Thanks

**Comment by danielgerlag** [comment]
Have a look at the Conductor implementation - https://github.com/danielgerlag/conductor/blob/master/src/Conductor.Domain/Services/WorkflowLoader.cs
