### ISSUE TITLE
Bug in GetWorkflowInstances

### ISSUE THREAD

**Issue by ccpony** [danielgerlag/workflow-core#7]
Hello Daniel.  Failure to set a non-zero value to the take parameter in, for example, EntityFrameworkPersistenceProvider.GetWorkflowInstances fails at the line:

`var rawResult = query.Skip(skip).Take(take).ToList();`

and returns no result.  Leads to an Internal Server Error (500) when called through WebApi.

Suggest that a non-zero value (i.e., 10?) be set if take parameter is zero.

Thanks for this great project.

**Comment by danielgerlag** [comment]
Yes, that sounds good.
Would it be possible for you to make the change on your fork and create a pull request?
I want to get more contributors active on this project.

**Comment by ccpony** [comment]
I can do that, although my coding skills don't really match yours.  But minor revisions and bug repairs, sure.

**Comment by ccpony** [comment]
Daniel - I'm not clear about exception handling in stepbodies.  An exception thrown in a stepbody sets the workflow to status 0 and attempts re-tries continuously (until, I presume, there is no exception).  The exception is logged to the console but not reflected back to the UI.  Nor is there any record of the error kept in the database.  What is best practice for handling an exception within the stepbody so that the user is alerted and the information can be conveyed back to technical support?

Corollary to this question: how does one response to an stepbody exception by terminating the workflow (and, hopefully, alerting the developers).

Thanks.

P.S.  I'm spending a lot of time with this application now.  Please direct me as to how I can help.
