### ISSUE TITLE
How to pass multiple values into a PublishEvent

### ISSUE THREAD

**Issue by germandb** [danielgerlag/workflow-core#70]
Hi Daniel, I have a Step that is a WaitFor and I need to pass more than one value to the PublisEvent, how can I achive that?.

And example could be if you change the example 4 and in the MyDataClass add a second property 

`public string StrValue2 { get; set; }`

then in the Step build you add another output

```c#
public void Build(IWorkflowBuilder<MyDataClass> builder)
        {
            builder
                .StartWith(context => ExecutionResult.Next())
                .WaitFor("MyEvent", (data, context) => context.Workflow.Id, data => DateTime.Now)
                    .Output(data => data.StrValue, step => step.EventData)
                   .Output(data => data.StrValue2, step => step.EventData)
                .Then<CustomMessage>()
                    .Input(step => step.Message, data => "The data from the event is " + data.StrValue)
                .Then(context => Console.WriteLine("workflow complete"));
        }
```

I try to define a new instance of MyDataClass and assign values into StrValue and StrValue2 and pass that object into the publishEvent 
`var values = new MyDataClass();
values.StrValue=1;
values.StrValue2=2;
host.PublishEvent("MyEvent", workflowId, values);`

the problem is that the ProcessOutputs recive in the body the entity MyDataClass and dosn't now how to look for the values to assign in the output data.

**Comment by danielgerlag** [comment]
Have you tried casting the `EventData`, like this? 

`.Output(data => data.StrValue2, step => (step.EventData as MyDataClass).StrValue2)`

**Comment by germandb** [comment]
Hi Daniel, I try what you suggest, but doesn't work.
When ProcessOutputs its call the body have the WaitFor object and when try to get the resolvedValue from the body the output is the values object that I pass in the PublishEvent.

When the function try to set the value for the output it fails because resolvedValue its and object and not a string.

I make a change in the ProcessOutputs function to look if resolvedValue get properties and in that case get the value of that property and if not resolve as before.

Could you please look at this,

`private void ProcessOutputs(WorkflowInstance workflow, WorkflowStep step, IStepBody body)
        {
            foreach (var output in step.Outputs)
            {
                var member = (output.Target.Body as MemberExpression);
                var resolvedValue = output.Source.Compile().DynamicInvoke(body);
                var data = workflow.Data;
                if (resolvedValue.GetType().GetProperties().Count() > 0)
                {
                    var resolvedData = resolvedValue.GetType().GetProperty(member.Member.Name).GetValue(resolvedValue);

                    data.GetType().GetProperty(member.Member.Name).SetValue(data, resolvedData);
                }
                else
                {
                    data.GetType().GetProperty(member.Member.Name).SetValue(data, resolvedValue);
                }
            }
        }`

**Comment by danielgerlag** [comment]
Could attach the project where you tried to do the cast?

**Comment by germandb** [comment]
Hi Daniel your past solution was correct, I was loading the workflow from a Dll and didn't realize that the proyect with that dll wasn't compiling in the solution. So I was using and old definition of the Workflow.

Thanks for your time.

**Comment by bautigaraventa** [comment]
Hi, How could I achieve multiple Outputs in the EventData when I want to load my workflow by JSON? I don't know how to do the "cast", I mean this:
``
(step.EventData as MyDataClass).StrValue2
``
