### ISSUE TITLE
Question: Multi workflow engines on one workflow db

### ISSUE THREAD

**Issue by JakeKuzman** [danielgerlag/workflow-core#703]
Hi, 
I have situation where i assign 2 workflow services to one db storage. If i initialize both service the same way, putting the sql connection string with UseSqlServer, then i get both workflow engines triggered when an event occurs. If i initialize one with UseSqlServer and one with just AddWorkflow then only one gets triggered. (The AddWorkflow get the Connection String from default WorkflowsDatabase setting)

Since i want to use the same db for 2 services this behavior works for me, but i just wanted to ask if this is a bug or intended behavior, and can i rely on this.

**Comment by send2vinnie** [comment]
You are probably asking the support for multiple-node configuration? It's recommended to check the closed issue: https://github.com/danielgerlag/workflow-core/issues/259

**Comment by danielgerlag** [comment]
https://workflow-core.readthedocs.io/en/latest/multi-node-clusters/
