### ISSUE TITLE
PostWorkflow middleware will be executed multiple times for one workflow

### ISSUE THREAD

**Issue by brucezlata** [danielgerlag/workflow-core#707]
And I am confuse about return next() in below code?
Why they are the same return next() whatever I get compeletedtime or not
    public Task HandleAsync(
        WorkflowInstance workflow,
        WorkflowDelegate next
    )
    {
        if (!workflow.CompleteTime.HasValue)
        {
            return next();
        }

        var duration = workflow.CompleteTime.Value - workflow.CreateTime;
        _log.LogInformation($@"Workflow {workflow.Description} completed in {duration:g}");

        foreach (var step in workflow.ExecutionPointers)
        {
            var stepName = step.StepName;
            var stepDuration = (step.EndTime - step.StartTime) ?? TimeSpan.Zero;
            _log.LogInformation($"  - Step {stepName} completed in {stepDuration:g}");
        }

        return next();
    }

**Comment by brucezlata** [comment]
Is that true if I want to one post workflow middleware executed only once. It should be registered the first order.
For example:

AddDescriptionWorkflowMiddleware will be called only once. But PrintWorkflowSummaryMiddleware will be called twice? 

     public void ConfigureServices(IServiceCollection services)
    {
        ...

        // Add workflow middleware
        services.AddWorkflowMiddleware<AddDescriptionWorkflowMiddleware>();
        services.AddWorkflowMiddleware<PrintWorkflowSummaryMiddleware>();

        // Add step middleware
        services.AddWorkflowStepMiddleware<LogCorrelationStepMiddleware>();
        services.AddWorkflowStepMiddleware<PollyRetryMiddleware>();

        ...
    }

**Comment by dflor003** [comment]
Hey! I implemented the workflow/step middleware feature. As far as I'm aware, each middleware should get executed exactly once per workflow. Are you seeing something different than this behavior?

The way that it works is that it builds a chain of middleware functions where calling `next()` just invokes the next middleware in the chain.

In the example above, if you registered `AddDescriptionWorkflowMiddleware` and `PrintWorkflowSummaryMiddleware` as your only two workflow middleware, it will run the following for each workflow in this order:

```
AddDescriptionWorkflowMiddleware -> PrintWorkflowSummaryMiddleware
```

**Comment by brucezlata** [comment]
@dflor003 Thanks for your reply. It is a real great job for pre/post middleware.
I found post middleware was executed multiple times in different threads. (I logged it and found pid is different)

I did some investigation. I doubt it caused by concurrency.

            if ((workflow.NextExecution != null) || (workflow.ExecutionPointers.Any(x => x.EndTime == null)))
                return;

            workflow.Status = WorkflowStatus.Complete;
            workflow.CompleteTime = _datetimeProvider.UtcNow;

            await _middlewareRunner.RunPostMiddleware(workflow, def);

**Comment by brucezlata** [comment]
BTW, I cannot repo in local. I deployed workflow core as service in cloud.
Is there any other way to log workflow summary?

**Comment by dflor003** [comment]
Hmm... Are you running in multi-node mode? i.e. Do you have multiple instances of the app running for your app in the cloud?

**Comment by brucezlata** [comment]
You recall me. I use azure app service. There is another slot node peering with main service. So, slot service also will pick up uncompleted workflow from cosmos database and start to run.

Actually, it is multi-node mode. Is that true?

**Comment by dflor003** [comment]
Did you set up a locking provider such as redis for this? I've seen it happen where if you don't set up a locking provider, any of the nodes can pick up the same workflow for processing multiple times. In that scenario, it would definitely run the middleware multiple times.

**Comment by brucezlata** [comment]
@dflor003 , sorry for late reply. Yesterday I fixed with DLM using azure storage blob.
Great thank you for your help.
