### ISSUE TITLE
Send More Info via PublishUserAction

### ISSUE THREAD

**Issue by Farshadhn** [danielgerlag/workflow-core#708]
Hi all,
I need to send an object via PublishUserAction. i mean instead of using : 
host.PublishUserAction(openItems.First().Key, "MYDOMAIN\\someuser", "Yes")
want to Send :
host.PublishUserAction(openItems.First().Key, "MYDOMAIN\\someuser", "Yes" , newObj)
I want to use this new object as an output for :

                .UserTask("Do you approve", data => "MYDOMAIN\\someuser")
                    .WithOption("Yes", "I approve").Do(then => then
                        .StartWith(context => Console.WriteLine("You approved"))
                    )
                    .WithOption("no", "I do not approve").Do(then => then
                        .StartWith(context => Console.WriteLine("You did not approve"))
                    )
                .Output(data => data.Definition, step => step .Definition)

Like what you can use for Events:

                .WaitFor(nameof(Leader), (data, context) => context.Workflow.Id, data => DateTime.Now)
                 .Output(data => data.Definition, step => step.Definition)

**Comment by danielgerlag** [comment]
The Users package is mostly meant as an example of how one can build extension modules around the core library, you could use it as a template for making your own customized extension that supports your use case.
