### ISSUE TITLE
How to utilize async steps

### ISSUE THREAD

**Issue by dimademi** [danielgerlag/workflow-core#717]
Hey, how does `workflow-core` treats steps that inherit from `StepBodyAsync` differently from `StepBody`? 

I saw i could use `.Parallel()` with regular steps as well so i think i am missing something.

Care to explain or add a sample code? What is the best practice? 

Thanks a lot!

**Comment by danielgerlag** [comment]
- https://workflow-core.readthedocs.io/en/latest/getting-started/#steps
- https://workflow-core.readthedocs.io/en/latest/control-structures/#parallel-paths
