### ISSUE TITLE
Can I have async workflows resuming in step 3 with state that steps 1 and 2 completed successfully in previous datetime?

### ISSUE THREAD

**Issue by weare8** [danielgerlag/workflow-core#718]
I am not sure this library is built for scenarios like that but worth checking with you guys because it is close to what I need but my requirements are asynchronous between steps (maybe Sagas?). See below my exact business requirement.

- User Journey Workflow Start
  - Step 1: Send SMS
  _... User will receive the SMS and take some action by clicking a link
  ... we capture this happened to some database...
  ... somehow the workflow is checking step 2 condition (recurring timer?) based on the above database state status if the link clicked_
  - Step 2: Database state exists now check data details and do something fulfilling step 2 and move to step 3 or step X
  - Step 3: Push notification to user
  - Step X: Some other business requirement

Any ideas on how this would be implemented and if feasible with workflows?

**Comment by danielgerlag** [comment]
External Events - https://workflow-core.readthedocs.io/en/latest/external-events/

**Comment by weare8** [comment]
Thanks, I will check it out. Great work!
