### ISSUE TITLE
Human workflow - "Go Back"

### ISSUE THREAD

**Issue by glaidler** [danielgerlag/workflow-core#719]
Hi, we're hoping to use workflow core to drive a human workflow engine - in essence a user-configurable "Wizard engine", with each Step mapping to a wizard step that the user completes before hitting "Next".  

The actual workflow steps don't do anything; we're really just wfc as a "wizard routing engine" - they do the same as the WaitFor primitive; they just wait for a "PROCEED" event with the current ExecutionPointer.Id as the key;

The "Next" button effectively just publishes this event with the "LastExecutionPointerId" as the key and the engine works perfectly.

This is all working great, but one of the requirements is for the user to hit the back button.  I know there are other questions about this, and they indicate that the "NextStepId" could be set, but this would remove the desired routing.

To get around this, I'm looking at several options:
a) whether we can just mark the previous steps "ExecutionPointer.EventPublished" flag to false in the db - this would bypass any middleware so likely to have side-effects?
b) Exploring the workflowHost.PersistenceStore.MarkEventUnprocessed, but this only marks it as unprocessed in the wfc.Event table, but doesn't update the ExecutionPointer record.

Any suggestions how we can achieve this?

**Comment by danielgerlag** [comment]
Perhaps use decision branches to loop back?
https://workflow-core.readthedocs.io/en/latest/control-structures/#decision-branches

**Comment by glaidler** [comment]
Thanks for getting back to me - can a decision branch be applied at runtime to take the executionpointer to the previous step?

**Comment by danielgerlag** [comment]
yes it can.
