### ISSUE TITLE
How to implement a cancellable waitfor

### ISSUE THREAD

**Issue by marc-mueller** [danielgerlag/workflow-core#72]
Hi

We have the requirement for a workflow, that we are waiting for two events in parallel. If one event is fired, we should finish the parallel processing and continue after the join. This means that if one event occurred, the other wait for should be cancelled.

I have seen that there is a cancellable step but I did not get it to work. Could anybody provide a solution on how to cancel a waitfor step?

Thank you in advance for your help!
Marc

Update: A parallel with a waitAny() whould also solve our problem.

**Comment by danielgerlag** [comment]
Hi Marc,

We don't have that functionality (yet), for now would it make sense to implement a single `WaitFor` and branch the workflow based on the data passed to that `WaitFor`?
Looking forward, I will definitely keep this scenario in mind for a future release.

**Comment by marc-mueller** [comment]
Hi Daniel

Thanks for your reply. If this is the only option right know, we have to think about that. The logic is a little bit more complex then described above and we'll end up with a loop and multiple if statements. 

I played around with your cancellable task, but without any success. Does the waitfor fully block the execution internally? Would a waitany task for a parallel fork be an easier solution? 

Another short question: Is there any way to check if a published event was handled? 

Thanks, 
Marc

**Comment by danielgerlag** [comment]
Hi Marc,

So the `CancellableStep` class is used internally, currently only by the `.Recur` fluent builder over here:

https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/FluentBuilders/StepBuilder.cs#L360

I don't see why we couldn't overload the `.WaitFor` methods to also use this wrapper, over here: 

https://github.com/danielgerlag/workflow-core/blob/master/src/WorkflowCore/Services/FluentBuilders/StepBuilder.cs#L114

If we had to implement the cancellation functionality as per it's use on the `Recur` step, would that solve your problem?

**Comment by marc-mueller** [comment]
Hi Daniel

Yes, that would really help if we could wrap the WaitFor in a CancellableStep. I tried exactly this with an extension method. Did I understood it correctly that I can provide an expression which is evaluated over and over and if true then the contained step is cancelled?

Could you show me how I correctly wrap it? I think I did it wrong.

Best,
Marc

**Comment by danielgerlag** [comment]
Hi Marc,

I have just published version 1.3.3 to NuGet, which adds a parameter to the `WaitFor` methods, allowing you to specify a cancel condition.  See usage in the test here: https://github.com/danielgerlag/workflow-core/blob/master/test/WorkflowCore.IntegrationTests/Scenarios/CancelledEventScenario.cs

Let me know if this solves your problem

**Comment by marc-mueller** [comment]
Hi Daniel

Thanks for your support! We did a quick test last week and it looked good so far. This week, we will integrate it into the big solution and I'll give you the more detailed feedback when we finish the integration.

Thanks
Marc

**Comment by danielgerlag** [comment]
Glad to help, let me know if you run into any other issues
