### ISSUE TITLE
How to use inputs and outputs in json？I got an error！

### ISSUE THREAD

**Issue by Jerryzxr** [danielgerlag/workflow-core#725]
When i define my workflows in JSON，vs warns me ‘No property or field 'XXX' exists in type 'Object'’.
Why can't I find this field? How to get the value in output？
Please help me, thank you!

**Comment by Jerryzxr** [comment]
When i define your workflows in JSON，vs warns me ‘No property or field 'XXX' exists in type 'Object'’.
Why can't I find this field? How to get the value in output？
Please help me, thank you!

**Comment by ShaoYir** [comment]
Can you provide your JSON ？

**Comment by danielgerlag** [comment]
You haven't set the `DataType` of your workflow - https://workflow-core.readthedocs.io/en/latest/json-yaml/

**Comment by Jerryzxr** [comment]
> You haven't set the `DataType` of your workflow - https://workflow-core.readthedocs.io/en/latest/json-yaml/
Sorry,i have one another question.
How to spell my if condition? Just like"<<if(data=>data.XXX==‘’)>>"or"<<if(data.XXX==‘’)>>"？

{
    "Id": "MyIfStep",
    "StepType": "WorkflowCore.Primitives.If, WorkflowCore",
    "NextStepId": "...",
    "Inputs": { "Condition": "<<expression to evaluate>>" },
    "Do": [[
        {
          "Id": "do1",
          "StepType": "MyApp.DoSomething1, MyApp",
          "NextStepId": "do2"
        },
        {
          "Id": "do2",
          "StepType": "MyApp.DoSomething2, MyApp"
        }
    ]]
}

**Comment by danielgerlag** [comment]
Here is the docs for the expression language - https://github.com/zzzprojects/System.Linq.Dynamic.Core/wiki/Dynamic-Expressions#expression-language
