### ISSUE TITLE
MongoDB persistence provider GetSubscriptions asOf condition correct?

### ISSUE THREAD

**Issue by xavidram** [danielgerlag/workflow-core#729]
https://github.com/danielgerlag/workflow-core/blob/d7b3c65028f5badadccca8dfcdb683c0fa13d664/src/providers/WorkflowCore.Persistence.MongoDB/Services/MongoPersistenceProvider.cs#L234

In the GetSubscritions function query for the MongoDb persistence provider. The `AsOf` condition should be greater than the date in the parameter no?

When I look at the function GetEvents in the same class, the `AsOf` condition in the query is greaterthan rather than less than the `AsOf` Datetime.

**Comment by danielgerlag** [comment]
No, this is correct, we want the subscriptions that already exist at this point in time.  For GetEvents, we want all the future scheduled events.
