### ISSUE TITLE
Is it possible to use this library in projects using .NET 4.7 but not using Core

### ISSUE THREAD

**Issue by SudhirMangla** [danielgerlag/workflow-core#73]
this statement is not working in Asp.net MVC 5 (.NET 4.7)
IServiceCollection services = new ServiceCollection();\

Error I am getting is 
The type or namespace name 'ServiceCollection' could not be found.

Is it possible to use this library in projects using .NET 4.7 but not using Core

**Comment by danielgerlag** [comment]
you need to add the `Microsoft.Extensions.DependencyInjection - 1.1.0` NuGet package

**Comment by SudhirMangla** [comment]
thanks, this solves the issues.
