### ISSUE TITLE
What's the correct way to delete a definition?

### ISSUE THREAD

**Issue by smadurange** [danielgerlag/workflow-core#731]
Hi I'm trying to allow deleting a workflow definition in the following order:

1. Delete the definition from mongo.
2. Terminate all workflow instances belonging to this definition (using `WorkflowController.Terminate()`.
3. Delete all the workflow execution errors of any workflow instances belonging to this definition from mongo.
4. Delete all the workflow instances belonging to this definition from mongo.
5. Deregister workflow definition from workflow registry.

However, I see that this leaves some stuff in redis queue. So, in workflow server, I get errors like

`my_app | 2020-12-17 10:15:58.6793|1.0.0.0|49||WorkflowExecutor|ERROR| EventId:  | Workflow 63d0541f-1bc3-429e-9661-f4d21ff02aad version 1 is not registered`

How can I make sure redis is cleaned when workflow instances are terminated and deleted from mongo?

**Comment by danielgerlag** [comment]
Workflow Core does not persist the definitions to the DB... unless you are using Conductor?

**Comment by smadurange** [comment]
@danielgerlag I'm hosting workflow core in an API like in Conductor and saving the definitions. I think I didn't phrase the question well. What I would like to do is to stop a running workflow instance (I use `IWorkflowController.Terminate()` for this), ensure no new workflows instances are spawned for this definition and delete the persisted workflow instance from storage.

I think the issue is with the redis backplane which doesn't clean itself (or perhaps I delete the workflow instance from storage too soon) when the terminate command is issued?

**Comment by smadurange** [comment]
Closing this. This doesn't have anything to do with workflow core.
