### ISSUE TITLE
Resume Workflow from Admin Portal

### ISSUE THREAD

**Issue by mabo4567** [danielgerlag/workflow-core#736]
Hi,

I have a solution which uses the workflow core engine. Separately I want to build up a admin portal where I can resume failed workflows. As this solution does not know the classes contained in the workflow data property i get the following error

 [Error: System.FormatException: An error occurred while deserializing the Data property of class WorkflowCore.Models.WorkflowInstance: Unknown discriminator value ''.

Is it possible to implemented a independet reprocessing admin portal?

Thanks for help

**Comment by dimademi** [comment]
Care to explain what are you trying to deserialize `WorkflowInstance` for? 

You have 2 options:
1. Use the same solution for your workflow engine and your admin portal
2. Write a REST api for your workflow engine and call it via the admin portal. (see [conductor](https://github.com/danielgerlag/conductor) for a general idea)

**Comment by mabo4567** [comment]
Thanks for the answer. I am aware of these solution but would prefer two seperate solution and to have a common implementation in the admin portal. In future I will have several micro services with workflow core and i do not want to be forced to make a implementation on the admin portal for each. So there is not way to execute the ResumeWorkflow without knowing the classes in the workflow data object?

**Comment by dimademi** [comment]
Im not sure what do you mean by "without knowing the classes ...", but I don't think it is possible. 
`ResumeWorkflow` is a function of `WorkflowHost`. You need to call it from the running `WorkflowHost`. 

You should start now with having the workflow engine as a microservice.

**Comment by danielgerlag** [comment]
You can use the `IWorkflowController` and inject it into your 2nd project's class with DI, and configure the host to not run any workflows.
