### ISSUE TITLE
Use object serialization for workflow data in MongoDB provider

### ISSUE THREAD

**Issue by danielgerlag** [danielgerlag/workflow-core#74]
Currently, it is serialized as a string which makes it difficult to run queries against the persistence store that can evaluate the contents of the custom workflow data

**Comment by ewyuen** [comment]
Are you going to provide an API (maybe from the workflow host) to retrieve the data of a current running workflow?

**Comment by danielgerlag** [comment]
you could achieve this currently by using the `IPersistenceProvider` to grab the workflow and then cast the `Data` property to the type
