### ISSUE TITLE
Azure service bus SessionId not set

### ISSUE THREAD

**Issue by legarasu** [danielgerlag/workflow-core#741]
Actually I am working in an application that uses Azure Service Bus so I am using Azure Provider, I have a problem because all messages go to dead letter queue and the error in bus tells: **"Session enabled entity doesn't allow a message whose session identifier is null."**

This is true because in Azure provider (_ServiceBusLifeCycleEventHub_) the send operation does not set a **SessionId** for the message (_PublishNotification(...)_ method) I have tried to set it, for example using WorkflowId, and it starts to work and the message goes to right queue and is received by same/another node.. 

After that another error comes from Azure Bus, '**It is not possible for an entity that requires sessions to create a non-sessionful message receiver'** and the message is not removed from queue, seems this is because __subscriptionClient_ should not call _CompleteAsync(..._) method instead only _Task.CompletedTask_ () as you can check [here](https://medium.com/@samuelhutama/net-core-azure-service-bus-send-and-receive-message-in-session-enabled-subscription-3f8ffecc47de)

Maybe I am wrong but seems a bug based on actual implementation.

**Comment by danielgerlag** [comment]
it sounds like you configured your topic to require sessions?

**Comment by legarasu** [comment]
Yes, sessions are configured in topic, otherwise with no sessions configured I receive this error (using **WebApiSample** in WorkflowCore) 

_warn: WorkflowCore.Providers.Azure.Services.ServiceBusLifeCycleEventHub[0]
      Error on receiving events
System.InvalidOperationException: A sessionful message receiver cannot be created on an entity that does not require sessions. Ensure RequiresSession is set to true when creating a Queue or Subscription to enable sessionful behavior. TrackingId:d0000e1c-694b-4d01-9a7d-914ad14605b9_B12, SystemTracker:slaterandgordon:Topic:XXXX|YYYY, Timestamp:2021-01-10T00:31:00 TrackingId:3c8a6b1cac6e4769be5a5eee006ed083_G13, SystemTracker:gateway7, Timestamp:2021-01-10T00:31:00
   at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.SessionReceivePump.SessionPumpTaskAsync()_

**Comment by danielgerlag** [comment]
@glucaci could you chime in here?

**Comment by jiripoledna** [comment]
Hi I have the same issue, It is not working when I create not sessioned suscribrition, but when it is created, then all events ends in DLQ because it has no session Id set.
