### ISSUE TITLE
How to resume workflow? Please Help me.

### ISSUE THREAD

**Issue by Jerryzxr** [danielgerlag/workflow-core#745]
If i start a IWorkflowHost and i use SuspendWorkflow,i can't reusme this workflow. If i stop this IWorkflowHost ,can i reusme this workflow?
And anthor question ,how to use mysql persistence? i don't know how to resume workflow.
Please help me! Thank you!

**Comment by danielgerlag** [comment]
If you use a persistence store then your workflows can resume on another instance of the host automatically.  If you call `SuspendWorkflow` on a specific workflow, you will need to call `ResumeWorkflow`

https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Persistence.MySQL
