### ISSUE TITLE
Cannot use a boolean value for workflow data

### ISSUE THREAD

**Issue by ewyuen** [danielgerlag/workflow-core#75]
I encounter an issue on mapping a boolean value in the data context to the output of a step.

For example, my data context is like below,

 public class MyData
    {
        public string Name { get; set; }
        public bool TrueOrFalse { get; set; }
    }

I register a workflow as below.
host.RegisterWorkflow<MyWofkflow, MyData>();

Then, I build a step of my workflow as follow,

 .WaitFor("MyEvent", (data, context) => context.Workflow.Id)
 .Output(data => data.TrueOrFalse, step => step.EventData)

This throws an exception at WorkflowExecutor.ProcessOutputs.   This is because the expression data.TrueOrFalse is not a MemberExpression since TrueOrFalse is a value type.   The expression is actually resolved as an UnaryExpression.

I have a fix as below.

 private void ProcessOutputs(WorkflowInstance workflow, WorkflowStep step, IStepBody body)
        {
            foreach (var output in step.Outputs)
            {
                var member = (output.Target.Body as MemberExpression);
                var unary = output.Target.Body as UnaryExpression;
                var resolvedValue = output.Source.Compile().DynamicInvoke(body);
                var data = workflow.Data;

                if (member != null)
                {
                    data.GetType().GetProperty(member.Member.Name).SetValue(data, resolvedValue);
                }
                else
                {
                    if (unary != null)
                    {
                        var memberExpression = unary.Operand as MemberExpression;
                        if (memberExpression != null)
                        {
                            data.GetType().GetProperty(memberExpression.Member.Name).SetValue(data, resolvedValue);
                        }
                    }
                }
            }
        }

I think this fix the issue.  I think the codes may have other areas which may encounter similar issue.

**Comment by danielgerlag** [comment]
@ewyuen , thanks for reporting this... I have found another workaround is to cast the `step.EventData` as follows

```c#
.WaitFor("MyEvent", (data, context) => context.Workflow.Id)
.Output(data => data.TrueOrFalse, step => (bool)step.EventData)
```

but I will look into fixing this within the library itself
