### ISSUE TITLE
Purge terminated workflows

### ISSUE THREAD

**Issue by DronVelikii** [danielgerlag/workflow-core#750]
Hello,
I faced with the problem that workflows with status "Terminated" are not removed from database. 
PurgeWorkflows(WorkflowStatus status, DateTime olderThan) method is used. 
I think the reason is that olderThan param is required but terminated workflows might not have CompleteTime (all workflows in my case)

Am I using this method incorrectly or there is another way to purge terminated workflows ?
Thanks

**Comment by mrcopperbeard** [comment]
Perhaps it will be useful to set `CompleteTime` when we terminate a workflow? I can make PR

**Comment by danielgerlag** [comment]
@mrcopperbeard that would be awesome

**Comment by mrcopperbeard** [comment]
Done. https://github.com/danielgerlag/workflow-core/pull/797
