### ISSUE TITLE
How to use 'UseDefaultErrorBehavior' in  JSON or YAML ?

### ISSUE THREAD

**Issue by sundakai** [danielgerlag/workflow-core#756]
I can set the global strategy per definition with

```
builder
  .UseDefaultErrorBehavior(WorkflowErrorHandling.Terminate)
  .StartWith(...)
```
But How to use this in  JSON or YAML .
Or how can I set All builder default error handling to 'WorkflowErrorHandling.Terminate' ?

**Comment by sundakai** [comment]
Emmm...Sorry, my english is not good, please don't care about this.

**Comment by danielgerlag** [comment]
use `DefaultErrorBehavior` and `DefaultErrorRetryInterval` in the root of the JSON or YAML document

**Comment by sundakai** [comment]
> use `DefaultErrorBehavior` and `DefaultErrorRetryInterval` in the root of the JSON or YAML document

thanks a lot ,is working.
I should have expected it.
sorry for the inconvenience.
