### ISSUE TITLE
Using Redis persistence , single workflow instance id is executing by mutliple nodes with REDIS persistance

### ISSUE THREAD

**Issue by vigneshwarb6** [danielgerlag/workflow-core#758]
We have starting using Redis persistence , and after that single workflow instance id is executing by mutliple nodes and causing issues as it is executing the queries multiple times. we used distributed locking and queuing mechanism but still not working. can you please help with the issue.

**Comment by danielgerlag** [comment]
How did you configure workflow core? can you paste it here?

**Comment by vigneshwarb6** [comment]
cfg.UseRedisPersistence(connectionString, prefix);
cfg.UseDistributedLockManager(sp => new RedisLockProvider(connectionString, sp.GetService<ILoggerFactory>()));
cfg.UseQueueProvider(sp => new RedisQueueProvider(connectionString, prefix, sp.GetService<ILoggerFactory>()));

**Comment by vigneshwarb6** [comment]
Daniel, we used RedisPersistence first but after seeing the issue we used QueueProvider and DistributedLock even then we see the issue.

**Comment by danielgerlag** [comment]
See the readme for the redis package on how to configure - https://github.com/danielgerlag/workflow-core/tree/master/src/providers/WorkflowCore.Providers.Redis
