### ISSUE TITLE
Wait for event trigger multiple times due to multiple entry into execution pointer

### ISSUE THREAD

**Issue by bhushan007** [danielgerlag/workflow-core#763]
.WaitFor(WorkflowTemplateContants.pendingAppraiser2, (data, context) => context.Workflow.Id, data => DateTime.Now)
                     .Output(data => data.EventData, step => step.EventData)
                 .Then<Application.Workflow.Step.AppraisalTaskResponse>()

publish event from api controller :

 Event message = context.Message as Event;
            await _host.PublishEvent(message.EventName, message.EventKey, message.EventMessage,DateTime.Now);

Solution are deployed into multiple docker pod

**Comment by danielgerlag** [comment]
Have you setup a distributed lock manager?

**Comment by danielgerlag** [comment]
https://workflow-core.readthedocs.io/en/latest/multi-node-clusters/
