### ISSUE TITLE
WorkflowCore.Persistence.SqlServer 3.3.0 not compatible with .NET Framework anymore

### ISSUE THREAD

**Issue by fhsakai** [danielgerlag/workflow-core#765]
Dear Daniel,
Seems WorkflowCore.Persistence.SqlServer version 3.3.0 start to have dependency with 
Microsoft.EntityFrameworkCore.SqlServer **5.0.1** that make it indirectly been dependent to **.net standard 2.1**
Is that the purpose of this version?
Will we have future version that will keep the **.net standard 2.0** support, to allow the WorkflowCore to be used with .NET framework applications?

Best Regards,

Flavio

**Comment by danielgerlag** [comment]
3.1.1 still targets .net standard 2.0, and has all the same functionality.  If there is sufficient demand, we can create a fork that stays on the older version of EF Core.  Unfortunately, the EF Core team has dropped support for older versions of .net.
You could also look at upgrading to .net 5.

**Comment by fhsakai** [comment]
Hi @danielgerlag , 
Thank you for the feedback.
We are using 3.1.1, we will keeping using it for while.
Unfortunately migrate the current system to .NET 5, will be a big challenge, maybe we will have to think to uncouple some how the WFC from the Current Service and integrate them.

Best Regards,

Flavio
