### ISSUE TITLE
WorkflowConsumer throws null reference exception

### ISSUE THREAD

**Issue by smadurange** [danielgerlag/workflow-core#777]
I'm using 2 workflow core nodes with redis backplane and mongodb.

Steps to reproduce:

1. Create a definition.
2. Start a large number of workflows for that definition (like 20,000 workflows within about 5 minutes).
3. Delete the workflow definition by first deregistering the definition from the workflow registry, publish a notification to redis so that the second node also deregisters the definition, call `TerminateWorkflow` of `IWorkflowController` in the first node for all the currently running workflows under the definition, delete any workflow errors under each of those workflows, delete workflow instances from mongodb, and finally delete the workflow definition from mongodb.

I see the exeption:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer+<ProcessItem>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at WorkflowCore.Services.BackgroundTasks.WorkflowConsumer+<ProcessItem>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WorkflowCore.Services.BackgroundTasks.QueueConsumer+<ExecuteItem>d__18.MoveNext()
```

May be I'm doing the deletion wrong? It looks like this is caused by the workflow entries in redis. I thought when we issue terminate command on a workflow, it will also remove the entries from redis.

**Comment by danielgerlag** [comment]
Sounds like there are still active workflows against the definition you are deleting?

**Comment by smadurange** [comment]
Yes, which is strange because I issue the terminate command for the workflows. Then I check in mongo if there are anymore active workflows and only when there are none, I start deleting the definition. At this time, I still see a large number of entries in redis list though. Does `IWorkflowController.TerminateWorkflow()` makes sure it cancels any scheduled tasks in the redis list?

**Comment by smadurange** [comment]
Didn't find anything new on this and didn't observe this lately.
