### ISSUE TITLE
Code is not thread safe while adding a key in a dictionary

### ISSUE THREAD

**Issue by georgebratu** [danielgerlag/workflow-core#778]
Hi Daniel,

Please revisit https://github.com/danielgerlag/workflow-core/pull/732
I added a comment there explaining the issue. The code is not thread safe and is prone to errors.

**Comment by georgebratu** [comment]
I have received now an email containing only this link https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/lock-statement
You said it was fixed using ConcurrentDictionary but we still got an exception saying the key is already present on line

`_activeTasks.Add(item, waitHandle);`

ConcurrentDictionary would be usefull if the could would have been like this:

```
if (!_activeTasks.Contains(item))
{
    lock(_activeTasks)
    {
        if (!_activeTasks.Contains(item))
        {
            _activeTasks.Add(item, waitHandle);
        }
    }
}
```

But you have code that runs between Contains and Add method calls.

**Comment by danielgerlag** [comment]
agreed, I think doing that check makes more sense than https://github.com/danielgerlag/workflow-core/pull/732/commits/fd30e5c0e7479c10a9dfed8e00f2820cd912e27a
Thanks for pointing this out.

**Comment by georgebratu** [comment]
I used a "while" loop instead of goto label, maybe making it less visible.

**Comment by georgebratu** [comment]
So will you agree with my pull request changes ? Did you understood the problem I was describing ? Did you acknowledge that there is a problem with the existing code ?

**Comment by danielgerlag** [comment]
Yes, but I think the PR is overly complex... I prefer the solution you suggested above.

**Comment by georgebratu** [comment]
The thing is that you have some logic that I want to keep between checking if the key exists and the moment you add the key to the dictionary. So that's why I am trying to jump to the place you check if the key exists.

```
if (hasTask)
{
    _secondPasses.Add(item);
    if (!EnableSecondPasses)
        await QueueProvider.QueueWork(item, Queue);

    skipExecute = true;
    break;
}

_secondPasses.TryRemove(item);
```

So if I find out that inside the lock, the key is not in the dictionary, I want to go back and execute the above code.
