### ISSUE TITLE
documenation is not in readable format

### ISSUE THREAD

**Issue by krishnadasika** [danielgerlag/workflow-core#779]

**Comment by danielgerlag** [comment]
@krishnadasika  Please don't post subject lines without proper descriptions of the issue.
Could you describe how/why the documentation is not readable?

**Comment by krishnadasika** [comment]
https://github.com/danielgerlag/workflow-core/wiki/01.-Getting-started

check this link .. i can see html but not any text

**Comment by danielgerlag** [comment]
try this one - https://workflow-core.readthedocs.io/en/latest/getting-started/
