### ISSUE TITLE
Is there a way to do parallel step asynchronous?

### ISSUE THREAD

**Issue by hsnuscars** [danielgerlag/workflow-core#78]
Hello Daniel,

I tried sample 9 and sample 13, seems it will run all first step of parallel tasks and then second ones.
For example, in sample 13, Item 2.1 will not come before 1.1 even if Item 1.1 takes a lot of time.
Did I miss something to make it asynchronous?

Thanks.

**Comment by danielgerlag** [comment]
Hi,

If you add a `.Delay(data => TimeSpan.FromSeconds(5))` or a `.WaitFor` within those tasks, you will notice the async processing.  The parallel feature does not execute steps within a workflow on separate threads, (only one step can execute on a workflow at a time) but any blocking steps (eg. `WaitFor` or `Delay`) will only block on the current path.

**Comment by hsnuscars** [comment]
Thanks a lot, it really help.
