### ISSUE TITLE
"WaitFor" in a "Do" loop only works the first time in the loop

### ISSUE THREAD

**Issue by ewyuen** [danielgerlag/workflow-core#79]
I am trying to put a WaitFor within a Do loop, where Context.Count is a static variable.   

        public void Build(IWorkflowBuilder<Context> builder)
        {
            builder
                .StartWith<HelloWorld>()
                .While(c => Context.Count < 3)
                .Do(g => g.StartWith(context => ExecutionResult.Next()).Then(k => Context.Count++)
                      .Then(j => Console.WriteLine("Context=" + Context.Count))
                      .Then(j => Console.WriteLine("#1"))
                      .WaitFor("MyEvent", data => "0")
                      .Then(j => Console.WriteLine("#2"))
                      .Then(j => Console.WriteLine("#3"))
                )
                .Then<GoodbyeWorld>();
        }

Then I publish an event as below after the workflow starts.

 Task.Delay(3000).ContinueWith((a) => host.PublishEvent("MyEvent", "0", null));

I expect a "Wait" after printing #1 in every loop.  It waits in the first loop.   However, it goes all the way without waiting in the 2nd and 3rd.

**Comment by hsnuscars** [comment]
Try this
.WaitFor("MyEvent", data => "0", data => Datetime.now)

but I'm not sure its meaning for.

**Comment by danielgerlag** [comment]
yes, using `.WaitFor("MyEvent", data => "0", data => Datetime.Now)` should work...
The reason is that `.WaitFor("MyEvent", data => "0")` will be triggered by all events named "MyEvent" with a key of "0", since the beginning of time... the third parameter allows you to specify only events that occurred after a a given time.

**Comment by ewyuen** [comment]
Thank you.  It works.
