### ISSUE TITLE
Parallel execution of steps is not async

### ISSUE THREAD

**Issue by georgebratu** [danielgerlag/workflow-core#793]
I have a workflow with let's say 10 steps. Since not all steps require the output of the previous one, I can make some of them to run in parallel and then join on them in the final step. Since the steps are independent and defined to run in parallel I thought they really run on different threads.

I ran the WorkflowCore.Sample13 which has ParallelWorkflow. If I change to code to this:

```
public class PrintMessage : StepBody
    {
        public string Message { get; set; }

        public override ExecutionResult Run(IStepExecutionContext context)
        {
            if (Message == "Item 1.1")
            {
                Thread.Sleep(1000);
            }

            Console.WriteLine(Message);
            return ExecutionResult.Next();
        }
    }
```

I expect to print in the following order:

Item 2.1
Item 3.1
Item 2.2
Item 3.1
Item 2.3
Item 1.1
Item 1.2

But the order doesn't change, because the steps are executed sequentially, on the same thread.

**Comment by danielgerlag** [comment]
That is by design. Since workflows are long running background processes, parallel in this context means that each parallel branch will not block another branch. So if you have a WaitFor or a Delay, etc... in one of the parallel branches, the others will still be free to execute.

**Comment by georgebratu** [comment]
But they do block each other. If I have a Delay in the first branch, I would expect the other branches to still execute, and they don't, they are waiting for the first branch to finish.

**Comment by mario-degenhardt-snkeos** [comment]
Hi Daniel,
Thanks for that great library, it helped a lot to implement workflows! :)
Unfortunately I noticed the same behavior, like georgebratu already described. 
I also expected that Parallel() let the branches run independently from each other, like here:
            Item 1.1 --  Item 1.2 ---------
         /                                                 \
Hello - Item 2.1 -- Item 2.2-- Item 2.3 - Goodbye
         \                                                 /
            Item 3.1 -- Item 3.2 ---------

But, the current implementation performs the tasks in the following sequence, where a task can block the following ones.
Hello - Item 1.1 -- Item 2.1 -- Item 3.1 -- Item 1.2 -- Item 2.2 --Item 3.2 --  Item 2.3   - Goodbye

Is there any option to run such branches concurrently inside a workflow?
