### ISSUE TITLE
Memory leak for CosmosClient in CosmosDbPersistenceProvider

### ISSUE THREAD

**Issue by brucezlata** [danielgerlag/workflow-core#809]
Not sure why AddTransient here. 
I doubt AddTransient will take too many socket resources. Why not use AddSingleton for cosmos db connection?
      public static WorkflowOptions UseCosmosDbPersistence(this WorkflowOptions options, string connectionString, string databaseId)
        {
            options.Services.AddTransient<ICosmosDbProvisioner>(sp => new CosmosDbProvisioner(connectionString, sp.GetService<ILoggerFactory>()));
            options.UsePersistence(sp => new CosmosDbPersistenceProvider(connectionString, databaseId, sp.GetService<ICosmosDbProvisioner>()));
            return options;
        }

**Comment by danielgerlag** [comment]
Do you know when and how often `ICosmosDbProvisioner` is used?

**Comment by brucezlata** [comment]
Sorry, I mixed Provisioner to provider. Change the tile t
But I think there is memory leak in CosmosClient. CosmosClient is a unmanaged resource which implements IDispose.


`        public CosmosDbPersistenceProvider(string connectionString, string dbId, ICosmosDbProvisioner provisioner)
        {
            _provisioner = provisioner;
            _dbId = dbId;
            _client = new CosmosClient(connectionString);
            _workflowContainer = new Lazy<Container>(() => _client.GetDatabase(_dbId).GetContainer(WorkflowContainerName));
            _eventContainer = new Lazy<Container>(() => _client.GetDatabase(_dbId).GetContainer(EventContainerName));
            _subscriptionContainer = new Lazy<Container>(() => _client.GetDatabase(_dbId).GetContainer(SubscriptionContainerName));
        }`

and in AddWorkflow, Persistence is AddTransient.
`services.AddTransient<IPersistenceProvider>(options.PersistanceFactory);`

That means for cosmos db, CosmosDbPersistenceProvider will create CosmosClient every time. And it will not be disposed.

**Comment by brucezlata** [comment]
How about DI for CosmosClient ?

**Comment by brucezlata** [comment]
like this?

public static WorkflowOptions UseCosmosDbPersistence(this WorkflowOptions options, string connectionString, string databaseId)
{
options.Services.AddTransient(sp => new CosmosDbProvisioner(connectionString, sp.GetService()));
options.Services.AddSingleton(sp => new CosmosClient(connectionString, sp.GetService()));
options.UsePersistence(sp => new CosmosDbPersistenceProvider(connectionString, databaseId, sp.GetService()));
return options;
}


public CosmosDbPersistenceProvider(ICosmosClient client, string dbId, ICosmosDbProvisioner provisioner)
{
_provisioner = provisioner;
_dbId = dbId;
_client = client;
_workflowContainer = new Lazy(() => _client.GetDatabase(_dbId).GetContainer(WorkflowContainerName));
_eventContainer = new Lazy(() => _client.GetDatabase(_dbId).GetContainer(EventContainerName));
_subscriptionContainer = new Lazy(() => _client.GetDatabase(_dbId).GetContainer(SubscriptionContainerName));
}

**Comment by danielgerlag** [comment]
Good catch, I'll look into implementing some kind of object pooling for this... you could also submit a PR if you like?

**Comment by brucezlata** [comment]
https://github.com/danielgerlag/workflow-core/pull/811
