### ISSUE TITLE
How to use StepBodyAsync with JSON

### ISSUE THREAD

**Issue by germandb** [danielgerlag/workflow-core#83]
Hi Daniell, I was trying to migrate mi workflow definition from code to the JSON implementation, and have some duds.
You use a different StepBody for async steps, which property is used to passe this to the json definition o theres no differences at all.

**Comment by danielgerlag** [comment]
It shouldn’t make any difference... the workflow definition does not know the implementation details of its components

**Comment by germandb** [comment]
Ok that make sense, thanks for the answer
