### ISSUE TITLE
Having issue while submit activity inside from an StepBodyAsync

### ISSUE THREAD

**Issue by sunilsoniudaipur** [danielgerlag/workflow-core#832]
**Bug Description**
I am having serious issue, I created a workflow with multiple activities, on each activity there are few activities and when all the sub activities are done and then In step body, I am calling another activity, the activity success is submitted but its execution did not start until I restart the web application. unable to understand the issue,  
**To Reproduce**
you can have a set of activities like this

- Activity Parent one
   - Chile Activity one
   - Chile Activity two (on completion of both I am calling the Activity Parent Two) _it is called but execution didnt started till I restart the application_
- Activity Parent Two
  - Child Activity 1
  - Child Activity 2
each activity having a different unique with different worker name, 

**Expected behavior**
When the activity submitted it should started, I also tried to give the TimeSpan of few seconds but still it doesnt work

**Additional context**
can you please help me with that, I spent a lot of time into this and in am in middle of project. I tried many ways but nothing works

**Comment by danielgerlag** [comment]
When you say `activity`, do you mean this - https://workflow-core.readthedocs.io/en/latest/activities/ ?
How are you constructing the parent/child relationships between them?
It might help to include the workflow definition.

**Comment by sunilsoniudaipur** [comment]
Yes, I am Declaring the Nested Activities, like this

this is the sample code, in case you need a complete workflow, I can add this

`Parrallel().Do(then=>then{
  .Activity("Parent",data)
    .Output()
      .Activity*"Child1",data)
       .Output(result)
   //based on this output I am calling the Parent 1 Activity

})
..Do(then=>then{
  .Activity("Parent 1",data)
    .Output()
      .Activity*"Child 2",data)
       .Output(result)
   //based on this output I am calling the Parent 1 Activity

})
`

**Comment by sunilsoniudaipur** [comment]
I am not sure how, but it working now.
