### ISSUE TITLE
Multithreaded Parallel Foreach

### ISSUE THREAD

**Issue by woutervanranst** [danielgerlag/workflow-core#848]
From the wording of Sample9 (https://github.com/danielgerlag/workflow-core/tree/master/src/samples/WorkflowCore.Sample09) I thought this would execute in parallel (read: multithreaded)
but after stepping through I understand the behavior is different.

Is there an _easy_ way of achieving multithreading with workflow-core?
Eg. in this snippet below, index all the files in a directory and as they are enumerated, start calculating their hashes ?

More broadly, I'm investigating whether workflow-core could replace my current TPL Dataflow setup to create a "cleaner"/more maintainable workflow (I esp. like the Fluent design).

```
    builder
        .StartWith<IndexFilesInDirectoryStep>()
        .ForEach(files => file.AsParallel().AsEnumerable()) // PSEUDOCODE
            .Do(x => x
                .StartWith<CalculateHashStep>())
```

**Comment by danielgerlag** [comment]
This is not a use case of workflow-core, it is targeted to long running processes.
