### ISSUE TITLE
MissingMethodException when using WorkflowTest.GetStatus (similar to Issue #496)

### ISSUE THREAD

**Issue by ckolumbus** [danielgerlag/workflow-core#849]
**Describe the bug**
When using the WorkflowTest package and a test suite example from the repository  the test execution with `dotnet test` throws a 
```
System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task`1<WorkflowCore.Models.WorkflowInstance> WorkflowCore.Interface.IWorkflowRepository.GetWorkflowInstance(System.String)'.
```
exception.

This seems to be similar to what had been reported in  #496

**To Reproduce**

Environment: 
* dotnet core 5.0.300
* development and test execution within a development container based on Linux, host is windows 10
* Example testsuite / case from the repo (with own workflow definition) 
* referenced packages (mind the old version of "WorkflowCore.Testing"!)
```
    <PackageReference Include="FluentAssertions" Version="5.10.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
    <PackageReference Include="NUnit" Version="3.12.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.16.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.10.0" />
    <PackageReference Include="WorkflowCore.Testing" Version="2.3.0" />
```

output
```
vscode ➜ /workspace/src/Workflow.Definitions.Test.Int (hackathon ✗) $ dotnet test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Tasks -> /workspace/src/Tasks/bin/Debug/net5.0/Tasks.dll
  Workflow.Definitions -> /workspace/src/Workflow.Definitions/bin/Debug/net5.0/Workflow.Definitions.dll
  Workflow.Definitions.Test.Int -> /workspace/src/Workflow.Definitions.Test.Int/bin/Debug/net5.0/Workflow.Definitions.Test.Int.dll
Test run for /workspace/src/Workflow.Definitions.Test.Int/bin/Debug/net5.0/Workflow.Definitions.Test.Int.dll (.NETCoreApp,Version=v5.0)
Microsoft (R) Test Execution Command Line Tool Version 16.10.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed NUnit_workflow_test_sample [305 ms]
  Error Message:
   System.MissingMethodException : Method not found: 'System.Threading.Tasks.Task`1<WorkflowCore.Models.WorkflowInstance> WorkflowCore.Interface.IWorkflowRepository.GetWorkflowInstance(System.String)'.
  Stack Trace:
     at WorkflowCore.Testing.WorkflowTest`2.GetStatus(String workflowId)
   at WorkflowCore.Testing.WorkflowTest`2.WaitForWorkflowToComplete(String workflowId, TimeSpan timeOut)
   at Workflow.Definitions.Test.Int.FrequentScannerDeploymentWorkflowTest.NUnit_workflow_test_sample() in /workspace/src/Workflow.Definitions.Test.Int/FrequentScannerDeploymentWorkflow.cs:line 25

Failed!  - Failed:     1, Passed:     0, Skipped:     0, Total:     1, Duration:  - /workspace/src/Workflow.Definitions.Test.Int/bin/Debug/net5.0/Workflow.Definitions.Test.Int.dll (net5.0)
vscode ➜ /workspace/src/Workflow.Definitions.Test.Int (hackathon) $ dotnet --version
5.0.300
```

**Expected behavior**

* with `dotnet test` we should get the output of the test run without the `MissingMethodException`

**Additional context**

it seems that the `WorkflowCore.Testing` package is very outdated. Last update was Jan-2020 and it has version 2.3.0 whereas the WorkflowCore package is 3.5.0 and has been recently updated.

The error message indicates that the Method `GetWorkflowInstance` is part of `IWorkflowRepository` whereas the [current code](https://github.com/danielgerlag/workflow-core/blob/30c98f83c5d70bae11dd2b65bada0db5619340f3/test/WorkflowCore.Testing/WorkflowTest.cs#L119) uses the implementation from `IPersistenceProvider`

**Comment by DavidPx** [comment]
I'm running into the same issue, I believe the problem is the addition of the optional cancellationToken argument to GetWorkflowInstance.  The Workflow.Testing package just needs to be rebuilt and pushed.

**Comment by ckolumbus** [comment]
I downloaded the source and compiled a version of WorkflowCore.Testing directly from HEAD (unfortunately not 3.5.0 tag exists that would match the latest nuget package).

This works perfectly. So IMHO only the newest version is missing in the nuget repo.

**Comment by danielgerlag** [comment]
Sorry about that... I published the package to nuget.

**Comment by ckolumbus** [comment]
@danielgerlag THANKS a lot!!! One more question: would it be possible to tag the release on GH and checkin the build/release process and nuspecs for the packages? It would be easier to debug such stuff locally with this additional information!
