### ISSUE TITLE
How to know if the WorkflowHost is started and a WorkflowDefinition its registered 

### ISSUE THREAD

**Issue by germandb** [danielgerlag/workflow-core#86]
Hi Daniell I'm implementing a n-layer application where I expose a proxy with a startworkflow method. When a service call come in my application layer the manager needs to Start the WorkflowHost, Register the Workflow and then call the Start Workflow method from WorkflowCore.

This work fine in the first call but when a second call come, If I call the start WorkflowHost again it faill becaouse it's already started, I need to know if the host it's already running but the only property that I find its the _shutdown but its private. 

The same with loading the JSON Workflow Definition, the first time the definition its loaded and registered, but the second time fails becaouse its already registered. I need a method that tell me if the workflow its already registered so I dont do this again.

I appreciate any thought that you have with this questions.

**Comment by danielgerlag** [comment]
This seems like a strange approach... the WorkflowHost is intended to be started on the initialization of you application and only stopped when your app shuts down.  It is a background service the runs inside your process to execute workflows from the persistence store that it is provided... Why would you want to spin up a new instance for every workflow?

**Comment by germandb** [comment]
Hi Daniel I think I didnt explain my self well. I dont want a new instance of the workflowhost to execute for every call. I'll try to explain the full picture to you:

I have the WorkflowCore running as part of a microservice, when I start that microservice I dont start the workflowhost because I dont want to run something that I dont need, thats why I want to start the workflowhost when the first request to start a workflow come to my microservice, and then have the host running untill the stop command its send or the microservice its shutdown. The problem its that I need something to let me know if the workflowhost its already running so I dont try to start the host again.  

In the case of the WorkflowDefinition, imagine this scenario:

I have the host already started and  a request to start a new workflow is sent to the microservice, the request only send the workflow Id and with that info I read from a database the json with the workflowDefinition and a DLL with the steps definition, in order to start the workflow I need to register the DLL into the context and load the JSON file that ends registering the Workflow in the Host; after this is done, I can call the WorkflowStart method and everything works fine. But then a second request to start the same workflow enter into the microservice and if I follow the same steps, it ends with the workflow host giving me and exception for trying to register the workflow a second time. I can catch the exception and continue but I think its better to have a method that you can invoke to know if a workflow its already registred into the host.

**Comment by danielgerlag** [comment]
How would you know you are not shutting down the workflow host while a second or third workflow are trying to execute?
Doing this would also render some of the features of workflow-core inoperable, such as the `WaitFor`, `Schedule` or `Delay` steps...
Perhaps, you should only use `WorkflowController` in your micro-service to control workflow instances but have an actual long running instance of `WorkflowHost` running on another "server" sharing the persistence, queue and locking providers?
