### ISSUE TITLE
Use SQL for Persistence with Azure DLM

### ISSUE THREAD

**Issue by peterkozak** [danielgerlag/workflow-core#87]
Hi Daniel,

I would like to run workflow-core on a Service Fabric cluster, consisting of several nodes.  As I understand, I need a DLM Provider like Azure, which is fine for me. Furthermore I would like to persist the Workflow State in a SQL Database.

How can I initialize both , the persistence and the DLM provider in Parallel?

Thanks,
Peter

**Comment by danielgerlag** [comment]
@peterkozak is this what you are looking for? (not sure I understood your question)

```c#
services.AddWorkflow(x =>
{
    x.UseAzureSyncronization(@"UseDevelopmentStorage=true");
    x.UseSqlServer(@"Server=.\SQLEXPRESS;Database=WorkflowCore;Trusted_Connection=True;", true, true);
});
```

**Comment by peterkozak** [comment]
Thanks Daniel, that was exactly what I was missing... :-)
