### ISSUE TITLE
“Expression” injection attack

### ISSUE THREAD

**Issue by brettwinters** [danielgerlag/workflow-core#873]
Hi @danielgerlag 

Great project, thanks a lot for what you've built here!

Im looking at developing a client portal which allows users to build their own approval workflows with a custom GUI builder but output would be uploaded as json for later execution. 

Is there any risk that "active" content / expressions in the json which is uploaded, stored then deserialised through your DSL engine into executable code could be used as an attack vector - in a similar way to SQL injection?

Regards

Brett

**Comment by danielgerlag** [comment]
The expression language comes from a 3rd party library - https://github.com/zzzprojects/System.Linq.Dynamic.Core#expression-language
It basically builds expression trees and the inputs are used to evaluate a result, rather than run a script.

**Comment by brettwinters** [comment]
I looked them up. Their expression parsing library has 25 million users so I'm sure we'd have heard about a problem if one existed.
