### ISSUE TITLE
MySqlDbContextOptionsExtensions rename to MySqlDbContextOptionsBuilderExtensions for .NET Core 5.0

### ISSUE THREAD

**Issue by netcore-jroger** [danielgerlag/workflow-core#876]
**Describe the bug**
```
Could not load type 'Microsoft.EntityFrameworkCore.MySqlDbContextOptionsExtensions' from assembly 'Pomelo.EntityFrameworkCore.MySql, Version=5.0.1.0, Culture=neutral, PublicKeyToken=2cc498582444921b'.
```

**To Reproduce**
Use `WorkflowCore.Persistence.MySQL` for .net 5.0 project.

**Expected behavior**

**Additional context**
`Pomelo.EntityFrameworkCore.MySql` for net5.0,
rename MySqlDbContextOptionsExtensions to MySqlDbContextOptionsBuilderExtensions.

The place where the error was reported is [here](https://github.com/danielgerlag/workflow-core/blob/master/src/providers/WorkflowCore.Persistence.MySQL/MysqlContext.cs#L24)

Pomelo.EntityFrameworkCore.MySQL change log: https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/compare/3.2.6...5.0.1

then search `MySqlDbContextOptionsExtensions`.

**Comment by danielgerlag** [comment]
Let's target v5 of Pomelo, which is built against .net standard 2.1.  Let's target .net standard 2.1 from `WorkflowCore.Persistence.MySQL` and continue to target .net standard 2.0 from `WorkflowCore.Persistence.EntityFramework`

**Comment by lfbertucci** [comment]
Some news for this issue?
I'm facing the same problem.

best regards

**Comment by netcore-jroger** [comment]
@lfbertucci See #882

**Comment by lfbertucci** [comment]
thks
