### ISSUE TITLE
Access context.Item (along with data) for If inside ForEach

### ISSUE THREAD

**Issue by brettwinters** [danielgerlag/workflow-core#897]
Hello

I would like an `If` inside a `ForEach` step to have access to the `context.Item` so I can access the current item, like this:

```c#
.ForEach(data => data.Users).Do(then => then
    .If((data, context) => ((User)context.Item).HasNotApproved).Do(x => x
        .WaitFor(...)
    )

    .Then(...)
)
```

But the iterator/context is not available, is this something you could add or am I on the wrong track here?

**Comment by brettwinters** [comment]
I've discovered by looking at the source that context is provided in the json DSL so I guess I have a workaround...

**Comment by ChrisBertrand** [comment]
I'm guessing this is still not possible? This would also be really useful in a while loop
