### ISSUE TITLE
Subscription still alives after WaitFor cancelled

### ISSUE THREAD

**Issue by hsnuscars** [danielgerlag/workflow-core#92]
Hello,

I tried WaitFor with cancel condition and found an issue.
If I toggle cancel condition after waitfor event subscribed,
it will be cancelled correctly and continue to next Join step,
but subscription will not be removed from database.

Thanks a lot.

In addition, do you have plan to add state hook for step?
ex: OnLoad, OnDataSaved, ... etc.

**Comment by hsnuscars** [comment]
If subscription was still there and workflow not end, it will be triggered when somebody send event which EvenName& EventKey matched.

**Comment by danielgerlag** [comment]
Thanks for letting me know. I will look into it

**Comment by danielgerlag** [comment]
@hsnuscars I have just published `1.4.1` which should resolve this issue for now.
Let me know if you have further problems.

**Comment by hsnuscars** [comment]
Thank you!
