### ISSUE TITLE
StartWorkflow("...").Result does not wait until the Workflow is finishing

### ISSUE THREAD

**Issue by Hoschi1982** [danielgerlag/workflow-core#920]
**Describe the bug**
host.StartWorkflow("...").Result does not wait until the Workflow is finishing

**To Reproduce**
Call the method like the description

**Expected behavior**
Wait until the Workflow is finishing

**Additional context**

Question: How can I wait until the Workflow is finished?
Thanks!

**Comment by dbb1215** [comment]
i have the same question.
