### ISSUE TITLE
duplicate event

### ISSUE THREAD

**Issue by EashShow** [danielgerlag/workflow-core#935]
**Describe the bug**
the workflow may create lots of duplicate event sometimes

**To Reproduce**
it is difficult to reproduce
random occurrence

**Expected behavior**
no duplicate events

**Additional context**
mysql V8.021
centos V7.9
dotnet core V5
[duplicate_event.xlsx](https://github.com/danielgerlag/workflow-core/files/7397487/duplicate_event.xlsx)

**Comment by danielgerlag** [comment]
unable to reproduce

**Comment by EashShow** [comment]
> **Describe the bug** the workflow may create lots of duplicate event sometimes
> 
> **To Reproduce** it is difficult to reproduce random occurrence
> 
> **Expected behavior** no duplicate events
> 
> **Additional context** mysql V8.021 centos V7.9 dotnet core V5 [duplicate_event.xlsx](https://github.com/danielgerlag/workflow-core/files/7397487/duplicate_event.xlsx)



> **Describe the bug** the workflow may create lots of duplicate event sometimes
> 
> **To Reproduce** it is difficult to reproduce random occurrence
> 
> **Expected behavior** no duplicate events
> 
> **Additional context** mysql V8.021 centos V7.9 dotnet core V5 [duplicate_event.xlsx](https://github.com/danielgerlag/workflow-core/files/7397487/duplicate_event.xlsx)



> unable to reproduce

my workflow is deployed on 2 servers for load balance, sometimes workflow concurrency is very large, then this bug is reproduced

**Comment by danielgerlag** [comment]
Are you using a distributed lock manager?

**Comment by EashShow** [comment]
No distributed lock is used.
the max duplicate event number is 248
there are 248 records in the table 'subscription' with the same EventKey almost in the same time

**Comment by danielgerlag** [comment]
Please use one of the distributed lock providers to prevent duplicates.

**Comment by EashShow** [comment]
the Mysql is one instance

2 app servers connect the same mysql instance

**Comment by EashShow** [comment]
the Mysql is one instance

2 app servers connect the same mysql instance

**Comment by danielgerlag** [comment]
https://workflow-core.readthedocs.io/en/latest/multi-node-clusters/

**Comment by EashShow** [comment]
I see. thanks a lot.
Can I persistence the workflow data in mysql, and use redis as a distributed lock?
