### ISSUE TITLE
Create dynamic DataModels composed by workflow def.steps

### ISSUE THREAD

**Issue by linkev44** [danielgerlag/workflow-core#95]
When i use JSON for creating a dynamic WF, i need to bind a C# strong typed model. We need a dynamic data model definition .. each step in JSON Workflow should create a part of this global model ... how you think that can be implemented ?

Sorry for my approximative english ..

**Comment by danielgerlag** [comment]
Hi,

I'm not sure I understand what you are asking... could you try explain it in different terms?

**Comment by linkev44** [comment]
Hi, 
When i will design a new workflow (by JSON) the workflow can be modified by users .. if an user add a step in dynamic workflow..  the workflow data model must be able to support this add of properties (needed by the new step) dynamically, like a property bag ... Do you see what i say ?

**Comment by ewyuen** [comment]
Do you mean when defining a workflow with IWorkflow<TData>, you want TData to be a dynamic class or a class which can be dynamically added properties to it?  Do you consider just add a Dictionary<string, object> property to your TData class?

**Comment by danielgerlag** [comment]
Could you use [System.Dynamic.ExpandoObject](https://msdn.microsoft.com/en-us/library/system.dynamic.expandoobject(v=vs.110).aspx) ?

**Comment by urdeveloper** [comment]
Hi Daniel, is it possible to use ExpandoObject?I tried it before with JSON definition and didn't seem to work. Let's say you'd like to assign a step's output value to Data.X (here Data is type of ExpandoObject and X is not defined yet), it will error out that X is not a member of ExpandoObject.

**Comment by danielgerlag** [comment]
I think there may be an issue with using dynamic types. Let me look into this further and get back to you.

**Comment by danielgerlag** [comment]
I can confirm that it is not possible to use dynamic types with the workflow data object on the current version.  I will look into adding this functionality in the next release.

**Comment by VadimLopatkin** [comment]
@danielgerlag hi, we are considering using your library in our app, but we really need the possibility to define workflows in JSON at runtime, including specifying the input and output variables. As a workaround I was thinking of changing the `WorkflowCore.Services.WorkflowExecutor.ProcessOutputs`  and `WorkflowCore.Services.WorkflowExecutor.ProcessInputs` such that they would work with `Dictionary<string, object>` (and issue a PR afterwards).

What do you think about it? Do you see a way the issue can be fixed?

**Comment by danielgerlag** [comment]
It is already possible to define JSON workflows at runtime. How would thr suggested change make a difference?

**Comment by VadimLopatkin** [comment]
The use case is the following. Let's say we want to define a workflow dynamically (in JSON)  by combining 5 steps, but somehow, we need to pass data from one step to another. The medium to do that would be the `DataType` object (so, we cannot redefine an object here - we should use something that is already compiled - not so dynamic), which properties are used for `Inputs`  and `Outputs` of the steps.

What if there is no such suitable object? Then you would have to create one in C# and recompile. The proposed solution is have `Dictionary` available as such object (at least) such that we could always had kind of a dynamic way of combining the steps and defining Inputs and Outputs for them.

Correct me if I am missing something here.

**Comment by danielgerlag** [comment]
A Dictionary is a concrete type, so I believe it would work.  The issue we have is with ExpandoObject and System.Dynamic

**Comment by VadimLopatkin** [comment]
That's what I meant.  `data.GetType().GetProperty(member.Member.Name).SetValue(data, resolvedValue);` inside `WorkflowCore.Services.WorkflowExecutor.ProcessOutputs()` doesn't work for dictionaries. Recommended way would be something like [here](https://stackoverflow.com/a/3086736/1984845). However, it's a bit more tricky - we need to check if the key-value not set already (Add throws otherwise), but doable.

What do you think?

**Comment by danielgerlag** [comment]
Yes, if you want to take a crack at doing a PR for this, that would be great 😃 
Perhaps, we should first refactor the `ProcessInputs` and `ProcessOutputs` into their own class and write some unit tests around them.
