### ISSUE TITLE
Confusing exception: System.ArgumentException: Unknown property for input Data on Export

### ISSUE THREAD

**Issue by kavatari** [danielgerlag/workflow-core#950]
**Describe the bug**
Using Microsoft's DI we can register our workflow steps to use them in a simple json worklfow description. But, for this we have to register our workflow steps, so they are know to the system. If we forget about the step registration, we will see the exception: 
**System.ArgumentException: Unknown property for input Data on Export**
I found it very confusing. Because _Data_ could also be some input data for the step. So, my first reaction was that the input data class is not found. 

**To Reproduce**
Example json: 
`{
    "Id": "SimpleExport",
    "Version": 1,
    "DataType": "XX.Workflows.Core.Workflow.WorkflowMetaData, XX.Workflows",
    "Steps": [
         {
            "Id": "Extract",
            "StepType": "XX.Workflows.Core.Steps.ExtractTextStep, XX.Workflows",
            "ErrorBehavior": "Terminate",
            "NextStepId": "ExtractDataStep",
            "Inputs": {
                "Data": "data"
            }
        }, 
        {
            "Id": "ExtractDataStep",
            "StepType": "XX.Workflows.Core.Steps.ExtractDataStep, XX.Workflows",
            "ErrorBehavior": "Terminate",
            "NextStepId": "Export",
            "Inputs": {
                "Data": "data"
            }
        },
        {
            "Id": "Export",
            "StepType": "XX.Workflows.Core.Steps.ProcurementDocumentExportStep, XX.Workflows",
            "ErrorBehavior": "Terminate",
            "Inputs": {
                "Data": "data"
            }
        }
    ]
}`

**Expected behavior**
I think it would be better to have a clear exception like: the StepType xy was not found.

**Additional context**
No additional context here.

**Comment by danielgerlag** [comment]
That's probably because the error you are seeing is not related to the step not being registered.
If you did not register the step you would see `Unable to construct step body {0}`

**Comment by kavatari** [comment]
Unfortunatly this error was resolved by registering the step - this was the only solution here.
