### ISSUE TITLE
Only poll runnable workflows who's definition has been registered

### ISSUE THREAD

**Issue by Aaron-Redmond** [danielgerlag/workflow-core#959]
**Is your feature request related to a problem? Please describe.**
I have multiple wf's that I want to split across multiple processes but utilise the same db. e.g. Application 1 has registered wf A and application 2 has registered wf B but bother applications utilise the same persistence store. 
Currently the runnable poller does not check if a wf has first been registered before attempting to run it,  and will may cause a an error as the workflow may not registered in the process that runs it, in the above scenario. 
The reason this would be useful is that it will give more flexibility to deployable pieces e.g. I can deploy application 1 and not 2 if changes are required. It also allows more granularity with some authentication scenarios e.g. if a wf needs to call to a web service utilizing windows authentication I can run that wf under the context of a specific account.   

**Describe the solution you'd like**
The RunnablePoller should check if the wf is registered before attempting to run

**Describe alternatives you've considered**
Make the RunnablePoller an interface that could be implemented 

**Additional context**
NA

**Comment by potatopeelings** [comment]
If you want to keep them separate, it would be easier to use separate databases (one for Application 1 with wf A and another for application 2 with wf B). Sharing datastores is usually more trouble than its worth. 

If you wanted to have an aggregate list somewhere it would be cleaner to use middleware to (asynchronously) feed that data store. Something like
- Application A with datastore A having workflow middleware replicating wf A state in Application C
- Application B with datastore B having workflow middleware replicating wf B state in Application C

----

That said, you could implement a solution by creating your own `IPersistenceProvider`.

One hacky way is to decorate the inbuilt PersistenceProvider and filters out workflows you are not interested in. For instance, if you use Mongo.

In DI
```c#
// HACK: not a complete solution
// has to be after opt.UseMongoDB(connectionString, databaseName);
opt.UsePersistence(sp =>
{
    var mongoClientSettings = MongoClientSettings.FromConnectionString(connectionString);
    var client = new MongoClient(mongoClientSettings);
    var db = client.GetDatabase(databaseName);
    return new MyMongoPersistenceProvider(db);
});
```
with

```c#
// HACK: not a complete solution
public class MyMongoPersistenceProvider : IPersistenceProvider
{
    internal const string WorkflowCollectionName = "wfc.workflows";

    private IMongoCollection<WorkflowInstance> WorkflowInstances => _database.GetCollection<WorkflowInstance>(WorkflowCollectionName);

    private readonly MongoPersistenceProvider _mongoPersistencProvider;
    private readonly IMongoDatabase _database;

    public MyMongoPersistenceProvider(IMongoDatabase mongoDatabase)
    {
        _mongoPersistencProvider = new MongoPersistenceProvider(mongoDatabase);
        _database = mongoDatabase;
    }

    public async Task<IEnumerable<string>> GetRunnableInstances(System.DateTime asAt, CancellationToken cancellationToken = default)
    {
        var now = asAt.ToUniversalTime().Ticks;
        var query = WorkflowInstances
            .Find(x => x.NextExecution.HasValue && (x.NextExecution <= now) && (x.Status == WorkflowStatus.Runnable) &&
                   // filtering out here
                   (x.WorkflowDefinitionId != "666"))
            .Project(x => x.Id);

        return await query.ToListAsync(cancellationToken);
    }
    
    // similarly filter out wherever you retrieve from the database
    // I believe failed workflows now go into ScheduledCommands for the retry, so you'll need to filter them out there as well. Similarly if you use events, you need to keep those separate as well.

    // for all others delegate to _mongoPersistencProvider 
```

But its going to be fragile. Any library upgrades which change the way the data is stored / retrieved could potentially break it.

**Comment by Aaron-Redmond** [comment]
Thanks @potatopeelings, your solution would work. I am looking at having to maintain about 20 databases + 20 processes and thought that if I reduce the db count, it may cause me the the least amount of pain. I understand I am just moving complexity around will update this thread if I end up regretting my decision. I ended up disabling polling via the WorkflowOptions object and then writing my own to filter out workflow definitions that haven't been registered.
