### ISSUE TITLE
How to use the UI interaction in workflow activity?

### ISSUE THREAD

**Issue by michael-laoyu** [danielgerlag/workflow-core#97]
How to use the UI interaction in workflow activity?

**Comment by danielgerlag** [comment]
You would not normally have UI interaction inside a workflow step... however, you could build a UI the interacts with the workflow via the WorkflowHost service.  By passed data and events to it that it may be waiting on.

**Comment by michael-laoyu** [comment]
thanks.In the business process,maybe  need to  human intervention, maybe  require the UI interaction.

**Comment by danielgerlag** [comment]
You could register external events for the workflow to listen to using `WaitFor` and then your UI can publish events with attached data to the workflow engine
