### ISSUE TITLE
Whats the meaning of IWorkflow.Version

### ISSUE THREAD

**Issue by esskar** [danielgerlag/workflow-core#99]
Hey,

thanks for the great library. I have a question about the Workflow.Version. What is it for and how does it influence the whole process. What happens when I have a pending workflow X of version 1, stop everything, update my workflow X to version 2 and start everything again.

thanks.

**Comment by danielgerlag** [comment]
Hi,

Any in flight workflows will only execute if the host process knows what the version of the workflow that it was started on looks like.  So, the idea is that you maintain multiple versions of each workflow until all legacy workflows are complete.
Does that make sense? not sure I explained it well.

**Comment by usaadi** [comment]
Hello,

Is there any documentation now on versioning? I have a question as to what are we allowed to modify in the workflow without needing to create a new version? I suppose it is only the behavior in the class definition of the steps without modifying the inputs and outputs. Is that correct?
