### ISSUE TITLE
Add support for OpenTelemetry

### ISSUE THREAD

**Issue by glucaci** [danielgerlag/workflow-core#996]
It will be nice to have more insights directly from the library and enable users to integrate easily with [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-dotnet). 
The `Step` and `Workflow` middleware are not enough to get full traceability what happens into the library.

If it's ok, I will do a PR to integrate [ActivitySource](https://docs.microsoft.com/en-us/dotnet/core/diagnostics/distributed-tracing-instrumentation-walkthroughs) into the library.

**Comment by Davilink** [comment]
Hi, Is there anything special that need to be configured to have the tracing ?
I'm using the aspire dashboard on my dev machine, but i can't seem to get the telemetry.

In my program.cs i added:
```csharp
builder
    .AddServiceDefaults()
    .Services
    .AddOpenTelemetry()
        .WithTracing(builder =>
            builder
                .AddSource("WorkflowCore.*"))
    .Services
    .AddWorkflow(opt =>
        opt.UsePostgreSQL(
            connectionString: workflowCdrConnectionString,
            canCreateDB: false,
            canMigrateDB: true))
```

Note: the `AddServiceDefaults()` is from https://aspire.dev/get-started/csharp-service-defaults/#add-service-defaults-functionality
